### ISSUE TITLE
How create ipa with lime from command line?

### ISSUE THREAD

**Issue by SergeyLabutin** [openfl/lime#1007]
i find this http://subathrathanabalan.com/2016/01/07/building-ipa-export-archive/
before archive need run `xcodebuild` with
`-archivePath "${PROJECT_BUILDDIR}/${SCHEME_NAME}.xcarchive" \`
and
`archive`

but not find this in lime, finded run on device only.

**Comment by jgranick** [comment]
I believe we `xcodebuild` but do not package. In the process of testing for the device, I believe it gets packaged and installed, but a standard `lime build` does not actually generate an IPA, I believe we finish only step 1 of 2 by default.

Perhaps we could add an `-archive` option, or always generate an IPA, as a part of our command-line build process. What is the use-case for this? How do you use the IPA after it is created?

Thanks :smile:

**Comment by SergeyLabutin** [comment]
IPA i upload to TestFlight, if try create IPA from XCode i have recompile always. Also for Jenkins need build create without any manipulations :) and in future need auto deploy to TestFlight.

**Comment by starburst997** [comment]
Personally I use [fastlane](https://github.com/fastlane/fastlane/tree/master/gym), it can build your IPA and deploy to itune all on the command-line.

**Comment by jgranick** [comment]
We added support for this using `lime deploy ios` :smile:
