### ISSUE TITLE
tvOS used ios.provisioning-profile

### ISSUE THREAD

**Issue by SergeyLabutin** [openfl/lime#1008]
https://github.com/openfl/lime/blob/55301ca4cf6f4f7c38d97b9cd478c8cc6b587825/lime/tools/helpers/TVOSHelper.hx#L352-L356
check `project.config.exists ("tvos.provisioning-profile")` but use `project.config.getString ("ios.provisioning-profile")`

**Comment by jgranick** [comment]
Thanks :smile:
