### ISSUE TITLE
Non-english path error

### ISSUE THREAD

**Issue by RblSb** [openfl/lime#1016]
When you run an windows build from a folder with a extended latin name, it produces an error `[lime.app.Preloader] ERROR: There is no asset library with an ID of "default"`

**Comment by ibilon** [comment]
Probably because of https://github.com/HaxeFoundation/haxe/issues/5935

**Comment by RblSb** [comment]
This can not be avoided by using relative paths to application resources? Or lime already uses them / it will not affect?

**Comment by jgranick** [comment]
This was a regression since switching to Haxe 3.4 in HXCPP, the HXCPP "std" library lacked Windows Unicode fixes. These have been restored in the latest source version of HXCPP:

https://github.com/HaxeFoundation/haxe/issues/5935

:smile:

**Comment by randomnine** [comment]
This bug wasn't fixed; can it be reopened?

While HXCPP's file functions appear to be working OK, Lime's src/util/Bytes.cpp still fails to load files with Unicode paths.
