### ISSUE TITLE
6-axis joystick event

### ISSUE THREAD

**Issue by madrazo** [openfl/lime#104]
When pressing a diagonal on the joystick 2 events are received. 

For example, tracing the event when pressing left-down:
[JoystickEvent type=axisMove bubbles=false cancelable=false device=0 id=0 x=-1 y=0 z=0]
[JoystickEvent type=axisMove bubbles=false cancelable=false device=0 id=0 x=-1 y=1 z=0]

Releasing:
[JoystickEvent type=axisMove bubbles=false cancelable=false device=0 id=0 x=0 y=1 z=0]
[JoystickEvent type=axisMove bubbles=false cancelable=false device=0 id=0 x=0 y=0 z=0]

I think it would be an improvement to only receive only one event.
*Note that in the example I have truncated the values to 0,1,-1
Cheers

**Comment by jgranick** [comment]
I think this was done. Thanks :smile:
