### ISSUE TITLE
C# compilation fails with "Unknown command-line option --arch"

### ISSUE THREAD

**Issue by Gama11** [openfl/lime#1073]
Trying out the experimental C# support, there seems to be an issue with calling `hxcs`:

```bash
> lime create project LimeCsTest

> cd LimeCsTest

> lime test cs
Unknown command-line option --arch
 Usage : haxelib run hxcs buildFile.txt [?... options]
 Options :
  --haxe-version <version> : sets what baseline haxe version was it compiled with
  --feature-level <level> : sets the feature level needed to compile the buildFile. Defaults to 0
  --out <filename> : sets the output file path
```

This is on latest Lime (5.5.0). Tried with hxcs 3.2.0, 3.4.0 and latest from GitHub, doesn't make a difference. Using a Haxe 4 dev build.

cc @vroad

**Comment by jgranick** [comment]
When last tested, it used @vroad's fork: https://github.com/vroad/hxcs

Some initial sample projects were working, but it wasn't production ready, likely on our end due to lack of investment
