### ISSUE TITLE
Compilation failed - Haxe [3.4.4] - OpenFL [6.2.0] - Lime [5.6.0]

### ISSUE THREAD

**Issue by railnation** [openfl/lime#1086]
Hello, 
If I try to compile the setup up shown below, targeting js, I get many compilation errors:

haxe -js bin/js/App.js -main Main -cp 01_dev/src -lib openfl -lib lime

[compilationErrors.txt](https://github.com/openfl/lime/files/1367859/compilationErrors.txt)

Any help would be nice!

Thank you

**Comment by jgranick** [comment]
Hello!

OpenFL and Lime are designed to use their own tools. Try the following:

```bash
openfl test html5
```

If you don't have a Lime project file yet, you can create an empty template project using this command

```bash
openfl create project MySampleProject
```

There's some more information here :)

http://www.openfl.org/learn/tutorials/displaying-a-bitmap/
