### ISSUE TITLE
Crash when playing video due to null pointer to glUseProgram

### ISSUE THREAD

**Issue by GMMan** [openfl/lime#110]
I've been playing Escape from Darkmoor Mansion (a game leveraging Lime) on the PC, and have ran into a crash where when the game attempts to start a video, it dies accessing an null pointer. Doing a bit of debugging, it appears that the problem is stemming from Lime, where there is no null check or stub for a call to glUseProgram(). The computer I was playing the game on has a fairly old integrated graphics adapter (Intel GMA 3100/Q35 Express Chipset) and only supports up to OpenGL 1.3, and as such does not support the glUseProgram() method, which is only available on OpenGL 2.0 and above. I'm not sure if the check for OpenGL version should be done by the code using the library, but I think having a check for GL version within the library somewhere, or maybe replacing functions that can't be imported with stubs, would be helpful and prevent some head scratching from end users when the developers are unaware.

**Comment by jgranick** [comment]
Officially, Lime is designed for a shader-based pipeline, so I'm not sure there's a lot that can be done here, except that we should perhaps consider ANGLE support again, which has been added to SDL2, as that can implement OpenGL methods over DirectX -- older hardware (and Windows in general) tends to support DirectX better. I am so sorry for your issue :frowning:
