### ISSUE TITLE
-swf-header gets removed (Flash target)

### ISSUE THREAD

**Issue by kasparsj** [openfl/lime#1107]
Why does the `-swf-header` haxeflag gets removed if there are any embeds?
https://github.com/openfl/lime/blob/develop/lime/tools/platforms/AIRPlatform.hx#L295
I would expect instead it being populated from window size...
Also when using `StageScaleMode.SHOW_ALL` it's neccessary that `stageWidth` and `stageHeight` are correct, but without the `-swf-header` they are always 500 x 375.

**Comment by jgranick** [comment]
It's a side-effect of how assets are embedded -- both files having a header breaks the final SWF, it only seemed to work properly if the later file we merge contains the header
