### ISSUE TITLE
AIR Target ContextMenuItem.hx extern compilation error

### ISSUE THREAD

**Issue by mmauri** [openfl/lime#1108]
Hi,
I have been playing lately with the revamped Air output.
It compiles with simple tests like DisplayingABitmap, Bunnymark, but it fails for my sample:
D:\HaxeToolkit\haxe\lib\lime/5,8,2/externs/air/flash/ui/ContextMenuItem.hx:8: characters 1-36 : Field clone should be declared with 'override' since it is inherited from superclass flash.display.NativeMenuItem

Steps to reproduce:
Haxe 3.4.3
Openfl 6.5.0
Lime 5.8.2
AIR 27
git clone https://github.com/mmauri/modestmaps-openfl.git
cd ModestMapsSample
openfl test air
OR 
openfl test air -android

**Comment by jgranick** [comment]
Please take a look at the fix I made, and see if it helps. I think this might resolve the issue (the confusing issue seems to be the base class is not available outside AIR?), but please give it a try and let me know, thanks :grinning:

**Comment by mmauri** [comment]
Compiling!!
Now I have another issue with the lime application.xml complete.
I will post it ASAP
