### ISSUE TITLE
[Android]change app icon size in AndroidPlatform.hx not working

### ISSUE THREAD

**Issue by CloudTsang** [openfl/lime#1113]
I found that the icon size generated by lime weren't looked very fit on most phones with big(or 4k) screen . 
Then i changed the number in lime/lime/tools/platforms/AndroidPlatform.hx line 384
now : [ 36, 48, 72, 96, 144, 192 ];
mine :  [ 96, 144, 192, 256, 384, 512 ];
But it wasn't work , the generated icon size was still 72 of hdpi and so on...

How to change the icon size?

Sorry for my poor English and hope for your responses.

**Comment by jgranick** [comment]
We currently choose icons one of a few ways:

 * By choosing an exact match (like `<icon path="icon-192.png" size="192" />`)
 * By choosing a close match, and scaling (like scaling a 192px graphic down to 144px)
 * By scaling an SVG icon (like `<icon path="icon.svg" />`)

According to [this chart](http://iconhandbook.co.uk/reference/chart/android/), I believe we have all of the sizes that Android will use for "legacy" icons. It appears they now have "adaptive" icon support for Android 8, which we do not create right now, but I'll create a task for it :smile:

You can't change the sizes of the icons the OS is expecting (unless there is a "xxxxhdpi" size we don't know about?) but you can customize how these files are generated
