### ISSUE TITLE
Calling a Haxe object's function from Java fails

### ISSUE THREAD

**Issue by danielmar** [openfl/lime#1117]
Hello,

With older versions of lime/openfl, I was able to call a haxe function from java using 
haxeObject.call2("funcName",  param1, param2);

However now I get a JNI error saying that funcName is not a field of the object.
My current workaround is to have a "funcName" dynamic variable that references the actual function.

openfl 6.5.0, lime 5.8.2

**Comment by jgranick** [comment]
Is there a good place I can find an example of this, to try out here? Thanks

**Comment by danielmar** [comment]
Yep, every function of IAPHandler here:
https://github.com/HaxeExtension/extension-iap/blob/master/extension/iap/android/IAP.hx#L228

**Comment by jgranick** [comment]
I just did a quick test, and it did work for me:

## TestObject

```haxe
class TestHaxeObject {
	
	
	public function new () {
		
		
		
	}
	
	
	public function callFromJava ():Void {
		
		trace ("Called from Java");
		
	}
	
	
}
```

## JNI Call

```haxe
var jni = JNI.createStaticMethod ("org.haxe.extension.MyNativeExtension", "testHaxeObject", "(Lorg/haxe/lime/HaxeObject;)V");
jni (new TestHaxeObject ());
```

## Java Extension

```java
public static void testHaxeObject (final HaxeObject haxeObject) {
		
		Log.i ("trace", "Test Haxe Object (Java)");
		
		Extension.callbackHandler.post (new Runnable () 
		{
			@Override public void run () 
			{
				Log.i ("trace", "Test Haxe Object (Java, Runnable)");
				haxeObject.call ("callFromJava", new Object[] { });
				haxeObject.call0 ("callFromJava");
			}
		});
		
	}
```

**Comment by danielmar** [comment]
Interesting.
Definitely had two of my own extensions break on this after upgrading (and also the extension-iap one)
Not using static methods on the haxe side.

**Comment by jgranick** [comment]
I don't think it makes much of a difference, but I added some types here locally to keep things straighter:

https://github.com/openfl/lime/commit/b2be9c08e560c0a1a47578664e6b6464bdc9543c

Try tracing the object and field name, to see if you can debug a little?

**Comment by danielmar** [comment]
Thanks, 
The type change does not make a difference.
My "callFromJava" function is not static, however the class that contains it is a static instance.

Tracing looks like this:
JNI.hx:173: object: [object FirebaseListener] (this is a static instance)
JNI.hx:174: method: onEvent (public function)
JNI.hx:175: args: []
JNI.hx:176: object fields: [] (Reflect.fields(object))
JNI.hx:184: onCallback - unknown field onEvent

**Comment by manjav** [comment]
Hi guys
Don't forget when using "-dce" flag with the "full" value, methods not found by the Reflect class.
Use "@:keep" for the class to all fields is unaffected by DCE.


https://haxe.org/manual/cr-dce.html
