### ISSUE TITLE
You cannot access the sys package while targeting js (for sys.FileSystem)

### ISSUE THREAD

**Issue by railnation** [openfl/lime#1133]
Hi, 

I updated to the latest openFL and Lime version today, but if I try to compile for html5 I get the following error.

C:/sdk/haxe_sdk_3.4.4/haxe/lib/lime/5,9,1/lime/project/HXProject.hx:31: characters 7-21 : You cannot access the sys package while targeting js (for sys.FileSystem)

Did I something wrong?

Best regards

**Comment by jgranick** [comment]
Are you using `HXProject` in your code somewhere? In what way? Thank you

**Comment by railnation** [comment]
Yes I am using the String Helper class.

C:/sdk/haxe_sdk_3.4.4/haxe/lib/lime/5,9,1/lime/tools/helpers/CompatibilityHelper.hx:7: characters 7-18 : You cannot access the sys package while targeting js (for sys.io.File)
C:/sdk/haxe_sdk_3.4.4/haxe/lib/lime/5,9,1/lime/project/HXProject.hx:9: characters 7-45 :     referenced here
C:/sdk/haxe_sdk_3.4.4/haxe/lib/lime/5,9,1/lime/tools/helpers/StringHelper.hx:7: characters 7-29 :     referenced here
