### ISSUE TITLE
of the lime version of canvas   any Implementation  paln?

### ISSUE THREAD

**Issue by longde123** [openfl/lime#1135]
Node canvas is a Cairo backed Canvas implementation for NodeJS.

https://github.com/Automattic/node-canvas

**Comment by jgranick** [comment]
We currently support Cairo on native platforms, which is similar to canvas. I believe that's what `node-canvas` uses under the hood. Could you share the use-case you have in mind? Is this for using Lime from within a NodeJS environment, or is this generally to run a command-line application? Thanks!
