### ISSUE TITLE
Overflow in flash font embed

### ISSUE THREAD

**Issue by chatziko** [openfl/lime#1138]
The font in [this dummy project](https://github.com/openfl/lime/files/1607124/fonttest.zip) causes flash build to fail:

```
$ openfl build flash
Called from ? line 1
Called from CommandLineTools.hx line 2080
Called from CommandLineTools.hx line 26
Called from a C function
Called from CommandLineTools.hx line 141
Called from CommandLineTools.hx line 734
Called from lime/project/PlatformTarget.hx line 99
Called from lime/tools/platforms/FlashPlatform.hx line 192
Called from lime/tools/helpers/FlashHelper.hx line 892
Called from lime/tools/helpers/FlashHelper.hx line 712
Called from format/swf/Writer.hx line 59
Called from format/swf/Writer.hx line 1256
Called from format/swf/Writer.hx line 1164
Called from format/swf/Writer.hx line 1132
Called from /usr/share/haxe/std/haxe/io/Output.hx line 180
Uncaught exception - Overflow
```

The problem is that the font's ```layout.kerning.length``` is 94322 which does not fit in UInt16 [here](https://github.com/HaxeFoundation/format/blob/c2b96371e5c22e13332d0cf0a799fd8799436900/format/swf/Writer.hx#L1132).

Not sure if this is a lime or format issue. Tested with the latest versions of both.

**Comment by jgranick** [comment]
Try using the haxelib version of format

**Comment by chatziko** [comment]
Same issue with both the haxelib (3.4.0) and the current git (aeacdbdc) version of format.
