### ISSUE TITLE
[HTML5] Preloading issue on Safari WebView

### ISSUE THREAD

**Issue by leshido** [openfl/lime#1141]
Preloading seems to get stuck on some WebViews running on an iPhone (i.e, Facebook WebView, Skype, etc). I've tracked the root of the problem to be the way fonts are loaded. Specifically, this code in `lime/text/Font.hx`:
```
private function __loadFromName (name:String):Future<Font> {
		
		var promise = new Promise<Font> ();
		
		#if (js && html5)
		
		this.name = name;
		
		var ua = Browser.navigator.userAgent.toLowerCase();
		var isSafari = (ua.indexOf(" safari/") >= 0 && ua.indexOf(" chrome/") < 0);
		
		if (!isSafari && untyped (Browser.document).fonts && untyped (Browser.document).fonts.load) {
			
			untyped (Browser.document).fonts.load ("1em '" + name + "'").then (function (_) {
				
				promise.complete (this);
				
			}, function (_) {
				
				Log.warn ("Could not load web font \"" + name + "\"");
				promise.complete (this);
				
			});
			
} else {
...
```
The check for `isSafari` is probably failing on some WebViews that don't have the word "safari" in their userAgent, but actually do run Safari behind the scenes. What is the purpose of this code? For now, I just patched this locally to be always `false` and that "solves" this.

**Comment by jgranick** [comment]
I believe this is the one:

https://caniuse.com/#feat=font-loading

On browsers with support, we receive a callback the moment a webfont has been loaded. If not, we need to poll and continuously look to see if we can figure out if a webfont is actually loaded or not.

We've seen Safari versions that report that they have `windows.fonts.load` but its actually broken. That's the purpose of the user agent code. It sounds like we may need to expand the black list, using something like the answer here:

https://stackoverflow.com/questions/2143763/does-uiwebview-send-the-same-user-agent-in-the-request-headers-as-mobile-safari
