### ISSUE TITLE
touch == primaryTouch failed Chrome  60.0.3080.5  Toggle Device

### ISSUE THREAD

**Issue by dzw** [openfl/lime#1144]
touch == primaryTouch failed Chrome  60.0.3080.5  Toggle Device

run html5 in Chrome  60.0.3080.5  Toggle Device 720x1280 
dubble click  than 
HTML5Window.hx
if (touch == primaryTouch) won't be success

**Comment by dzw** [comment]
click and drag

**Comment by dzw** [comment]
Toggle to mobile Device

**Comment by dzw** [comment]
is there any multitouch property that I can set to false to prevent this issue
if (touch == primaryTouch)

**Comment by jgranick** [comment]
This appears to work fine in Chrome 64.0.3282.140, using the device simulator at 720x1280. Each click, double-click, move and release is coming through as `touch == primaryTouch`, so perhaps this was a bug in the older version of Chrome?
