### ISSUE TITLE
Forget GL.PointSize(size:Int) in lime.graphics.openGL.GL.hx ???

### ISSUE THREAD

**Issue by sourceskyboxer** [openfl/lime#1163]
Hello everyone,

do you have to forget adding feature like old or new version?
Since OpenGL 1.1 was out and it has PointSize() and it has same for newest version too
Check https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_PointSize.xhtml Scroll down to "Version Support"
It has worked for latest version OpenGL too
Please add GL.PointSize(size:Int);

If you don't know than you can find OpenTK's Github and find PointSize(size:int) than you can add to Haxe version. Thanks!

**Comment by jgranick** [comment]
Tracking here: https://github.com/openfl/lime/issues/1211
