### ISSUE TITLE
lime.graphics.utils → gaussianBlur() method draws too smal mask rectangle, when parameter 'quality' = 3

### ISSUE THREAD

**Issue by DarthVan** [openfl/lime#1166]
Hi!
I use OpenFl GlowFilter (based on gaussianBlur()) in my app., and when i set level of quality = 1 or 2, all draws fine, but on level 3 object's glow clippes too closer... 

screenshot:
https://www.dropbox.com/s/3on0s4c9kcuy6c1/scr.png?dl=0

ty!

**Comment by jgranick** [comment]
Do you have a way of reproducing this in a small sample project we could use to test against? Thank you :smile:

**Comment by jgranick** [comment]
I believe it works in current releases, but please let me know otherwise

**Comment by DarthVan** [comment]
Hi! Yep, it works fine now :) but.. for webGL render type only.
If i use DOM or Canvas, filter shows as big blinked rectangle :(  and no mater, what options it has.
Can u fix this too? 

I use FD and build my app to thml5 target.
If needed, i can make simple project for reproduce those bugs. thanks!

**Comment by DarthVan** [comment]
Here an example: https://www.dropbox.com/s/oy61fzww4gqmt9p/FilterBug.7z?dl=0
By default it uses render type 'webGL', but if i change it, all filters breaks.
And one more thing - textFields with applyed GlowFilter draws incorrectly :(

**Comment by Gama11** [comment]
>i use the lastest haxe (4.7.1)

Do you mean 3.4.7? There's no such thing as Haxe 4.7.1.

**Comment by DarthVan** [comment]
oh, ya:) sorry
