### ISSUE TITLE
Android support broken in latest release?

### ISSUE THREAD

**Issue by fameless0x01** [openfl/lime#1179]
1. `lime build android` keeps asking to run `lime setup android` again and again.
I searched the net and found this -http://community.openfl.org/t/lime-build-android-fails-after-lime-setup-android/10429/7
Apparently the xml configuration generated is wrong.

On fixing the config manually, I hit the  issue -

2) lime does not support latest ndk 
I could alsp find this issue here http://community.openfl.org/t/android-ndk-not-building-cant-find-platform-system-directory/9937/12

So is the only solution to use an old ndk? Is a new lime release coming soon?

**Comment by fameless0x01** [comment]
> I think right now, yes.
  
Okay, thank you.
  
> I think it's actually HXCPP that needs to be updated for this, not Lime.
  
I will open an issue for the NDK support in that repo if not already open.
  
But for the wrong xml generation issue I think this is the right place.

**Comment by jgranick** [comment]
Fixed, it was a minor issue between using `<define />` (which `setup` writes now) and `<set />`

`<define />` should be like `<haxedef />` + `<set />` now after the fix
