### ISSUE TITLE
Template file error after upgrading from lime-3.7.4/openfl-4.8.1 to lime-6.3.1/openfl-8.1.0

### ISSUE THREAD

**Issue by derRaab** [openfl/lime#1181]
Hi! We're working an quite a big application using OpenFl targeting Flash / AIR. It was still running on OpenFl 4.8.1 with lime 3.7.4 but since we like to use Electron instead of Adobe AIR we figured it might be a good idea to use the latest library versions for the latest html5 support.

`haxelib run openfl build flash -debug` works just finde with the old setup, but after upgrading to lime-6.3.1 and openfl-8.1.0 build fails with this output:

```
Warning: Could not find template file: haxe
Warning: Could not find template file: flash/hxml
Called from ? line 1
Called from CommandLineTools.hx line 2069
Called from CommandLineTools.hx line 26
Called from a C function
Called from CommandLineTools.hx line 147
Called from CommandLineTools.hx line 740
Called from lime/project/PlatformTarget.hx line 107
Called from lime/tools/platforms/FlashPlatform.hx line 223
Called from /usr/share/haxe/std/neko/_std/sys/io/File.hx line 30
Uncaught exception - [file_contents,Export/flash/haxe/debug.hxml]
```
I know it has something todo with the template files and their locations. With the old setup the autput path for debug was e.g. `Export/flash/debug/haxe/debug.hxml` and for final `Export/final/haxe/final.hxml`. So OpenFl generated two different folders.

Now OpenFl seems to expect `Export/flash/haxe/debug.hxml` but it doesn't exist and won't be generated. In fact, no `haxe` folder will be generated. Just an empty `bin` and `obj/assets.swf`.

I did look into the haxelib directory, but there is no templates folder any more (exists in openfl-4.8.1). Is flash output not supported anymore?

I guess I make an fundamental mistake?

**Comment by derRaab** [comment]
Well, if I upgrade using haxelib set openfl 8.1.0 and haxelib set lime 6.3.1 I get the errors from above. If I then downgrade again - using haxelib set openf 4.8.1 and set lime 3.7.4 I still get the same errors. Uninstall the newer library version doesn't help. Uninstalling Haxe doesn't help either. Just uninstalling everything, restarting and the installing everything again (to the old versions) will make it work again.

Im on the latest macOS.

**Comment by Gama11** [comment]
It it possible that there were some files leftover from the OpenFL 8 build? Have you tried a clean build after switching back to OpenFL 4.8.1?

**Comment by Gama11** [comment]
I can compile OpenFL and Flixel sample projects to Flash just fine with OpenFL 8.1, so this is probably specific to your project in some way. Have you tried with one of the projects from openfl-samples?

**Comment by derRaab** [comment]
I will! But not just yet. I need to get work done now - but I also think there is a specific issue (maybe regarding my build machine) and not a general problem. At least since you tried compiling to flash and it works for you. Are you on macOS?

**Comment by Gama11** [comment]
No, Windows.

**Comment by jgranick** [comment]
Hmm, this seems like a tell-tale sign:

```
Warning: Could not find template file: haxe
Warning: Could not find template file: flash/hxml
```

Perhaps there is an issue here with defines you may have, conflicting with the behavior. Is it possible your project file forces "-Dair"?

I would recommend using the new AIR target instead:

```
lime test air
```

I believe there is no issue here in the tools, but if you have any further issues with your specific project, please let me know. http://community.openfl.org is a great place to discuss if it isn't working
