### ISSUE TITLE
Locale::GetSystemLocale return incorrect language string on iphone 6 plus (ios 11.x.x)

### ISSUE THREAD

**Issue by maaniv** [openfl/lime#1189]
With system language set to Russian on the device, this function return en_RU (with region set to Russia) . Code that reads locales can be found in "project/src/system/Locale.mm".

Workaround:
Replace string
`NSString* locale = [[NSLocale currentLocale] localeIdentifier];`
with
```
NSString* localeLanguage = [[NSLocale preferredLanguages] firstObject];
NSString* localeRegion = [[NSLocale currentLocale] countryCode];
NSString* locale = [[localeLanguage stringByAppendingString:@"_"] stringByAppendingString:localeRegion];
```
Result: returned values will be like "ru-RU_RU" or "en-US_RU"

**Comment by maaniv** [comment]
Diff file for changes.
[locale-diff.txt](https://github.com/openfl/lime/files/2046807/locale-diff.txt)

**Comment by jgranick** [comment]
Merged, thank you :smile:

**Comment by maaniv** [comment]
There are some changes need in lime/system/Locale.hx (it present in locale-diff.txt, that i posted later), because now on ios returned locale string consist of <language_code>-<country code>_<region>:
```
@:noCompletion private function get_language ():String {
		
		if (this != null) {
			
			var index = this.indexOf ("_");
			
			if (index > -1) {
				
                                var dashIndex = this.indexOf ("-");
                                if (dashIndex > -1 && dashIndex < index) index = dashIndex;
				return this.substring (0, index);
				
			}
			
			index = this.indexOf ("-");
			
			if (index > -1) {

```

**Comment by jgranick** [comment]
Done :smile:
