### ISSUE TITLE
Window -static builds fail in some cases

### ISSUE THREAD

**Issue by Gama11** [openfl/lime#1192]
After `lime rebuild windows -static`, `lime build windows -static` on the hello world lime sample fails for me with the following:

```
cannot open input file '<...>\lime\ndll\Windows\liblime.lib'
```

The file in `lime\ndll` is in fact named `liblime-19.lib`, not `liblime.lib`. Manually renaming the file works.

This is likely a flaw in [Lime's logic to determine the correct suffix](https://github.com/openfl/lime/blob/4936156067950d25bbc781cdeb90b87bf6907f00/lime/tools/platforms/WindowsPlatform.hx#L536-L552) - I have both VS 2017 and 2015 installed, and Lime seems to think that as soon as any older versions exist, it can't be VS 2017.

**Comment by jgranick** [comment]
I tried to improve the logic here, let me know if there are still issues. Instead of looking for older installs, it should look for Visual Studio Community being available and/or %VS140COMNTOOLS%.
