### ISSUE TITLE
Alternatives to OpenAL

### ISSUE THREAD

**Issue by larsiusprime** [openfl/lime#1201]
There's been ongoing problems with using OpenAL on certain targets, related either to the implementation itself, or to the fact that some targets require static linking, which OpenAL's license forbids.

We could consider adding alternatives to OpenAL, hidden behind some defines for now, and seeing how it goes. If it goes well enough, we might consider replacing OpenAL entirely.

Candidate one: MojoAL
http://hg.icculus.org/icculus/mojoAL/

MojoAL was written by Ryan Gordon of the SDL team, as a drop-in single C library replacement for OpenAL. It uses the same API but is a different implementation, and has a permissive license rather than the LGPL. The main upside is that this is drop-in and minimal, the downside is that it might be missing a few features. But on certain platforms it may well be more than good enough, especially considering how OpenAL is entirely unavailable on those platforms otherwise.

Candidate two: FAUDIO
https://github.com/flibitijibibo/FACT

FAUDIO is written by Ethan Lee (also an SDL contributor, and the maintainer of FNA). FAUDIO/FACT is a permissively licensed open source reimplementation of XAudio/XACT, part of the DirectX standard. Although the API is not a drop-in for OpenAL, my understanding is it's more full-featured than MojoAL. It could either be hooked into Lime's audio API directly, or maybe we could wrap it to mimic the OpenAL api.

FAUDIO has been in development for a while but I think it's approaching stability based on my conversations with Ethan. It might be ready to start experimenting with on platforms where OpenAL is not available, for instance.

**Comment by larsiusprime** [comment]
I've just been notified that Kha and HEAPS both have implementations they might be interested in sharing. I'll post links if I can get source.

**Comment by larsiusprime** [comment]
I think the Kha stuff is here:
https://github.com/Kode/Kore/blob/master/Sources/Kore/Audio1/Audio.h#L29

**Comment by RobDangerous** [comment]
Kha uses a software mixer (we have a Haxe mixer and a C++ mixer): https://github.com/Kode/Kha/blob/master/Sources/kha/audio2/Audio1.hx
Backends for that are ~100 lines of code: https://github.com/Kode/Kore/blob/master/Backends/System/Android/Sources/Kore/Audio.cpp

It's all super-simple but also very easy to extend. It's great if you want to keep up yourself with how things are working. It's not great if you want a feature-complete drop-in solution.

**Comment by jgranick** [comment]
I'm going to mark this as closed for now, with the addition of MojoAL. We can look at using MojoAL on all or most platforms, with additional testing of performance and consistency.

In the future, I think we should look at adding a second option, but for now, keeping AL retains our lower-level API, which I think is a great start :smile:
