### ISSUE TITLE
Add Windows64 ndll to releases

### ISSUE THREAD

**Issue by intoxopox** [openfl/lime#1202]
Can Windows64 ndll please be added to future releases? I don't really understand why it's not in each release, while the 32 bit Windows one is. I've had to checkout full src and rebuild each release just to get Windows64 ndll, which is no fun.

**Comment by jgranick** [comment]
How does the Windows 64 build compare to the Windows 32 builds in performance and memory?

**Comment by intoxopox** [comment]
I haven't done any benchmarks or profiling, but my very draw-heavy app is noticeably more responsive as 64 bit exe.

**Comment by guruas3** [comment]
My app was working with big bitmapdata consuming a lot of RAM. And my app just crashed with normal 32 build until i switched to 64 one.
