### ISSUE TITLE
How to convert float array to BytePointer?

### ISSUE THREAD

**Issue by darmie** [openfl/lime#1205]
I have a float array 
`var floatData = [0, 0, 0, 1...];`

And I need to pass it into `GL.uniform4fv`,

How do I convert `floatData` to `BytePointer` ?

**Comment by jgranick** [comment]
Hi! Sorry for the delay

Try using `haxe.io.Bytes`, `lime.utils.Bytes` or `lime.utils.Float32Array` instead. Bytes types (like these) should be able to convert into a native pointer properly
