### ISSUE TITLE
broken links 

### ISSUE THREAD

**Issue by raould** [openfl/lime#1223]
i've hit a few broken links across all the lime / openfl sites. please run a link checker on everything. sort of sad when one of the main links is busted.

http://api.openfl.org/lime/
on
http://www.openfl.org/lime/

gives me

403 Forbidden

    Code: AccessDenied
    Message: Access Denied
    RequestId: 678AF8D2569CD353
    HostId: jKBcL9Mq1vbKjEFSBi9hXimnACmkp05uZJC0/FA7XjU08vWXGpwgUbMByG5asnpvWxpfkBH4nyg=

**Comment by jgranick** [comment]
We added a redirect to `openfl.org/lime`, though the API link is broken due to how our API pages are generated. I'm sorry for the inconvenience, and hopefully we can come up with a better system when a page is missing (like a default error page that redirects back to the home page)
