### ISSUE TITLE
iOS HTTPRequest curl_multi_remove_handle bad memory access exception

### ISSUE THREAD

**Issue by maaniv** [openfl/lime#1227]
This exception happens randomly. After (quite) some time reading through the sources I (finally) found the place in CURLBindings.cpp where curl_multi_remove_handle is called (gc_curl function):
```
	value multi_handle = (value)curlMultiReferences[handle];
	curl_multi_remove_handle ((CURLM*)val_data (multi_handle), handle);
	curlMultiReferences.erase (handle);

```
I've replaced the middle line with
`curl_multi_remove_handle ((CURLM*)val_data (multi_handle), (CURL*)val_data (handle));`
and now exception is gone (tho it's so weird that I can't be 100% sure that this is the right solution).

**Comment by jgranick** [comment]
THANK YOU

It's scary this compiled. I really appreciate your help in finding this! It looks you have just the right solution
