### ISSUE TITLE
[Flash] Writer overflow

### ISSUE THREAD

**Issue by mayakwd** [openfl/lime#1236]
Trying to build flash sample with:
- openfl [8.4.1]
- lime [7.0.0]
- format [3.4.1]

Getting:
```
$ openfl test flash
Called from ? line 1
Called from CommandLineTools.hx line 2084
Called from CommandLineTools.hx line 25
Called from CommandLineTools.hx line 146
Called from CommandLineTools.hx line 730
Called from lime/tools/PlatformTarget.hx line 109
Called from FlashPlatform.hx line 202
Called from lime/tools/FlashHelper.hx line 900
Called from lime/tools/FlashHelper.hx line 720
Called from format/swf/Writer.hx line 59
Called from format/swf/Writer.hx line 1270
Called from C:\HaxeToolkit\haxe\std/haxe/io/Output.hx line 206
Uncaught exception - Overflow
```

**Comment by jgranick** [comment]
Could you make sure you have the latest version of the Haxe `format` library, then `openfl rebuild tools` again? Thanks :smile:

**Comment by mayakwd** [comment]
Checked it before creating an issue, updated all libraries, and rebuilt tools.

**Comment by jgranick** [comment]
I've had this issue before, when this code was not in place:

https://github.com/HaxeFoundation/format/commit/13b3da8343d5f102db13bea26e7c830c37e1ac95

We also have this code to guard against an overflow when writing:

https://github.com/HaxeFoundation/format/commit/13b3da8343d5f102db13bea26e7c830c37e1ac95

Perhaps this isn't related to fonts, and instead is trying to write a Flash SWF file that's too large for the Haxe writer to handle.

**Comment by mayakwd** [comment]
Hm, that's weird, I've downgraded openfl to 7.2.1 and lime to 6.2.0 and still facing same issue. Rebuilding tools is not helping. The most weirdest thing that the project have no assets, It's just pure class with project.xml:

```haxe
class Main extends Sprite {
 public function new() {
  super();
 }
}

**Comment by mayakwd** [comment]
Well everything works fine, thanks
