### ISSUE TITLE
ThreadPool

### ISSUE THREAD

**Issue by wenbinshi** [openfl/lime#1242]
怎样使用这个类，代码里面都没有注释0.0

**Comment by jgranick** [comment]
There is a live demo in this video (at 1:24:00):

https://haxe.org/videos/conferences/haxe-summit-us-2018/openfl-advanced-joshua-granick.html

The basic concept is something like:

```haxe
var pool = new ThreadPool (0, 2); // minimum 0 threads, max 2 threads
pool.doWork.add (function (state) {
   // do work
   var result = 100; // can be any type
   pool.sendComplete (result);
});
pool.onComplete.add (function (result) {
   trace ("Work done! " + result);
});
pool.queue ({ state: "can be any type and is optional" });
```

So you 1.) have a worker function (which will run in another thread, so be careful of thread safety), and which can send progress, as well as error or complete status. These methods are thread safe.

Then 2.) `queue` up additional work. Depending on the amount of work, `ThreadPool` can keep threads running, and spin up new threads to process additional work. 

`ThreadPool` is the more complex approach, compared to `BackgroundWorker` for a single thread, or just `Future` for a quick threaded script

**Comment by jgranick** [comment]
Feel free to visit http://community.openfl.org/c/lime as well with any questions :smile:

**Comment by wenbinshi** [comment]
thank you very much@jgranick
