### ISSUE TITLE
Getting started tutorial leads to 404

### ISSUE THREAD

**Issue by CoruNethron** [openfl/lime#1253]
When pressing "Improve this page" within "Getting started" tutorial: https://lime.software/docs/home/ it leads to 404 github page.
Just wanted to add some information about building "SimpleImage" example.

---

What i wanted to add is recomendation, not to use "Msys2" / "Mingw" / "Cygwin" while building html5 example, cause there is issues somewhere within NodeJS, that leads to:

```
CoruNethron@ZOBR MINGW64 /c/pro/haxe/lime/SimpleImage
$ lime test html5

Error: EINVAL, invalid argument
    at new Socket (net.js:156:18)
    at process.stdin (node.js:664:19)
    at Object.<anonymous> (C:\HaxeToolkit\haxe\lib\lime\7,1,1\templates\bin\node\http-server\bin\http-server:161:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Better to use Windows cmd in this case.

---

Also, when setting up windows target and trying to build same example, it's not enough to install just C++ compiler, at least under windows 10, you also need to tick "Windows Universal CRT SDK" to avoid:
`corecrt.h: No such file or directory`
and "Windows 10 SDK", to avoid:
`windows.h: No such file or directory`

**Comment by jgranick** [comment]
Thanks for the feedback! I fixed the "Improve this Page" link, just now, we switch to a separate repository:

https://github.com/openfl/lime.software

Maybe [this page](https://lime.software/docs/advanced-setup/windows/) would be better for the recommendations on setup for Windows C++, and [this page](https://lime.software/docs/advanced-setup/html5/) for HTML5?

Thanks :smile:
