### ISSUE TITLE
lime.text.Font:renderGlyph broken

### ISSUE THREAD

**Issue by imcasper** [openfl/lime#1257]
Lime 6.4.0 all ok.
Lime 7.0.0 and 7.1.1 have exception:

Function "lime.text.Font:renderGlyph" generated exception in line 247:
`var data = bytes.sub (dataPosition, width * height);`

I think that internal function must generate bytes, but it no do:
After call:
`NativeCFFI.lime_font_render_glyph`
I have "bytes" with zero length.

PS For test I use several symbol (F, H, etc.), font "arial.ttf" from windows. All internal data for first view is ok.

**Comment by jgranick** [comment]
I believe this should be resolved on dev:

https://github.com/openfl/lime/commit/6af853b002be9981b739ed07895fa65e7e5c7577
