### ISSUE TITLE
ImageDataUtil.gaussianBlur strength dont work

### ISSUE THREAD

**Issue by imcasper** [openfl/lime#1262]
As I understand it, the function works through two buffers. Each pass "active buffer" is changed. The result of the last operation ("strength" -- alpha multiplication) is ignored. We look at the last lines of the function - the wrong buffer is returned.

PS And not need call expensive alpha multiplication function for strength = 1

https://github.com/openfl/lime/pull/1263

**Comment by imcasper** [comment]
PPS I think, that "strength" can smaller than one:
https://github.com/openfl/lime/pull/1265/commits

**Comment by jgranick** [comment]
This should be resolved in the latest release
