### ISSUE TITLE
Compilation errors with haxe 4 preview 5

### ISSUE THREAD

**Issue by Klug76** [openfl/lime#1270]
When my project is compiled with the latest version of haxe (4preview5), for html5 target, there are three errors:
Haxe4p5/std/haxe/io/Input.hx:309: characters 30-38 : Too many arguments
Haxe4p5/std/js/_std/haxe/io/BytesBuffer.hx:58: characters 24-32 : Too many arguments
Haxe4p5/std/haxe/io/Output.hx:282: characters 29-37 : Too many arguments
Looks like lime/7,1,1/src/haxe/io/Bytes.hx not compatible with Haxe4p5/std/haxe/io/Bytes.hx, because new optional argument _encoding_ has been added:
`public static function ofString( s : String, ?encoding : Encoding ) : Bytes`

**Comment by jgranick** [comment]
Could you try the latest release, made yesterday?

**Comment by Klug76** [comment]
Yes, those errors are gone. But one small problem remains: class lime/7,2,0/src/haxe/io/Bytes has no field `ofHex`.

**Comment by jgranick** [comment]
It should be fixed in Lime 7.2.1

https://github.com/openfl/lime/blob/develop/src/haxe/io/Bytes.hx
