### ISSUE TITLE
Error: "tizen" is an unknown target

### ISSUE THREAD

**Issue by mikewach** [openfl/lime#1272]
Does the Tizen target platform still work? I get the following error when I run `lime test tizen`:

Error: "tizen" is an unknown target

When I run `lime setup tizen` there is nothing output to the command line. I have the following haxelib versions installed to Haxe v3.4.7:

actuate 1.8.9
box2d 1.2.3
hxcpp 4.0.4
layout 1.2.1
lime 7.2.0
openfl 8.7.0
starling 2.4.2

Since I was not prompted to specify the TIZEN_SDK path, I manually added it the Lime config.xml, however that did not resolve this issue. Which versions of the Tizen SDK are supported?

**Comment by jgranick** [comment]
Here's the current status:

https://community.openfl.org/t/openfl-and-tizen/7774/2?u=singmajesty

However, I have tested and confirmed support on a Samsung Z1 using the HTML5 target. It's not as nice as a native target, perhaps, but it is something we're getting for free at the moment :smile:

Happy to help if someone wanted to work on native Tizen support today

**Comment by mikewach** [comment]
Oh Samsung.. I will start with the free option and let you know how well the html5 target goes with my Samsung TV. Thanks for your help!!
