### ISSUE TITLE
Html5 target exception while playing sound after 30 seconds of silence

### ISSUE THREAD

**Issue by maaniv** [openfl/lime#1273]
To reproduce:
play sound, wait greater than 30 secs (don't play any others sounds), play sound again
Latest howler.js from github (v2.1.0) works fine.

**Comment by jgranick** [comment]
I've updated Lime's version of Howler.js to 2.1.0 :grin:

https://github.com/openfl/lime/commit/1ee9f02646d3523fc14244baff81276c52dd437b
