### ISSUE TITLE
Compile error in Vorbis.h/.cpp for windows

### ISSUE THREAD

**Issue by CawawaC** [openfl/lime#1274]
Hi!

I need your help, I can't compile my game for windows: I get errors in Vorbis.h and Vorbis.cpp. Here are the first 2 lines, the rest is long and probably stems from it. Sorry, they are in French ^^'

`include\lime/media/vorbis/Vorbis.h(59): error C2059: erreur de syntaxe : 'constante'
include\lime/media/vorbis/Vorbis.h(59): error C2238: jetons inattendus avant ';'`

Should translate to 
`include\lime/media/vorbis/Vorbis.h(59): error C2059: syntax error: 'constant'
include\lime/media/vorbis/Vorbis.h(59): error C2238: unexpected tokens before ';'`

I tried with both lime 7.2.0 and the git development version.
Fun fact : everything compiles fine for both neko and android.

**Comment by jgranick** [comment]
Which version of Visual Studio C++ are you using?

**Comment by CawawaC** [comment]
For some reason I've got all of them: 2017, 2015 and 2013. But I couldn't find how to point lime to the right one. Where is lime at, which one should I use? And how do I tell lime which one tu use?

**Comment by jgranick** [comment]
It's up to HXCPP to decide which one it wants to use. I think it uses the newest one, or tries to, unless you specify `HXCPP_MSVC`, but that works only for 2013 and older (I think) where there are VCCOMNTOOLS environment variables you can use. Is your HXCPP up-to-date?

**Comment by CawawaC** [comment]
Yes, it's 4.0.4

**Comment by CawawaC** [comment]
Oh wow, perfect, it works! I didn't need that reference anyway ^^
Thank you for the quick and efficient fix, as always 👌
