### ISSUE TITLE
HXCPP static build fails with setupapi-related linkage errors

### ISSUE THREAD

**Issue by Dimous** [openfl/lime#1278]
```
Link: Main.exe
   Creating library Main.lib and object Main.exp
liblime-19.lib(261fc550_hid.obj) : error LNK2001: unresolved external symbol "__imp_SetupDiDestroyDeviceInfoList"
liblime-19.lib(261fc550_hid.obj) : error LNK2001: unresolved external symbol "__imp_SetupDiEnumDeviceInterfaces"
liblime-19.lib(261fc550_hid.obj) : error LNK2001: unresolved external symbol "__imp_SetupDiGetClassDevsA"
liblime-19.lib(261fc550_hid.obj) : error LNK2001: unresolved external symbol "__imp_SetupDiGetDeviceInterfaceDetailA"
liblime-19.lib(261fc550_hid.obj) : error LNK2001: unresolved external symbol "__imp_SetupDiEnumDeviceInfo"
liblime-19.lib(261fc550_hid.obj) : error LNK2001: unresolved external symbol "__imp_SetupDiGetDeviceRegistryPropertyA"
```
|  | version |
|---|---|
| haxe |  4.0.0-preview.5+a37320cb5 |
| openfl | git e11712c3f1ba0795423d59dbb23726b3c9a47620 |
| lime | git 4f5c9a09879332e80abc18ec1d9c5a955debc776 |

I added  `<flag value = "-IC:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\um\x64" />` in `<compiler id="MSVC" if="windows">` block in .hxcpp_config.xml and rebuilt lime with:
```
lime rebuild windows -clean -v -static -64 -D MSVC17+ -D HXCPP_OPTIMIZE_LINK
lime rebuild tools -clean -v
```

**Comment by jgranick** [comment]
I think I just fixed it with this commit, but let me know if it still doesn't build.

A `lime rebuild windows -clean` is a good idea since the last commit in Lime, where we're updating SDL to 2.0.9, which may mean some native dependencies need to be invalidated since the previous compilations

**Comment by Dimous** [comment]
It's working now. Thanks!
