### ISSUE TITLE
Linux target doesn't start unless working directory matches executable

### ISSUE THREAD

**Issue by karliss** [openfl/lime#1284]
Target:
* Lime 7.2.1
* lime-samples 7.0.0
* openfl 8.8.0
* haxe 3.4.7
* Arch Linux

To reproduce:
* Get BunnyMark from lime-samples
* build `lime build linux`
* `cd Export/linux/bin`
* `./BunnyMark` - observe that it runs
* `cd ..`
* `./bin/BunnyMark` - observe error 

> Error : [lime.utils.Preloader] ERROR: There is no asset library with an ID of "default"

Expected behavior:
Executable starts correctly regardless of working directory

**Comment by player-03** [comment]
One way to "fix" this is to make a shell script:

```bash
cd /absolute/path/to/Export/linux/bin
./BunnyMark
```

But why couldn't `main()` do the same? Maybe it could. Just call `Sys.setCwd()` as the very first operation. But... static initializers get run even before `main()`, so there's still an opportunity for errors.

I'd say partial support is worse than no support. The shell script option is simple and guaranteed to work; let's stick with that.

**Comment by player-03** [comment]
Having thought about it more, I came up with another option. (See pull request.)

**Comment by player-03** [comment]
Whoops, I meant to close this when merging that pull request.
