### ISSUE TITLE
Native HTTPRequests returning corrupted data on Neko/Native(?) since 464dc88c447866e2f12368f1b7a7948bf8e27b9a

### ISSUE THREAD

**Issue by Skerper** [openfl/lime#1285]
Since 464dc88c447866e2f12368f1b7a7948bf8e27b9a, using openfl.display.Loader has been frequently returning garbled PNGs or `Unknown error` throws on Neko and presumably CPP targets. When recovered, loaded images are usually loaded to about halfway, then garbled beyond that.

Here is an example:
![image](https://user-images.githubusercontent.com/31716517/52189789-239d1c00-287e-11e9-8261-d17aecad3920.png)

This data was obtained by saving `bytes` to disk in lime/graphics/Image.hx near line 1734; attempting to create a BitmapData object with this data will return null, writing: `libpng error: bad adaptive filter` in the console with no exception thrown. They also cause Loader.load to throw `Unknown error` due to the resultant null BitmapData. Loading via URLRequest will not throw an exception at all, simply yielding a blank BitmapData object. 

Attempting to retry the load, even by creating a new Loader, HTTPRequest, and LoaderContext, will often return the exact same garbled image, often resulting in an endless loop until the program is restarted. This is not mitigated by sleeping or otherwise delaying retries. 

Ocassionally, partially garbled but still blittable images are returned (usually showing discolouration on the bottom 1/5th of the image) with no error thrown.

I initially suspected that something was causing NativeHTTPRequest to throw onComplete prematurely, however tracing out writebytesloaded/total in NativeHTTPRequest.hx around line 450 shows that theory to be incorrect.

I have now found that this issue can be switched on and off like a light by switching lime/project/src/net/curl/CURLBindings.cpp between fa4d47a9ec635eea8a3fab0162c77f9e3ec29366 and 464dc88c447866e2f12368f1b7a7948bf8e27b9a and running `lime rebuild neko`. 

With fa4d47a9ec635eea8a3fab0162c77f9e3ec29366, every load works perfectly first time.

With 464dc88c447866e2f12368f1b7a7948bf8e27b9a, the first load fails almost every time, with about a 50% chance of causing an endless loop of identical failures. The remaining 50% of the time, subsequent loads are successful or succesful after a single retry.

**Comment by jgranick** [comment]
Please try this change:

https://github.com/openfl/lime/commit/864dcf74ccbd1eacb3fc7d54c87fe30dc68a8538

**Comment by Skerper** [comment]
Yep, that seems to have resolved the issue entirely!

**Comment by jgranick** [comment]
Awesome :smile:
