### ISSUE TITLE
Cannot build for hl: Function body required in NativeCFFI.hx

### ISSUE THREAD

**Issue by starry-abyss** [openfl/lime#1288]
I heard that hl target support in lime is beta, but for me even the openfl bunnymark project gives the following error:

```
Running process: D:\build\HaxeDevelop\Tools\fdbuild\fdbuild.exe "D:\build\HaxeToolkit\haxe\lib\openfl-samples\8,7,0\demos\BunnyMark\BunnyMark.hxproj" -ipc 809da870-bb5d-45b2-84d4-04c522b23113 -version "3.4.7" -compiler "D:\build\HaxeToolkit\haxe" -library "D:\build\HaxeDevelop\Library" -target "hl"
Building BunnyMark
Running Pre-Build Command Line...
cmd: "D:\build\HaxeToolkit\haxe/haxelib" run lime build "project.xml" hl -debug -Dfdb
D:/build/HaxeToolkit/haxe/lib/lime/7,2,1/src/lime/_internal/backend/native/NativeCFFI.hx:3435: characters 23-97 : Function body required
Build halted with errors.
Done(1)
```

**Comment by Gama11** [comment]
Looks like you're on Haxe 3.4.7? That would require quite an outdated HL version at this point. The current versions are Haxe 4.0.0-rc.1 and HL 1.9.

**Comment by starry-abyss** [comment]
Ah, looks like haxelib has some 0.1.0 stub or script instead of real hashlink xD
Is there any guide on how to get openfl/lime running on hl, once Haxe 4.0.0-rc.1 is installed and HL 1.9 is downloaded?

**Comment by Gama11** [comment]
Joshua shared some details here recently: https://community.openfl.org/t/hashlink-target-build-problems/11447/2?u=gama11

**Comment by starry-abyss** [comment]
Thanks! Don't have time to test this way right now, but eventually will do!
