### ISSUE TITLE
lime.text.Font:renderGlyph returns garbled image

### ISSUE THREAD

**Issue by zagortenej** [openfl/lime#1301]
Maybe I'm not doing something right or maybe this **is** a bug. To reproduce, run `lime create project font-test` and then add this code to Main.hx:

    import sys.io.File;

    import lime.app.Application;
    import lime.text.Font;
    import lime.utils.Assets;
    import lime.ui.KeyCode;
    import lime.ui.KeyModifier;
    import lime.graphics.ImageFileFormat;

    class Main extends Application {
        
        public function new () {
            super ();
        }

        public override function onKeyDown( keyCode : KeyCode, modifier : KeyModifier ) : Void {

            switch( keyCode ) {

                case KeyCode.ESCAPE:
                    window.close();

                case KeyCode.F:

                var font = Assets.getFont( 'assets/amiri-regular.ttf' );
                var point = 'b';
                var glyph = font.getGlyph( point );
                var img = font.renderGlyph( glyph, 24 );
                var bytes = img.encode( ImageFileFormat.PNG );
                // change path to whatever fits is best
                var outputPath = Sys.environment().get( 'HOME' ) + '/tmp/glyph_' + point + '.png';
                File.saveBytes( outputPath, bytes );
                
                default:
            }
            
        }
    }

Run and press 'F' to get the glyph image saved to PNG.

I've tried `a` `A` `b` and `B`, and got these as a result:
[a.png](https://github.com/zagortenej/stuff/raw/master/lime/renderGlyph/glyph_a.png)
![glyph_a](https://user-images.githubusercontent.com/24719593/55120127-b611ad00-50c2-11e9-830e-416cc6a6b6d4.png)
[A.png](https://github.com/zagortenej/stuff/raw/master/lime/renderGlyph/glyph_A.png)
![glyph_A](https://user-images.githubusercontent.com/24719593/55120235-17d21700-50c3-11e9-8a18-37487998cf59.png)
[b.png](https://github.com/zagortenej/stuff/raw/master/lime/renderGlyph/glyph_b.png)
![glyph_b](https://user-images.githubusercontent.com/24719593/55120209-fcffa280-50c2-11e9-9e10-8137dfb595af.png)
[B.png](https://github.com/zagortenej/stuff/raw/master/lime/renderGlyph/glyph_B.png)
![glyph_B](https://user-images.githubusercontent.com/24719593/55120210-fcffa280-50c2-11e9-87fe-0b542d9fa362.png)

This may or may not be related to #1257

Tried the code above on both 7.2.1 (master) and current `develop` branch, on OSX and Linux, same result (garbled images, not sure if it outputs **the same** images every time).

**Comment by zagortenej** [comment]
While working on some other unrelated issues (but having to do with using PNG images for textures) I connected few dots that bugged me in this issue.

After some spelunking and more testing, here's the thing:

- glyph rendering happens on native side by [call to `FT_Render_Glyph`](https://github.com/openfl/lime/blob/a5de7d83c2b2c8c3ab4993482a66fe32e7d2c67f/project/src/text/Font.cpp#L950). Whatever `FT_Render_Glyph` returned as raw bitmap data is copied verbatim to the output `Bytes`. `FT_Bitmap.pitch` is taken into account here so data being copied into `Bytes` instance has pitch (or `stride`) equal to `FT_Bitmap.width`. So far so good.
- `Font.renderGlyph` creates new `ImageBuffer` and [sets `bitsPerPixel` to **1**](https://github.com/openfl/lime/blob/a5de7d83c2b2c8c3ab4993482a66fe32e7d2c67f/src/lime/text/Font.hx#L241) and this is the first issue, since:
	- it is a fixed value
	- the fixed value _assumes_ `FT_Render_Glyph` always returns 1-bit-per-pixel bitmap
- once `Font.renderGlyph` creates an `ImageBuffer` instance with bitsPerPixel == 1, `ImageBuffer` assumes that buffer data _always_ contains pixels as 32-bit values and returns [fixed `stride` based on this assumption](https://github.com/openfl/lime/blob/a5de7d83c2b2c8c3ab4993482a66fe32e7d2c67f/src/lime/graphics/ImageBuffer.hx#L220)

These two things: bits=per-pixel == 1 and stride == width * 4 result in Image.encode() producing wrong image of the glyph.


The glyph is ultimately rendered by a FreeType's `FT_Renderer` instance called in `FT_Render_Glyph_Internal` function. This function [selects first matching renderer](https://github.com/native-toolkit/freetype/blob/9f306566315a7853c525e70eb667ec36c3b7391e/src/base/ftobjs.c#L4527) for the job. I didn't dig further to figure out what happens there and which renderers are registered and where. It turns out that what `Font.renderGlyph` returns is an 8-bit-per-pixel rendering of requested glyph in all my test cases on Linux, OSX and Windows.

Test Lime app that has workaround for this issue (based on _assumption_ ;)  that `Font.renderGlyph` will always return 8-bpp image) can be found [here](https://github.com/zagortenej/stuff/tree/master/lime/renderGlyph/font-test).

Patches that address fixed values in `Font.hx` and `ImageBuffer.hx` are trivial and that is one reason I didn't create pull request. The other reason is that replacing

	var buffer = new ImageBuffer(new UInt8Array(data), width, height, 1);

with

	var buffer = new ImageBuffer(new UInt8Array(data), width, height, 8);

_still_ assumes that `FT_Render_Glyph_Internal` will always return 8-bpp image, and that doesn't really sounds like a bug fix to me.

**Comment by jgranick** [comment]
I believe that there was an issue (a long time ago) where we accidentally treated `bitsPerPixel` as if it were `bytesPerPixel` -- I think it was resolved everywhere but this function. `Font.renderGlyph` as well as `Font.renderGlyphs` were disabled for a long time due to underlying C++ changes, but `Font.renderGlyphs` as later restored -- and this issue seems to have carried over with it for `renderGlyph`

This should be only the alpha channel.

On the topic of 8-bit images -- I'd love to see improvements for better handling of 8- or 16-bit images in general, like this topic: https://github.com/openfl/lime/issues/872

**Comment by zagortenej** [comment]
Btw, [this line](https://github.com/openfl/lime/blob/a5de7d83c2b2c8c3ab4993482a66fe32e7d2c67f/src/lime/graphics/ImageBuffer.hx#L220) in ImageBuffer also needs to be updated to something like

`return width * bitsPerPixel / 8;`

for this issue with `renderGlyph()` to be fixed. Or `renderGlyph()` could convert 8-bit alpha image to 32-bit image with pixels set to (0,0,0,a) or something. Otherwise the image returned by `renderGlyph()` will still be garbled.

`width * 4` assumes that we always deal with 32-bit pixels, which for `renderGlyph()` is not the case.
