### ISSUE TITLE
Update MojoAL

### ISSUE THREAD

**Issue by larsiusprime** [openfl/lime#1324]
Opening this issue at the request of a friend.

Apparently there's a bug in the version of MojoAL that OpenFL is currently shipping with. Something to do with Spinlocks, or so I'm told.

In any case, the latest version of MojoAL is supposed to solve this, and I **believe** this is the latest & correct version (but I might be wrong):
https://hg.icculus.org/icculus/mojoAL/file/tip/mojoal.c

**Comment by jgranick** [comment]
That matches the version we should be using:

https://github.com/native-toolkit/mojoal

I think the lock fixes (not sure if they are fully stable?) are not officially part of the library yet?

**Comment by player-03** [comment]
Update was merged into 8.2.0-Dev; closing this.
