### ISSUE TITLE
Window::onMove not fired on AIR target

### ISSUE THREAD

**Issue by nixbody** [openfl/lime#1327]
When I use `appWnd.onMove.add(...)` the callback is never called on AIR target. I was able to listen to MOVE events using `NativeWindow` directly like this:
`cast(appWnd.stage, Stage).nativeWindow.addEventListener(NativeWindowBoundsEvent.MOVE, ...)`
but it would be nice to be able to use standard `Window::onMove` so the code could be platform independent.

**Comment by jgranick** [comment]
Thanks for noticing this!

Could you try the above fix and see if it fixes it for you?

**Comment by nixbody** [comment]
Sorry for late response, I had some difficulties building lime from source. Yes, the above fix works for me, thank you! But I noticed that `onResize` event is also not fired. Should I create new issue?

**Comment by jgranick** [comment]
I'm getting resize events here, but perhaps AIR behaves differently with certain window modes?

I just used the following test code in a new OpenFL project:

```haxe
package;

import openfl.display.Sprite;

class Main extends Sprite
{
	public function new()
	{
		super();
		
		stage.window.onResize.add(function(w, h) {
			trace ("RESIZE: " + w + ", " + h);
		});
	}
}
```

**Comment by nixbody** [comment]
Oh, my bad, It actually works correctly, sorry for bothering you. Thanks again for the above fix, much obliged!
