### ISSUE TITLE
Update ios-deploy executable to support iOS 13 devices

### ISSUE THREAD

**Issue by joshtynjala** [openfl/lime#1382]
The current version of _templates/bin/ios-deploy_ used with `openfl test ios` doesn't seem to work with my iPad running iOS 13. I see this error in my terminal:

> Device doesn't support wireless sync.

Locally, I replaced it with the newer ios-deploy v1.10.0, and that seemed to do the trick.

**Comment by player-03** [comment]
Fixed in 1b809a4918780e01f73c9dfdb608ba83a3cfbde7, presumably?
