### ISSUE TITLE
Part Downloads

### ISSUE THREAD

**Issue by sirinath** [openfl/lime#140]
In lime setup please make sure if there is an error it does not download the complete file from the start.

**Comment by jgranick** [comment]
Thank you, I don't think there is a way to support this using the Haxe HTTP API (which "setup" uses currently) but I think we should perhaps look at re-implementing "setup" using cURL instead, which we use in production for Lime/OpenFL projects. I'm sorry for this inconvenience, and thanks for reporting :smile:
