### ISSUE TITLE
The @:generic calls in UIntArray8 and UIntArray32 are causing `Invalid Call` with haxe development head on `lime` command

### ISSUE THREAD

**Issue by 0b1kn00b** [openfl/lime#1413]
Still there in HaxeFoundation/haxe@3ba716717c3839243cc816c6cdc7fb44f6fd830f

**Comment by player-03** [comment]
Probably unrelated, but Haxe 4.2.4 seems to have trouble with `lime.app.Promise` being `@:generic`. Never stopped to figure out why, just commented it out. Someday we'll have to take a closer look at these generics.

**Comment by player-03** [comment]
This is several Haxe versions old by now, and no one else has reported this, so I think it's safe to assume it's fixed.
