### ISSUE TITLE
Lime taking an absurd amount of time to build

### ISSUE THREAD

**Issue by rafaelferreiraql** [openfl/lime#1440]
(Note: I'm using Windows 8)

I'm on HaxeFlixel but I'm assuming the problem is with Lime. Lime is taking _over a full minute_ to build a very basic "Hello World" application on HTML5 (haven't tried other build targets). I've been suggested on the discord that it's just my computer, but I've used other build systems like this one and it didn't take such a ridiculous amount of time to build.  Lime bindings on VSCode also take a similarly long time to activate.

NOTE: I admittedly use an underpowered laptop, 4 gigs RAM and an i3. Still, it should not be an "one minute to build the most basic project" rig.

**Comment by jgranick** [comment]
Can you try `lime test html5 -clean -verbose` and see if it helps indicate where the time is spent?

**Comment by player-03** [comment]
Sounds like a pain, and I agree it shouldn't take that long. But it's three and a half years later, so I assume you either moved on or got a new machine that doesn't have the issue.
