### ISSUE TITLE
[iOS] Signing requires a development team 

### ISSUE THREAD

**Issue by pnkapadia64** [openfl/lime#1459]
I've selected the development team in xcode and the build within xcode works well too. But when running `lime build ios` on terminal, it empties the selected Team field in xcode and gives the error:
```
note: Using new build system
note: Planning build
note: Constructing build description
error: Signing for "<project-name>" requires a development team. Select a development team in the Signing & Capabilities editor. (in target '<project-name>' from project '<project-name>')
```

Lime Command-Line Tools (7.9.0)
Haxe Library Manager 4.0.2
Installed flixel version: 4.9.0

**Comment by player-03** [comment]
I checked through [the documentation](https://lime.software/docs/project-files/xml-format/#certificate) and found this:

```xml
<certificate team-id="ABC" />
```

Also looked at Lime's source code and found some useful-looking undocumented options. I don't think they apply here, but they may come up in the future.

```xml
<config:ios identity="iPhone Developer" />
<config:ios provisioning-profile="ABC" />
```

If none of that helps, it's possible to use your project file as a template, meaning Lime won't overwrite it, but it's far from ideal.

**Comment by pnkapadia64** [comment]
Ok thank you @player-03 , the `team-id` part worked.

Although, `lime build ios` gives an error:
```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MTLSamplerDescriptor", referenced from:
      objc-class-ref in liblime.a(09027d115c01df8eeac9088e2042c6.o)
  "_OBJC_CLASS_$_MTLTextureDescriptor", referenced from:
      objc-class-ref in liblime.a(09027d115c01df8eeac9088e2042c6.o)
  "_OBJC_CLASS_$_MTLRenderPassDescriptor", referenced from:
      objc-class-ref in liblime.a(09027d115c01df8eeac9088e2042c6.o)
  "_OBJC_CLASS_$_MTLVertexDescriptor", referenced from:
      objc-class-ref in liblime.a(09027d115c01df8eeac9088e2042c6.o)
  "_OBJC_CLASS_$_MTLRenderPipelineDescriptor", referenced from:
      objc-class-ref in liblime.a(09027d115c01df8eeac9088e2042c6.o)
  "_MTLCreateSystemDefaultDevice", referenced from:
      _METAL_CreateRenderer in liblime.a(09027d115c01df8eeac9088e2042c6.o)
ld: symbol(s) not found for architecture arm64
```

Building for simulator doesn't give any error.

**Comment by player-03** [comment]
Have you tried `<dependency name="Metal.framework" if="ios" />`?
