### ISSUE TITLE
SDL out of date

### ISSUE THREAD

**Issue by rvh1986** [openfl/lime#1462]
Getting the following error trying to compile to Android:

`> Task :app:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\Drive\DEV\IDEA\SquareSpinner\Export\android\bin\app\src\main\java\org\libsdl\app\SDL.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.`

It looks like this is solved in the latest version of SDL: https://github.com/libsdl-org/SDL/blob/main/android-project/app/src/main/java/org/libsdl/app/SDL.java

I can't find a way to update the SDL.java file in my own project as it gets rebuild every time I compile.

Haxe 4.2.1
Lime 7.9.0
OpenFL 9.1.0

**Comment by player-03** [comment]
Late response, but Lime contains [a template folder for SDL](https://github.com/haxelime/lime/tree/develop/templates/android/template/app/src/main/java/org/libsdl/app). If you overwrite Lime's copy, it'll keep the changes.
