### ISSUE TITLE
Lime is not Building at all

### ISSUE THREAD

**Issue by Xandoshi** [openfl/lime#1463]
(using Windows 7)
So i have been recently been trying to create a mod for an open source game recently, which requires building the whole game to add the items.

However, every time i try to do so, Lime does not build, I First thought it was another haxe item; Polymod. but after removing it from the game, it just did not do anything.

After some research, i tried the -verbose command, and it was just frozen on "msvs WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\" .

I do not know what is going on, i had reinstalled the required items for the game. and lime multiple times. and its just frozen.

Specs if you want them:
Manufacturer: Dell
Model: Inspiron 580
Processor: Intel(R) Core(TM) i3 CPU 550 @3.20GHz 3.20 GHz
Installed Memory (RAM): 8 GB (7.87 GB Usable)
System Type: 64-Bit Operating System.

**Comment by Xandoshi** [comment]
Haxe: 4.1.5
openfl: 9.1.0
Lime: 7.8.0

Command i use are "lime test windows" and "lime build windows" i interchange, but they result in the same freeze.

**Comment by maitag** [comment]
I have simmiliar issue on windows 7 since i installed msvc 2015 community edition.
Native building allways stucks and i need to kill a "powershell.exe" via taskmanager manually to continue building.
