### ISSUE TITLE
GL.getParameter(GL.FRAMEBUFFER_BINDING) - lime_gl_get_parameter - returns null since 1.4 update.

### ISSUE THREAD

**Issue by Greg209** [openfl/lime#149]
A call to lime_gl_get_parameter via GL.getParameter(GL.FRAMEBUFFER_BINDING) now returns NULL since updating to OpenFL 1.4 using 'lime upograde openfl'. It appears (after some investigation) that the new NME backend has some lines commented out - https://github.com/haxenme/nme/blob/master/project/src/opengl/OGLExport.cpp line 369 - but I'm not entirely sure if that's the correct place to look.

Previously this was working and returned the current/default framebuffer which is specifically required to return the original buffer id for iOS, so it can be correctly restored after rendering to texture.

**Comment by jgranick** [comment]
This was fixed, but iOS was also fixed to support `bindFramebuffer` with null to go back to the default framebuffer, so I think that's the real thing we needed. You should be able to use it just like other targets now :smile:
