### ISSUE TITLE
[Android]  Pixel 5/Android 11 issues

### ISSUE THREAD

**Issue by MercutioGraveman** [openfl/lime#1492]
Android 11 turns on Scudo by default, which replaces memory allocation libraries with stricter versions.  In Google Play's automated suite of test devices, only Pixel 5 is running this.  It's catching a heap allocation error, in my app.  But it doesn't provide enough information to locate the source.  I've run Valgrid's Memcheck, DHat, and Massif checks on the Linux build, but they don't point to anything obvious.  Since memory is managed in Haxe, I'd have to try pretty hard to make this happen!

I tried to prepare a minimum test case, but instead of a crash, the app fails to initialize fullscreen and clips away the test text.  This behavior on Pixel 5 is different than the dozens of other phones tested.  Unfortunately, since this isn't a crash it doesn't provide a logcat file.

Here's the test code, although it's not doing anything special:

```
package;

import openfl.display.Sprite;
import flash.text.TextField;
import flash.text.TextFormat;

class SystemFonts extends Sprite {

	public function new () {

		super ();

#if android
		var format = new TextFormat( "/system/fonts/NotoSansCJK-Regular.ttc" );
#else
		var format = new TextFormat( "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc" );
#end

		makeLabel( "ελληνικά", 10, format );
		makeLabel( "Pусский", 20, format );
		makeLabel( "日本", 30, format );
		makeLabel( "中国", 40, format );
	}

	private function makeLabel( str:String, y:Int, format:TextFormat )
	{
		var tf = new TextField();
		tf.embedFonts = false;
		tf.selectable = false;
		tf.defaultTextFormat = format;
		tf.text = str;
		tf.x = 10;
		tf.y = y;
		addChild( tf );
	}

}
```
The blocking issue is screen initialization on this model/OS version, which I'm guessing is a Lime issue.  After that, I can continue layering on OpenFl systems to isolate the memory corruption issues.

**Comment by player-03** [comment]
While this doesn't sound like a [tagged pointers](https://source.android.com/devices/tech/debug/tagged-pointers) issue, can you try setting `android:allowNativeHeapPointerTagging="false"` just to be sure?

**Comment by MercutioGraveman** [comment]
Helps?  That causes all android devices to fail with a null pointer dereference.  It at least provides a traceable stack:

> signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
> Stack frame #00 pc 00435084  /data/app/...==/lib/arm/libApplicationMain.so: Routine openfl::utils::ByteArrayData_obj::readUTFBytes(int) at emutls.c:?

Is this a symptom of the problem or byproduct of the escape hatch?

**Comment by player-03** [comment]
Since I can't reproduce the error, I'd assume it's on your end. Maybe it's the memory allocation, maybe it's the escape hatch, or maybe it's something else entirely.

What happens if you compile a sample project? Here are the steps you can follow to replicate my test:

1. Run `openfl create DisplayingABitmap`.
2. Add these lines to project.xml:
  `<config:android minimum-sdk-version="19" target-sdk-version="31" />`
  `<template path="AndroidManifest.xml" rename="app/src/main/AndroidManifest.xml" />`
3. Copy over [Lime's template](https://github.com/haxelime/lime/blob/develop/templates/android/template/app/src/main/AndroidManifest.xml).
4. Insert `android:allowNativeHeapPointerTagging="false"`.
5. Run `lime test android`.

**Comment by player-03** [comment]
Oh yeah, and if you want actual line numbers in your stack trace, try this line: `<haxedef name="HXCPP_DEBUG_LINK" />`. You'll need to do a clean build (specifically, delete Export/android/obj/) before it'll take effect. (Oh, and make sure not to include it in the release.)

**Comment by MercutioGraveman** [comment]
I shouldn't need to copy over the template if I include in project.xml

>\ <config:android allowNativeHeapPointerTagging="false" />

...right?  I mean, it had pretty big effect, so I'm sure that's working.

The stack trace above is processed with _ndk-stack_ against the libraries compiled with HXCPP_DEBUG_LINK.  Normally I don't upload the build with the symbol information itself, since that would exceed Google's upload limit.  In any case,  _readUTFBytes_ is used in exactly one place in my code, to read in localization files.

```
var bytes:ByteArray = ByteArray.fromFile( 'locale/' + Std.string(language) + '.txt' );
var file:String = bytes.readUTFBytes(bytes.length);

```
Is that the correct method to read in translations?  In the Haxe Cookbook, it said

>\var file:String = sys.io.File.getContent('locale/' + Std.string(language) + '.txt');

...but Android did not like that *at all*.

I'll try DisplayABitmap's code, but it'll have to include the gradle commands to package an app bundle, too.

**Comment by MercutioGraveman** [comment]
So DisplayABitmap behaves like my minimal test code above:  all devices show a full screen image, except Pixel 5 / Android 11.  There, it displays the clear color in a small rectangle -- the size of the system menu before launch.  The video capture shows the bot clicking on it, but nothing else.  And again, since it's not a crash, no logcat output.

This is with the escape hatch enabled, as well.

**Comment by player-03** [comment]
> I shouldn't need to copy over the template if I include in project.xml
> 
>> `<config:android allowNativeHeapPointerTagging="false" />`
> 
> ...right? I mean, it had pretty big effect, so I'm sure that's working.

The tag _must_ end up in Export/android/bin/app/src/main/AndroidManifest.xml for it to have any effect. Check for yourself, and you'll see that it isn't there.

>  Normally I don't upload the build with the symbol information itself, since that would exceed Google's upload limit.

That's perfectly fine.

> Is that the correct method to read in translations? In the Haxe Cookbook, it said
> 
>> `var file:String = sys.io.File.getContent('locale/' + Std.string(language) + '.txt');`
> 
> ...but Android did not like that at all.

That's one way to get a file, but you have to be confident that file path exists. I'm going to guess that in this case, it doesn't.

I think the Haxe Cookbook assumed (a) you weren't using Lime and (b) you'd populate the locale/ folder yourself. When using Lime/OpenFL, it's almost always safer and easier to use the asset system. Then Lime will copy your text files into the APK, saving you the trouble.

(There are also upsides to placing translations in the res/ folder, but that's a lot more advanced. I don't recommend it while you're still debugging.)

**Comment by MercutioGraveman** [comment]
You're right, the escape hatch was missing.  But after after uploading, it made no difference to the minimal test (DisplayABitmap).  Pixel 5 / Android 11 still initializes with a fractional screen size.  I do see a corner of the image, so I know that loaded, at least.

I'll try my entire app next with the escape hatch.  How important is target-sdk-version 31?  I'm using 30, because 31 failed to build complaining something about "android:exported" and I totally didn't want to go down another rabbit hole, before I dealt with the current issues.

**Comment by player-03** [comment]
I think Google wants you to target 30 or above. 31 isn't required yet.

So the sample is rendering correctly other than the screen size? What base size (if any) are you setting in your `<window />` tag?

To get a better view of the boundaries, you could try adding an `Event.RESIZE` listener to the stage, and resize the bitmap to fill the whole screen whenever it's called.

**Comment by MercutioGraveman** [comment]
I use 

>\<window width="0" height="0" fullscreen="true" if="mobile"/>

which is working everywhere except in Android 11.  Which leads me to think that Lime's screen initialization should react to this.

In fact, how could DisplayABitmap, for example, even react to a resize event?  It's simply centering the image.  After the resize event (assuming it comes) the screen is still clipping to this small, off-center rectangle.  An app level bug might require readjusting your GUI aspect ratio, but this seems like an engine level bug.

In Neko, I can resize my app's borders and the screen scales smoothly.  I'm already handling resize.  DisplayABitmap clips the image if the screen is shrunk smaller or draws white outside the image if the resize extends past the image in Neko.  I suspect that somehow the resize signal is never coming in this error case, because none of that is happening.

**Comment by player-03** [comment]
>  &lt;window width="0" height="0" fullscreen="true" if="mobile"/&gt;

I think that's correct. I've always found it weird how you're supposed to do that, but it works.

> In fact, how could DisplayABitmap, for example, even react to a resize event? It's simply centering the image.

Well, you'd re-center the image.

> the screen is still clipping to this small, off-center rectangle.

I've heard of scaling issues happening on certain iOS devices (see #607), but those have long since been fixed.

> I suspect that somehow the resize signal is never coming in this error case, because none of that is happening.

Oh right, you probably need to rotate the phone to generate a resize event. Can you ask your testers to do that? Shouldn't even need to rebuild.

Though if you do make a new build, it wouldn't hurt to get some debug info:

```haxe
function printStageInfo():Void {
    trace('dimensions: ${stage.stageWidth}x${stage.stageHeight}, scale factor:${stage.contentsScaleFactor}`);
}

printStageInfo();
timer.delay(printStageInfo, 500);
```

**Comment by MercutioGraveman** [comment]
That's the problem.  These are Google's automated tests.  I don't have control over them, so I can't simulate a rotation.  They launch the app and a bot monkey clicks until it covers most buttons.  And since the app isn't crashing (now), it doesn't provide a logcat to trace into.

I tried running Android 11 in an emulator to repro locally, but there's no x64 build yet and the ARM64 image runs _super_ slow and just ANRs.  I'll try again with DisplayABitmap and see if that logs anything before the thread watchdog shuts it down.

Android 11 was released a year ago... how is it I'm the first one reporting this?

**Comment by player-03** [comment]
> And since the app isn't crashing (now), it doesn't provide a logcat to trace into.

That's fixable.

```haxe
function printStageInfo():Void {
    trace('dimensions: ${stage.stageWidth}x${stage.stageHeight}, scale factor:${stage.contentsScaleFactor}`);
}

printStageInfo();
Timer.delay(function():Void {
    printStageInfo();
    throw "log this please";
}, 500);
```

> Android 11 was released a year ago... how is it I'm the first one reporting this?

Presumably it doesn't happen on all Android 11 devices. Maybe it's related to Pixel 5 specifically, or maybe it's just this one test device.

**Comment by MercutioGraveman** [comment]
Well, I can't repro on emulator.  The arm64 API 31 image ANRs itself, even before I can install the apk.  

When you say that's fixable, do you mean induce a crash after we trace what we want?  What's the Haxe equivalent of C's *(0x0) = 0?

**Comment by player-03** [comment]
> When you say that's fixable, do you mean induce a crash after we trace what we want?

Exactly.

> What's the Haxe equivalent of C's *(0x0) = 0?

If `throw` doesn't work, try `trace((null:String).length)`.

**Comment by MercutioGraveman** [comment]
All that was too polite.  To get it to crash, I had to 
```
	var a:Sprite = null;
	a.x = 5;
```
On Pixel 5, it printed this twice:

> source/DisplayABitmap.hx:39: dimensions: 2204x1080, scale factor:1

**Comment by player-03** [comment]
Those look about right. Slightly shorter than the screen, but all that means is it's leaving room for the button bar (back/home/recent apps). I guess this confirms it isn't the same as the iOS Retina bug.

I'd be tempted to assume this one test device is messed up, but there's still some debugging you can do if you're up for it.

- Create a ["hello world" app](https://developer.android.com/training/basics/firstapp/creating-project) (including a [simple layout](https://developer.android.com/training/basics/firstapp/building-ui)) in Android Studio. If this is also confined to the corner of the screen, you can stop here because the device is clearly broken.
- Try to see if it's possible to draw beyond the region you seem to be limited to.
  - Place bitmaps beyond the stage bounds.
  - Change the background color.
- Take measurements.
  - Compare the size of the drawable area to the screen. Does it look like it's half as long/wide? A quarter? Does it divide evenly?
  - A [512x200 image](https://github.com/openfl/openfl-samples/blob/master/features/display/DisplayingABitmap/Assets/openfl.png) should take up about a quarter of the screen horizontally and one fifth vertically. Is it scaled to the full screen size or to the drawable area?
  - (Or upload a screenshot here - GitHub supports drag and drop.)
- Open the Android project that Lime generated (Export/android/bin) in Android Studio, and add a simple layout (like in the "hello world" test). Edit [SDLActivity.java](https://github.com/haxelime/lime/blob/develop/templates/android/template/app/src/main/java/org/libsdl/app/SDLActivity.java#L262) to [load it](https://developer.android.com/guide/topics/ui/declaring-layout#load). (Be sure to compile with Gradle and not Lime.)
- Mess around with [SDLSurface](https://github.com/haxelime/lime/blob/develop/templates/android/template/app/src/main/java/org/libsdl/app/SDLActivity.java#L1783-L1786) (specifically the copy in Export/android/bin) and see if you can increase the size of the drawable area. Your changes will be overwritten the next time you compile with Lime, so don't worry about breaking anything.

**Comment by MercutioGraveman** [comment]
The video starts, as on all devices, with the system bar.
![video0](https://user-images.githubusercontent.com/92586527/140736368-c744b6fe-b5da-419c-8639-974fbf8473d0.jpg)

DisplayABitmap is launched on Pixel 5.  Rather than centered and fullscreen, the image is off-center and clipped to the previously displayed system bar.  This image has alpha, so you can see the clear color is grey and is also clipped.
![video](https://user-images.githubusercontent.com/92586527/140736391-d15f6cad-a79b-4129-a66c-cb2531cea222.jpg)

It seems fantastical to me that Google's device image could be faulty.  Stackoverflow would be raging with queries about it.  The two variables here are the device and the OS.  We know the device is the top of the line, so it might be exposing a race condition in Lime initialization.  We did see that screen size is reported correctly, after all.

The other variable is the OS, where we know it's using different libraries for memory allocation.  But this build has the escape hatch invoked.  Does that mean that those libraries are bypassed, or that their errors are squelched instead?  Or the OS could be doing something else different that's testing Lime's initialization assumptions.  But what?

**Comment by player-03** [comment]
Ok, so I tried Android Studio for the first time, and I have some better directions than what I gave above.

1. Open Android Studio.
2. Open DisplayingABitmap/Export/android/bin/build.gradle as a project. (Drag and drop works, or you can click "open project" and navigate.)
3. Go to Navigate -> Class (or press ctrl+N) and type in "SDLActivity."
4. Scroll down to [line 262](https://github.com/haxelime/lime/blob/c743fe10c404fb73003e24100f319a472cb4203f/templates/android/template/app/src/main/java/org/libsdl/app/SDLActivity.java#L262).
5. Change that line to `setContentView(R.layout.main_view);`.
6. You'll get an error message that `R` is not found. Click the error and select "import class."
7. You'll get an error message that there's no layout with that ID. Click the error and tell it to make a new xml file. It'll bring up a space for editing.
8. Drag and drop a few ImageViews from the palette. They'll start out small, but dragging the handles can make them more visible.
9. Go to Build -> Generate Signed Bundle / APK and follow the directions.
10. Upload as normal.

**Comment by MercutioGraveman** [comment]
It drew the ImageView properly in all devices, but the Pixel 5.  Again, the image was clipped off-center, just like the bitmap was.

**Comment by player-03** [comment]
Aha. That narrows it down significantly.

Next step, try again with a brand-new project. Close DisplayingABitmap and create a fresh Android Studio project. The "fullscreen activity" template is probably the closest match, but honestly any of them should work. Keep all the default settings, and optionally toss in an image.

**Comment by MercutioGraveman** [comment]
By default, it made a portrait app.  But all devices extended to the bottom of the screen, including the Pixel 5.  No repro of the bug.

**Comment by player-03** [comment]
Ok, that confirms that it's an issue with Lime, and gives us a much better picture of where the error is. But we need to narrow it down further.

The error is probably in [`SDLActivity`](https://github.com/haxelime/lime/blob/develop/templates/android/template/app/src/main/java/org/libsdl/app/SDLActivity.java), or at least, that's where I'd start. Copy code from DisplayingABitmap into your working project, or vice versa, until you can get your working project to break or DisplayingABitmap to work. Good luck!

**Comment by MercutioGraveman** [comment]
That's way too vague.  My intent in using Haxe/Lime/OpenFl is to abstract away platform specifics.  I've reported and verified a bug in Lime.  If you have a better picture, I'll test your ideas, as a courtesy.  But if I wanted to debug java bugs, I'd write my own.
