### ISSUE TITLE
[Android] Memory leak on playing sounds and musics

### ISSUE THREAD

**Issue by Hasufel** [openfl/lime#153]
If a sound or a music is played, then stopped/replayed repeatedly, ram usage keeps building up, until the ram of the device is full. Device services tend to crash one by one until application itself crashes due to RSS/VSS being completely filled up.
Memory leak surveyed with top on OUYA, and Nvidia Shield.
Test on Ouya, at launch, 358MB taken.
![screen shot 2014-05-01 at 19 09 39](https://cloud.githubusercontent.com/assets/794571/2854699/0061451c-d154-11e3-9eb9-e518c3683f70.png)
After some time, music is replayed on and on and sounds played on and on, 433MB taken
![screen shot 2014-05-01 at 19 12 27](https://cloud.githubusercontent.com/assets/794571/2854713/35853cb2-d154-11e3-90ec-78039dda41c8.png)

Shortly after that, we're hitting the total Ram limit and all services crash one by one. Application finally dies: we did nothing but reading music/sounds.
Totally unrelated, but reminds me a bit of https://github.com/haxenme/nme/pull/64

**Comment by jgranick** [comment]
I think this was resolved, thanks :smile:
