### ISSUE TITLE
libjpeg forks

### ISSUE THREAD

**Issue by player-03** [openfl/lime#1530]
Wikipedia lists [two well-known forks of libjpeg](https://en.wikipedia.org/wiki/Libjpeg#Forks): [libjpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo) is optimized for speed, while [mozjpeg](https://github.com/mozilla/mozjpeg) is optimized for filesize. Should Lime use one of these instead of the original? If so, which?

(Bonus: both are Git repos, meaning they'll be easier to keep up to date.)

**Comment by Apprentice-Alchemist** [comment]
Since lime only does jpeg decoding, the best replacement would be libjpeg-turbo.
MozJPEG is a fork of libjpeg-turbo with improvements for compression and encoding, so it wouldn't provide any advantages for lime.

**Comment by player-03** [comment]
Fair enough. That's probably the same reason Chrome prefers it.

**Comment by player-03** [comment]
Oh right, this didn't get closed because the PR wasn't merged into develop. But in this case, 8.2.0-Dev is just as good, so closing manually.
