### ISSUE TITLE
How to get Android External Storage Directory in haxe?

### ISSUE THREAD

**Issue by MAJigsaw77** [openfl/lime#1553]
im not sure if this function can work in haxe because it will return a java.io.File instad of a string
```
public static function getExternalStorageDirectory():String
{
  var getExternalStorageDirectory_jni = JNI.createStaticMethod("android/os/Environment", "getExternalStorageDirectory", "()Ljava/io/File;");
  return getExternalStorageDirectory_jni();
}
```

**Comment by player-03** [comment]
Yeah, `java.io.File` is definitely not a string, but if you look up [the class reference](https://docs.oracle.com/javase/7/docs/api/java/io/File.html), you can find [how you're supposed to convert to string](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#getAbsolutePath\(\)).

From there you have two options: do the conversion from Haxe or do it in Java. If this is all you'll ever need to do, pure Haxe is fine, but if you're going to need more, I recommend doing the extra work now to save time later.

To do it in Haxe, you need to call `getAbsolutePath()`, which is a member method. I _think_ that would work like this:

```haxe
public static function getExternalStorageDirectory():String
{
	var getExternalStorageDirectory_jni = JNI.createStaticMethod("android/os/Environment", "getExternalStorageDirectory", "()Ljava/io/File;");
	var directoryFile = getExternalStorageDirectory_jni();
	
	var getAbsolutePath_jni = JNI.createMemberMethod("java/io/File",  "getAbsolutePath", "()Ljava/lang/String;");
	return getAbsolutePath_jni(directoryFile);
}
```

To do it in Java, start by making an extension. `openfl create extension PsychEngineJNI` will create a new extension project in its own folder. You could use it as-is, but what you probably want to do is merge it into your main project. Copy the dependencies/ folder, and copy the `<dependencies />` tag from include.xml to Project.xml.

Now you have your own Java class that can more easily call Java functions. Open PsychEngineJNI.java, and replace `sampleMethod()` with your own function:

```java
public static String getExternalStorageDirectory() {
	return android.os.Environment.getExternalStorageDirectory().getAbsolutePath();
}
```

Now you only need one JNI call to get the information in string form.

**Comment by jigsaw-4277821** [comment]
Thanks

**Comment by jigsaw-4277821** [comment]
Ok, in the haxe version the game crashed

**Comment by jigsaw-4277821** [comment]
Can you help?

**Comment by player-03** [comment]
Try the Java version? As I said it's better long-term.

**Comment by jigsaw-4277821** [comment]
I kinda want to try to make it in haxe

**Comment by jigsaw-4277821** [comment]
With jni

**Comment by jigsaw-4277821** [comment]
The java version is working but yeah I want to try in haxe

**Comment by jigsaw-4277821** [comment]
I think the ploblem is when you try to get the absolute path

**Comment by player-03** [comment]
> I think the ploblem is when you try to get the absolute path

Sure it could be, but I can't tell you how to fix it. I reviewed the source code, and it looks like my guess was correct. If it still isn't working... who knows? This isn't documented, so you're kind of doing this blind.

Good luck!

**Comment by MAJigsaw77** [comment]
Thanks

**Comment by MAJigsaw77** [comment]
Ok, @player-03 the haxe version worked! I tested rn

**Comment by player-03** [comment]
Neat! Any idea why it didn't work earlier? Did something change?

**Comment by MAJigsaw77** [comment]
Idk really but now it worked
