### ISSUE TITLE
What happened to the Lime website

### ISSUE THREAD

**Issue by MasterEric** [openfl/lime#1562]
This is what `lime.software` looks like for me right now:

![image](https://user-images.githubusercontent.com/4635334/178088418-a72ff22f-f1bc-4f3e-8f70-356b6aebf27e.png)

**Comment by player-03** [comment]
This was brought up on Discord over a week ago, and they said they're working on a fix. No news since then.

**Comment by player-03** [comment]
Actually there was news since then: [the site has a temporary new home](https://openfl.github.io/lime.software/).

**Comment by loudoweb** [comment]
New website is here: https://lime.openfl.org

Please close the issue.
