### ISSUE TITLE
android x86_64 liblime not found

### ISSUE THREAD

**Issue by 91ebagacm** [openfl/lime#1563]
(NOTE:Github Actions)
![Screenshot_20220711-004742_Chrome](https://user-images.githubusercontent.com/59393483/178163219-c15fc347-7984-4cca-bfa9-86b186b05df6.png)

**Comment by player-03** [comment]
Yeah, at the moment it seems like Lime omits that architecture by default. And I kind of get it: x86 Android devices are rare.

If you're sure you need to support it, you can generate the needed binary yourself using `lime rebuild android -x64`.

**Comment by 91ebagacm** [comment]
damn i waiting i guy he trys make x86_64 lib
