### ISSUE TITLE
-armv6 build failed (-armv5 is same)

### ISSUE THREAD

**Issue by mcagabe19** [openfl/lime#1565]
again github actions
![Screenshot_20220712-015213_Chrome](https://user-images.githubusercontent.com/82843871/178372189-a3b6ded3-a471-40af-80dd-60c8770682c4.png)

**Comment by joshtynjala** [comment]
What command are you running that gives you this error message? You need to provide way more information if you want anyone to help you.

**Comment by mcagabe19** [comment]
i used haxelib run lime build android --app-version="4.0.0" -armv6

**Comment by mcagabe19** [comment]
and after "                      -armv5

**Comment by mcagabe19** [comment]
and again sayed this

**Comment by joshtynjala** [comment]
I found this issue which includes the same error message when building an extension for Android:

luckydog7/Funkin-android#1846

It might be worth trying NDK r15c, if you are using a different version. I've also had success with NDK r21e.

**Comment by mcagabe19** [comment]
thanks nosensly worked

**Comment by player-03** [comment]
What's happening is that hxcpp doesn't support armv6 or armv5 anymore. For newer NDKs, only armv7, arm64, x86, and x64 are allowed.

Switching to an old NDK will work for now, but once #1531 is merged, you'll be required to use the newer version. Even though it isn't required yet, you may want to take this opportunity to begin migrating away from armv6.

**Comment by mcagabe19** [comment]
thanks i using r11c

**Comment by player-03** [comment]
Sure, just remember that you'll have to switch in the future.
