### ISSUE TITLE
Is there a way to call constructor from java class via jni

### ISSUE THREAD

**Issue by Sirox228** [openfl/lime#1566]
![Screenshot_2022-07-13-15-43-31-190_com android chrome](https://user-images.githubusercontent.com/71220271/178737257-d3febf87-845d-47b4-9cf8-749af365d97e.jpg)

i was making a lib that have some of java android classes  ported to haxe via jni, but i need to call constructor, could it be called via jni?

**Comment by player-03** [comment]
It seems there is, though it isn't documented and the code is somewhat confusing. Short version is try this:

```haxe
var processConstructor = JNI.createStaticMethod("android/os/Process", "<init>", "()V");
var process = processConstructor();
```

Where I got this information:

- From [Oracle's documentation](https://docs.oracle.com/en/java/javase/13/docs/specs/jni/functions.html#newobject-newobjecta-newobjectv), you must use `<init>` as the function name and `V` as the return type.
- From [Lime's source code](https://github.com/openfl/lime/blob/d9b35012f4e5d85144ab1119440a8b5eca04d6bb/project/src/system/JNI.cpp#L1726-L1744), you must treat it as a static function, but [internally it treats it as an instance function](https://github.com/openfl/lime/blob/d9b35012f4e5d85144ab1119440a8b5eca04d6bb/project/src/system/JNI.cpp#L1596-L1602). (Thus `createMemberMethod()` won't throw an error, but the function it returns will fail.)
