### ISSUE TITLE
(ThreadPool) Enable multithreading support for HashLink target?

### ISSUE THREAD

**Issue by twilson90** [openfl/lime#1580]
Presumably you just need to change `#if (cpp || neko)` to `#if (cpp || neko || hl)`.

**Comment by player-03** [comment]
I forget if it really was that easy, but I know #1518 resolves this one way or another.

**Comment by joshtynjala** [comment]
Oh! This might be why `NativeHTTPRequest` doesn't seem to dispatch progress events on HL, even though it does on Neko/C++.
