### ISSUE TITLE
Shaders issue

### ISSUE THREAD

**Issue by Sirox228** [openfl/lime#1582]
i was trying to add a shader in my project, but faced some problems, first of all, shaders need to be fully reworked to work in the project, i don't really know about it, but i found some shaders already reworked for lime/openfl projects, they have some variables like ``` openfl_textureCoordv``` and some other things like this that are replacing default shader code, but is there any table or something that lists what need to be edited in shader code to work in project? (i already tried to search for any documentation about this, but didn't find any) also i need to load some new channels to my shader, but i don't know how and i couldn't find any documentation, again. (i mean, i already have sampler2D uniforms, but i can't find the way to load an image/bitmap into them)

**Comment by loudoweb** [comment]
Name of inputs vary depending of the engine so you have to have some understanding of the shader you are porting.

I have started porting some shaders and here are some advices : https://github.com/loudoweb/openfl-shaders#contributions
(please note that my shaders are not 100% complete since I still ignore colorTransform in most of them...)

To set a uniform, you have to do this: 

**vec2**

```
//in your shader
uniform vec2 thickness;
//in haxe
data.thickness.value = [0.1, 0.1];```

**sampler2D**

```
//in your shader
uniform sampler2D foreground;
//in haxe
data.foreground.input = foreground;//foreground is a bitmapData
```

**Comment by Sirox228** [comment]
thanks for the explanation, i know some basics of glsl and basics for adapting it to openfl, but there's 1 problem, it seems that texture() function is not defined in openfl shader api, logs say so and game crashing... there's literally no replacement for that function (just in case, i tried to use ```flixel_texture2D()``` and ```texture2D``` instead but both of them resulted into gray screen)
example of code:
```
        vec3 textex(sampler2D channel, vec3 p)
        {
            vec3 ta = texture(channel, p.xy).xyz;
            vec3 tb = texture(channel, p.xz).xyz;
            vec3 tc = texture(channel, p.yz).xyz;
            return (ta * ta + tb * tb + tc * tc) / 3.0;
        }
```

**Comment by loudoweb** [comment]
You should use `texture2D` on openfl. I guess `flixel_texture2D` is a replacement in Flixel engine.
For the grey screen, maybe your shader is wrong.

**Comment by Sirox228** [comment]
maybe that was happening because i put ```bitmap``` channel into all 3 channels shader use, i need try again, thanks for helping me.

**Comment by loudoweb** [comment]
That would be great to close the issue.

**Comment by Sirox228** [comment]
sorry, i forgot about it ;-;

**Comment by Sirox228** [comment]
sorry for bothering you again, but do you know anything about multi buffer shaders? i just understood that shader i'm using is multi buffer.

**Comment by loudoweb** [comment]
@Sirox228 I don't know this term. You'll have more chances in the discord channel (or maybe the forum).

**Comment by Sirox228** [comment]
where i can find discord channel?
