### ISSUE TITLE
iOS GitHub workflow 

### ISSUE THREAD

**Issue by MAJigsaw77** [openfl/lime#1584]
So basically idk how to make one I tried to make one but it gives errors
https://github.com/MAJigsaw77/FNF-Chain-Saw-Engine/actions/runs/3123048885/jobs/5065406992

**Comment by player-03** [comment]
That isn't a GitHub workflow issue, it's an iOS issue. You'll need to [specify a certificate](https://lime.openfl.org/docs/project-files/xml-format/#certificate).

**Comment by MAJigsaw77** [comment]
Thanks
