### ISSUE TITLE
Is there a way to get a typedef from a String of it's package?

### ISSUE THREAD

**Issue by Sirox228** [openfl/lime#1585]
i was making some hscript api for my app, it have a function that uses ```Type.resolveClass($class);``` and ```Type.resolveEnum($enum);``` to get the class/enum and then sets it to hscript Interp, but the problem is not about hscript at all. it seems that neither or those 2 functions can return typedef, is there any way to get typedef like that?

**Comment by joshtynjala** [comment]
It's probably better to ask a question like this at https://community.haxe.org/, where you can get input from the larger Haxe community. The Lime issues on Github are more for Lime feature requests and Lime bug reports, and it's not really meant as a general forum.

For Lime questions that aren't bugs/features, there's also https://community.openfl.org/. In this case, though, it seems more like a general Haxe question.

You could also consider asking in the Haxe Discord. It's not too hard to find the invite link, I suspect.
