### ISSUE TITLE
pixman gives an error when compiling liblime for android

### ISSUE THREAD

**Issue by Sirox228** [openfl/lime#1586]
i need to compile liblime (the one from `project` folder in this repository)
windows build is fully working, but it seems that android build falls with literally tons of errors in `pixman-arm-neon-asm-bilinear`, also in ndll folder are liblime-64 + hash and liblime-debug-64 + hash, so most likely this happens when building armv7 lib or debug version of arm64, how it can fixed? (i'm asking about that because when downloading lime with haxelib there are builded libs and no project folder, that means that someone from developers successfully built it)
log is attached to this message (not full, because was very big and powershell have text limit)
[LOG.txt](https://github.com/openfl/lime/files/9746514/LOG.txt)

**Comment by Sirox228** [comment]
i think i just found out why this happens, but even in that case, there's big issue.
When calling rebuild lime says that i need to `specify and architecture HXCPP_ARM64, HXCPP_X86 etc...`
but no matter the architecture i specified (with `-D` option) it builds for all 4 architectures and because of that, compilation would die in any project, is there any way to solve this problem with specifying architecture? (i clearly remember, that +- 1 year ago, i was able to rebuild without specifying an architecture and it was fine)

**Comment by joshtynjala** [comment]
You closed this issue, so I assume that means that you solved it on your own. It would be nice if you could share how you did it, just in case someone else ends up here through Google in the future, and they are dealing with the same issue.

https://xkcd.com/979/

**Comment by Sirox228** [comment]
i used ndk r15c and it didn't ask me to specify an architecture and not error

**Comment by player-03** [comment]
[Pixman knows about this issue but doesn't have concrete plans to fix it](https://gitlab.freedesktop.org/pixman/pixman/-/issues/46). In the meantime, we can at least support r21e using the flag `-fno-integrated-as`, which I made sure to include in my submodule update pull request.
