### ISSUE TITLE
Name Changes & File Linking Problems

### ISSUE THREAD

**Issue by Jillinger** [openfl/lime#1595]
I'm using the latest Lime, but getting errors on not finding files.
I'm not sure if this is due to name changes, or what.

For example, KhaApplication.hx is searching for Renderer.hx (import lime.graphics.Renderer;), but this file is missing from the graphics directory.
I'm getting many errors for other missing files.

```
...src/lime/_internal/backend/kha/KhaApplication.hx:5: characters 8-23 : Typenot found : lime.app.Config
...src/lime/_internal/backend/kha/KhaApplication.hx:24: characters 8-49 : Type not found : openfl._internal.renderer.kha.KhaRenderer
...src/lime/_internal/backend/kha/KhaApplication.hx:70: characters 32-38 : Type not found : Config
```

Openfl also has this problem.
```
Type not found : 
openfl._internal.utils.ObjectPool
```

The problem with openfl, is the folder structure being wrong.
The folder structure is - openfl\src\openfl\utils\_internal, and the file ObjectPool.hx is in openfl\src\openfl\utils, not openfl\_internal\utils.

I created a structure that fits the file's query. Only, now that requires changing all the package names. 
`src/openfl/_internal/utils/ObjectPool.hx should be `package openfl._internal.utils;`
I substituted RenderContext.hx for Renderer.hx, which got rid of at least one error in KhaApplication.hx.

I'm trying to manually fix as much as I can, if possible, all. 
If I knew the name changes, or the files replaced, that would be helpful.

**Comment by Jillinger** [comment]
I'm down to three errors.
```
...src/lime/_internal/backend/kha/KhaApplication.hx:5: characters 8-23 : Typenot found : lime.app.Config
...src/lime/_internal/backend/kha/KhaApplication.hx:8: characters 8-30 : Typename lime.graphics.RenderContext is redefined from module lime.graphics.RenderContext
...src/lime/_internal/backend/kha/KhaApplication.hx:71: characters 32-38 : Type not found : Config
```

Does anyone know what has replaced lime/app/Config.hx?

**Comment by player-03** [comment]
`Config` might now be [`lime.tools.ConfigData`](https://github.com/openfl/lime/blob/develop/src/lime/tools/ConfigData.hx), though I'm not sure as that's mainly available at build time.

**Comment by Jillinger** [comment]
I created a dummy config file, and that got rid of the Config error.
```
package lime.app;

class Config {
    // don't knpw what I am doing here
}
```

The Renderer is the remaining problem.
...src/lime/_internal/backend/kha/KhaRenderer.hx:19: characters 21-29 : Type not found : Renderer

Apparently the import line is not the problem, since I created a Renderer.hx file, in the graphics directory, and commenting out the line gives the same error,
The problem is with these lines of code -
```
	private var parent:Renderer;
	...
	public function new(parent:Renderer)
	{
		this.parent = parent;
	}
```
The thing is, I fear not using them will result in errors in other files, since I believe parent was made public, in order to be utilized elsewhere.
I can give it a try.

What does this mean?
`...src/lime/_internal/backend/kha/KhaApplication.hx:8: characters 8-30 : Type name lime.graphics.RenderContext is redefined from module lime.graphics.RenderContext`

**Comment by player-03** [comment]
> I created a dummy config file, and that got rid of the Config error.

But you could also just delete the import.

> src/lime/_internal/backend/kha/KhaRenderer.hx

Ah, I wasn't looking there.

After looking through the other backends, I've concluded that `Renderer` is now `Window`. Every other backend has, [at minimum](https://github.com/openfl/lime/tree/develop/src/lime/_internal/backend/air), a [Backend]Application.hx file and a [Backend]Window.hx file. Also, all the [Backend]Window classes take `parent:Window` as a constructor argument, and assign `this.parent = parent`.

**Comment by Jillinger** [comment]
Changing Render to Window results in so many errors.
```
...lime\src/lime/_internal/backend/kha/KhaApplication.hx:8: characters 8-30 : Typename lime.graphics.RenderContext is redefined from module lime.graphics.RenderContext
...lime\src/lime/graphics/Image.hx:1539: characters 19-25 : Type not found : Reader
...lime\src/lime/graphics/Image.hx:1540: characters 16-21 : Type not found : Tools
...lime\src/lime/graphics/Image.hx:1541: characters 18-23 : Type not found : Tools
...lime\src/lime/graphics/Image.hx:1543: characters 20-38 : Warning : This typedefis deprecated in favor of js.lib.Uint8Array
...lime\src/lime/graphics/Image.hx:1547: characters 19-25 : Float should be Int
...lime\src/lime/graphics/Image.hx:1547: characters 19-25 : ... For function argument 'done'
...lime\src/lime/_internal/backend/html5/HTML5Window.hx:362: characters 36-47 : lime.app._Application.ApplicationBackend has no field framePeriod
...lime\src/lime/_internal/backend/html5/HTML5Window.hx:366: characters 41-52 : lime.app._Application.ApplicationBackend has no field framePeriod
...lime\src/lime/_internal/backend/html5/HTML5Window.hx:372: characters 47-58 : lime.app._Application.ApplicationBackend has no field framePeriod
...lime\src/lime/_internal/backend/html5/HTML5Window.hx:979: characters 75-86 : lime.app._Application.ApplicationBackend has no field framePeriod
...lime\src/lime/_internal/backend/html5/HTML5Window.hx:983: characters 75-86 : lime.app._Application.ApplicationBackend has no field framePeriod
...lime\src/lime/_internal/backend/html5/HTML5Window.hx:987: characters 75-86 : lime.app._Application.ApplicationBackend has no field framePeriod
...lime\src/lime/_internal/backend/kha/KhaRenderer.hx:30: characters 20-23 : Unknown identifier : KHA
...lime\src/lime/_internal/backend/kha/KhaRenderer.hx:31: characters 10-14 : lime.ui.Window has no field type
...lime\src/lime/_internal/backend/kha/KhaRenderer.hx:31: characters 17-20 : Unknown identifier : KHA
...lime\src/lime/_internal/backend/kha/KhaApplication.hx:136: characters 4-43 : Not enough arguments, expected a2:lime.ui.MouseWheelMode
...lime\src/lime/_internal/backend/kha/KhaApplication.hx:80: characters 28-37 : lime.app.Application has no field renderers
...lime\src/lime/_internal/backend/kha/KhaApplication.hx:80: characters 21-37 : You can't iterate on a Dynamic value, please specify Iterator or Iterable
...lime\src/lime/_internal/backend/kha/KhaApplication.hx:82: characters 17-28 : Class<lime._internal.backend.kha.KhaRenderer> has no field framebuffer

```

**Comment by Jillinger** [comment]
Please don't worry with this.
The mistake was mine. I corrected the problem.
haxelib downloads the correct dependencies, and the library I am using requires lime 2.9.1.
Using the latest will result in errors.
Thanks for your response.
Regards

**Comment by player-03** [comment]
> This is a lot of work.

I'm afraid you were just getting started. It seems like Kha support has been neglected for a while, and the classes are severely out of date. (For the record, seeing the big list of errors was a good sign. Those errors were always there, but the compiler wasn't showing them until you fixed the imports.)

> the library I am using requires lime 2.9.1.

In that case, the code wouldn't have worked even after fixing Kha support. Glad you noticed.

You know, I still keep a copy of 2.9.1 around, since one of my projects is still using it and I don't want to put in the work to update my code. (Instead, I'm putting in the work to re-write my code from scratch. Priorities!)
