### ISSUE TITLE
Kha backend out of date

### ISSUE THREAD

**Issue by player-03** [openfl/lime#1596]
The [Kha backend](https://github.com/openfl/lime/tree/develop/src/lime/_internal/backend/kha) has missed out on the past few years of backend updates, and no longer works. It refers to non-existent classes like `Config` and `Renderer`, it's missing now-required functionality like `framePeriod`, and probably more that we didn't get to in #1595.

Based on the other backends, I think `Renderer` is supposed to be `Window`, but I haven't looked into it beyond that because I don't use Kha personally.

**Comment by joshtynjala** [comment]
We might just want to delete it. I'm not sure any core contributors to Lime use Kha.

**Comment by barisyild** [comment]
Lime has never supported the kha backend.

A period was planned but left unfinished, we can see it as cancelled, I think it should be deleted completely.

**Comment by player-03** [comment]
Looks like you're right. I've made a pull request.
