### ISSUE TITLE
lime setup linux fails on Arch 32 bits

### ISSUE THREAD

**Issue by porfirioribeiro** [openfl/lime#160]
When trying to setup lime on my Manjaro(Arch) 32 bits it fails with this error:
```
[porfirio@porf-manjaro ~]$ lime setup linux
error: target not found: multilib-devel
error: target not found: lib32-mesa
error: target not found: lib32-mesa-libgl
error: target not found: lib32-glu
...
Uncaught exception - Error running: sudo pacman -S --needed multilib-devel lib32-mesa lib32-mesa-libgl lib32-glu []
```

As i can see it is trying to install multilib libraries as it was running on a 64 bits OS but since it is runnig on a 32 bits OS it fails.

**Comment by jgranick** [comment]
Thanks, do you have a recommendation for a fix?

**Comment by porfirioribeiro** [comment]
On Arch 32 bits it should be
`sudo pacman -S --needed mesa mesa-libgl glu`
