### ISSUE TITLE
`Uncaught exception Cannot call null` in Lime `8.0.0` Jni?

### ISSUE THREAD

**Issue by MAJigsaw77** [openfl/lime#1602]
`/opt/hostedtoolcache/haxe/4.2.5/x64/lib/extension-androidtools/git/android/os/Build.hx:30: characters 35-113 : Uncaught exception Cannot call null
/opt/hostedtoolcache/haxe/4.2.5/x64/lib/lime/8,0,0/src/lime/system/JNI.hx:190: characters 4-22 : Called from here
/opt/hostedtoolcache/haxe/4.2.5/x64/lib/lime/8,0,0/src/lime/system/JNI.hx:137: characters 3-9 : Called from here
/opt/hostedtoolcache/haxe/4.2.5/x64/lib/extension-androidtools/git/android/os/Build.hx:30: characters 35-107 : Called from here`

This never happened in Lime `7.9.0`.

```
/**
 * The name of the underlying board, like 'goldfish'.
 */
public static final BOARD:String = JNI.createStaticField('android/os/Build', 'BOARD', 'Ljava/lang/String;').get();
```

This is the function if helps with something.

**Comment by player-03** [comment]
Looks like you're using macros now, or importing this class from one that uses macros. Several things don't work in a macro context, and don't always give the best errors. Try this:

```haxe
#if !macro
/**
 * The name of the underlying board, like 'goldfish'.
 */
public static final BOARD:String = JNI.createStaticField('android/os/Build', 'BOARD', 'Ljava/lang/String;').get();
#end
```

**Comment by MAJigsaw77** [comment]
I tryed, same error

**Comment by player-03** [comment]
I mean, it looks like you [only wrapped one JNI call](https://github.com/MAJigsaw77/extension-androidtools/commit/8d3b2b275333796d15eba6e49b40f4820b40d047), and there are several others. Are you sure the new error message is pointing to line 27 and not line 33?

**Comment by player-03** [comment]
Pretty sure that pull request should solve it without needing you to type `#if !macro`.

**Comment by MAJigsaw77** [comment]
A ok
