### ISSUE TITLE
WAV audio assets fail to load in Safari with Lime 8

### ISSUE THREAD

**Issue by brettchalupa** [openfl/lime#1607]
When using OpenFL or HaxeFlixel, assets fail to load in Safari but do load in Firefox and Chrome. I've noticed this issue happens with both .wav and .ogg assets even though Safari supports both of these.

``` console
[lime.utils.AssetLibrary] WARNING: Could not load "assets/click.wav"
```

Here's a zip file for a simple reproduction: 

[OpenFLSoundTest.zip](https://github.com/openfl/lime/files/10144363/OpenFLSoundTest.zip)

Versions:
- Safari 16.0
- Haxe 4.2.5
- Lime 8.0.0
- OpenFL 9.2.0

I'm opening this issue in Lime because the console error comes from `lime.utils.AssetLibrary`, but let me know if OpenFL is a more appropriate project. Happy to share or do anything else I can do to help. Thank you!

Related HaxeFlixel issue: https://github.com/HaxeFlixel/flixel/issues/2687

**Comment by joshtynjala** [comment]
According to this table on MDN, the OGG and PCM/WAV are _not_, in fact, supported by Safari:

https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Cross-browser_audio_basics#audio_codec_support

**Comment by brettchalupa** [comment]
@joshtynjala according to caniuse and my own experiences both work and are supported (although Ogg in Safari is recent with with some restrictions).

- ogg: https://caniuse.com/ogg-vorbis - since ver 14.1, with limitations (1 Partial due to the lack of Ogg container support, and being limited to macOS 11.3 or later.)
- wav: https://caniuse.com/wav - since ver 4

Supporting these open codecs across all of the browsers would be quite helpful to not have to manage converting to MP3 for just Safari, especially since it is now supported.

**Comment by joshtynjala** [comment]
As I understand it, typically _.ogg_ files are an Ogg container with Vorbis audio data. I think that may be what the "lack of Ogg container support" is referring to, which _still_ makes me wonder about support for _.ogg_ files.

Unfortunately, my searches for more information about Ogg support in Safari don't bring up much except the caniuse page, and a lot of people complaining that they can't use Ogg in Safari.

I also found that [Wikipedia seems to use ogv.js](https://www.mediawiki.org/wiki/Extension:TimedMediaHandler/ogv.js) to play _.ogg_ files. Maybe they're still using it for backwards compatibility, or this page is out of date. Again, I can't seem to find anything beyond caniuse.

Well, I might as well just try it...

In HTML, this doesn't seem to work in Safari. Worked fine in Firefox and Chrome, though.

```html
<audio controls src="example.ogg">
```

**Comment by brettchalupa** [comment]
@joshtynjala that makes sense, thanks for the info and details and experimenting. I can confirm on my end that ogg like that doesn't work in Safari as well for me. But the WAV file provided in the Issue description does play without issue. So I'll refine the issue to be that WAV files don't work in Safari with Lime. 👍

**Comment by player-03** [comment]
I'm not familiar with this issue, but if WAV support is fixable, shouldn't we leave this open?
