### ISSUE TITLE
Separated Compile for android architectures

### ISSUE THREAD

**Issue by MAJigsaw77** [openfl/lime#1608]
For example, I want to compile only arm64 and I don't want to compile armv7, what do I do to get this because when I compile android for some reason it compiles armv7 too

**Comment by player-03** [comment]
[The documentation](https://lime.openfl.org/docs/project-files/xml-format/#architecture) appears to be severely out of date, but `<architecture exclude="armv7" />` should still work.

**Comment by MAJigsaw77** [comment]
But if I don't want to compile it, what do I do?

**Comment by player-03** [comment]
By default it compiles armv7 and arm64. The code I posted should exclude armv7. Not sure what you're asking.

**Comment by MAJigsaw77** [comment]
A i got it now

**Comment by MAJigsaw77** [comment]
Thanks foe the info
