### ISSUE TITLE
openfl Shader.hx in haxeflixel project without call

### ISSUE THREAD

**Issue by theTabaxi** [openfl/lime#1618]
The problem boils down to this: I get every time I test a game I'm making with haxeflixel, I get a problem from a file named "WARNING:0" saying "#version directive missing". Along with this, my terminal gets spammed with code, partially following bellow:

[openfl.display.Shader] Info compiling vertex shader
WARNING: 0:8: '' :  #version directive missing

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#endif

attribute float openfl_Alpha;
                attribute vec4 openfl_ColorMultiplier;
                attribute vec4 openfl_ColorOffset;
                attribute vec4 openfl_Position;
                attribute vec2 openfl_TextureCoord;

                varying float openfl_Alphav;
                varying vec4 openfl_ColorMultiplierv;
                varying vec4 openfl_ColorOffsetv;
                varying vec2 openfl_TextureCoordv;

                uniform mat4 openfl_Matrix;
                uniform bool openfl_HasColorTransform;
                uniform vec2 openfl_TextureSize;

                void main(void) {

                        openfl_Alphav = openfl_Alpha;
                openfl_TextureCoordv = openfl_TextureCoord;

                if (openfl_HasColorTransform) {

                        openfl_ColorMultiplierv = openfl_ColorMultiplier;
                        openfl_ColorOffsetv = openfl_ColorOffset / 255.0;

                }

                gl_Position = openfl_Matrix * openfl_Position;

                }
[openfl.display.Shader] Info compiling fragment shader
WARNING: 0:8: '' :  #version directive missing

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#endif

varying float openfl_Alphav;
                varying vec4 openfl_ColorMultiplierv;
                varying vec4 openfl_ColorOffsetv;
                varying vec2 openfl_TextureCoordv;

                uniform bool openfl_HasColorTransform;
                uniform sampler2D openfl_Texture;
                uniform vec2 openfl_TextureSize;

                void main(void) {

                        vec4 color = texture2D (openfl_Texture, openfl_TextureCoordv);

                if (color.a == 0.0) {

                        gl_FragColor = vec4 (0.0, 0.0, 0.0, 0.0);

                } else if (openfl_HasColorTransform) {

                        color = vec4 (color.rgb / color.a, color.a);

                        mat4 colorMultiplier = mat4 (0);
                        colorMultiplier[0][0] = openfl_ColorMultiplierv.x;
                        colorMultiplier[1][1] = openfl_ColorMultiplierv.y;
                        colorMultiplier[2][2] = openfl_ColorMultiplierv.z;
                        colorMultiplier[3][3] = 1.0; // openfl_ColorMultiplierv.w;

                        color = clamp (openfl_ColorOffsetv + (color * colorMultiplier), 0.0, 1.0);

                        if (color.a > 0.0) {

                                gl_FragColor = vec4 (color.rgb * color.a * openfl_Alphav, color.a * openfl_Alphav);

                        } else {

                                gl_FragColor = vec4 (0.0, 0.0, 0.0, 0.0);

                        }

                } else {

                        gl_FragColor = color * openfl_Alphav;

                }

                }
[openfl.display.Shader] Info compiling vertex shader
WARNING: 0:8: '' :  #version directive missing

#ifdef GL_ES
#ifdef GL_FRAGMENT_PRECISION_HIGH
precision highp float;
#else
precision mediump float;
#endif
#endif

attribute float openfl_Alpha;
                attribute vec4 openfl_ColorMultiplier;
                attribute vec4 openfl_ColorOffset;
...

It goes on for a lot longer, put placing it here would be impractical. I don't use the openfl Shader file anywhere in my project, So I guess another file I do use calls it. Can anyone explain what is going on exactly?

**Comment by Dimensionscape** [comment]
Its just a warning and I believe it will display even in a simple application, I think we used to ignore the shader warnings but now they are shown in debug mode. You can disregard it for now until we resolve the warning.

**Comment by theTabaxi** [comment]
Thanks for the clarification.
