### ISSUE TITLE
Unable to load file with non-ASCII name via Bytes.fromFile on Mac/Linux target

### ISSUE THREAD

**Issue by tobil4sk** [openfl/lime#1624]
For example, this returns null when the file clearly exists:
```haxe
lime.utils.Bytes.fromFile("/home/user/é.txt"); // null
```

Files with ASCII names load fine:
```haxe
lime.utils.Bytes.fromFile("/home/user/e.txt"); // returns correct contents
```

This function ends up using SDL_RWFromFile:
https://github.com/openfl/lime/blob/d75b9f9cfaafbca58cafadeaf91475ea36362c8a/project/src/backend/sdl/SDLSystem.cpp#L759

According to the documentation of this function, it should support utf8... so I'm not sure what exactly is going wrong here. See: https://wiki.libsdl.org/SDL2/SDL_RWFromFile

**Comment by tobil4sk** [comment]
So, it seems HXCPP uses [UTF16 for unicode strings](https://haxe.org/manual/std-String-encoding.html), so that would make sense why it doesn't work if UTF8 is expected.

Looks like this problem was solved for Windows but never for Unix systems:
https://github.com/openfl/lime/commit/7a3b9f6b1c8d16060f8fbfdada32ef4b3747316e#diff-32f7dcd12e1b85aaef9967aba781da613f5e834c9934b9fed994eb6b368813bdR634-R636

**Comment by tobil4sk** [comment]
#1472 seems to resolve this issue.

**Comment by Shallowmallow** [comment]
Oh it's kind of important. Wonder why it hasn't been merged.

**Comment by tobil4sk** [comment]
Yes, hopefully it can be merged soon.
