### ISSUE TITLE
Calling Window.alert() on HL returns gibberish

### ISSUE THREAD

**Issue by ThePlank** [openfl/lime#1631]
Calling for example, `stage.window.alert("akjgkdkjgksah", "test");` (i'm using OpenFL) shows messageboxes like this
![image](https://user-images.githubusercontent.com/75984453/217825625-1d5fdf2c-d9c4-4822-b084-4741d204e1b8.png)

Possible encoding issue? May i suggest using `hl.UI.dialog()`?

**Comment by nixbody** [comment]
#1472 also resolves this issue. It's not just encoding, it's also incorrect usage of input parameters in the corresponding C++ function.

**Comment by libauror-a** [comment]
fixed by #1695 i think
