### ISSUE TITLE
audio issues in lime 8.0.1

### ISSUE THREAD

**Issue by Vortex2Oblivion** [openfl/lime#1638]
I've been experiencing an issue where audio will cut out for like half a second and then come back on with like a static noise in between
i downgraded my lime to 8.0.0 and it seemed to fix the issue.
anyone else having this problem?

**Comment by player-03** [comment]
Can you try undoing the changes from #1558 and see if that helps? (Don't forget to `lime rebuild tools`.)

**Comment by Vortex2Oblivion** [comment]
yep that seemed to fix it

**Comment by joshtynjala** [comment]
Since the PR #1639 wasn't a proper resolution, I'm reopening this. Copying some of the discussion for context:

@justin-espedal said:
> [We can't go] back to the previous behavior, which was also buggy.
>
> The only platform the previous behavior was definitively wrong for was iOS. If somebody can't figure out exactly what's going wrong here, perhaps some platform-specific code could be used as a crutch?
>
> What platform are you experiencing issues on, @Vortex2Oblivion?

@ Vortex2Oblivion said:
> im on windows c++

**Comment by joshtynjala** [comment]
@Vortex2Oblivion Did you close this because you are happy with #1646?
