### ISSUE TITLE
SVG clipPath does not work

### ISSUE THREAD

**Issue by DalekCraft2** [openfl/lime#1647]
Lime 8.0.1 (along with OpenFL 9.2.1 and HaxeFlixel 5.2.2), and on the Windows target
I created a very simple SVG file for an icon, and it had a `clipPath` tag for removing a section from one element. I set the icon path to its path in `Project.xml` using the `icon` tag. The SVG looks correct when I view it in Chrome and in the editor what I was using, Inkscape, but the icon shown in the taskbar when running the app had nothing clipped from it.

The icon should look like this:
![icon](https://user-images.githubusercontent.com/50336832/224398798-6182fe67-faee-471d-8b9d-21fec5d6a7a1.png)

But, instead, it looks like this:
![image](https://user-images.githubusercontent.com/50336832/224398746-7826fb6c-3290-4adf-9e0e-3605a36affa6.png)

**Comment by player-03** [comment]
Pretty sure this is an issue with [openfl/svg](https://github.com/openfl/svg). Lime uses that to render them.

**Comment by DalekCraft2** [comment]
I've checked the source; Lime has a its own SVG rasterizer.
[ImageHelper.hx](https://github.com/openfl/lime/blob/develop/src/lime/tools/ImageHelper.hx#L16)
It's used here:
[IconHelper.hx](https://github.com/openfl/lime/blob/develop/src/lime/tools/IconHelper.hx#L364)

**Comment by player-03** [comment]
That function defers to svg.n, a.k.a. the compiled version of openfl/svg.

**Comment by DalekCraft2** [comment]
Ah, okay. Thank you for clarifying.

**Comment by DalekCraft2** [comment]
Closing this because it was on the wrong repository.
