### ISSUE TITLE
Problem of lime test windows

### ISSUE THREAD

**Issue by lez26** [openfl/lime#1649]
Warning: Lime version C:\Users\username\Documents\fridaynightfunkin\lime-develop\tests\runtime\test\lime may not be compatible with OpenFL 9.0.2 (expected version 7.7.*)
Use <lime version="" /> before <haxelib name="openfl" /> to include a specific version
Warning: Could not find template file: cpp/hxml
Error: Could not process argument export/release/windows/haxe/release.hxml (file not found)
Invalid character: /

Sorry if my English is incorrect.
I tried searching for it, but nothing came up.
I tried many different ways but they were no meaning.

Version is lime 7.8.0, haxe 4.1.5 , Open FL 9.0.2 now.

**Comment by joshtynjala** [comment]
It looks like you might have used `haxelib dev` to configure a local version of Lime checked out from Github. I suspect that this path is incorrect: C:\Users\username\Documents\fridaynightfunkin\lime-develop\tests\runtime\test\lime

You probably meant to use this path instead: C:\Users\username\Documents\fridaynightfunkin\lime-develop

**Comment by lez26** [comment]
What should I do?

**Comment by lez26** [comment]
Documents\fridaynightfunkin\lime-develop does not exist
I was deleting files.but the error does not disappear.
I have already lime version 7.8.0 installed.

**Comment by lez26** [comment]
It's strange that even though I deleted the file, the error still persists.

**Comment by player-03** [comment]
Try `haxelib set lime 7.8.0` to switch back to the installed version.

**Comment by joshtynjala** [comment]
> Documents\fridaynightfunkin\lime-develop does not exist

You still need to run `haxelib dev lime` to clear the old path, even if you deleted it:

```sh
haxelib dev lime
```

**Comment by joshtynjala** [comment]
Do you still get these warnings too?

> Warning: Lime version C:\Users\username\Documents\fridaynightfunkin\lime-develop\tests\runtime\test\lime may not be compatible with OpenFL 9.0.2 (expected version 7.7.*)
> Use before to include a specific version
> Warning: Could not find template file: cpp/hxml

Or just the error?

> Error: Could not process argument export/release/windows/haxe/release.hxml (file not found)
Invalid character: /

**Comment by lez26** [comment]
Warning: Lime version C:\Users\username\Documents\fridaynightfunkin\lime-develop\tests\runtime\test\lime may not be compatible with OpenFL 9.0.2 (expected version 7.7.*)
Use <lime version="" /> before <haxelib name="openfl" /> to include a specific version
Warning: Could not find template file: cpp/hxml
Error: Could not process argument export/release/windows/haxe/release.hxml (file not found)
Invalid character: /

This one

**Comment by joshtynjala** [comment]
To be honest, it might just be easiest for you to uninstall Haxe and start fresh.

**Comment by lez26** [comment]
C:\Users\username>haxelib path lime
-L C:\HaxeToolkit\haxe\lib\lime/7,8,0/ndll/
--macro lime._internal.macros.DefineMacro.run()
C:\HaxeToolkit\haxe\lib\lime/7,8,0/src/
-D lime=7.8.0

**Comment by joshtynjala** [comment]
It just doesn't make any sense to me for you to get a warning about _C:\Users\username\Documents\fridaynightfunkin\lime-develop\tests\runtime\test\lime_ when `haxelib path lime` returns _C:\HaxeToolkit\haxe\lib\lime/7,8,0/_.

**Comment by lez26** [comment]
But the error does not disappear. It's strange.

C:\Users\username>haxelib path lime
-L C:\HaxeToolkit\haxe\lib\lime/7,8,0/ndll/
--macro lime._internal.macros.DefineMacro.run()
C:\HaxeToolkit\haxe\lib\lime/7,8,0/src/
-D lime=7.8.0

**Comment by joshtynjala** [comment]
Which command are you using to build the project? Something like this? (it might be `lime` instead of `openfl`... either one is fine)

```sh
openfl build windows
```

You could try adding `-clean` at the end. This will ensure that anything cached in your project directory might not be causing a conflict.

```sh
openfl build windows -clean
```

**Comment by lez26** [comment]
Sorry,I couldn’t it. 
the error doesn't disappear.

C:\Users\username\Documents\fridaynightfunkin\Kade-Engine-1.5.4\Kade-Engine-1.5.4>openfl build windows -clean
Warning: Lime version C:\Users\username\Documents\fridaynightfunkin\lime-develop\tests\runtime\test\lime may not be compatible with OpenFL 9.0.2 (expected version 7.7.*)
Use <lime version="" /> before <haxelib name="openfl" /> to include a specific version
Warning: Could not find template file: cpp/hxml
Error: Could not process argument export/release/windows/haxe/release.hxml (file not found)
Invalid character: /

**Comment by player-03** [comment]
Ok, let's leave this project aside for a moment and try a [Hello World](https://haxeflixel.com/documentation/hello-world/) project.

```cmd
cd C:\Users\username\Documents
flixel tpl -n "HelloWorld"
cd HelloWorld
lime test neko
```

(Replace `username` with your name, of course.)

If that doesn't work, let's back up even further and try an OpenFL sample.

```cmd
haxelib install openfl-samples
cd C:\Users\username\Documents
openfl create DisplayingABitmap
cd DisplayingABitmap
lime test neko
```

**Comment by lez26** [comment]
C:\Users\username\Documents\DisplayingABitmap>lime test neko
Warning: Lime version C:\Users\username\Documents\fridaynightfunkin\lime-develop\tests\runtime\test\lime may not be compatible with OpenFL 9.0.2 (expected version 7.7.*)
Use <lime version="" /> before <haxelib name="openfl" /> to include a specific version
Warning: Could not find template file: neko/hxml
Error: Could not process argument Export/neko/haxe/release.hxml (file not found)
Package name must start with a lowercase letter

What should I do

**Comment by lez26** [comment]
C:\Users\username\Documents\fridaynightfunkin\Kade-Engine-1.5.4\Kade-Engine-1.5.4>flixel tpl -n "HelloWorld"
Copying template files...
Adding project files for Visual Studio Code (can be changed with "flixel setup")...

**Comment by player-03** [comment]
Yeah, something fundamental is definitely broken. Let's try to figure out what.

First, try `lime --version`. If that fails, we have our culprit. Otherwise, try `lime display neko` in the DisplayingABitmap folder.

**Comment by player-03** [comment]
Hmm. There's no include for Lime. I wonder, does `echo %lime%` print anything?

**Comment by lez26** [comment]
C:\Users\username\Documents\fridaynightfunkin\Funkin-master>echo %lime%
C:\Users\username\Documents\fridaynightfunkin\lime-develop\tests\runtime\test\lime

**Comment by player-03** [comment]
That would do it. You'll need to [get rid of that](https://www.howtogeek.com/787217/how-to-edit-environment-variables-on-windows-10-or-11/).

**Comment by lez26** [comment]
Thank you,The error has changed!
C:\Users\username\Documents\fridaynightfunkin\Kade-Engine-1.5.4\Kade-Engine-1.5.4>lime test windows
source/Main.hx:80: characters 59-63 : Float should be Int
source/Main.hx:80: characters 59-63 : For optional function argument 'updateFramerate'
source/StoryMenuState.hx:31: characters 11-12 : Expected ]

**Comment by player-03** [comment]
Does DisplayingABitmap work now? Let's confirm the basics before tackling the big projects.

**Comment by player-03** [comment]
If you just mean DisplayingABitmap doesn't have anything moving, that's normal. It's just an unmoving image in the middle of the stage.

If your whole computer froze, restart I guess?

**Comment by lez26** [comment]
It was right!

**Comment by player-03** [comment]
Ok, no worries. DisplayingABitmap was just to confirm that you can compile at all. Since that's done, you can delete that folder and the HelloWorld folder.

As for the errors in Kade-Engine-1.5.4, those tell you what's wrong.

- "source/Main.hx:80: characters 59-63 : Float should be Int" means that on line 80, you're passing a Float value for `updateFramerate`. You'll need to change it to an Int.
- "source/StoryMenuState.hx:31: characters 11-12 : Expected ]" means you left out a closing square bracket on line 31. (Or just before line 31. This type of error isn't always precise.)

If you install the Haxe and Lime extensions for VS Code, it will underline the errors to make them easier to find.

**Comment by lez26** [comment]
Build succeeded. thank you so much!!
