### ISSUE TITLE
Emoji text input no longer works in Windows (html5 target)

### ISSUE THREAD

**Issue by johnridges** [openfl/lime#1655]
The change in HTML5Window.hx of the Input Element type from 'text' to 'password' (commit e03cc18) has disabled emoji input in Windows (using window-period). This change should only be made for the Android platform.

**Comment by joshtynjala** [comment]
Unfortunately, there's no way to make the change only for the Android platform, since it's the same compiled output for all platforms.

You can add the `lime_enable_html5_ime` define to restore the old behavior, if it helps.

**Comment by player-03** [comment]
> Unfortunately, there's no way to make the change only for the Android platform, since it's the same compiled output for all platforms.

Wait, what? Are you saying it's compiled into the command line tools, and that the command line tools are handling the text fields?

I'm pretty sure that isn't the case, and that a basic `#if android` tag should work.

**Comment by player-03** [comment]
Ignore my earlier comment. I forgot that this was HTML5 target vs. HTML5 target, not HTML5 target vs. Android target.

That said, there should still be a way to detect platform at runtime...

**Comment by joshtynjala** [comment]
Other than checking user agent, which isn't reliable since it can be changed, I'm not sure that there's a good way to detect Android.

Ideally, we'd figure out how to make IME input work in html5. It's a pretty quirky situation, though, with our hidden HTMLInputElement.

**Comment by player-03** [comment]
> which isn't reliable since it can be changed

So what? A user can spoof what system they're on to force the app's keyboard behavior to be slightly worse?

**Comment by joshtynjala** [comment]
Yeah, I guess it's not terrible. I won't argue if you want to implement that.

**Comment by player-03** [comment]
At least for now, I'd say.
