### ISSUE TITLE
HaxeFlixel problem

### ISSUE THREAD

**Issue by MINCREFAT** [openfl/lime#1669]
When I try to run "Filters" from HaxeFlixel demos github folder it says "Standard library not found. You may need to set your `HAXE_STD_PATH` environment variable"

**Comment by MINCREFAT** [comment]
Yes i am using lime command
Proof:
_/\\\\\\______________________________________________
_\////\\\______________________________________________
_____\/\\\_____/\\\_____________________________________
______\/\\\____\///_____/\\\\\__/\\\\\_______/\\\\\\\\___
_______\/\\\_____/\\\__/\\\///\\\\\///\\\___/\\\/////\\\__
________\/\\\____\/\\\_\/\\\_\//\\\__\/\\\__/\\\\\\\\\\\___
_________\/\\\____\/\\\_\/\\\__\/\\\__\/\\\_\//\\///////____
________/\\\\\\\\\_\/\\\_\/\\\__\/\\\__\/\\\__\//\\\\\\\\\\__
________\/////////__\///__\///___\///___\///____\//////////___

**Comment by MINCREFAT** [comment]
fxe
efx

**Comment by Dimensionscape** [comment]
You need to install Haxe
