### ISSUE TITLE
Windows ARM64 Cant Rebuild Lime

### ISSUE THREAD

**Issue by mcagabe19** [openfl/lime#1672]
Im using VS Community 2019 with Windows Server 2022 Datacenter and its says cant find input file opengl32.lib

![image](https://user-images.githubusercontent.com/82843871/234137830-a204327f-5656-4d33-ab5b-6d25b26d2876.png)

Its fixable?

**Comment by player-03** [comment]
The readme says "On a Windows machine, you should have Microsoft Visual Studio C++ (Express is just fine) installed." I'm not familiar with all the versions of Visual Studio, but I know they have [a separate page for Visual Studio with C++](https://visualstudio.microsoft.com/vs/features/cplusplus/). Not sure if you need to download that separately or if you can install the C++ components from within VS 2019.

**Comment by mcagabe19** [comment]
I mean Im already have toolchains and build tools for arm64 and x64 and rebuilding lime for x64 is fine

![image](https://user-images.githubusercontent.com/82843871/234139481-81fc55c9-87dc-4a6f-ba26-0aa1dacba643.png)

I think its a path issue or there is really not a lib there idk

**Comment by player-03** [comment]
Sounds like you do have the right Visual Studio components, then.

I tried looking up "opengl32.lib" and found some confusing but potentially useful information. Maybe one of these can help you.

https://stackoverflow.com/q/73464570
https://stackoverflow.com/q/13986459

**Comment by mcagabe19** [comment]
no one of them worked :( i tried it still the same error and i checked to arm64 folder (in windows sdk) there is no opengl32.lib or .dll i think i needed this lib but i cant find any at internet

**Comment by mcagabe19** [comment]
its like unfixable closing issue if there is a way to fix that reopen issue thanks
