### ISSUE TITLE
Can't build iOS version with XCode 14.2

### ISSUE THREAD

**Issue by buble** [openfl/lime#1675]
i'm trying to use newer Xcode for iOS version of my app

x86 mac - all works just fine like before
macOS Big Sur 11.7.6
XCode 13.2.1 sdk 15.2

Apple silicon mac - can't build
macOS Monterey 12.6.5
Xcode 14.2 sdk 16.2

we are using our lime and openfl forks, however lime should be close to develop version
https://github.com/soccertutor/openfl
https://github.com/soccertutor/lime
haxe 4.2.5
hxcpp 4.3.2

we needed small fix, to avoid error "no such file or directory: 'arm64'"
https://github.com/openfl/lime/commit/29f60aeaf93b4277bdeacc61e56f03392c7060ce
now `lime rebuild ios` command works fine

Looks like this can be common error for ios development
https://stackoverflow.com/questions/74805019/info-plist-contained-no-uiscene-configuration-dictionary-looking-for-configurat

i get this crash at launch

```
(lldb)     command script import "/tmp/6B5F4CEB-08B7-4467-8599-FB515DD80035/fruitstrap_00008112_0011381C0EA3C01E.py"
(lldb)     command script add -f fruitstrap_00008112_0011381C0EA3C01E.connect_command connect
(lldb)     command script add -s asynchronous -f fruitstrap_00008112_0011381C0EA3C01E.run_command run
(lldb)     command script add -s asynchronous -f fruitstrap_00008112_0011381C0EA3C01E.autoexit_command autoexit
(lldb)     command script add -s asynchronous -f fruitstrap_00008112_0011381C0EA3C01E.safequit_command safequit
(lldb)     connect
(lldb)     run
success
(lldb)     autoexit
2023-04-27 21:13:28.833943+0300 TacticsManager[722:77841] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2023-04-27 21:13:29.487623+0300 TacticsManager[722:77841] Unbalanced calls to begin/end appearance transitions for <SDLLaunchScreenController: 0x109009cd0>.
2023-04-27 21:13:29.499189+0300 TacticsManager[722:77841] Unbalanced calls to begin/end appearance transitions for <SDL_uikitviewcontroller: 0x1090154f0>.
2023-04-27 21:13:29.499278+0300 TacticsManager[722:77841] Unbalanced calls to begin/end appearance transitions for <SDL_uikitviewcontroller: 0x1090154f0>.
2023-04-27 21:13:29.499297+0300 TacticsManager[722:77841] Unbalanced calls to begin/end appearance transitions for <SDL_uikitviewcontroller: 0x1090154f0>.
2023-04-27 21:13:29.499354+0300 TacticsManager[722:77841] Unbalanced calls to begin/end appearance transitions for <SDL_uikitviewcontroller: 0x1090154f0>.
libc++abi: terminating with uncaught exception of type Dynamic

PROCESS_STOPPED
  thread #1: tid = 0x13011, 0x00000001fcb05674 libsystem_kernel.dylib`__pthread_kill + 8, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001fcb05674 libsystem_kernel.dylib`__pthread_kill + 8
```

Anyone experienced this?

**Comment by joshtynjala** [comment]
Haxe version? hxcpp version?

**Comment by buble** [comment]
haxe 4.2.5 
hxcpp 4.3.2

**Comment by joshtynjala** [comment]
Give hxcpp 4.2.1 a try.

**Comment by buble** [comment]
hmm, I'll try 
but I need some fixes from 4.3.2

**Comment by joshtynjala** [comment]
`openfl test ios` is working for me with the following configuration:

Haxe 4.2.5
hxcpp 4.3.2
OpenFL 9.2.1
Lime 8.0.1
macOS Ventura 13.3.1 (Apple Silicon)
Xcode 14.3
iOS SDK 16.4

**Comment by joshtynjala** [comment]
> libc++abi: terminating with uncaught exception of type Dynamic

I could be wrong, but that mention "Dynamic" suggest to me that the exception is being thrown from Haxe. It might be something that you can catch, if you can figure out where it's coming from.

It's a tedious process, but you might just need to comment out code until it launches successfully, and then slowly enable more and more code until you can reproduce again to narrow it down.

**Comment by buble** [comment]
@joshtynjala thanks for help
I'll check this

I thought that it was an error 
`2023-04-27 21:13:28.833943+0300 TacticsManager[722:77841] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
`

because same project works fine with older Xcode

**Comment by buble** [comment]
looks like there is a problem in project itself, sample project works fine with Xcode 14.2
