### ISSUE TITLE
Custom Path for ndll's

### ISSUE THREAD

**Issue by MAJigsaw77** [openfl/lime#1676]
Is this possible with the current version of lime?

**Comment by player-03** [comment]
I don't believe so. There are several places where the path is more or less hard-coded.

**Comment by MAJigsaw77** [comment]
This should be a cool future if added cause we would be able to use any dir we want for libs

**Comment by player-03** [comment]
Hang on, are you trying to override lime.ndll, or add your own ndll?

**Comment by MAJigsaw77** [comment]
> Hang on, are you trying to override lime.ndll, or add your own ndll?

Nah, I just want to use another dir then `ndll/Platform` one for libs

**Comment by player-03** [comment]
Can you give an example of a library you're trying to add? I still can't tell if you're trying to override lime.ndll.

**Comment by MAJigsaw77** [comment]
> Can you give an example of a library you're trying to add? I still can't tell if you're trying to override lime.ndll.

For example, I'm trying to add `libvlc.so` into a application and i need to add `ndll` in include.xml but I want to use a custom path for it, to not use `ndll` folder

**Comment by MAJigsaw77** [comment]
I'm not trying to override that lime.ndll xd

**Comment by player-03** [comment]
Ok, I see what you're getting at. Luckily, I think the option you want is available, it just isn't documented. Instead we have to [look at the source code](https://github.com/openfl/lime/blob/468c1933306d72ed2b32014d5ff44ba4bc6cc853/src/lime/tools/ProjectXMLParser.hx#L1282-L1320).

Judging from the source, you can set the following attributes in project.xml:

```xml
<ndll name="[name]" haxelib="[optional]" dir="[subdirectory]" type="[static or dynamic]" register="[optional]" />
```

So try something like `<ndll name="libvlc.so" dir="your/file/path" if="cpp" />`, and if that doesn't work, try `<dependency path="your/file/path/libvlc.so" if="cpp" />`.

**Comment by MAJigsaw77** [comment]
I'll try

**Comment by MAJigsaw77** [comment]
It works, thank you for helping
