### ISSUE TITLE
some kind of error

### ISSUE THREAD

**Issue by ROCK201888** [openfl/lime#1685]
Haxe 4.3.1
Haxelib 3.3.0
openfl 9.2.1
lime 7.8.0

![image](https://github.com/openfl/lime/assets/113576910/85d5a027-4f73-4c63-9da2-83691a109480)

windows x64

**Comment by player-03** [comment]
I don't think Lime 7.8.0 is compatible with OpenFL 9+. Try updating Lime?

Also, since C++ code is involved, what version of hxcpp do you have?

**Comment by ROCK201888** [comment]
lol i fix it myself by using `lime test neko` instead of `lime test windows`

**Comment by player-03** [comment]
Yeah, Neko is nice for testing.

Just be warned that Neko isn't great for distribution. If you want to publish your game as HTML5, it's probably fine. But if and when you want to distribute a downloadable game, you'll want to get `lime test windows` working.

**Comment by ROCK201888** [comment]
then why `lime test neko`  builded the game in the export

**Comment by player-03** [comment]
That's the default folder name.

To be fair, if someone has Neko installed, they can play your Neko game. But most people don't have Neko.

**Comment by ROCK201888** [comment]
so can i let them download the game with neko packaged in

**Comment by player-03** [comment]
That should work. Won't give as good performance as HL or C++, but if it's a lightweight game maybe that's fine.

**Comment by ROCK201888** [comment]
so 1 last question, how do i package it in (i make friday night funkin' i don't know how to control source that much)

**Comment by player-03** [comment]
Not sure, but I seem to recall that Lime does that automatically for HashLink apps. Might be worth a shot.

**Comment by ROCK201888** [comment]
bruh i just wanan know how to fix this `lime test windows` issue

**Comment by player-03** [comment]
> I don't think Lime 7.8.0 is compatible with OpenFL 9+. Try updating Lime?
> 
> Also, since C++ code is involved, what version of hxcpp do you have?

**Comment by ROCK201888** [comment]
hxcpp 4.3.2
Haxe 4.3.1
Haxelib 3.3.0
openfl 9.2.1
lime 8.0.1
flixel 5.3.1

**Comment by player-03** [comment]
Does the same error happen when you [run a Flixel demo](https://haxeflixel.com/documentation/flixel-tools/)?

**Comment by ROCK201888** [comment]
let me try

**Comment by ROCK201888** [comment]
it's the same

**Comment by player-03** [comment]
Hmm. I don't think you're rebuilding tools, but if you were, you'd need [Visual Studio C++](https://visualstudio.microsoft.com/vs/features/cplusplus/). Might be worth grabbing regardless.

Also, try `lime setup windows` and see if it has any suggestions.

**Comment by ROCK201888** [comment]
mmm i have vs c++ already

**Comment by ROCK201888** [comment]
so how to fix
![image](https://github.com/openfl/lime/assets/113576910/a0b61e3b-a311-431e-9a12-19bc8b93491f)
![image](https://github.com/openfl/lime/assets/113576910/fd96fcb7-4a14-4443-ac23-3d855ec4fec2)

**Comment by player-03** [comment]
It really should work if you have the right version installed. Maybe uninstall and reinstall [from the C++ page](https://visualstudio.microsoft.com/vs/features/cplusplus/).

**Comment by ROCK201888** [comment]
nothing changed

**Comment by player-03** [comment]
FNF still claims to need [Haxe 4.1.5](https://haxe.org/download/version/4.1.5/). (Would be nice if they'd fix that. Haxe 4.3 offers some excellent features.)

I don't see how the Haxe version could be the source of this issue, but at this point I don't know what else to try.

Edit: they also have some Windows-specific instructions.

> For Windows, you need to install Visual Studio Community 2019. While installing VSC, don't click on any of the options to install workloads. Instead, go to the individual components tab and choose the following:
> 
>     MSVC v142 - VS 2019 C++ x64/x86 build tools
>     Windows SDK (10.0.17763.0)

**Comment by Apprentice-Alchemist** [comment]
The easy fix would be to compile with `-D lime_disable_gpu_hint`.
The proper fix would be to figure out why your C++ compiler doesn't support `_declspec`.
One thing to try is to replace `_declspec` with `__declspec` here: https://github.com/openfl/lime/blob/deecd6c6f872f2855a879d8006dfb97f63134f84/src/lime/system/System.hx#L39-L40
Although if you're using MSVC it should support `_declspec` unless something is passing `/Za` to the C compiler...

**Comment by ROCK201888** [comment]
now it give me this error
![image](https://github.com/openfl/lime/assets/113576910/79611834-7ef7-45a2-b160-7d7f733ce259)

**Comment by Apprentice-Alchemist** [comment]
...are you using Mingw or something?
That error can only happen if you're using GCC/Clang instead of MSVC.

**Comment by ROCK201888** [comment]
let me retry...

**Comment by ROCK201888** [comment]
![image](https://github.com/openfl/lime/assets/113576910/d5f46369-5550-4500-8953-f942a54b0a28)
now this happens

**Comment by player-03** [comment]
Not sure why we never responded to that last one, but for the record, you can set environment variables from the system settings (just search the computer for "environment variable"). You'd make a new variable named `MINGW_ROOT` with the MinGW folder as the value.

But this is a year late and you probably either figured that out or moved on, so it's time to close this.
