### ISSUE TITLE
a hell amount of errors when rebuilding lime

### ISSUE THREAD

**Issue by ghost** [openfl/lime#1686]
in arm64 linux and im really tired help [pt2.txt](https://github.com/openfl/lime/files/11470225/pt2.txt)

**Comment by player-03** [comment]
Per the readme, you need these packages (or similar) to build on Linux.

```bash
sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev g++ g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev
```

**Comment by ghost** [comment]
> Per the readme, you need these packages (or similar) to build on Linux.
> 
> ```shell
> sudo apt-get install libgl1-mesa-dev libglu1-mesa-dev g++ g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev
> ```

installed already and even tried reinstall from debian unstable repo no change and multilibs not exists in arm64

**Comment by ghost** [comment]
fixed somehow
