### ISSUE TITLE
File Dialog and Google Drive Conflict when opening/saving a file.  

### ISSUE THREAD

**Issue by hoangdung-qbt** [openfl/lime#1696]
**Platform: Windows 10
HxCpp 4.3.2
Lime 8.0.2
OpenFL 9.2.1
Haxe 4.2.5**
Neko/C++
Code:
```
b = bitmapData.encode(bitmapData.rect, new JPEGEncoderOptions(70));
fd = new FileDialog();
fd.save(b, "jpg", dest, "Lime Exmaple");
fd.onSave.add (function(path:String):Void{});
```
**Errors:**
_[10284:ShellIpcClient] shell_ipc_client.cc:116:Connect Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_z8080_shell
[10284:ShellIpcClient] shell_ipc_client.cc:116:Connect Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_z8080_shell
[13220:ShellIpcClient] shell_ipc_client.cc:116:Connect Can't connect to socket at: \\.\Pipe\GoogleDriveFSPipe_z8080_shell_

Workaround: turn on GDrive for syncing, this error is completely gone

**Comment by joshtynjala** [comment]
This does not appear to be a Lime or Haxe issue. I can see many questions on StackOverflow for other programming languages where the same warning is reported. It seems to be a GDrive issue.
