### ISSUE TITLE
Clipboard does not return text in HTML5

### ISSUE THREAD

**Issue by DigiEggz** [openfl/lime#1703]
When running an HTML5 javascript app, no text is returned when accessing Clipboard.text. Desktop access works properly, however.

**Comment by joshtynjala** [comment]
In web browsers, JavaScript is not allowed to read from the clipboard unless the user explicitly uses the Ctrl+V keyboard shortcut or selects Paste from the edit menu. This is a security restriction that we have no control over.

**Comment by DigiEggz** [comment]
The code is partially working. I was tracing out the `value` in the `set_text()`function of Clipboard and I can see the correct text.

 If I comment out the `__update()` within `get_text`, it correctly pastes the text when I use a keyboard shortcut. I'll keep testing things out.
