### ISSUE TITLE
webify for linux armhf/arm64???

### ISSUE THREAD

**Issue by ghost** [openfl/lime#1706]
idk haskell and I'm using [termux proot-distro](https://github.com/termux/proot-distro)
can anyone help me?

**Comment by joshtynjala** [comment]
Just adding some context.

I see that we have some executables named webify in _templates/bin_. They seem to be for generating webfonts. Probably this project: https://github.com/ananthakumaran/webify

I assume that this is a request to add webify executables for Linux armhf/arm64 too. We currently support x86/x64 only. I don't think any of our bundled executables support ARM yet.

**Comment by ghost** [comment]
> Just adding some context.
> 
> I see that we have some executables named webify in _templates/bin_. They seem to be for generating webfonts. Probably this project: https://github.com/ananthakumaran/webify
> 
> I assume that this is a request to add webify executables for Linux armhf/arm64 too. We currently support x86/x64 only. I don't think any of our bundled executables support ARM yet.

I'm trying to build rn if I did any progress I will tell you

**Comment by ghost** [comment]
@joshtynjala I've got webify builded in proot if you want close this issue and I can send files
