### ISSUE TITLE
Problem with compile on Hashlink

### ISSUE THREAD

**Issue by ghost** [openfl/lime#1710]
I want to compile the game on Hashlink, but I get an error

``D:\Projects\hashlink\src\module.c(513) : FATAL ERROR : Invalid signature for function lime@hl_audio_load_file : POBi_OiiOiOiB_iiii_iDDDDDOiD_i__OiiOiOiB_iiii_iDDDDDOiD_i_ required but POBi_OiiOiOiB_iiii_iDDDDDOiD___OiiOiOiB_iiii_iDDDDDOiD__ found in hdll``

What should I do?

**Comment by player-03** [comment]
Are you using the Haxelib or Git version of Lime? And if Git, which branch?

**Comment by ghost** [comment]
Haxelib

**Comment by ghost** [comment]
I understand everything, it turns out I have a modified AudioBuffer, which is saved in "source / lime / media" and that's why it doesn't compile for me.
