### ISSUE TITLE
Encoding bug I found within Hashlink

### ISSUE THREAD

**Issue by moxie-coder** [openfl/lime#1711]
Whenever I use the [alert](https://lime.openfl.org/api/lime/ui/Window.html#alert) method from Window in hashlink, it seems to be using the wrong encoding for the text as shown in the screenshot below.

![image](https://github.com/openfl/lime/assets/124418090/d7196fc9-2fc6-427c-a602-24e0bf653958)

**Comment by libauror-a** [comment]
duplicate of #1631

**Comment by moxie-coder** [comment]
oops
