### ISSUE TITLE
can I set the default architecture of lime?

### ISSUE THREAD

**Issue by I-am-someone-sh** [openfl/lime#1713]
is it possible?
help me

**Comment by player-03** [comment]
Try the [`<architecture />` tag](https://lime.openfl.org/docs/project-files/xml-format/#architecture):

```xml
<architecture name="armv7" />
<architecture name="arm64" />
<architecture exclude="x86" />
<architecture exclude="x64" />
```

Not sure you need all of those, but I'm guessing you at least want `arm64`.

Edit: oh wait, you said you're using x86? Then maybe invert it.

```xml
<architecture exclude="armv7" />
<architecture exclude="arm64" />
<architecture name="x86" />
<architecture name="x64" />
```

**Comment by I-am-someone-sh** [comment]
> 

thanks I will try it

**Comment by I-am-someone-sh** [comment]
> Try the [`<architecture />` tag](https://lime.openfl.org/docs/project-files/xml-format/#architecture):
> 
> ```
> <architecture name="armv7" />
> <architecture name="arm64" />
> <architecture exclude="x86" />
> <architecture exclude="x64" />
> ```
> 
> Not sure you need all of those, but I'm guessing you at least want `arm64`.
> 
> Edit: oh wait, you said you're using x86? Then maybe invert it.

> 
> ```
> <architecture exclude="armv7" />
> <architecture exclude="arm64" />
> <architecture name="x86" />
> <architecture name="x64" />
> ```
is not work, I build as x86_64 but is now the default is arm64 although I add "architecture" to the project.xml
there is my old screenshot of my first time to build macos as x86_64
![Screen Shot 2023-09-08 at 07 08 53](https://github.com/openfl/lime/assets/134118442/29759a62-a0f0-4e69-96ac-57fbc9cfa8e5)
