### ISSUE TITLE
Android build failed, unexpected character: '\''

### ISSUE THREAD

**Issue by DinoMah** [openfl/lime#1719]
I'm using Lime 8.1.0, NDK 20.0.5594570

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Carlos\Documents\Haxe\Flixel\4Blind\export\android\bin\build.gradle' line: 48

* What went wrong:
Could not compile build file 'C:\Users\Carlos\Documents\Haxe\Flixel\4Blind\export\android\bin\build.gradle'.
> startup failed:
  build file 'C:\Users\Carlos\Documents\Haxe\Flixel\4Blind\export\android\bin\build.gradle': 48: Unexpected character: '\'' @ line 48, column 11.
                ndkPath 'C\:\\Users\\Carlos\\AppData\\Local\\Android\\Sdk\\ndk\\20.0.5594570'
               ^

**Comment by player-03** [comment]
Try either NDK [r15c](https://github.com/android/ndk/wiki/Unsupported-Downloads#r15c) or [r21e](https://github.com/android/ndk/wiki/Unsupported-Downloads#r21e).

**Comment by DinoMah** [comment]
Don't know whats happening with lime that adds C\: to the ndk path (like escaping :) or is missing one \, I just update lime to 8.1.0

**Comment by player-03** [comment]
Are you on Windows? If so, is "C:\Users\Carlos\Documents\Haxe\Flixel\4Blind" correct?

Also, be sure to try NDK r15c or r21e.

**Comment by DinoMah** [comment]
Yes, I was planning to update from something newer than r15c and tried r21e, it compiled with r21e but gave me error at launch
![image](https://github.com/openfl/lime/assets/42949369/d3d97be7-202b-4c87-b791-46d847236df4)

**Comment by player-03** [comment]
Honestly, that's what I'd expect from r21e. It was never compatible with Lime 8.1.0 and below, but some people reported using it anyway. So I figured, maybe it worked as long as you don't rebuild the ndlls?

If you've run `lime rebuild android` at any point, maybe all you need to do is redownload the ndlls from Haxelib. Otherwise, I think your only options are to downgrade to NDK r15c or upgrade to Lime 8.2.0-Dev.

**Comment by DinoMah** [comment]
I found this comment in openfl release page and did what this user said and it worked perfect[https://community.openfl.org/t/openfl-9-3-0-and-lime-8-1-0-release/13807/8](url)
I can close this C:

**Comment by DinoMah** [comment]
I found this comment in openfl release page and did what this user said and it worked perfectly
[https://community.openfl.org/t/openfl-9-3-0-and-lime-8-1-0-release/13807/8](https://github.com/openfl/lime/issues/url)
I can close this C:

**Comment by player-03** [comment]
Glad you got it working! As I mentioned in that thread, `<` is technically incorrect and you'd be better off commenting the line, but it likely won't matter as long as you never need to use an old Gradle plugin.

**Comment by joshtynjala** [comment]
> Honestly, that's what I'd expect from r21e. It was never compatible with Lime 8.1.0 and below, but some people reported using it anyway. So I figured, maybe it worked as long as you don't rebuild the ndlls?

If I remember correctly, r21e may have worked with the previous Haxe and hxcpp 4.2 releases, but stopped working after the Haxe and hxcpp 4.3 updates.
