### ISSUE TITLE
Issue involving lime.ndll

### ISSUE THREAD

**Issue by moxie-coder** [openfl/lime#1747]
After an failed to attempt to compile on Windows, this just now happens

I'm on the latest git lime, and haxe 4.3.3

```
Called from ? line 1
Called from CommandLineTools.hx line 1903
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 125
Called from CommandLineTools.hx line 640
Called from lime/tools/PlatformTarget.hx line 107
Called from WindowsPlatform.hx line 305
Called from a C function
Called from lime/tools/ProjectHelper.hx line 57
Called from hxp/Log.hx line 50
Called from hxp/Log.hx line 152
Called from a C function
Called from C:\HaxeToolkit\haxe\std/neko/Lib.hx line 43
Uncaught exception - load.c(237) : Failed to load library : D:\HaxeToolkit\haxe\lib\lime\git//ndll/Windows/lime.ndll
```

**Comment by moxie-coder** [comment]
EDIT: tried to delete it, now this happens
```
Called from ? line 1
Called from CommandLineTools.hx line 1903
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 125
Called from CommandLineTools.hx line 640
Called from lime/tools/PlatformTarget.hx line 107
Called from WindowsPlatform.hx line 305
Called from a C function
Called from lime/tools/ProjectHelper.hx line 57
Called from hxp/Log.hx line 50
Called from hxp/Log.hx line 152
Called from a C function
Called from C:\HaxeToolkit\haxe\std/neko/Lib.hx line 43
Uncaught exception - load.c(237) : Failed to load library : lime.ndll
```
great
**great**

**Comment by player-03** [comment]
You can copy lime.ndll from the latest Haxelib release of Lime.

If this happened because you switched to 8.2.0-Dev, you'll need to get it from an actions run, or go through the trouble of rebuilding it yourself.

**Comment by moxie-coder** [comment]
> You can copy lime.ndll from the latest Haxelib release of Lime.
> 
> If this happened because you switched to 8.2.0-Dev, you'll need to get it from an actions run, or go through the trouble of rebuilding it yourself.

I'm using develop, and I can't find it in actions

**Comment by moxie-coder** [comment]
okay well
@player-03 same issue, even after replacing the ndll
```
Called from ? line 1
Called from CommandLineTools.hx line 1903
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 125
Called from CommandLineTools.hx line 640
Called from lime/tools/PlatformTarget.hx line 107
Called from WindowsPlatform.hx line 305
Called from a C function
Called from lime/tools/ProjectHelper.hx line 57
Called from hxp/Log.hx line 50
Called from hxp/Log.hx line 152
Called from a C function
Called from C:\HaxeToolkit\haxe\std/neko/Lib.hx line 43
Uncaught exception - load.c(237) : Failed to load library : D:\HaxeToolkit\haxe\lib\lime\git//ndll/Windows/lime.ndll
```

**Comment by player-03** [comment]
More ideas to try:

- Make sure you copied both Windows/lime.ndll and Windows64/lime.ndll into their respective folders, just in case it's telling you the wrong one.
- Try reinstalling hxp.
- Run `lime rebuild tools`, even though this isn't the usual error for that.
- Delete lime.ndll from Export/windows/bin and try again.
- Try building with `-eval` (e.g., `lime test windows -eval`).

It's crashing while trying to print a "source path does not exist" error message, so if you start seeing that message instead, you'll know it's fixed.

**Comment by moxie-coder** [comment]
okay, so, seems like that fixed it, but an issue unrelated to lime came back, so I'mma close this
