### ISSUE TITLE
Error compiling android on latest Ubuntu

### ISSUE THREAD

**Issue by moxie-coder** [openfl/lime#1748]
This error keeps showing up when trying to compile android, this is from a workflow and I've seen issues about it, but they're very old and outdated, and this is on latest Haxe, OpenFL, & Lime
```
Called from ? line 1
Called from CommandLineTools.hx line [19](https://github.com/moxie-coder/NullFunkinSource/actions/runs/7598105495/job/20693714574#step:9:20)03
Called from CommandLineTools.hx line 22
Called from a C function
Called from CommandLineTools.hx line 125
Called from CommandLineTools.hx line 640
Called from lime/tools/PlatformTarget.hx line 98
Called from AndroidPlatform.hx line 448
Called from lime/tools/HXProject.hx line 1087
Uncaught exception - Invalid field access : split
```

Like I said earlier, I've seen issues about it but they're dated, and I don't really know what's causing this, and the answers I tried mentioned before didn't work. So I'm kinda at a dead end here

**Comment by moxie-coder** [comment]
nvm I fixed it by using haxe 4.2.5

**Comment by player-03** [comment]
Apparently there was an error getting information from Haxelib. We don't know what the error was, because the code attempts to hide it. And in the process of hiding it (twice over), a string gets set to null, causing the null pointer error you encountered.

Glad it works now for you, but we'd better rewrite some of this anyway.

**Comment by moxie-coder** [comment]
> Apparently there was an error getting information from Haxelib. We don't know what the error was, because the code attempts to hide it. And in the process of hiding it (twice over), a string gets set to null, causing the null pointer error you encountered.
> 
> Glad it works now for you, but we'd better rewrite some of this anyway.

probably a good idea, since there’s no safety checks when that happens, for me at least

**Comment by player-03** [comment]
Should be fixed now.
