### ISSUE TITLE
[Question] Wrong .dll name when building hashlink?

### ISSUE THREAD

**Issue by T1mL3arn** [openfl/lime#1756]
Is `vcruntime.dll.dll` correct lib name ?

https://github.com/openfl/lime/blob/f8a70444f5d8a6bd3208e2e28b53e57568ba2eee/src/lime/tools/HashlinkHelper.hx#L47

I see in hashlink dir only `vcruntime140.dll` file.

**Comment by player-03** [comment]
@Apprentice-Alchemist, do you know if this is a typo or a real file?

**Comment by T1mL3arn** [comment]
I also checked hashlink repo, it only mentions `vcruntime140.dll`

**Comment by Apprentice-Alchemist** [comment]
It's probably a typo.
