### ISSUE TITLE
lime rebuild extension-webm windows error

### ISSUE THREAD

**Issue by KhaiKien** [openfl/lime#1768]
i type lime rebuild extension-webm windows and say this
![Ảnh chụp màn hình 2024-03-15 153437](https://github.com/openfl/lime/assets/163157682/549fd144-d3fb-4471-8238-8c8083248333)

**Comment by KhaiKien** [comment]
help me pls

**Comment by moxie-coder** [comment]
this is technically the wrong place to put this issue and extension-webm is discontinued

**Comment by joshtynjala** [comment]
Closing because extension-webm is not a part of Lime.

**Comment by moxie-coder** [comment]
> Closing because extension-webm is not a part of Lime.

that too actually
