### ISSUE TITLE
Lack of option to disable automatic `full-screen` mode.

### ISSUE THREAD

**Issue by MAJigsaw77** [openfl/lime#1773]
There's this thing in the `NativeWindow` that makes the game go fullscreen by pressing `Alt+Enter`. However there's no way to prevent this action in any way.

**Comment by joshtynjala** [comment]
You can prevent it by cancelling Lime's onKeyDown event (or, if you're using OpenFL, you should be able to `preventDefault()` the `KeyboardEvent.KEY_DOWN` event).

```haxe
window.onKeyDown.add((keyCode, keyModifier) -> {
	if (keyCode == KeyCode.RETURN && keyModifier.altKey) {
		window.onKeyDown.cancel();
	}
});
```
