### ISSUE TITLE
[8.2.0-dev] Target Cairo version doesn't exist

### ISSUE THREAD

**Issue by EliteMasterEric** [openfl/lime#1798]
Trying to clone and build this branch but this commit (https://github.com/openfl/lime/commit/7824a39e815984549560fcb3a4ef0ad7cd453a4f) refers to a commit on `freedesktop/cairo`, which is a repo that doesn't exist.

**Comment by player-03** [comment]
Yeah, we had to update .gitmodules to point to freedesktop.org (2b3fe0ac0de16d25ed4b80a57b69eb17f43930bb). You should already have this commit, but you may still need to run `git submodule sync && git submodule update`.

**Comment by joshtynjala** [comment]
And if you need to switch back from 8.2.0-Dev to develop, you will need to run `git submodule sync && git submodule update` again to go back to the original module URLs that develop is still using for our 8.1 updates. After we merge 8.2.0-Dev into develop, this commands won't be needed anymore.

**Comment by EliteMasterEric** [comment]
The issue I was having was that I was unable to checkout the branch due to the missing submodule. I ended up being able to use `--no-recurse-submodules` and that allowed me to check out the corrected `.gitmodules` file, and then after that I could perform the git submodule sync.

**Comment by player-03** [comment]
Weird. My best guess is that when you previously checked out that branch, github.com/freedesktop/cairo still existed, and it remembered that URL. Maybe another solution would have been to delete your local copy of 8.2.0-Dev, then run `git checkout upstream 8.2.0-Dev`.

Anyway, glad you got it working.

**Comment by EliteMasterEric** [comment]
Logging it here in case people try to find it, I encountered an error if I ever attempted to fetch the `cairo` submodule repository in its entirety:

```
error: object e5b831b107ad18e78ec9ea5e6da68eb30bf71126: missingSpaceBeforeDate: invalid author/committer line - missing space before date
fatal: fsck error in packed object
fatal: fetch-pack: invalid index-pack output
```

It seems some old commit in that repo is corrupted and needs to be fixed by them. In the meantime, I was able to do this to pull just the commit I needed:

```
git fetch --depth 1 origin tag 1.17.6
```
