### ISSUE TITLE
`lime test neko` fails on Ubuntu14

### ISSUE THREAD

**Issue by DavisDevelopment** [openfl/lime#181]
I'm trying to build a demo for a new rendering system for my game engine, and when I run `lime test neko`, or `lime test linux`, I get the following error:
    Warning: Could not find template file: haxe
    Warning: Could not find template file: neko/hxml
    Fatal error: exception Failure("File not found bin/linux/neko/haxe/release.hxml")
and the build fails.  I've tried everything I could think of and the problem persists.  Any suggestions?

**Comment by ImmanuelSamuel** [comment]
I have this issue as well. What did you do?
