### ISSUE TITLE
Been trying to compile game, keep getting errors telling me "ApplicationMain.getEntryPoint(); Called from macro here

### ISSUE THREAD

**Issue by VillianousJ0ker** [openfl/lime#1815]
Been compiling a HaxeFlixel Project atm and keep getting this error when using "Lime Test Windows"
![image](https://github.com/openfl/lime/assets/153438815/7873fb54-69c0-470d-aeda-e1da20429d14)

**Comment by player-03** [comment]
Is that the complete error message? Normally there would be more error details above or below.

**Comment by VillianousJ0ker** [comment]
yeah this is all it displays

**Comment by player-03** [comment]
Can you make the window bigger to show more? Or try scrolling?

**Comment by VillianousJ0ker** [comment]
wait nvm, did FlxSprite get moved or smth, it just keeps marking each use of it as invalid, using VSCode atm.

**Comment by VillianousJ0ker** [comment]
wait, just figured it out, sorry!

**Comment by VillianousJ0ker** [comment]
was a simple thing in the import.hx file i changed that messed stuff up
