### ISSUE TITLE
Make x86 target flags more specific

### ISSUE THREAD

**Issue by tobil4sk** [openfl/lime#1819]
As discussed in #1813, `-64` and `-32` are currently used in a lot of places to mean `x86_64` and `x86_32` respectively. Now that arm64 systems are widespread (and 8.2.0-Dev has [arm64 Mac support](#1640)), which is also a 64 bit architecture, it would be better to have more specific flags that are specifically for x86 architectures.

It looks like the ios target already uses the `i386` flag: https://github.com/openfl/lime/blob/ca52db81efa10b1bd8c76e43c714faa9dbbc4c94/src/lime/tools/IOSHelper.hx#L124

**Comment by joshtynjala** [comment]
Interesting background here on x86, i386, and IA-32, which all can refer to 32-bit Intel architecture processors: https://unix.stackexchange.com/questions/489145/why-do-linux-world-use-the-term-i386-instead-of-x86

Similarly, 64-bit Intel/AMD can be x86_64, x64, AMD64, and Intel 64 (but not IA-64, which was used for Intel Itanium instead).
