### ISSUE TITLE
Completely Nondescript Error When Compiling Project

### ISSUE THREAD

**Issue by Jaduplex** [openfl/lime#1822]
I honestly have no clue how I'm supposed to report this, but it seems to be a compiler issue, so I'll report it here.

While compiling a HaxeFlixel project that doesn't report any errors, compiling gets very slightly in, only to fail with a completely non-descript "Error". No error code, no explanation, nothing. This started earlier today and I have no clue why. I haven't changed any libraries at all. No edits to Project.xml. Only edits to the codebase (In this circumstance, I'm trying to optimize the imports by not importing everything with .* in import.hx. I've fully updated every .hx file to have proper imports).

Screenshot below. If you have even the SLIGHTEST clue of what's going on here, it would be much appreciated. The only thing I can possibly think of is the ANSI extension for Command Prompt that I installed earlier, but builds succeeded after that and it shouldn't conflict with Lime so I doubt it.

![image](https://github.com/user-attachments/assets/f4fe0c50-4491-49b0-846b-06bf229b05d8)

**Comment by dimensionscape** [comment]
Have you tried a clean build?

**Comment by Jaduplex** [comment]
> Have you tried a clean build?

I deleted the export directory. I'm pretty sure that's all -clean does?

**Comment by Jaduplex** [comment]
> > Have you tried a clean build?
> 
> I deleted the export directory. I'm pretty sure that's all -clean does?

Just tried, same error.

**Comment by joshtynjala** [comment]
Maybe try `-verbose` too. Sometimes, it shows more information.

**Comment by dimensionscape** [comment]
You might try building a minimal or sample flixel project to rule out some problems and narrow it down to something systemic or isolated in your project.

**Comment by Jaduplex** [comment]
> Maybe try `-verbose` too. Sometimes, it shows more information.

Error message is still nondescript.
![image](https://github.com/user-attachments/assets/7a694a9e-889d-4b28-aadd-a658d02a802f)

**Comment by Jaduplex** [comment]
> You might try building a minimal or sample flixel project to rule out some problems and narrow it down to something systemic or isolated in your project.

I'll give that a shot.

**Comment by Jaduplex** [comment]
> You might try building a minimal or sample flixel project to rule out some problems and narrow it down to something systemic or isolated in your project.

Created and built the template HelloWorld project. Same error. I am starting to think this might be a haxelib issue, so I'll try reinstalling everything and see if that works.
![image](https://github.com/user-attachments/assets/f9a1c6db-a2a5-407d-a0bb-fba911dcbb74)

**Comment by dimensionscape** [comment]
> > You might try building a minimal or sample flixel project to rule out some problems and narrow it down to something systemic or isolated in your project.
> 
> Created and built the template HelloWorld project. Same error. I am starting to think this might be a haxelib issue, so I'll try reinstalling everything and see if that works. ![image](https://private-user-images.githubusercontent.com/65635932/351464890-f9a1c6db-a2a5-407d-a0bb-fba911dcbb74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3NjI5MjksIm5iZiI6MTcyMTc2MjYyOSwicGF0aCI6Ii82NTYzNTkzMi8zNTE0NjQ4OTAtZjlhMWM2ZGItYTJhNS00MDdkLWEwYmItZmJhOTExZGNiYjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDE5MjM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNDU4ODA1YzRjNWZkZmIwYjBmNjBjMjBmYmRjZmU4NTEwNmE3NzIyMzc4NmIyZDU4MTE4MjEwYmY1NWE5MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SRX0bZsThLR2VRFRK0YWRc8UO4TS6QpznsbQGjEPt6g)

Yea, for sure. Also make sure you're not limited by disk space or other system resources.

**Comment by Jaduplex** [comment]
That didn't fix it. Even reverting the commit the issue started with didn't work. I'm sort of lost now.

**Comment by dimensionscape** [comment]
I'm going to go ahead and close this, since its not technically an Lime issue. I would perhaps ask around in the haxe forums. Maybe someone else has experienced and resolved the same kind of problem.

**Comment by Jaduplex** [comment]
Ok, so you know that random thing I mentioned earlier? You know, the ANSICON thing I didn't think would have an impact?
Yeah. That was the problem. I uninstalled it and everything is fine now.

**Comment by player-03** [comment]
I was about to say that could be the issue. Lime likes to use color highlighting, and maybe the extension interpreted one of the colors to mean "hide this bit of text."

That wouldn't cause the error, but it could certainly make it display as just "Error".

**Comment by dimensionscape** [comment]
> Ok, so you know that random thing I mentioned earlier? You know, the ANSICON thing I didn't think would have an impact? Yeah. That was the problem. I uninstalled it and everything is fine now.

Thanks for the follow up resolution. Glad you figured it out.
