### ISSUE TITLE
lime rebuild rpi -clean -release -nocffi  new issue while compiling 

### ISSUE THREAD

**Issue by isamu2025** [openfl/lime#1825]
Compiling group: native-toolkit-zlib
arm-linux-gnueabihf-g++ -Ilib/zlib/ -DZ_HAVE_UNISTD_H -c -fvisibility=hidden -O2 -fpic -fPIC -Wno-overflow -DHX_LINUX -DRASPBERRYPI=RASPBERRYPI -DHXCPP_VISIT_ALLOCS(haxe) -DHXCPP_API_LEVEL=0(haxe) -I/home/pi/haxelib/hxcpp/git/include ... tags=[haxe,static]
 - lib/zlib/uncompr.c 
 - lib/zlib/zutil.c 
 - lib/zlib/inftrees.c 
 - lib/zlib/inflate.c 
 - lib/zlib/inffast.c 
 - lib/zlib/infback.c 
 - lib/zlib/gzwrite.c 
 - lib/zlib/gzlib.c 
 - lib/zlib/adler32.c 
 - lib/zlib/gzread.c 
 - lib/zlib/trees.c 
 - lib/zlib/compress.c 
 - lib/zlib/crc32.c 
 - lib/zlib/deflate.c 
 - lib/zlib/gzclose.c 
Link: ../ndll/RPi/lime.ndll
/usr/lib/gcc-cross/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/bin/ld: 找不到 -ldrm: 没有那个文件或目录
/usr/lib/gcc-cross/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/bin/ld: 找不到 -lEGL: 没有那个文件或目录
/usr/lib/gcc-cross/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/bin/ld: 找不到 -lGLESv2: 没有那个文件或目录
/usr/lib/gcc-cross/arm-linux-gnueabihf/12/../../../../arm-linux-gnueabihf/bin/ld: 找不到 -lbcm_host: 没有那个文件或目录

this is  issue 
Link: ../ndll/RPi/lime.ndll

/usr/lib/gcc-cross/arm-linux-gnueabihf/12/../../../../ Arm linux-gnueabihf/bin/ld: cannot find - ldrm: there is no file or directory for that

/usr/lib/gcc-cross/arm-linux-gnueabihf/12/../../../../ Arm linux-gnueabihf/bin/ld: cannot find - lEGL: there is no file or directory for that

/usr/lib/gcc-cross/arm-linux-gnueabihf/12/../../../../ Arm linux-gnueabihf/bin/ld: cannot find - lGLESv2: there is no file or directory for that

/usr/lib/gcc-cross/arm-linux-gnueabihf/12/../../../../ Arm linux-gnueabihf/bin/ld: cannot find - lbcm_rost: does not have that file or directory

**Comment by isamu2025** [comment]
<img width="834" alt="wechat_20240807013533" src="https://github.com/user-attachments/assets/107594b4-8a1f-435b-b4e3-9e89552328f5">

Screenshot file

**Comment by joshtynjala** [comment]
Did you install the required native libraries with `apt`?

https://github.com/openfl/lime/tree/develop/project#prerequisites

**Comment by isamu2025** [comment]
> 您是否安装了所需的本机库？`apt`
> 
> https://github.com/openfl/lime/tree/develop/project#prerequisites

sudo apt install libgl1-mesa-dev libglu1-mesa-dev g++ libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev libpulse-dev libxcursor-dev libdbus-1-dev libdrm-dev libgbm-dev libudev-dev

**Comment by gepatto** [comment]
``` 
 sudo apt install -y build-essential
 sudo apt install -y libdrm-dev libgbm-dev libx11-dev libxext-dev libgles2-mesa-dev libasound2-dev libudev-dev
 sudo apt install -y libxcursor-dev libxinerama-dev libxi-dev libxrandr-dev libdbus-1-dev libpulse-dev
 ```
 These are the requirements when you run bullseye or bookworm.
 But you will need my fork of this repository for this. 
 If you are running 64bit you will also need hxcpp from git.

**Comment by isamu2025** [comment]
<img width="399" alt="wechat_20240807224940" src="https://github.com/user-attachments/assets/67eefb32-2405-4ad9-bfe7-185d341dcfa8">
<img width="1291" alt="wechat_20240807224538" src="https://github.com/user-attachments/assets/a2ebe3ac-9190-4059-9476-674e82056d40">


@gepatto @joshtynjala   thank you for your help!

**Comment by gepatto** [comment]
Great.  
We will merge my changes in the near future.
