### ISSUE TITLE
HTML5 memory leak

### ISSUE THREAD

**Issue by mikaleerhart** [openfl/lime#1862]
![Screenshot 2024-11-14 at 5 07 22 PM](https://github.com/user-attachments/assets/b49a87a7-daf7-4c91-8c36-328351eb2bf7)

I don't really know where to start to look into this. There's no terminal or console warnings. I was using Phaser and am now porting my game over to HaxeFlixel. I ran into a bad memory leak today in my project (a simple object catching game with pngs, spritesheets, fonts, and sounds). It ran all the way up to 150GB in a matter of seconds.

**What I've tried**: update haxelib, using git versions of lime/openfl/hcxpp, and using different browsers. I'm stumped so I thought I would make this public. Will happily provide private access to my repo if anyone has time to take a look.

Only is happening in the html5 target (tried debug & final options). Memory usage is fine in neko target although my sound wasn't playing which is why I tried html5 in the first place.

**Comment by barisyild** [comment]
Do you have a code that can reproduce the problem?

**Comment by mikaleerhart** [comment]
Gave you access to my private repo. The memory runs up as soon as you load it in the html5 target.

**Comment by barisyild** [comment]
> Gave you access to my private repo. The memory runs up as soon as you load it in the html5 target.

I built the game and it works fine.

**Comment by barisyild** [comment]
I contacted you on discord.

**Comment by mikaleerhart** [comment]
Weird, you're right, I just built it on my old Linux laptop and no memory leak there. It must be my OS/hardware (macOS 15.1, M2 Mac mini).
I just tried creating a fresh user account on the Mac, made a new directory for haxelib and installed haxe/lime/openfl/flixel. Ran `lime test html5` and the leak is back. I'm keeping this open in case anyone has any ideas or can look into it further.

**Comment by barisyild** [comment]
> Weird, you're right, I just built it on my old Linux laptop and no memory leak there. It must be my OS/hardware (macOS 15.1, M2 Mac mini). I just tried creating a fresh user account on the Mac, made a new directory for haxelib and installed haxe/lime/openfl/flixel. Ran `lime test html5` and the leak is back. I'm keeping this open in case anyone has any ideas or can look into it further.

try to update flixel with `haxelib install flixel`

**Comment by mikaleerhart** [comment]
Ok, It's a combo of my project/hardware/OS. I'm gonna comment out every line of code tomorrow until I find the line that is causing the issue and post here to close the issue.

**Comment by barisyild** [comment]
> Ok, It's my project. Not happening in any examples. I'm gonna comment out every line of code tomorrow until I find the line that was causing the issue, and post it here & close the issue.

Ok I found the problem, the problem is debug draw can you please start the program without debug and retry?

**Comment by mikaleerhart** [comment]
That's it! 
`FlxG.debugger.drawDebug = true;`
Thank you. Should we close the issue now?

**Comment by barisyild** [comment]
> That's it! `FlxG.debugger.drawDebug = true;` Thank you. Should we close the issue now?

I think don't close issue because it is a problem that debug draw causes this.

**Comment by barisyild** [comment]
Please create the issue here: https://github.com/HaxeFlixel/flixel/issues

**Comment by mikaleerhart** [comment]
Will do.

**Comment by mikaleerhart** [comment]
[Here](https://github.com/HaxeFlixel/flixel/issues/3285) is the link to the new issue.
