### ISSUE TITLE
Tools.hxml missing

### ISSUE THREAD

**Issue by Le-Fleurrr** [openfl/lime#1865]
He guys, so when I try to run the command `haxelib run lime flixel`, this error shows up:

Error: Could not process argument tools.hxml (file not found)
Invalid character:

Any help is appreciated

**Comment by player-03** [comment]
Did you download Lime from git? Not sure why else it would need to rebuild tools. But either way, it ought to be able to find tools.hxml.

Try these commands next:

- `haxelib run lime --version`
- `haxelib run lime setup`

**Comment by Le-Fleurrr** [comment]
No, I did not download it from git, should I though?

**Comment by Le-Fleurrr** [comment]
All of them say the same thing:

```
Error: Could not process argument tools.hxml (file not found)
Invalid character:
```
![image](https://github.com/user-attachments/assets/96ff8e31-11b4-4965-8a34-4c855b3d2254)

**Comment by tobil4sk** [comment]
Run `haxelib libpath lime`, which will give you the path to your lime installation. Navigate to that folder and check if there is a `tools` folder that contains a `tools.hxml`. If not, then perhaps lime has not installed correctly, try reinstalling it.

**Comment by Le-Fleurrr** [comment]
It does have a folder called `tools`, and yet there is a file called `tools.hxml`. So idk why it says that, I tried reinstalling and that didn't work, perhaps I need to install it through github?

**Comment by Le-Fleurrr** [comment]
I think I have an idea, maybe I should download from github? I think it has more compiled code.

**Comment by tobil4sk** [comment]
Lime installed from haxelib should still work properly. What version does it show if you run: `haxelib list lime`?

Is your lime install in the default location? Should be `C:\HaxeToolkit\haxe\lib\lime\x,x,x\`. If it's somewhere else maybe there is a permission issue, where some access rights are preventing haxe from being able to see the `tools.hxml` file.

You can also try `haxelib run lime setup -v` to get verbose output.

**Comment by Le-Fleurrr** [comment]
Mine is 8.2.1, but the file directory is: `C:\Windows\HaxeLib\haxe\lime\8.2.1`, there is no folder called `lib`.

**Comment by tobil4sk** [comment]
I don't think it's a good idea to have it in the `C:\Windows` folder. Try moving your haxelib repository somewhere else, e.g. `haxelib setup C:\HaxeToolkit\haxe\lib` (you should move `C:\Windows\HaxeLib\haxe` there first if you want to keep your current library installs).

**Comment by Le-Fleurrr** [comment]
My filepath is already `C:\HaxeToolkit\haxe`, yet there is no folder called `lib`, should I create one?

**Comment by Le-Fleurrr** [comment]
Okay, so I've put all of library installs to the lib folder, but it still doesn't work. Any solutions?

**Comment by tobil4sk** [comment]
So `haxelib libpath lime` now says `C:\HaxeToolkit\haxe\lib\lime\8,2,1\`, correct? To confirm, did you reinstall lime after changing the lib folder?

**Comment by Le-Fleurrr** [comment]
Yes the path is correct, no I did not reinstall lime after changing the lib folder.

**Comment by tobil4sk** [comment]
Try reinstalling lime again one more time. Then run `haxelib run lime setup -v`

**Comment by Le-Fleurrr** [comment]
![image](https://github.com/user-attachments/assets/00830318-1b54-4ee8-bf7e-5e02df3a7367)
:\

**Comment by Le-Fleurrr** [comment]
Maybe I should add lime to the environment PATH variable?

**Comment by joshtynjala** [comment]
If I had to guess, it can't find _tools/tools.n_, and it's trying to rebuild tools which is why it is referencing _tools.hxml_. That's weird because Lime from Haxelib definitely includes _tools/tools.n_. Looking at _RunScript.hx_, the only way that finding _tools/tools.n_ wouldn't work with the `if (!FileSystem.exists("tools/tools.n")` code is if the current working directory were wrong, which is really odd. This to me seems like a larger issue than just Lime, and maybe something is broken in the Haxe installation.

I think that you should uninstall Haxe, delete the _C:\HaxeToolkit_ directory completely, and then reinstall Haxe and Lime from scratch. Make sure to install Haxe to the default location of _C:\HaxeToolkit_, and not anywhere else like _C:\Windows_ or _C:\Program Files_. Similarly, use the default path for Haxelib too. Then, try to install Lime again.

**Comment by Mcknight231** [comment]
Nope. Still tried it and the problem still persists

**Comment by player-03** [comment]
Also try running _tools.n_ manually. `cd` into the _tools_ directory, then run `neko tools.n`.

**Comment by Le-Fleurrr** [comment]
![image](https://github.com/user-attachments/assets/44fef86a-2660-4de8-8176-09449ff96990)

This is what it says

**Comment by Le-Fleurrr** [comment]
Anyone find any solutions yet?

**Comment by dimensionscape** [comment]
> Anyone find any solutions yet?

It sounds like your environment is probably messed up somehow. Do what Josh recommended and start with a fresh haxe and lime dev environment. I don't think anyone can reproduce the problems you're having, including myself.

**Comment by Le-Fleurrr** [comment]
I did that 3 times, and the problem still persists, idk what to do anymore

**Comment by player-03** [comment]
What happens when you try `neko run.n` from Lime's root directory?

**Comment by Le-Fleurrr** [comment]
https://github.com/openfl/lime/issues/1865#issuecomment-2490214330

**Comment by player-03** [comment]
From another directory? `neko path/to/lime/run.n`

Because if that works too, you could set up an alias and bypass Haxelib altogether.

**Comment by Le-Fleurrr** [comment]
It says the same error
```
Error: Could not process argument tools.hxml (file not found)
Invalid character:
```

**Comment by player-03** [comment]
Good to know. Seems Haxelib isn't setting the right working directory either. The next step is to figure out what directory it's actually using.

Open up _tools/RunScript.hx_, and insert some `trace` statements near the bottom:

```haxe
	//...
	Sys.exit(runCommand("", "haxe", args));
}

trace(Sys.getCwd());
trace(FileSystem.exists("tools/tools.n"));

if (!FileSystem.exists("tools/tools.n") || args.indexOf("-rebuild") > -1)
{
	rebuildTools();
}
```

Once you make the changes, run `haxe run.hxml` from the _tools_ directory, and then retrigger the error and see what it prints.

**Comment by Le-Fleurrr** [comment]
Sorry if I was ayway for awhile, was busy lol, here is what it says and looks like:

![image](https://github.com/user-attachments/assets/affaed91-841c-418c-b9e0-c2ec2431499f)

**Comment by player-03** [comment]
You do need hxp to do anything with Lime. What happens after installing it?

**Comment by Le-Fleurrr** [comment]
After running the line again nothing happens..

![image](https://github.com/user-attachments/assets/4a019fe4-8f9d-419e-85d3-a856ea8a37e4)

**Comment by player-03** [comment]
That's a success. Now when you try `haxelib run lime` it should print more info.

**Comment by Le-Fleurrr** [comment]
![image](https://github.com/user-attachments/assets/ade31fc6-9a62-40f5-ac2e-beeef90fc72a)

AAAAAHHHHH IM GOING INSANE

**Comment by player-03** [comment]
Hmm. So it isn't making it that far down? Try `neko run.n` directly from the Lime folder, and make sure that prints the extra data.

**Comment by Le-Fleurrr** [comment]
![image](https://github.com/user-attachments/assets/936fded7-68c5-4e88-a224-6568a1a6a30c)

**Comment by player-03** [comment]
That worked a few days ago.

- Did _tools.n_ get deleted somehow?
- If not, does `neko tools/tools.n` at least work from the Lime directory?

Edit: oh yeah, and did you [add the two `trace` statements to RunScript.hx](#issuecomment-2506764781)?

**Comment by Le-Fleurrr** [comment]
Both wrong, and yeah I did add the two trace statements

**Comment by tobil4sk** [comment]
It seems like haxe/neko are just unable to read from the `tools` directory for some reason?

**Comment by player-03** [comment]
Let's simplify. First, add these two lines at the very top of `main()`:

```haxe
public static function main()
{
	Log.info(Sys.getCwd());
	trace(FileSystem.exists("tools.n"));

	//...
}
```

Save your changes, then run `haxe -lib hxp --run RunScript` from the _tools_ directory.

This covers several possible issues:

- Maybe `trace()` is broken but `Log.info()` isn't.
- Maybe `main()` was exiting before getting to the bottom, where the old `trace()` statements were.
- Maybe rebuilding _run.n_ silently failed somehow.
- Maybe running Neko apps fails somehow.
- Maybe your machine can't handle the forward slash in "tools/tools.n".

**Comment by player-03** [comment]
Actually, I wonder if it really is that last one. Try `neko tools\tools.n` from the Lime directory.

**Comment by Le-Fleurrr** [comment]
When I try `haxe -lib hxp --run RunScript` it says this:
![image](https://github.com/user-attachments/assets/7f0f8949-7dfd-4a1c-8d5d-556f00a82d6e)

When I try `neko tools/tools.n` it says this:
![image](https://github.com/user-attachments/assets/df90bfca-3aee-4e24-a42e-fe1252b4fc55)

When I try `neko tools.n` it says this:
![image](https://github.com/user-attachments/assets/eb561c4a-49dc-492f-8bf6-74d7ec45f2a8)

**Comment by player-03** [comment]
> Duplicate class field declaration

I didn't mean copy all the lines I posted, just the two that print information. Put them at the top of the existing `main()` function.

```haxe
Log.info(Sys.getCwd());
trace(FileSystem.exists("tools.n"));
```

In Haxe there can only be one of each function, or you'll get that error.

> When I try `neko tools/tools.n`

You have to try that from outside the _tools_ directory, or there won't be a _tools\tools.n_ for it to find.

> When I try `neko tools.n`

Good to see that one still works.

**Comment by Le-Fleurrr** [comment]
![image](https://github.com/user-attachments/assets/0759f03a-8fe0-42da-bef9-79aa8247c248)

**Comment by player-03** [comment]
Well, it's printing data, so that's good. Of course the rest of it doesn't work from there, but that wasn't the point of the test.

I guess the next step is to see if we can go back to Neko. Let's do a `haxe run.n`, followed by `haxelib run lime`.

**Comment by Le-Fleurrr** [comment]
![image](https://github.com/user-attachments/assets/6601a30a-3d9f-4dbd-b890-47203f9d91eb)

**Comment by player-03** [comment]
Sorry, I misspoke. It's `haxe run.hxml` (from the tools directory as before), then `haxelib run lime`.

**Comment by Le-Fleurrr** [comment]
![image](https://github.com/user-attachments/assets/d59b8cac-5621-4eeb-9764-d50dd090db93)

**Comment by player-03** [comment]
You need to be in the _tools_ directory before calling `haxe run.hxml`.

**Comment by Le-Fleurrr** [comment]
![image](https://github.com/user-attachments/assets/0c7da297-d631-4d67-a303-ff435770effd)

**Comment by player-03** [comment]
Aha, it's running from _System32_ for some reason. Which also seems to be the folder Command Prompt starts in. I wonder if there's a way to turn that off, but I don't know where to start in that regard.

For now, I'll try updating `RunScript` to use the absolute path to _tools.n_. More on that in a half hour or so.

**Comment by player-03** [comment]
Ok, please replace _RunScript.hx_ with [my updated version](https://raw.githubusercontent.com/player-03/lime/refs/heads/RunScript_absolute_paths/tools/RunScript.hx), and give that a shot.

1. Download my updated version, or copy-paste if that's easier. (Be sure to select all if copy-pasting.)
2. Run `haxe run.hxml` again. As always, this must be done from the _tools_ directory.
3. Try `haxelib run lime`.

**Comment by Le-Fleurrr** [comment]
![image](https://github.com/user-attachments/assets/185dc583-56b5-43c0-b27f-1a851a31f79b)

Well isn't that interesting

**Comment by player-03** [comment]
Ok, so that was it. For some reason your computer likes to run things from _System32_, and this overrides Haxelib's normal behavior.

Switching to absolute paths makes it not matter which directory we're in, so that fixes it.

In that case, you should be good to go. I'd personally recommend `haxelib run lime setup` to install the `lime` shortcut, but that's up to you.

**Comment by Le-Fleurrr** [comment]
YES! Oh my God, thank you so much, it works now!

**Comment by player-03** [comment]
You're welcome, and thanks for sticking with me as we debugged this.

**Comment by tobil4sk** [comment]
That's very strange that `haxelib run` is running things in `C:\Windows\System32`, do you think you might be able to share the output of `haxelib list` too? @Mcknight231
