### ISSUE TITLE
[HL] 'lime rebuild hl' complains about missing PCRE build files

### ISSUE THREAD

**Issue by EliteMasterEric** [openfl/lime#1867]
> Error: pcre_dfa_exec.c
> c1: fatal error C1083: Cannot open source file: './lib/hashlink/include/pcre/pcre_dfa_exec.c': No such file or directory

> Error: pcre_compile.c
> c1: fatal error C1083: Cannot open source file: './lib/hashlink/include/pcre/pcre_compile.c': No such file or directory

> - lib/hashlink/include/pcre/pcre2_extuni.c
> - lib/hashlink/include/pcre/pcre16_ord2utf16.c
process.c
> ./lib/hashlink/src/std/process.c(108): warning C4133: 'function': incompatible types - from 'uchar *' to 'LPSTR'

I believe this file is out of date, it looks like PCRE got replaced with PCRE2 a bit ago.

https://github.com/openfl/lime/blob/4812f6a1dd867ac2df284bd8c59a98bdb5d4534d/project/BuildHashlink.xml#L65

**Comment by joshtynjala** [comment]
I am unable to reproduce this issue with either of Lime's `develop` or `8.3.0-Dev` branches.

It's a good idea to add the `-clean` flag to ensure that it's not using any cached files.

Additionally, if you run `git status` and see that any of the submodules have been updated, you should run `git submodule sync` and `git submodule update` to be sure that you're using the correct commits for the submodules. When switching branches, it doesn't automatically set the submodules to the correct commits for the new branch, so you need to do that manually.

**Comment by EliteMasterEric** [comment]
Yeah it appears the repo was linking to a different version of HashLink.

**Comment by ADA-Funni** [comment]
> > Error: pcre_dfa_exec.c
> > c1: fatal error C1083: Cannot open source file: './lib/hashlink/include/pcre/pcre_dfa_exec.c': No such file or directory
> 
> > Error: pcre_compile.c
> > c1: fatal error C1083: Cannot open source file: './lib/hashlink/include/pcre/pcre_compile.c': No such file or directory
> 
> > * lib/hashlink/include/pcre/pcre2_extuni.c
> > * lib/hashlink/include/pcre/pcre16_ord2utf16.c
> >   process.c
> >   ./lib/hashlink/src/std/process.c(108): warning C4133: 'function': incompatible types - from 'uchar *' to 'LPSTR'
> 
> I believe this file is out of date, it looks like PCRE got replaced with PCRE2 a bit ago.
> 
> [lime/project/BuildHashlink.xml](https://github.com/openfl/lime/blob/4812f6a1dd867ac2df284bd8c59a98bdb5d4534d/project/BuildHashlink.xml#L65)
> 
> Line 65 in [4812f6a](/openfl/lime/commit/4812f6a1dd867ac2df284bd8c59a98bdb5d4534d)
> 
>  <file name="${HASHLINK_PATH}/include/pcre/pcre_compile.c" />

I just removed all the files that said "pcre_" and the pcre16 one in the ProjectHashlink thing and it worked for me
So just do that
