### ISSUE TITLE
With readability change of output.js for html5 the breakpoints are shifted

### ISSUE THREAD

**Issue by Dreaded-Gnu** [openfl/lime#1872]
Hello it seems that with the readability change of output.js template for html5 the generated sourcemap is shifted by a few lines. When changing the `::SOURCE_FILE::` part back to first line as it was before, the generated sourcemap matches the code.

Discovered this behaviour with my personal project and also with a demo project like `DisplayingABitmap`.

**Comment by joshtynjala** [comment]
Confirmed. Since we are using the source maps generated by the Haxe compiler before inserting the JS into our template, all of the code before the source file must be forced onto line 1 so that the source map line numbers still match up.
