### ISSUE TITLE
Problem with Console Compilation

### ISSUE THREAD

**Issue by ghost** [openfl/lime#1881]
I run command `lime build ps4` `lime build ps3` and `lime build switch` but have `Could not find haxelib "(library)", does it need to be installed?`
the "lime-ps4"/"lime-ps3"/"lime-switch" libraries is no longer exists

**Comment by jgranick** [comment]
The `lime-switch` library requires a signed NDA with Nintendo to be shared

Other libraries require a signed NDA with platform holders (such as Microsoft) as well as a signed NDA with Wayforward, who partnered to provide these console backends. I believe the Xbox backend was released in production, I do not recall a PS4 release, I believe the Wii U backend was operational though I do not recall if a product was released on the platform
