### ISSUE TITLE
Uncaught exception - load.c(181) : Module not found : run.n

### ISSUE THREAD

**Issue by srivathsa-d** [openfl/lime#214]
Hi guys, 

I'm trying to install opnefl for the first time. I'm following instructions from http://www.openfl.org/documentation/setup/install-lime/. I downloaded Haxe for windows (v 3.1.3). Next I tried to install lime using command "haxelib install lime". It started downloading, but after a while, it gave me connection timeout error. So I went ahead and did a manual install as described in the above link. But after installing lime, when I try to do "haxelib run lime setup", It give me the following error, 

Uncaught exception - load.c(181) : Module not found : run.n

I can't seem to figure out what the problem is. I'm attaching this image in case it helps. 
![capture](https://cloud.githubusercontent.com/assets/8538116/4024001/f603f426-2bb1-11e4-9786-762a87283ede.JPG)

I'm really excited about openfl and can't wait to start working on this. Any help is appreciated. 

Thank you.

**Comment by TerryCavanagh** [comment]
Hah, I just ran into this too - Windows 10 changes the cmd path to /windows/system32/ by default, so I changed it and got the same error. You might get a lot more people having this problem soon.

**Comment by jgranick** [comment]
Is there anything we can do on our end to work around this issue or to detect the problem and provide a better error?

**Comment by TerryCavanagh** [comment]
Hmm, well, it's reproducible - follow this guide to change your start folder: http://www.sevenforums.com/customization/77997-change-command-prompt-default-directory.html

... and you should get the same error message!
