### ISSUE TITLE
iOS: Touches in subview propagate to root view with incorrect coordinate origin.

### ISSUE THREAD

**Issue by neurofuzzy** [openfl/lime#224]
If I add a subView (in this case, for an iAD banner), touches to the banner propagate to the root view with the coordinates of the subview.

    [[[[UIApplication sharedApplication] keyWindow] rootViewController].view addSubview: adBanner];

If I place the banner at the bottom of the screen, then touch at `{ x: 20, y: 20 }` on the banner, the touch is also registered at the top of the screen, because the touch propagates to the root view at `{ x: 20, y: 20 }` instead of the correct `{ x: 20, y: 738 }`.

**Comment by jgranick** [comment]
Do you have any sort of simple extension or code that could be used to reproduce this?

**Comment by jgranick** [comment]
I'm going to move this to the OpenFL issue tracker, hopefully there's a way we can sanitize touch events in the UIStageView so it only dispatches if it comes from the correct view?

https://github.com/openfl/openfl/issues/513

From a Lime perspective, the Lime legacy code is old and no longer supported. From an OpenFL perspective, however, this is the iOS target -- so we want to make sure that behaves properly. I'm going to keep the Lime issue tracker for issues impacting the public Lime API, I hope that makes sense :smile:

Thanks for your help!
