### ISSUE TITLE
Add support for native text fields

### ISSUE THREAD

**Issue by bazzisoft** [openfl/lime#232]
In order to use Lime/OpenFL for apps with significant data entry, it would be good to support native text entry (different keyboard layouts based on text/email/numeric entry, swype/multilanguage support, etc).

It occurs that it might be possible to place a native text control, with a transparent background, on top of the OpenGL view to achieve this, along with an API to set/retrieve text, size and events.

Does anyone know if this is even possible or a good/bad idea? I'm happy to spend the time trying to implement this but would appreciate some pointers on where to start if anyone has ideas.

**Comment by jgranick** [comment]
Not going to track TODO items as issues :smile:
