### ISSUE TITLE
Fullscreen issue on Mac

### ISSUE THREAD

**Issue by pozirk** [openfl/lime#235]
If I run app in fullscreen mode on Mac, system stops responding to Command-Tab.
More info: http://gamedev.stackexchange.com/a/38109

This problem was fixed in SDL 2, there are two fullscreen modes now:
**SDL_WINDOW_FULLSCREEN** and **SDL_WINDOW_FULLSCREEN_DESKTOP**
More info: https://wiki.libsdl.org/SDL_SetWindowFullscreen

With **SDL_WINDOW_FULLSCREEN_DESKTOP** Command-Tab and other key combinations works fine.
Could you please add this feature to OpenFL?
Thank you!

**Comment by jgranick** [comment]
Pretty sure this was fixed, thanks! :smile:

**Comment by raggy** [comment]
Actually, NME is still using SDL_WINDOW_FULLSCREEN (so no window manager functions, including Cmd+Tab, will work):

https://github.com/haxenme/nme/blob/f9482127d6d2461ec8bbfa040f35016e98515577/project/src/sdl/SDLStage.cpp#L311

**Comment by jgranick** [comment]
Oh, gotcha. So we use real display mode switching, which is preferable for titles that may use a lower resolution than the actual screen resolution. Perhaps we should make exceptions for more OS X shortcuts, as we do already from Command + Tab and Command + Q I believe. Could anyone share the shortcuts they use that they still expect to use?

**Comment by raggy** [comment]
Is there an exception for Command + Tab? It doesn't activate anything when I test it here (OS X 10.10.2). I think if that worked, then this wouldn't be an issue.

If that's impossible, maybe we could have a switch somewhere that decided between SDL_WINDOW_FULLSCREEN and SDL_WINDOW_FULLSCREEN_DESKTOP? The latter is preferable in our game.

**Comment by jgranick** [comment]
I think that while fullscreen is the full screen resolution, we probably should use FULLSCREEN_DESKTOP, but when we add an official screen mode switching API, then I think it should probably use FULLSCREEN mode then, when we want to force a locked display mode. I think the issue is not that we need Alt+Tab support, it's that OS X has two different kinds of fullscreen, and I think the FULLSCREEN_DESKTOP behavior is probably most appropriate for the average title

**Comment by pozirk** [comment]
I would say casual games need SDL_WINDOW_FULLSCREEN_DESKTOP, while hardcore games may require SDL_WINDOW_FULLSCREEN.
But FULLSCREEN_DESKTOP is what I need right now. :)
Thank you Joshua!

**Comment by raggy** [comment]
Seems like a reasonable solution. Cheers!
