### ISSUE TITLE
Support Include.hxp files

### ISSUE THREAD

**Issue by Gama11** [openfl/lime#244]
I tried both `include.hxp` and `Include.hxp`, but it neither seem to be used.

Following the convention to start the include file with a lowercase letter (`include.xml`) wouldn't work I think, as Haxe requires classes to start with an uppercase letter.

(Copy of https://github.com/openfl/aether/issues/15 since the aether repo is now deprecated)

**Comment by jgranick** [comment]
Thanks again for this, I'm going to close this as I'm trying to weed out TODO items and just leave bugs in the issue tracker for now. This is a good idea for improvement, perhaps it could be a pull request
