### ISSUE TITLE
.hxp errors lead to temporary file

### ISSUE THREAD

**Issue by Gama11** [openfl/lime#258]
![](http://i.imgur.com/eObe8Zi.png)

The tools should sanitize error messages from Haxe to contain the correct path to the `.hxp` file. This is especially important for IDEs (e.g. FD which displays errors in the results panel and opens them at the specified position on double click).

**Comment by jgranick** [comment]
I think this is a good idea from a usability perspective, but the tools (intentionally) try not to intercept this type of compiler output. I'm concerned that doing so would lead to more fragility than the upside would be worth.

I am going to close this for now as a "won't fix", but if we come up with something as a pull request, I'd be happy to include it if we're sure it's not going to cause trouble. Thanks for understanding
