### ISSUE TITLE
getPixels() fills the blue channel of non transparent images with 255 (Neko/mac/android)

### ISSUE THREAD

**Issue by mbalestrini** [openfl/lime#270]
After calling BitmapData.getPixels() of an image with no alpha channel, that area of the image gets modified. Every pixel get a blue value of 255

Here's the code to reproduce the bug:
```
var sourceBmd = Assets.getBitmapData("assets/someimage2.jpg");
sourceBmd.getPixels(new Rectangle(50,50,100,100));
var anotherBitmapData = new BitmapData(sourceBmd.width, sourceBmd.height, true, 0);
var bmp = new Bitmap(anotherBitmapData);
addChild(bmp);
anotherBitmapData.draw(sourceBmd);
```

I tried to find the place where that error could happen. I don't get all the complex structure of lime/openfl/nme, but after a while of surfing through the different sources/libraries, I think I found it.
The problem seems to be here in /legacy/project/src/common/Surface.cpp

```
void SimpleSurface::getPixels(const Rect &inRect,uint32 *outPixels,bool inIgnoreOrder, bool inLittleEndian)
```
...
```
if (!(mPixelFormat & pfHasAlpha))
 {
    for(int x=0;x<r.w;x++)
    {
       *a = 255;
       a+=4;
    }
 }
```

Hope it helps

**Comment by gunnbr** [comment]
Sure enough--that looks wrong to me. The only thing I can think of is that someone was using that as a temporary test. I can't see when it got added though.

Taking that out does fix the problem. I also added a bunch of unit tests for other cases and am trying to get them to work on all targets before I can get the fix checked in though.

And note that it's actually pretty easy to get lime and openfl development environments setup, so you can try out the fix yourself as well!

**Comment by mbalestrini** [comment]
I didn't want to change this particular code because I don't know how lime handles image formats. I could've fixed this particular issue, but without knowing if I was doing it the wrong way.
I thought it may have something to do with some change in the order of the ARGB channels, but I have no idea when or why they did it.

**Comment by gunnbr** [comment]
Okay--the fix is in. After the next release comes out, give it a try!
