### ISSUE TITLE
Templates are not working as before

### ISSUE THREAD

**Issue by TBaudon** [openfl/lime#271]
Hello,

I use last lime version on haxelib (2.0.0) and last openfl and today I had a problem with templates.
I usually use a template to add some facebook info to my PROJ-Info.plist and avoid to have to add the info in the plist manually on each update, but today the template is not used anymore.

in my include.xml I use the following command : 
```<template path="templates" />```
and in my templates folder I have the following 

```" iphone/PROJ/PROJ-info.plist "```

What changed in the new version ? How can I use my template again ?

I triied to use 
``` <template path="path/to/the/plist" replace="projectName-info.plist" /> ``` 
and it seems to work fine. 

thanks

**Comment by TBaudon** [comment]
Are <template> tag executed in a include.xml file from a used lib ?
I'm working on an extension which uses resources file, and I'd like to add those automaticly with templates when using "lime update".

Here is the include.xml i use : https://github.com/TBaudon/OpenFLMopub/blob/master/include.xml

and here is the template folder : https://github.com/TBaudon/OpenFLMopub/tree/master/templates

In my project.xml, i include the extension after ```<haxelib name!"openfl" />```

I though templates were overwriting existing openfl file and adding others. When I use -verbose with ```lime update``` I don't see anything happening about my template, and in my xcode project, my resources file are not added.

I'm I missunderstanding something about templates ? Thanks.

**Comment by jgranick** [comment]
I just added support for a "Resources" directory:

https://github.com/openfl/lime/commit/712749e9d7ede65779552fa34033c9b9422b4718

Please let me know if this is working as you would expect it to :smile:

**Comment by TBaudon** [comment]
Thanks.
Yes it does the trick, the files are copied ine the Resources folder.
I think the xcodeproj template needs some change as well because even if the file are added in the resources folder, they aren't in the project. I'm trying to figure out what part need to change but this file is quite hard to understand >.<

**Comment by jgranick** [comment]
I don't really have a way of testing here.

I'm going to close this for now, if it is not quite working as you need it to, do this --

1.) Generate the OpenFL project
2.) Open the project in Xcode
3.) Copy the project somewhere to back it up
4.) Make the needed change manually in Xcode to make it work
5.) Send me both Xcode projects so I can compare, or run a diff program (WinMerge, Meld, etc) against them to get the needed diff yourself

Thanks again :smile:
