### ISSUE TITLE
Rendering inconsistency between flash and native when using rotation and scrollRect

### ISSUE THREAD

**Issue by agersant** [openfl/lime#28]
When displaying the following texture:
![cover](https://f.cloud.github.com/assets/817256/2026965/92c7833c-88a5-11e3-923f-38fad46fea45.png)

Using the following code:
```haxe
var bitmapData = Assets.getBitmapData("img/cover.png");
var bitmap = new Bitmap(bitmapData);
addChild(bitmap);
bitmap.x = 100;
bitmap.y = 100;
bitmap.rotation = 30;
bitmap.scrollRect = new Rectangle(64, 64, 128, 128);
```
The output looks different between Flash and Windows native:
![flash output](https://f.cloud.github.com/assets/817256/2026961/8b4bbd12-88a5-11e3-8189-d5e8f4d02e6d.jpg)
![native output](https://f.cloud.github.com/assets/817256/2026960/8b487544-88a5-11e3-9756-157560863bf5.jpg)

I would say the Flash output is the expected behaviour.

**Comment by jgranick** [comment]
Thank you I'm going to close this issue, and track it in OpenFL here: https://github.com/openfl/openfl/issues/509

Have a great day :smile:
