### ISSUE TITLE
iOS wav stop working after a phone call interruption

### ISSUE THREAD

**Issue by ibilon** [openfl/lime#284]
This is a bug that was reported on haxepunk's forum (see http://forum.haxepunk.com/index.php?topic=880.0).

- Wav files play normally
- Game is interrupted for a phone call
- Wav files can't play: well at least they don't make any sound

**Comment by jgranick** [comment]
Hi! :smile: 

I'm moving Lime legacy issues to the OpenFL tracker, so we can confirm the correct Flash API behavior of each relevant issue. From a Lime perspective (without OpenFL) Lime legacy is deprecated, and is not considered a defect. I've opened a new issue we can track, here:

https://github.com/openfl/openfl/issues/512

Thanks! :smile:
