### ISSUE TITLE
[html5] Android stock browser: Float32Array is not defined

### ISSUE THREAD

**Issue by RafaelOliveira** [openfl/lime#295]
Tested on Samsung Galaxy Y

typed arrays is only supported on Android 4 and above 
http://caniuse.com/#feat=typedarrays

Threre is a polyfill that works
http://inexorabletash.github.io/polyfill/typedarray.js

and about the polyfill:
http://stackoverflow.com/questions/11278619/looking-for-javascript-typed-arrays-emulation-library/11278663#11278663

It's hard to debug on the android stock browser, I found a app that helped. It's a webview with a javascript console:
https://play.google.com/store/apps/details?id=com.starbug1.android.htmldomviewer

**Comment by RafaelOliveira** [comment]
I was thinking if we could have the polyfill in the lib folder (in the output), and load the file only on androids with lower versions. The problem is to detect the android version. The number is in the user agent string, but each agent string is different from the others.

This is a problem now but it will go away someday. Maybe lime could have a option to build with the polyfill, for the people that need support to android 2.3.

**Comment by jgranick** [comment]
Okay, revisiting this again, I think that we should not include a polyfill for this in Lime right now:

http://caniuse.com/#feat=typedarrays

If we could reliably include the polyfill only when required, then I'd be open to it, but I'm concerned about the difficulty of testing this. I'd be open to a pull request, but for now, I think that perhaps not including it is reasonable by default, however, it could definitely be included per project, like this:

 1. Download [typedarray.js](https://raw.githubusercontent.com/inexorabletash/polyfill/master/typedarray.js) into your project
 2. Add <dependency path="to/typedarrays.js" if="js" /> to your project XML

This would add 38KB to your project, and should ensure that this is available once you run your project
