### ISSUE TITLE
"lime test" successfully builds but fails to run projects with a space in the name

### ISSUE THREAD

**Issue by q00u** [openfl/lime#30]
Making a simple Hello World test.

```
>lime test flash
'Hello' is not recognized as an internal or external command,
operable program or batch file.
```

What's interesting to me is that it DOES build the project successfully, so at least for part of the process it is handling names with spaces just fine. It is only the final step where it stops working.

I tried flash, neko, and windows as targets. All built successfully, and all failed to run after.

**Comment by jgranick** [comment]
This appears to be resolved, but please let me know if you encounter a specific OS + target combination that does not work properly with spaces. Certain targets fail to work properly if you use a file name with spaces, such as the Android target, which may be outside our control, but it seems that the default templates will remove spaces in the file name now, and running with spaces appears to work here
