### ISSUE TITLE
[html5] tilesheet.drawTiles is only drawing in the area initially visible in the stage

### ISSUE THREAD

**Issue by RafaelOliveira** [openfl/lime#302]
If I use the tilesheet.drawTiles to draw a sprite bigger than the stage, only the area initially visible on the stage is drawn. The rest of the sprite has nothing drawn.

**Comment by jgranick** [comment]
I'm going to go ahead and close this, since this would be an OpenFL issue, but please feel free to make a new issue on the OpenFL tracker, and please share the use case for this -- is this because the stage was resized? Thank you! :smile:
