### ISSUE TITLE
ImageDataUtil.getPixels returns pixels in a order different from older version of lime

### ISSUE THREAD

**Issue by vroad** [openfl/lime#303]
For non-flash targets ImageDataUtil now returns pixels in a different order. That broke texture rendering of my openfl-stage3d based apps.
Why did you change that??

https://github.com/openfl/lime/blob/4cec0df3156296e8465d04ce8296beb97c8f2d63/lime/graphics/utils/ImageDataUtil.hx

**Comment by jgranick** [comment]
You should be able to fix using `#if (lime > "2.0.3")` in your code, I apologize for the problem.

Using `getPixels` (as well as `getPixel` or `getPixel32`) should be consistent when using it against different data store types. The `getPixel` or `getPixel32` values returned pixels in ARGB format, similar to Flash or HTML5. When calling `getPixels` it was inconsistent, which was a bad way to go.

I think we could consider doing a different color order if it made sense not to use ARGB, or if there was a really compelling reason, we could allow it to be data type specific, but I would prefer to avoid it.

**Comment by jgranick** [comment]
By the way, in an unrelated, I'm interested still in your Node.js work, I had trouble finding a way to build the node NDLL module, if that was working, I have a feeling we're pretty close to being able to use it as a target, that and thinking if there was a way to make a Node.js binary that works without arguments

**Comment by vroad** [comment]
This is really confusing... What is "consistency" you are talking about? Isn't that true for little endian systems?
I believe pixels are originally stored in RGBA format in ImageBuffer, which can be directory passed to glTexImage2D with GL_RGBA format. Currently ```getPixels``` converts this to ... GBAR? What are you trying to do? Did you want to convert pixels to BGRA, so that images can be uploaded to GPU without swapping channels?
```
//0123
//RGBA
//1230
//GBAR
[0] = g; // (i + 1)
[1] = b; // (i + 2)
[2] = a; // (i + 3)
[3] = r; // (i)
```

If so I don't think that is a very good idea, because WebGL doesn't support BGRA and UNSIGNED_INT_8_8_8_8_REV, and breaks compatibility with flash target.

**Comment by vroad** [comment]
For node.js target

I think I have uploaded "package.json" to starling-openfl repo.
Copy json file to bin directory and execute "npm install". bindings module will be installed.
bindings is a node module that helps developers to load native addons, I suppose.
node_ndll can be easily built with node-gyp.

You should place the addon(node_ndll.node) by yourself since it is still not published to npm.
(Maybe there is a way to install addon from local repo, but I don't know it since I'm still new to node.)
Place it in "build" directory so that bindings module can find it.

You should fork node.js to execute an app without arguments and console.
On linux you don't have to do anything special to hide console, I think.
I already tried that in my own fork, so you can check it out.

Hope this helps.

**Comment by jgranick** [comment]
The intention is to provide consistency if you use `Image.getPixel`, `Image.getPixel32` or `Image.getPixels` in regards to the color order. I believe it should ARGB now on all targets, or that is the intention. If this is not the case, then we should fix it, unless we decide that Lime should be RGBA across the board, but I'm not sure. Either way, it should be one or the other.

This is different, potentially, then the data store format. The `imageBuffer.data` property might be RGBA so that it's consistent with what OpenGL expects. Part of this is the difference (and intention behind) the unified, higher-level (and optional) `Image` pixel APIs, versus setting the data directly.

**Comment by vroad** [comment]
You didn't mention endianness. Are you sure that byte order changes on big endian computers?

I beilieve pixels are not correctly ordered even for little-endian computers. They cannot be uploaded with BGRA(and UNSIGNED_INT_8_8_8_8_REV) format correctly. They should be stored in "BGRA" format to maintain consistency with getPixel32, because on little endian computers pixels are stored in reversed over.

BGRA is how OpenGL calls 32bit texture format which is natural for little-endian computers. Direct3D9 was calling texture formats in the opposite way since it was only designed for little endian computers, but this is really confusing for me.

**Comment by vroad** [comment]
And

**Comment by vroad** [comment]
Sorry I was also confused. ```BitmapData.getPixels``` always returns pixels in big endian format. Then pixels should be stored in ARGB, not BGRA.

**Comment by vroad** [comment]
Then this is corect behaviour... Maybe I should directly get ImageBuffer with untyped to get RGBA data without expensive swizzle operation.

**Comment by jgranick** [comment]
Yeah, perhaps it should be public, or there should be `bitmapData.getImage ()` or something, so you could `bitmapData.getImage ().buffer.data` directly, or something like that
