### ISSUE TITLE
loadPCMFromByteArray is not working

### ISSUE THREAD

**Issue by Type1J** [openfl/lime#307]
I have a function that generates a sound, and then loads it into a Sound object:

      public function SynthSamplesToSound(sound:Sound):Void {
        // get the samples
        var sampleOutput=new ByteArray();
        SynthAllSamples(sampleOutput);
        sampleOutput.position=0;
        sound.loadPCMFromByteArray(sampleOutput, sampleOutput.length>>2, "float", false, 44100.0);
      }

This function works in Flash (>15.0), but on native, I get the following message:

    Error after opening sound data
    Not Sound
    AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by Type1J** [comment]
I figured this one out. Here's my new function:

      public function SynthSamplesToSound(sound:Sound):Void {
        // get the samples
        var sampleOutput=new ByteArray();
        sampleOutput.bigEndian = false;
        #if flash
          SynthAllSamples(sampleOutput);
          sampleOutput.position=0;
          // The following function only works in Flash Players >= 15.0
          sound.loadPCMFromByteArray(sampleOutput, sampleOutput.length>>2, "float", false, 44100.0);
        #else
          ExportWAVToByteArray(sampleOutput); // Adds WAV headers, then calls SynthAllSamples() internally.
          sampleOutput.position=0;
          // OpenFL support WAV as a compressed data format.
          sound.loadCompressedDataFromByteArray(sampleOutput, sampleOutput.length);
        #end
      }
The v2 implementation of loadPCMFromByteArray does something similar. However, the generated samples are floating point samples. I changed ExportWAVToByteArray() to generate 16-bit samples to get everything working.

However, the reason that loadPCMFromByteArray wasn't working initially was that it accepts "float" (and "float" is the default), but in lime, OpenALSound::OpenALSound(float *inData, int len), and a few other constructors for other input types have the following lines:

         //Work out the format from the data
         if (_channels == 1) {
            if (_bitsPerSample == 8 ) {
               format = AL_FORMAT_MONO8;
            } else if (_bitsPerSample == 16) {
               format = (int)AL_FORMAT_MONO16;
            }
         } else if (_channels == 2) {
            if (_bitsPerSample == 8 ) {
               format = (int)AL_FORMAT_STEREO8;
            } else if (_bitsPerSample == 16) {
               format = (int)AL_FORMAT_STEREO16;
            }
         } //channels = 2

However, _bitsPerSample is 32! To use OpenAL to play FLOAT32 samples requires an extension, which isn't available on all platforms. Ogg will not produce FLOAT32, so we're safe there. Since the main use for WAV files will be very short sounds, we may want to consider converting FLOAT32 samples to 16-bit samples in this block. It will be something like:

    while(inPtr < endInPtr)
      *outPtr++ = (float)(*inPtr++) / 32767.0f;

where inPtr and endInPtr are float*, and outPtr is short* (or int16_t).

That change in lime legacy will make OpenFL's loadPCMFromByteArray work as expected. However, that's adding the hidden cost of this loop. I think it's worth it because this function is usually called only when the app is loading something, so it's probably during a "Loading . . ." screen. It's still so fast that it's unnoticeable for small files.

**Comment by Type1J** [comment]
It seems that there's some work for html5 sound loading, but I'm not sure if that includes from samples. It looks like only loading from an URL with sound.js is currently supported in OpenFL. Does Lime have a way to load samples on html5, yet?

**Comment by jgranick** [comment]
Hi!

Although this is technically in Lime legacy, I'm moving legacy issues into the OpenFL issue tracker, so they can be tracked as Flash API behavior bugs and fixes. From a Lime API perspective, the legacy API is deprecated, so I'm going to keep the Lime issue tracker open for issues in the Lime 2 API.

It sounds like, ideally, we want to find a way to automatically detect the audio type without adding a header, and then make sure that when you use a ByteArray, that it's in a format that's compatible with OpenAL? Happy to talk about this more on the new issue I've opened:

https://github.com/openfl/openfl/issues/511

Thank you! :smile:
