### ISSUE TITLE
lime.embed limited to accepting elementName

### ISSUE THREAD

**Issue by urbananimal** [openfl/lime#312]
Hey everyone. I am working on an openfl project which needs to be integrated with a third party wrapper application, therefore I cannot use the default index.html output by the openfl compilation process. I have to kick-off the application manually by calling lime.embed from within my code and passing the function an element which the wrapper instructs me to use. The problem is that lime embed specifically expects a string elementName and then finds the element to render in by getElementById(). This is a problem for my application because my code runs in an iframe but the element the wrapper passes me is in the parent document so document.getElementById will not find the element. At the moment I'm hacking it with my build script but it's a pretty straightforward change that could potentially benefit others.

I would like to propose that either - 

1. Another optional parameter is added to the embed method domElement (or similar) which if passed is used as the element in place of searching the dom for it.

or 

2. elementName type is changed from String to Dynamic then the element is only looked up if a string is passed.

Any thoughts?

Thanks

Mark

**Comment by jgranick** [comment]
Perhaps it should always be an element, then the default template should `getElementByName` as the argument

**Comment by jgranick** [comment]
Okay, I took your advice and made it accept both -- I can't expect this to affect performance, and this will make it more usable -- either the ID string or the actual element reference is going to be more convenient, but it will depend on the use case.

https://github.com/openfl/lime/commit/faf4fd71abe9c7f006647ef0feea3deb705b653f

Thank you, and please let me know if it works out for you! :smile:

**Comment by urbananimal** [comment]
Excellent! Really helps me out. Thanks :)
