### ISSUE TITLE
Why do we use #if (js && html5) instead of just #if html5?

### ISSUE THREAD

**Issue by vroad** [openfl/lime#314]
HTML5 is always used with JavaScript, so I don't understand why this conditional compliation macro is combined with js.

**Comment by jgranick** [comment]
Sometimes I run with HTML5 and not JavaScript, for example, for documentation. As well, I think it helps make sure that we're thinking properly about what is JavaScript *AND* HTML5, or what is just JavaScript. As you know already, a Node.js environment with JavaScript is not the same as having the DOM as well. As "html5" and "js" are used interchangeably (or were), perhaps it helps keep us honest as well :wink:
