### ISSUE TITLE
SDL_DestroyRenderer is never used (memory leak?)

### ISSUE THREAD

**Issue by vroad** [openfl/lime#317]
Shouldn't we call this in SDLRenderer's destructor?

https://wiki.libsdl.org/SDL_DestroyRenderer
https://github.com/openfl/lime/blob/8e3d3285925db777e6d365f9c9f4e9173b542c21/project/src/backend/sdl/SDLRenderer.cpp#L25

**Comment by jgranick** [comment]
Good call, here we go :smile:

https://github.com/openfl/lime/commit/8fe8659
