### ISSUE TITLE
GlowFilter is not working with inner = true on native platform

### ISSUE THREAD

**Issue by pozirk** [openfl/lime#318]
With **inner = false** it works fine.
I have tried on Window platform.
Everything works as expected on Flash.

>haxelib list
>actuate: 1.8.0 [1.8.1]
>admob: [1.1.0]
>format: [3.1.2]
>haxelib_client: [3.1.0-rc.4]
>hxcpp: 3.1.0 [3.1.48]
>lime-tools: [1.5.7]
>lime: 1.0.1 2.0.4 [2.0.5]
>nook-shop: [0.0.1]
>openfl-samples: 1.3.0 2.2.0 [2.2.1]
>openfl: 2.0.1 2.2.1 [2.2.3]
>svg: [1.0.8]
>swf: 1.5.2 1.7.3 [1.7.5]

Thank you!

**Comment by jgranick** [comment]
Hi!

I'm closing this and moving it to OpenFL, even though this is technically a Lime issue, I'm not going to continue to track Lime legacy issues here, and instead can track them as OpenFL behavior issues. I've opened a new issue up under OpenFL, here https://github.com/openfl/openfl/issues/510

Thanks!
