### ISSUE TITLE
MOD, XM via SDL2_Mixer?

### ISSUE THREAD

**Issue by neolit123** [openfl/lime#322]
hello,

SDL based platforms can use SDL2_Mixer to play tracker formats via the modplug library and also there are players for Flash (FLOD)  and some for JS.
so i was wondering if that's planned for lime?

thanks

**Comment by jgranick** [comment]
I'm going to close this for now, as we can discuss more on the OpenFL forums or in the OpenFL Slack (can send an invite), closing TODO-style items on the issue tracker for now to better keep track of bugs, thanks!
