### ISSUE TITLE
lime tools on iOs: set -DHXCPP_API_LEVEL

### ISSUE THREAD

**Issue by waneck** [openfl/lime#323]
On the bleeding edge at Haxe, hxcpp defines a property that is used by the haxe code only if HXCPP_API_LEVEL >= 313 : https://github.com/HaxeFoundation/hxcpp/blob/master/include/hxcpp.h#L208

Since the lime build tool calls hxcpp with `-D no-compilation` and compiles HXCPP itself, this flag must be passed to the native compiler (e.g. `haxelib run hxcpp Build.xml -DHXCPP_API_LEVEL=313`) otherwise the build fails

**Comment by jgranick** [comment]
Is this define written in the Options.txt file that HXCPP outputs? If not, is there some place/way that we can automatically determine this value?

**Comment by waneck** [comment]
Yes it is written on Options.txt

**Comment by jgranick** [comment]
We should be reading Options.txt and passing it all in

**Comment by waneck** [comment]
Hmmm you're right. It seems that the problem is that Options.txt outputs it in lower-case, while lime outputs to the makefile in upper-case. Hxcpp seems to only deal with them if they are in lower-case. I've tried changing the makefiles myself and got it to compile.
Do you have any idea why it's outputting with a different case?

**Comment by jgranick** [comment]
I don't see it converting the case:

https://github.com/openfl/lime/blob/a369f16709c0615030bd75f25b48e5d9e2d3f2c7/tools/helpers/CPPHelper.hx#L29

...though sometimes HXCPP will define something in lower-case (like -Dwindows) and then, in turn, pass a new define onto the C++ process (HX_WINDOWS)

This, however, is done in each toolchain, or by the build common, perhaps the variable isn't being passed through on the HXCPP side, in the toolchain XML or common XML

**Comment by waneck** [comment]
But this is only when you compile directly through lime, right? For iOs, it seems to use a makefile that is generated here:
https://github.com/openfl/lime/blob/master/templates/iphone/PROJ/haxe/makefile#L53

**Comment by jgranick** [comment]
Hmm, yeah, iOS is still the odd duck, what a bother. That's in lime/tools/platforms/IOSPlatform.hx (where it defines the CPP_BUILD_FLAGS), perhaps there should be a method in CPPHelper to get the standard CPP build flags, then the CPPHelper build can call that, and the IOSPlatform can call that just to get the flags and pass them into the template

BTW, what is the "native property" functionality, that's defined here? Do you know?

**Comment by waneck** [comment]
Yeah, I'm also not sure what's the best way to deal with that. Why don't you compile haxe directly (without -D no-compilation)?

>BTW, what is the "native property" functionality, that's defined here? Do you know?
I'm not sure; My guess is that it's got to do with dynamic property access. Not sure how though.
