### ISSUE TITLE
lime 2.0.6 broke blackberry builds

### ISSUE THREAD

**Issue by stahlratte** [openfl/lime#328]
when i switch to lime 2.0.6 blackberry builds will build and run, but immediately close again.
sdk 10.2 on a z10 with 10.2

**Comment by YaroslavKrykun** [comment]
Same behavior with lime 2.0.6 BlackBerry tabletos and android. 2.0.5 works fine.

**Comment by jgranick** [comment]
This was caused by an initial bad build, 2.0.6 was re-released on haxelib with a fixed build
