### ISSUE TITLE
WebGL Broken in Lime 2.0.6 (OpenFL 2.2.4)

### ISSUE THREAD

**Issue by starburst997** [openfl/lime#335]
On Lime 2.0.4 (didn't test on 2.0.5) and OpenFL 2.2.2 when I use the -Dwebgl everything is fine, but with the latest update I get a bunch of

```
WebGL: INVALID_OPERATION: texImage2D: type UNSIGNED_BYTE but ArrayBufferView not Uint8Array
228(index):1 
[.WebGLRenderingContext]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering or is not 'texture complete'
```

**Comment by jgranick** [comment]
I think this should fix it: https://github.com/openfl/lime/commit/f7ff0f79049a118e62311c0e25a8a871f3e63490
