### ISSUE TITLE
BitmapData.applyFilter() works wrong

### ISSUE THREAD

**Issue by void616** [openfl/lime#337]
BitmapData.applyFilter() works differently on flash and windows targets.

-- Code:

bd.applyFilter(
    bd,
    bd.rect,
    new Point(0, 0),
    new ColorMatrixFilter([
        2.00,	0.15,	-1.15,	0,	0,
        -0.60,	1.30,	0.35,	0,	0,
        0.58,	-1.65,	2.00,	0,	0,
        0,	0,	0,	1,	0
    ])
);

-- Result:
![87a8169f6e46beec](https://cloud.githubusercontent.com/assets/10888589/6087516/8f628870-ae5d-11e4-857f-72e1e9e12135.png)
![2d6e2306b8464849](https://cloud.githubusercontent.com/assets/10888589/6087520/9542ab26-ae5d-11e4-9066-5d3c7c71bd3d.png)

Looks like value overflow.

**Comment by jgranick** [comment]
Fixed, thank you! :smile:

https://github.com/openfl/lime/commit/b0438b8686b718c1da3fe812192711dcde2f4244
