### ISSUE TITLE
haxeflag parameter escaping problem

### ISSUE THREAD

**Issue by lafiosca** [openfl/lime#346]
Hi, I'm fairly new to Haxe/OpenFL/lime, so please pardon me if I'm being ignorant. I think this might also be related to issue #170, but possibly not.

I'm attempting to develop a Flash game using HaxeFlixel in OSX. I was running lime 2.0.6, but I upgraded to 2.1.2 in the process of trying to troubleshoot this issue. I think the behavior was the same in both.

I was trying to pass an include initialization macro to haxe via the Project.xml config like this, as I saw in examples online:

```xml
    <haxeflag name="--macro" value="include('foo.bar')" />
```

Running a "lime test flash" with this in my Project.xml failed out with an unhelpful error. Running "lime -verbose test flash" ends like this:

```
Running command: BUILD
 - Running command: haxe -main ApplicationMain -cp /usr/lib/haxe/lib/flixel/3,3,6 -D flixel=3.3.6 -cp /usr/lib/haxe/lib/openfl/2,2,4 -D openfl=2.2.4 -cp /usr/lib/haxe/lib/lime/2,1,2 -D lime=2.1.2 -cp source -D lime-openal -D tools=2.1.2 -D flash-use-stage -D no-compilation -D lime-opengl -D NAPE_RELEASE_BUILD -D openfl-flash -D FLX_RENDER_BLIT -D lime-curl -D web --macro 'include('foo.bar')' -swf-lib /Users/xxx/devel/xxx/export/flash/obj/assets.swf -swf-version 11.8 -swf export/flash/bin/xxx.swf -cp export/flash/haxe
--macro:1: character 0 : Unknown identifier : foo
--macro:1: character 0 : Parameter should be a constant
```

Assuming that this line is being called in a shell, the **--macro 'include('foo.bar')'** in particular looks fishy because it won't properly pass the single quotes in the value of the argument. So I tried to change it up by switching the single and double quotes in the XML like this:

```xml
    <haxeflag name="--macro" value='include("foo.bar")' />
```

This gave me the desired argument syntax in the debug output, **'include("foo.bar")'**, but it still failed:

```
Running command: BUILD
 - Running command: haxe -main ApplicationMain -cp /usr/lib/haxe/lib/flixel/3,3,6 -D flixel=3.3.6 -cp /usr/lib/haxe/lib/openfl/2,2,4 -D openfl=2.2.4 -cp /usr/lib/haxe/lib/lime/2,1,2 -D lime=2.1.2 -cp source -D lime-openal -D tools=2.1.2 -D flash-use-stage -D no-compilation -D lime-opengl -D NAPE_RELEASE_BUILD -D openfl-flash -D FLX_RENDER_BLIT -D lime-curl -D web --macro 'include("foo.bar")' -swf-lib /Users/xxx/devel/xxx/export/flash/obj/assets.swf -swf-version 11.8 -swf export/flash/bin/xxx.swf -cp export/flash/haxe
--macro:1: character 0 : Invalid macro call
```

That made me scratch my head a little, and I tried running the exact haxe command there manually by copying/pasting it into my shell command prompt. Sure enough, the command worked just fine. So I believe that lime is doing something to further mangle the macro argument between outputting the debug line and actually executing the command.

Please let me know if you agree or if I am missing something obvious.

Thanks,
/joe

**Comment by jgranick** [comment]
This appears to work correctly (either way) in Windows, so this must be specific to OS X or bash scripting. I need to boot up OS X and give it a try

**Comment by jgranick** [comment]
That's strange, I just booted OS X, and it works here, too (both versions)

Are you using Haxe 3.1.3, or another version?

**Comment by lafiosca** [comment]
Haxe is showing 3.1.3, and I'm still on Mavericks:

```
$ haxe -version
3.1.3
$ uname -a
Darwin yidhra 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64 x86_64
$ bash --version
GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin13)
Copyright (C) 2007 Free Software Foundation, Inc.
```

If there's anything else useful I can provide, let me know. I'm not very familiar with the haxe stack yet.

Thanks,
/joe

**Comment by lafiosca** [comment]
For reference, I was using the default Project.xml generated by HaxeFlixel. I'm not sure if anything else in the file could have any bearing on this. I can share the entire file it helps.

/joe

**Comment by jgranick** [comment]
Is there any chance you have `lime-tools` or `aether` installed, and that your `lime` command references old tools? Do you think I could recreate with a standard Flixel sample project?

If you have a simple project that breaks that you could post somewhere (just the source of project.xml and Main.hx are fine) that would also be nice :smile:

**Comment by lafiosca** [comment]
I don't recall installing lime-tools or aether. How would I check to be sure?

Here's a tarball of a Flixel template project with the haxelib line added. It's giving me the failure behavior:

 https://dl.dropboxusercontent.com/u/17649003/bugtest.tgz

I included all the files, just in case.

Here's the full output for me:

```
~/bugtest$ lime -verbose test flash
 ___     
/\_ \    __                       
\//\ \  /\_\    ___ ___      __   
  \ \ \ \/\ \ /' __` __`\  /'__`\ 
   \_\ \_\ \ \/\ \/\ \/\ \/\  __/ 
   /\____\\ \_\ \_\ \_\ \_\ \____\
   \/____/ \/_/\/_/\/_/\/_/\/____/

Lime Command-Line Tools (2.1.2)

Initializing project...
Using project file: /Users/fnord/bugtest/project.xml
Reading HXCPP config: /Users/fnord/.hxcpp_config.xml
Using target platform: FLASH

Running command: UPDATE
 - Embedding asset: (TEXT) assets/data/data-goes-here.txt
 - Embedding asset: (TEXT) assets/images/images-go-here.txt
 - Embedding asset: (TEXT) assets/music/music-goes-here.txt
 - Embedding asset: (TEXT) assets/sounds/sounds-go-here.txt
 - Embedding asset: (MUSIC) /usr/lib/haxe/lib/flixel/3,3,6/assets/sounds/beep.mp3
 - Embedding asset: (MUSIC) /usr/lib/haxe/lib/flixel/3,3,6/assets/sounds/flixel.mp3
 - Embedding asset: (TEXT) assets/data/data-goes-here.txt
 - Embedding asset: (TEXT) assets/images/images-go-here.txt
 - Embedding asset: (TEXT) assets/music/music-goes-here.txt
 - Embedding asset: (TEXT) assets/sounds/sounds-go-here.txt
 - Embedding asset: (MUSIC) /usr/lib/haxe/lib/flixel/3,3,6/assets/sounds/beep.mp3
 - Embedding asset: (MUSIC) /usr/lib/haxe/lib/flixel/3,3,6/assets/sounds/flixel.mp3
 - Copying template file: /usr/lib/haxe/lib/lime/2,1,2/templates/haxe/ApplicationMain.hx -> export/flash/haxe/ApplicationMain.hx
 - Copying template file: /usr/lib/haxe/lib/lime/2,1,2/templates/haxe/DefaultAssetLibrary.hx -> export/flash/haxe/DefaultAssetLibrary.hx
 - Copying template file: /usr/lib/haxe/lib/openfl/2,2,4/templates/haxe/ApplicationMain.hx -> export/flash/haxe/ApplicationMain.hx
 - Copying template file: /usr/lib/haxe/lib/openfl/2,2,4/templates/haxe/NMEPreloader.hx -> export/flash/haxe/NMEPreloader.hx
 - Copying template file: /usr/lib/haxe/lib/lime/2,1,2/templates/flash/hxml/debug.hxml -> export/flash/haxe/debug.hxml
 - Copying template file: /usr/lib/haxe/lib/lime/2,1,2/templates/flash/hxml/final.hxml -> export/flash/haxe/final.hxml
 - Copying template file: /usr/lib/haxe/lib/lime/2,1,2/templates/flash/hxml/release.hxml -> export/flash/haxe/release.hxml
 - Copying template file: /usr/lib/haxe/lib/openfl/2,2,4/templates/flash/hxml/debug.hxml -> export/flash/haxe/debug.hxml
 - Copying template file: /usr/lib/haxe/lib/openfl/2,2,4/templates/flash/hxml/final.hxml -> export/flash/haxe/final.hxml
 - Copying template file: /usr/lib/haxe/lib/openfl/2,2,4/templates/flash/hxml/release.hxml -> export/flash/haxe/release.hxml

Running command: BUILD
 - Running command: haxe -main ApplicationMain -cp /usr/lib/haxe/lib/flixel/3,3,6 -D flixel=3.3.6 -cp /usr/lib/haxe/lib/openfl/2,2,4 -D openfl=2.2.4 -cp /usr/lib/haxe/lib/lime/2,1,2 -D lime=2.1.2 -cp source -D lime-openal -D tools=2.1.2 -D FLX_NO_DEBUG -D flash-use-stage -D no-compilation -D lime-opengl -D NAPE_RELEASE_BUILD -D openfl-flash -D FLX_RENDER_BLIT -D lime-curl -D web --macro 'include('foo.bar')' -swf-lib /Users/fnord/bugtest/export/flash/obj/assets.swf -swf-version 11.8 -swf export/flash/bin/bugtest.swf -cp export/flash/haxe
--macro:1: character 0 : Unknown identifier : foo
--macro:1: character 0 : Parameter should be a constant
```

And here's the contents of .hxcpp_config.xml:

```
<xml>

	<section id="vars">
		
		<set name="ANDROID_SETUP" value="true" />
		<set name="ANDROID_NDK_ROOT" value="/opt/android-ndk" />
		<set name="MAC_USE_CURRENT_SDK" value="1" />
		<set name="ANDROID_SDK" value="/opt/android-sdk" />
		<set name="ANT_HOME" value="/opt/apache-ant" />
		
	</section>

</xml>
```

**Comment by lafiosca** [comment]
For additional information, I'd like to share these verbose outputs from two other versions of the haxelib line.

The original quote switcheroo:

```xml
    <haxeflag name="--macro" value='include("foo.bar")' />
```

yields **--macro 'include("foo.bar")'** which looks right but doesn't seem to be executed correctly:

```
 - Running command: haxe -main ApplicationMain -cp /usr/lib/haxe/lib/flixel/3,3,6 -D flixel=3.3.6 -cp /usr/lib/haxe/lib/openfl/2,2,4 -D openfl=2.2.4 -cp /usr/lib/haxe/lib/lime/2,1,2 -D lime=2.1.2 -cp source -D lime-openal -D tools=2.1.2 -D FLX_NO_DEBUG -D flash-use-stage -D no-compilation -D lime-opengl -D NAPE_RELEASE_BUILD -D openfl-flash -D FLX_RENDER_BLIT -D lime-curl -D web --macro 'include("foo.bar")' -swf-lib /Users/fnord/bugtest/export/flash/obj/assets.swf -swf-version 11.8 -swf export/flash/bin/bugtest.swf -cp export/flash/haxe
--macro:1: character 0 : Invalid macro call
```

And, even weirder, adding a comma for the second parameter makes the argument look completely wrong:

```xml
    <haxeflag name="--macro" value="include('foo.bar', true)" />
```

yields **--macro "'include('foo.bar', true)'"** as follows:

```
 - Running command: haxe -main ApplicationMain -cp /usr/lib/haxe/lib/flixel/3,3,6 -D flixel=3.3.6 -cp /usr/lib/haxe/lib/openfl/2,2,4 -D openfl=2.2.4 -cp /usr/lib/haxe/lib/lime/2,1,2 -D lime=2.1.2 -cp source -D lime-openal -D tools=2.1.2 -D FLX_NO_DEBUG -D flash-use-stage -D no-compilation -D lime-opengl -D NAPE_RELEASE_BUILD -D openfl-flash -D FLX_RENDER_BLIT -D lime-curl -D web --macro "'include('foo.bar', true)'" -swf-lib /Users/fnord/bugtest/export/flash/obj/assets.swf -swf-version 11.8 -swf export/flash/bin/bugtest.swf -cp export/flash/haxe
File "interp.ml", line 190, characters 32-38: Assertion failed
```

**Comment by jgranick** [comment]
Got it, popped up on OS X with your project. This was really weird to try and fix! :smile:

**Comment by lafiosca** [comment]
Hmm, I think your diff looks like it should work, but trying to apply it manually to my installed 2.1.2 is not giving me any different results. (I think I may just be doing something wrong on my system because it seems like /usr/lib/haxe/lib/lime/2,1,2/lime/tools/platforms/FlashPlatform.hx is not even being called.)

I can wait until the next version release to test again because I am already working around my need for the macro via code. Not in a rush.

Thanks for your quick and helpful responses.

/joe

**Comment by jgranick** [comment]
If you patched your file, you'll want to:

    haxelib install format
    lime rebuild tools

to apply it :smile:

**Comment by lafiosca** [comment]
That worked for the original problem, thanks! Should I open a separate issue for the problem with handling values containing commas?

**Comment by jgranick** [comment]
It was not actually the comma, but the space. I think I found a way to prevent the command from being quoted (and thereby messing it up, since it already is quoted/escaped) without affecting other arguments. Whew!

**Comment by lafiosca** [comment]
Great work. I tested this with all four permutations (single/double-quote swap, with and without second argument), and all looked good to me.

Thanks again for your effort.

/joe
