### ISSUE TITLE
iOS build failure with latest version (legacy): no ApplicationMain.*.a

### ISSUE THREAD

**Issue by bendmorris** [openfl/lime#351]
Trying to build with iOS results in this error:

haxe Build.hxml -D HXCPP_ARM64 -cpp build/Release-iphoneos-64
cd build/Release-iphoneos-64; export HXCPP_NO_COLOR=1; haxelib run hxcpp Build.xml -Dios -Diphone -DHXCPP_ARM64 -DHXCPP_CPP11  -DHXCPP_CLANG -DOBJC_ARC `grep " -D" Options.txt`
cp build/Release-iphoneos-64/ApplicationMain.iphoneos-64.a ../lib/arm64/libApplicationMain.a
cp: build/Release-iphoneos-64/ApplicationMain.iphoneos-64.a: No such file or directory
make: *** [build-haxe-arm64] Error 1

There's no ApplicationMain.iphoneos-64.a in that directory, but there is a libApplicationMain.iphoneos-64.a.

Updating the Makefile template to change ApplicationMain to libApplicationMain seems to solve the issue, but not sure if this has other effects or is the best solution.

**Comment by jgranick** [comment]
What version of HXCPP are you using?

**Comment by bendmorris** [comment]
Latest version from Git.

**Comment by jgranick** [comment]
Thanks! Yep, this is specific to the dev version, and not in a release. Fixed (in a semi-hacky way for now) here:

https://github.com/openfl/lime/commit/e51871c3728985d6397ce21d00430bddfab5e409

There must be a better way to set up the iOS project template than this makefile :confused:
