### ISSUE TITLE
Still memory leaks are there?

### ISSUE THREAD

**Issue by vroad** [openfl/lime#352]
I checked whether SDLRenderer/SDLWindow/Font's destructors are called but they were not called unfortunately.
SDLWindow and FOnt can be destroyed with lime_window_close() and lime_destroy_font(), but what about Renderer?

**Comment by jgranick** [comment]
Perhaps we need to null the Window/renderer references, and force a GC run when doing a clean exit. These are supposed to be collected when it hits garbage collection, but I suppose they never do hit garbage collection in a normal application lifecycle

**Comment by vroad** [comment]
There are multiple memory leak problems in this project. It should be written from beginning, I guess.
 - variables allocated with AutoGCRoot is not released
 - val_gc is not used for some objects
 - Base interface classes has no virtual destructor, so destructor of derived classes will not be invoked

lime is relying on val_gc, but on nodejs, it seems very difficult to call C++ destructor when an object is destructed. It is still possible to call them at exit, though. If we support nodejs as well, we should manually destruct C++ objects when we no longer need them.

**Comment by vroad** [comment]
We may need to store pointers in objects rather than storing it directly, so that we can pass them by reference.
Lime is using val_gc against floating point numbers for now, but on V8,  numbers seem not be garbage collected at all.

How are numbers treated in other targets? Aren't they passed by value? They may not be garbage collected even on neko and cpp.

**Comment by vroad** [comment]
I created NativePointer class which wraps C++ objects, and installs finalization callback automatically.
As this store pointer inside an object, this should work on all targets including nodejs. I also added virtual destructor to some classes so that destructor of derived classes work when they are deleted.

https://github.com/vroad/lime/commit/7e44744950c0c2afecb8e1a4453a052c755b8c30

**Comment by vroad** [comment]
Will this issue fixed? Latest lime is still using double for native pointers.
Without wrapping native pointers, it's impossible to run lime on nodejs without memory leaks.

**Comment by jgranick** [comment]
Tracking here: https://github.com/openfl/lime/issues/876

Thanks :smile:
