### ISSUE TITLE
Debug/Release should not clean one another

### ISSUE THREAD

**Issue by larsiusprime** [openfl/lime#353]
The biggest time-sink in my daily work is whenever I trigger a clean build for native (in my case windows) targets. It takes so long for the C++ compiler to churn through my whole project. This makes me extremely reluctant to switch between debug/release modes because I know I'll have to wait through a whole new chug just to get back to incremental compiling for the other mode.

I propose:
- Cleanly separate debug/release mode incremental output
- Triggering a "clean" build on a new debug/release compile will only clean the respective debug/release directory

This will MASSIVELY speed up my workflow if it could be implemented, and I think it would be equally helpful to other developers.

**Comment by grisevg** [comment]
I have something like that
```
<app path="bin/debug/" if="debug"/>
<app path="bin/release/" if="release"/>
```
Well actually i have more configurations so it's
`<app path="bin/${myproject_configuration}"/` />

**Comment by larsiusprime** [comment]
So you're saying if I just do that, everything will be fine?

**Comment by underscorediscovery** [comment]
Generally hxcpp build output is separated by debug/release and switching only has to build the changes. you don't need to clean to switch between them (at least not from hxcpp perspective). 
Check your cpp/ folder inside there, you should see the separation something like:

![screenshot 2015-02-25 14 06 35](https://cloud.githubusercontent.com/assets/236374/6376286/8b1635ca-bcf7-11e4-8ceb-0f1c38f572a6.png)

**Comment by larsiusprime** [comment]
Interesting, I wonder why running "lime test windows -release" when debug output exists seems to clean it, and vice versa.

**Comment by jgranick** [comment]
Using `lime rebuild windows -clean` used to remove the "obj" directory entirely, now it uses HXCPP's own clean functionality, to allow it to clean only the current architecture being rebuilt.

Using `lime build windows -clean`, on the other hand, currently cleans the entire build directory, including the "obj" folder as well the "bin" folder. I'm not sure if we should handle it differently when you `lime build windows -clean` versus `lime clean windows`, or...

**Comment by larsiusprime** [comment]
I think the most natural thing for it to do is to clean whatever directory (release or debug) is implied by default when not specifying -debug or -release int he command.

**Comment by larsiusprime** [comment]
Okay!

So @grisevg's solution worked great. I did this:

```
<app file="DefendersQuest" path="export/debug" main="com.leveluplabs.defq1.Main" if="debug"/>
<app file="DefendersQuest" path="export/release/" main="com.leveluplabs.defq1.Main" if="release"/>
```

Is there any reason a setup like this isn't the default project setup? Once it's set it up it should save people a lot of time with unnecessary cleans when they switch back and forth between debug/release mode.

**Comment by grisevg** [comment]
@larsiusprime you can get rid of duplication:
```
<app file="DefendersQuest" main="com.leveluplabs.defq1.Main" />
<app path="export/debug/"  if="debug"/>
<app path="export/release/" if="release"/>
```

**Comment by larsiusprime** [comment]
Neat.

**Comment by larsiusprime** [comment]
That solves my issue. I think it would be smart to make something like the syntax in @grisevg's comment the default, as it's not immediately obvious how to do that and I think it could save a lot of people compiling time. I just tested it now and it works, switching to "debug" mode in flashdevelop after compiling in release mode does not trigger a clean, this is perfect and now it's very user friendly.

**Comment by delahee** [comment]
Agreed !

**Comment by jgranick** [comment]
Separating based on the build configuration -- is this something that you guys are interested in, just to handle the "clean" behavior, or are you interested in this in order to preserve two entirely separate "bin" directories?

**Comment by larsiusprime** [comment]
My first priority is to just avoid the clean trigger, and this seems like the simplest way to accomplish that as all it requires is a small change to the default xml template.

**Comment by delahee** [comment]
Same as Lars, Default visual studio setup is same too.

**Comment by kevinresol** [comment]
+1 for this to be default behavior

**Comment by kevinresol** [comment]
I dunno, but @grisevg 's solution does not work for me while the follow worked:
```xml
<set name="BUILD_DIR" value="export/debug/" if="debug" />
<set name="BUILD_DIR" value="export/release/" if="release" />
```

**Comment by Tiago-Ling** [comment]
Both methods provided don't work for me. Is it a version thing (using 2.4.4 from haxelib) or does where you put those lines matter?

**Comment by ibilon** [comment]
We could use `debug` and `release` (+ final) subdirs in `$Export\os\target\` directly in the tools maybe.

**Comment by Tiago-Ling** [comment]
+1 for that!

Tiago Ling Alexandre
Tel: +55 41 8819-3191


2016-06-05 10:20 GMT-03:00 Valentin Lemière <notifications@github.com>:

**Comment by ibilon** [comment]
Couldn't test all the targets, so hopefully this didn't add any bugs.
