### ISSUE TITLE
shell command: 'openfl setup blackberry' downloads an NDK installer that doesn’t work on OSX Yosemite 10.10

### ISSUE THREAD

**Issue by bemusementpark** [openfl/lime#354]
The installer is 600MB, and gives an OSX10.10 user only one option: to quit.
It'd help to alert a user prior to the download.
It could be good to link to a valid NDK and avoid the installer.

Installer in question available here:
http://developer.blackberry.com/native/downloads/fetch/installer-bbndk-2.1.0-macosx-1032-201209271809-201209280007.dmg

**Comment by jgranick** [comment]
Lime no longer supports BlackBerry 10 directly in current releases, but for older releases, it sounds like a manual install would be necessary on a newer version of OS X.

We love BlackBerry 10, but the "market has spoken." Thanks for your feedback, have a great day :grin:
