### ISSUE TITLE
opengl getParameter design is insuficient

### ISSUE THREAD

**Issue by delahee** [openfl/lime#357]
When querying for extension, I always have to modify and recompile lime/nme/etc to hardcode extension names/identifiers.

This is against the interest of gl users.

GL has put in place getParameter and extensions to be able to detect extensions and parameters at runtime, for example to query MAX_TEXTURE_MAX_ANISOTROPY_EXT sample count.

@jgranick 

I propose we add :

```
getParameterInt
getParameterFloat
getParameterString
```

that would fallback to get parameter on js.

and that those _do not ever_ try to identify the passed value so that unknown extensions are acceptable.

If you agree, we can provide a patch for cpp.

**Comment by jgranick** [comment]
Tracking here: https://trello.com/c/lCKWqKf6/48-improve-the-behavior-of-gl-getparameter
