### ISSUE TITLE
<set> has differents behaviors on iOs and android.

### ISSUE THREAD

**Issue by TBaudon** [openfl/lime#364]
Hello,

I think I met a bug lately with the tag <set>.

My use case is the following :

in my application.xml I use the tag ```<set name="hasStore">``` to indicate that my game use inAppPurchase.

In the include.xml of a custom lib, is use the tag ```<haxelib name="iap" if="hasStore" />``` and in my code I use ```#if hasStore
...
#end``` to activate shop in the game or not.

Everything works fine when building for android on windows, but for iOs on OsX this doesn't seems to work, hasStore is undefined. I had to use ```<haxeflag>``` instead but then the variable hasStore is not defined for the included include.xml

Thanks

**Comment by jgranick** [comment]
When you `<set />`, it should apply to XML, and should not be available to Haxe code unless you use `<haxedef />`
