### ISSUE TITLE
Launch Images on ios 8

### ISSUE THREAD

**Issue by starburst997** [openfl/lime#367]
On a iPhone 4s with iOS 8 I can't get the launch image to show up (black screen) but with iOS < 8 it does.

Here's what I use inside the XML:

```
        <launchImage path="Assets/ios/Default.png" width="320" height="480" />
        <launchImage path="Assets/ios/Default@2x.png" width="640" height="960" />
        <launchImage path="Assets/ios/Default-568h@2x.png" width="640" height="1136" />
        <launchImage path="Assets/ios/Default-Portrait.png" width="768" height="1024" />
        <launchImage path="Assets/ios/Default-Landscape.png" width="1024" height="768" />
        <launchImage path="Assets/ios/Default-Portrait@2x.png" width="1536" height="2048" />
        <launchImage path="Assets/ios/Default-Landscape@2x.png" width="2048" height="1536" /> 
        <launchImage path="Assets/ios/Default-667h@2x.png" width="750" height="1334" />
        <launchImage path="Assets/ios/Default-736h@3x.png" width="1242" height="2208" />
        <launchImage path="Assets/ios/Default-736h-Landscape@3x.png" width="2208" height="1242" />
```

On Lime 2.0.4 everything seems to works fine, so this is since Images.xcassets was added.

Also I did try on a clean new PiratePig sample, latest XCode, lime test ios, black screen on launch.

**Comment by jgranick** [comment]
Are you still having this problem with newer versions?

**Comment by adventure1911** [comment]
Im still experiencing this problem on iPhones all generations.

**Comment by TFGames** [comment]
Hello, I use the game development platform Stencyl and am also unable to get launch images to show up in landscape mode. The Stencyl dev team traces the problem to this bug. Hoping it can get some attention soon, thanks.

**Comment by larsiusprime** [comment]
@TFGames -- do you know what version of Lime/OpenFL Stencyl uses?

**Comment by TFGames** [comment]
They tell me they are using 2.0.6 and updated in February or March.  They also say: "If it was fixed, all we need to know is when it was fixed, and we can pull in the fix."

Thanks!

**Comment by TFGames** [comment]
So is this still an open issue? I'm not an experienced programmer, so I may have the wording wrong. I'm just trying to facilitate between here and the Stencyl team. Thanks!

**Comment by jon914** [comment]
Stencyl now uses Lime 2.6.8, but our users still claim to see this. Could you look into it?

**Comment by larsiusprime** [comment]
@jon914, Oh cool, you're on the latest Lime branch? Let me ping @jgranick

**Comment by jon914** [comment]
Yeah, we've been able to keep up to date a lot better since moving our entire stack to Git.

**Comment by jon914** [comment]
@larsiusprime - Did @jgranick find out anything about this?
