### ISSUE TITLE
[ios] can't build: lime tools PNG.hx runtime error

### ISSUE THREAD

**Issue by eliasku** [openfl/lime#374]
trying to build ios on the latest lime/openfl, tried with/without -DLegacy, done `lime rebuild tools`, `lime rebuild mac`

```
Reading HXCPP config: /Users/eliasku/.hxcpp_config.xml
Using target platform: IOS

Running command: UPDATE
 - Generating image: export/ios/game/Images.xcassets/LaunchImage.launchimage/Default.png
Called from ? line 1
Called from CommandLineTools.hx line 1349
Called from CommandLineTools.hx line 25
Called from a C function
Called from CommandLineTools.hx line 126
Called from CommandLineTools.hx line 567
Called from lime/project/PlatformTarget.hx line 70
Called from lime/tools/platforms/IOSPlatform.hx line 442
Called from lime/graphics/Image.hx line 298
Called from lime/graphics/format/PNG.hx line 28
Uncaught exception - Segmentation fault
```

failed at: `return lime_image_encode (image.buffer, 0, 0);`

**Comment by jgranick** [comment]
Should be fixed: https://github.com/openfl/lime/commit/c73fb1b3937a0985f9ff79e52b373517b5899210

**Comment by jgranick** [comment]
You can get an updated build here:

http://www.openfl.org/builds/lime/

Download the newest build and use `haxelib local <name of zip>` :wink:

**Comment by eliasku** [comment]
lime-2.2.1.zip not works for me, I need to repack zip "lime" folder content to plain zip file: as haxelib.json placed at the zip root, and remove dot files (only dots files removing don't help).

Now I can generate files ony if I run lime with SUDO (it would be nice to do it without extra-permissions), but error happens later:

```
- Creating directory: export/ios/cvs_client/lib
 - Creating directory: export/ios/cvs_client/lib/armv7
 - Creating directory: export/ios/cvs_client/lib/armv7-debug
 - Copying file: /usr/lib/haxe/lib/hxcpp/3,2,37/lib/iPhone/libstd.iphoneos-v7.a -> export/ios/cvs_client//lib/armv7/libstd.a
 - Copying file: /usr/lib/haxe/lib/hxcpp/3,2,37/lib/iPhone/libregexp.iphoneos-v7.a -> export/ios/cvs_client//lib/armv7/libregexp.a
Error: Source path "/usr/lib/haxe/lib/lime/2,2,1/ndll/IPhone/liblime.iphoneos.a" does not exist
```

**Comment by jgranick** [comment]
That problem is related to haxelib, "haxelib selfupdate" fixed it for me, but perhaps the RC version of haxelib still needs to be patched for .files and directories

For iOS right now, please use "-Dv2" or "-Dlegacy", iOS support should be coming soon once we determine why SDL2 for iOS is showing a blank screen :frowning:

**Comment by eliasku** [comment]
-Dlegacy works :+1:

 it's really works now, but i can't get further than compilation, because I've lose my cerfs and keys, but it looks like build phases are ok!
