### ISSUE TITLE
[flash] 2.2.1: can't build

### ISSUE THREAD

**Issue by eliasku** [openfl/lime#376]
can't build flash target with openfl 3.0.0 git version  + lime 2.2.1 + haxe 3.2 rc2 + mac os 10.9.5

```
>> lime test flash

sh: haxe -main ApplicationMain -cp /usr/lib/haxe/lib/lime/2,2,1 -D lime=2.2.1 -cp 
/Users/eliasku/p/c/w/gore/src -D gore=0.0.1 -cp /Users/eliasku/p/c/w/rage/src -D rage=0.0.1 -cp 
/usr/lib/haxe/lib/openfl/git -D openfl=3.0.0-beta -cp /Users/eliasku/p/c/w/flash-console/src 
-D flash-console=0.0.1 -cp /Users/eliasku/p/c/w/horror/src -D horror=0.0.1 -cp /usr/lib/haxe/lib/format/3,1,2 -D format=3.1.2 -cp /Users/eliasku/p/c/w/cvsapi/src -D cvsapi=0.0.1 
-cp /Users/eliasku/p/c/w/comalib/src -D comalib=0.0.1 -cp /usr/lib/haxe/lib/promhx/1,0,17/src/main 
-D promhx=1.0.17 -cp src -D haxe3 -D openfl-next -D hrr_openfl -D flash-use-stage -D openfl-flash 
-D rage -D hrr_stage3d -D gore -D tools=2.2.1 -D horror -D flash-console -D no-compilation 
-D hrr_flash -D hrr_agal -D cvsapi -D no_debug -D fdb -D web -dce full -swf-lib export/flash/obj/assets.swf -swf-version 11.3 -swf export/flash/bin/game.swf 
-cp export/flash/haxe: File name too long

```

**Comment by jgranick** [comment]
Now that Haxe helps escape Sys.command, perhaps we need to do something like this for Mac as well:

https://github.com/openfl/lime/commit/71af10bc80112515833de87ebc31854e2be402ed

**Comment by jgranick** [comment]
If you're able to modify that second file and recompile the tools (`lime rebuild tools`) it would be great to hear if it works for you, even if you add something like `<haxeflag name="--macro" value="include('hello world')" />` (which broke compilation before)

**Comment by eliasku** [comment]
When I remove all `if (PlatformHelper.hostPlatform == Platform.MAC)` block and leave just `ProcessHelper.runCommand ("", "haxe", args);` - all works correctly!!! Thank you!

**Comment by jgranick** [comment]
Thank you :smile:
