### ISSUE TITLE
[html5] TextField compile error (haxe 3.2 rc2)

### ISSUE THREAD

**Issue by eliasku** [openfl/lime#380]
macos + lime 2.2.1 + openfl 3.0.0beta from git + haxe 3.2 rc2

when I compile my project with `-Dlegacy` I got error: 
```
export/html5/haxe/ApplicationMain.hx:4: characters 11-20 : Class not found : lime.Lime
```

when I compile without legacy flag:
```
/usr/lib/haxe/lib/openfl/git/openfl/text/TextField.hx:1188: characters 3-47 : js.html.DOMElement should be js.html.Element
```

BTW i fix the type error locally, then stuck with same problem as https://github.com/openfl/lime/issues/378

**Comment by ibilon** [comment]
`/usr/lib/haxe/lib/openfl/git/openfl/text/TextField.hx:1188: characters 3-47 : js.html.DOMElement should be js.html.Element` is something I failed to mention in my issue, but I have it too.
Did you tried removing `lime/git/js/Boot.hx`? Works for me.

**Comment by eliasku** [comment]
@ibilon I've just changed `createElement` to `createDivElement` at 1190 line to get code compiled with haxe 3.2 rc2

**Comment by eliasku** [comment]
@ibilon removing js/Boot.hx - project is running but hangs after lime preloader

**Comment by ibilon** [comment]
@eliasku If you open a development console, most likely F12 (at least on firefox) and reload does-it show an error?

**Comment by eliasku** [comment]
@ibilon  yeah, BytesData is ArrayBuffer now, and I can't cast it to ArrayBufferView in my GLDriver as before, so it's my fault now :) so I'll investigate other issues on my own

**Comment by eliasku** [comment]
All my WebGL stuff now works fine! I've created a pull request to solve a TextField compile error issue.
