### ISSUE TITLE
Cannot get 60fps in window mode with Intel GPUs (if vsync is enabled)

### ISSUE THREAD

**Issue by vroad** [openfl/lime#390]
I couldn't get 60FPS on lime-samples with vsync enabled. This doesn't occur with NVIDIA GPUs.
Surprisingly, Intel's GPU driver uses Sleep() to emulate vsync in window mode. Sleep is affected by timer resolution settings, so it may sleeps 15ms or more with default timer resolution (15.6ms). I have heard this on Intel's Forum.

What we can do to solve this issue?
- Use timeBeginPeriod to increase timer accuracy?
- Use DwmFlush or D3DKMTWaitForVerticalBlankEvent?

I don't want to use timeBeginPeriod/timeEndPeriod as it globally changes system settings.
According to comments on this chromium issue, D3DKMTWaitForVerticalBlankEvent looks the best, but it requires you to install WIndows DDK, which should makes building lime difficult on windows.
So... using DwmFlush (if available) looks the best for us.
https://code.google.com/p/chromium/issues/detail?id=467617

I have tested this on my Windows8.1 machine with Intel GPU.
https://github.com/vroad/lime/commit/75e101766bd8b15b77b211d61036e5aaadf59271

**Comment by duckware** [comment]
D3DKMTWaitForVerticalBlankEvent does not require anything to be installed.  It can be directly called, if that is what you want...

**Comment by vroad** [comment]
I hesitate to use D3DKMT* API because it will force other developers to install Windows DDK.
I think that most game developers don't have DDK installed.

**Comment by duckware** [comment]
I call/use D3DKMTWaitForVerticalBlankEvent and never installed any DDK.

**Comment by vroad** [comment]
D3dkmthk.h is not included in Windows SDK, is it?

**Comment by vroad** [comment]
Created test branch in https://github.com/vroad/lime/tree/vsync-fix .
I tried to handle all cases as much as possible, though I haven't tested this on Windows 7 or Vista without desktop composition enabled. On Windows8 you cannot disable desktop composition.

**Comment by jgranick** [comment]
If it has not been done already, I think we should try and bring this topic up with the SDL2 developers, and see about getting it resolved at that possible

**Comment by vroad** [comment]
I removed DwmFlush calls because I sometimes got frame skip.

Driver version 10.18.14.4264 does not seem to have this problem anymore. The may have fixed this issue. We may need workaround for older drivers, though.
