### ISSUE TITLE
With no fill, Graphics.lineStyle hides next lineTo segment 

### ISSUE THREAD

**Issue by scriptorum** [openfl/lime#395]
I'm trying use the OpenFL drawing API to draw shapes without fills. On non-flash targets, this code for drawing a triangle will only draw the second and third line segments:

```haxe
		var shape = new Shape();
		var g = shape.graphics;
		g.lineStyle(1, 0xFF0000);
		g.lineTo(100, 0);
		g.lineTo(50, 44);
		g.lineTo(0, 0);
		addChild(shape);
```

Also, if I add a `lineStyle()` call before each `lineTo()`, nothing shows at all. The fix is to either use fills, or to remind Graphics of the cursor position after each `lineStyle()` call:

```haxe
		var shape = new Shape();
		var g = shape.graphics;
		g.lineStyle(1, 0xFF0000); g.moveTo(0, 0);   g.lineTo(100, 0);
		g.lineStyle(1, 0x00FF00); g.moveTo(100, 0); g.lineTo(50, 44);
		g.lineStyle(1, 0x0000FF); g.moveTo(50, 44); g.lineTo(0, 0);
		addChild(shape);
```

I only observed this problem with `lineTo()`; `curveTo()` performed correctly for me, as did `drawRect()`. On Lime 2.3 and OpenFL 3/beta3, targeting Mac, Neko, and Html5.

**Comment by mrcdk** [comment]
Thanks for reporting it. I sent a PR with the fix :smile:

**Comment by scriptorum** [comment]
That was quick. I think it only fixes part of the problem, though. I just put together a multi-segment `curveTo()` example, and unfortunately that does trigger a similar issue:

```haxe
		g.lineStyle(1, 0xFF0000); g.curveTo( 75,  20,  50, 100);
		g.lineStyle(1, 0x00FF00); g.curveTo(  0, 120, -50, 100);
		g.lineStyle(1, 0x0000FF); g.curveTo(-75,  20,   0,   0);
```
Here's my pope hat, consisting of three curves. The first curve is correct, but the second and third are drawn as if they start from 0,0 rather than the last cursor point. So they're visible, but misdrawn. I imagine my `lineTo()` example above would fail in the same manner, with lines radiating from 0,0. Adding `moveTo()` instructions after each `lineStyle()` fixes this issue as well.

**Comment by mrcdk** [comment]
oh well, it will take more work then, I'll try to fix it ASAP

**Comment by scriptorum** [comment]
Thanks!
