### ISSUE TITLE
Segfault on setup on Linux

### ISSUE THREAD

**Issue by Jellonator** [openfl/lime#396]
Running "haxelib run lime setup" causes a segfault.
This is the terminal output:
```
Called from lime/utils/ByteArray.hx line 109
Called from lime/system/System.hx line 286
Called from lime/system/System.hx line 405
Uncaught exception - Segmentation fault
```
This is from a fresh install, in ~/.haxe/ after having the same issue in a previous install.
Running Linux Mint 17.
Edit: Got it to work. Went with another fresh install, this time using OpenFL's install-haxe.sh script instead.

**Comment by jgranick** [comment]
Does `haxelib run lime setup -nocffi` work? What does `haxelib path lime` return?

**Comment by Distraxel** [comment]
Nevermind, I got it to work. Thanks for helping anyways :)

**Comment by jgranick** [comment]
What was wrong? :smile:

**Comment by Distraxel** [comment]
To be honest, I have no idea. It works now and that's really all I know.
