### ISSUE TITLE
'lime create' fails

### ISSUE THREAD

**Issue by kewp** [openfl/lime#397]
running 'lime create' produces the following error.

Called from ? line 1
Called from CommandLineTools.hx line 1349
Called from CommandLineTools.hx line 25
Called from CommandLineTools.hx line 110
Called from CommandLineTools.hx line 678
Called from utils/CreateTemplate.hx line 381
Called from /usr/lib/haxe/std/neko/_std/sys/FileSystem.hx line 94
Uncaught exception - std@sys_read_dir

i'm using lime 2.3.0 on windows.

**Comment by adamscott** [comment]
Same here. Using lime 2.3.0 on Windows 8.1 x64.
