### ISSUE TITLE
HandlingInputEvents fails to build

### ISSUE THREAD

**Issue by kewp** [openfl/lime#398]
using lime 2.3.0.

C:\Users\Karl\openfl>lime create HandlingInputEvents

C:\Users\Karl\openfl>cd HandlingInputEvents

C:\Users\Karl\openfl\HandlingInputEvents>lime test windows
Source/Main.hx:100: lines 100-109 : Field onMouseMove overloads parent class wit
h different or incomplete type
Source/Main.hx:100: lines 100-109 : x : Float -> y : Float -> button : Int -> Vo
id should be x : Float -> y : Float -> Void

similarly with -Dlegacy

C:\Users\Karl\openfl\HandlingInputEvents>lime test windows -Dlegacy
Source/Main.hx:51: characters 13-18 : openfl.display.Stage should be lime.app.IM
odule
Source/Main.hx:51: characters 13-18 : openfl._legacy.display.Stage should be lim
e.app.IModule
Source/Main.hx:51: characters 13-18 : For function argument 'module'
Source/Main.hx:100: lines 100-109 : Field onMouseMove overloads parent class wit
h different or incomplete type
Source/Main.hx:100: lines 100-109 : x : Float -> y : Float -> button : Int -> Vo
id should be x : Float -> y : Float -> Void

**Comment by jgranick** [comment]
Fixed, thank you :)

https://github.com/openfl/lime-samples/commit/150601f088b45cabb5b62b853839082e722056d2
