### ISSUE TITLE
Dynamic sound not working properly on native targets.

### ISSUE THREAD

**Issue by PaulGene** [openfl/lime#40]
To demonstrate the problem, I have created this example project https://github.com/PaulGene/PitchShiftingSound

Flash: everything works as expected.

Windows: Works most of the time but sometimes SampleDataEvent.SAMPLE_DATA stops being fired when lime_sound_channel_needs_data(__handle); returns false at https://github.com/openfl/openfl-native/blob/master/flash/media/SoundChannel.hx#L114

Antroid: SampleDataEvent.SAMPLE_DATA gets fired about 3 times then we have the same problem as Windows, lime_sound_channel_needs_data(__handle); returns false at https://github.com/openfl/openfl-native/blob/master/flash/media/SoundChannel.hx#L114

iOS: lime_sound_channel_create_dynamic(request.data, soundTransform); always returns null at https://github.com/openfl/openfl-native/blob/master/flash/media/Sound.hx#L186

**Comment by starburst997** [comment]
I too had problem with dynamic audio, I was able to fix them all using this fix: https://github.com/openfl/openfl/pull/488

I used http://www.tanjent.se/labs/tanjentxm.html to test the functionnality, got it working on Android, iOS, Windows, Mac, Flash
