### ISSUE TITLE
Shape.getBounds includes control points in extents

### ISSUE THREAD

**Issue by scriptorum** [openfl/lime#401]
A Flash shape excludes control points from the extents of a Shape when calling `getBounds()`, whereas Lime does not. This can be demonstrated as follows:

```haxe
		var shape = new Shape(); var g = shape.graphics; // draw curve shape
		g.lineStyle(1, 0xFF);
		g.curveTo( 75,  20,  50, 100);
		g.curveTo(  0, 120, -50, 100);
		g.curveTo(-75,  20,   0,   0);
		addChild(shape);

		var bounds = shape.getBounds(parent); // get shape bounds

		var shape = new Shape(); var g = shape.graphics; // draw control points
		g.beginFill(0xFF0000);
		g.drawCircle( 75,  20, 2);
		g.drawCircle( 0,  120, 2); 
		g.drawCircle( -75, 20, 2);
		addChild(shape);

		shape = new Shape(); g = shape.graphics; // draw shape bounds
		g.lineStyle(1, 0);
		g.drawRect(bounds.x, bounds.y, bounds.width, bounds.height);
		addChild(shape);

		this.x = 400;
		this.y = 50;
		this.scaleX = this.scaleY = 4;
```

When targeting flash, the bounding box is clearly shown to encompass the visible shape, whereas on CPP targets the box extends to the control points.

**Comment by scriptorum** [comment]
For those who like pictures, a Neko build is on the left, Flash is on the right. I added the yellow/green background color for ... well no good reason. But you can see the variation in the bounding box.
![lime401](https://cloud.githubusercontent.com/assets/3144427/7013467/71d1a144-dc87-11e4-82c9-b1d015a1159f.png)

**Comment by jgranick** [comment]
Hi!

I'm closing this issue, I just opened a new one under OpenFL to track it. I think we need a formula to calculate the exact midpoint of the curve

https://github.com/openfl/openfl/blob/master/openfl/display/Graphics.hx#L335
