### ISSUE TITLE
Cannot find Sound

### ISSUE THREAD

**Issue by kewp** [openfl/lime#404]
This is about Flappybalt, a haxeflixel sample. I know it's not to do with 'lime' but the error is directly related to recent lime commits (removing Sound.java).

I'm trying to 'lime test android' on the haxeflixel Flappybalt sample and it says

`
    [javac] C:\Users\Karl\dev\flixel\Flappybalt\export\android\bin\src\org\haxe\
lime\GameActivity.java:83: error: cannot find symbol
    [javac]     private Sound _sound;
`

Bizarrely everything builds fine for the other samples.

Any idea what's happening ?

**Comment by jgranick** [comment]
Should be fixed:

https://github.com/openfl/lime/commit/81accad

Sorry about this! We'll release an update fairly soon. The Sound.java file hasn't been used for quite some time (since we added OpenAL support) and has been causing compile problems switching between legacy and new code :)

**Comment by kewp** [comment]
Ok cool. Thanks.

Just a side question: Do you know why the Flappybalt demo project uses this class and the others don't ? I see it's in the 'legacy' folder but I didn't compile with -Dlegacy ....

**Comment by sebastiencarceles** [comment]
Hello
I have the same problem with lime 2.3.1 in legacy mode. Please let me know when the fix is released ;)

**Comment by larsiusprime** [comment]
@kewp: Flixel by default forces legacy mode. The include.xml file in every flixel template sets the "legacy" flag to true.

**Comment by kewp** [comment]
@larsiusprime: I don't see the result of what you mean. There is nothing in my project.xml file that specifies legacy ... Where is the legacy flag set to true ?

**Comment by larsiusprime** [comment]
It's not in your project file, it's in the flixel library itself.

https://github.com/HaxeFlixel/flixel/blob/dev/include.xml#L9

Any library can come with an "include.xml" file that forces certain files and/or compile flags to be included in any project that uses that library. This is how the default flixel assets are automatically included in your assets library without you having to manually include them. Another thing it does is specify -Dlegacy by default via this file.

So you'll notice there's an "unless='next'" property in that same line. So if you want to compile a flixel app in legacy mode, you don't do anything. If you want to NOT have legacy mode, you need to define the "next" flag in your project.xml, or pass in -Dnext on the command line.

**Comment by kewp** [comment]
Wow, that's very interesting. Thanks for the info.

I see that line was added by Gama11 17 days ago ... https://github.com/HaxeFlixel/flixel/commit/4f4b6d433bc8db5bf62655cc85d6741cd0b65e97
