### ISSUE TITLE
openfl - 3.0.2 with lime -2.3.2, android SDL nativeGetHint problem

### ISSUE THREAD

**Issue by kusamochi** [openfl/lime#407]
E/art     ( 6884): No implementation found for java.lang.String org.libsdl.app.SDLActivity.nativeGetHint(java.lang.String)

when I downgrade back to openfl 2.2.8 with lime 2.1.3 there is no problem.
can someone please take a look and check the SDL Library for android? thanks

**Comment by jgranick** [comment]
Could you try using a simple Lime or OpenFL sample, and see if you have a problem with those? This seems to be behaving like it's running somehow with the wrong lime.so, or something like that

**Comment by musou1500** [comment]
I have same problem.
I try to re-install lime,but I can't resolve this problem.

**Comment by jgranick** [comment]
@musou1500 Did you try a -clean build?

**Comment by musou1500** [comment]
@jgranick 
Yes. I remove old build files before rebuild my project.

**Comment by kusamochi** [comment]
sorry for the late reply, I am currently working with the old version for the moment and haven't tested latest version recently. and yes I tested with a simple hello world sample..

**Comment by Anheurystics** [comment]
I've also encountered this error, but only when using TextField objects (they cause the application to crash on Android)
