### ISSUE TITLE
Segfaults on Mac OSX at Neko in System.hx

### ISSUE THREAD

**Issue by hyperumlabs** [openfl/lime#408]
Segfaults whenever I run `haxelib run openfl setup` or `haxelib run lime` or `lime` or `openfl`

    $ haxelib run openfl setup
    Called from lime/utils/ByteArray.hx line 110
    Called from lime/system/System.hx line 304
    Called from lime/system/System.hx line 419
    Uncaught exception - Segmentation fault

**Comment by jgranick** [comment]
This should be resolved with current versions :smile:
