### ISSUE TITLE
BitmapData premultiplied alpha behavior is inconsistent across platforms when used in a Stage3D texture.

### ISSUE THREAD

**Issue by Type1J** [openfl/lime#409]
Because Flash BitmapData automatically multiplies alpha at the time the pixels are given to it, 

    Context3D.setBlendFactors(Context3DBlendFactor.ONE, Context3DBlendFactor.ONE_MINUS_SOURCE_ALPHA)

is expected to be used when drawing a texture with Stage3D when the texture came from BitmapData because the pixels in the BitmapData are expected to have their colors already multiplied by their alpha values, and the Context3D uploads that premultipled data unmodified. The above call produces the correct results in Flash, but on html5 and native the correct result is produced by

    Context3D.setBlendFactors(Context3DBlendFactor.SOURCE_ALPHA, Context3DBlendFactor.ONE_MINUS_SOURCE_ALPHA)

, which suggests that BitmapData stores color values in non-premultiplied form.

This may be an OpenFL issue, but since Lime doesn't seem to have a way for OpenFL to tell it to premultiply the colors by the alpha on Image.setPixels(), and because ImageDataUtil has functions to premultiply colors, this should probably be fixed in Lime. OpenFL's BitmapData may still need modification to indicate that it want's the colors to be multiplied by alpha as they're going into the lime.graphics.Image if the default lime.graphics.Image pixel format is not premultiplied.

**Comment by jgranick** [comment]
We need to keep the pixels stored in unmultiplied form, we will lose color data. I went down this road and found that depending on the level of alpha, you're losing color information, so ultimately get/set pixels would fail to produce sane results.

In order to handle premultiplied alpha before an upload to the GPU, we need to do something like the following:

```haxe
var image = image.clone ();
image.premultiplied = true;
```

Instead of doing premultiplied alpha on a set pixel call (which would reduce the image fidelity potentially) we need to premultiply the entire image, but if you need to edit it again, clone it so we preserve the original pixel data

**Comment by Type1J** [comment]
I agree. The unmultiplied form should be kept. This issue isn't really with that aspect of the implementation.

I think I've come up with a better explanation of the issue that's more closely tied to how I'm using it.

First, here's Adobe's docs about getPixels(), which is where I got the original explanation:
>All pixels in a BitmapData object are stored as premultiplied color values. A premultiplied image pixel has the red, green, and blue color channel values already multiplied by the alpha data. For example, if the alpha value is 0, the values for the RGB channels are also 0, independent of their unmultiplied values. This loss of data can cause some problems when you perform operations. All BitmapData methods take and return unmultiplied values. The internal pixel representation is converted from premultiplied to unmultiplied before it is returned as a value. During a set operation, the pixel value is premultiplied before the raw image pixel is set.

I personally would want to be able to get the original values back if I asked for them, which goes along with what you were saying. However, there is this problem: flash.display3D.textures.Texture.uploadFromBitmapData() gets the "internal" premultiplied values from a BitmapData object. If one wants to load unmultiplied values, one must use flash.display3D.textures.Texture.uploadFromByteArray() instead.

Given that my problem is that I'm porting something from Flash with Stage3D, and it used BitmapData to load texture data, I believe that in order to be consistent with Flash, OpenFL should probably just make sure that whatever uploadFromBitmapData() gets from the BitmapData should be premultiplied.

Should I make this issue on OpenFL instead, since that's where the change would need to be?

**Comment by jgranick** [comment]
I don't have a way of testing easily, but perhaps we need to do a clone and a premultiplied set inside the analog for uploadFromBitmapData

It's interesting that Flash Player keeps it as premultiplied, then unmultiplies when getting/setting pixels. I wonder how they do this without losing fidelity as badly as I was, trying the same

**Comment by Type1J** [comment]
A copy already occurs in uploadFromBitmapData:

		#if js
		var source = new UInt8Array (data.length);
		data.position = byteArrayOffset;
		
		var i:Int = 0;
		
		while (data.position < data.length) {
			
			source[i] = data.readUnsignedByte ();
			i++;
			
		}
		#else
		var source = new UInt8Array (data);
		#end

Most of the code is already there for the js target. The rest of it would be similar to what lime.graphics.utils.ImageDataUtils.multiplyAlpha() does.

I'm sorry for not making a pull request. I'm on a phone right now.

**Comment by Type1J** [comment]
After seeing https://github.com/openfl/openfl/pull/604, which looks like it would be slower due to cache fills, and yet it's faster, I'm wondering if the reason that Adobe gets no loss is because they keep the pixel data with 16-bits per channel, which would save most lost information from those 3 8-bit by 8-bit multiplies (unless alpha is 0 for that pixel). If it's truly just as fast to copy pixels this way (one channel at a time), then taking the top 8-bits on a getPixels() or getVector() call would probably be fine.

Then again, I could be missing something.

**Comment by delahee** [comment]
My wild guess :

Answer is simpler they actually get a loss but at render time, it's
imperceptible.

Since they keep both unmul compressed and premul version the api serves
pixels from either source according to the spec.

With legacy alpha is always  "straight" (vernacular for non premul) whereas
in flash sometimes it comes premul

At mt we use both mostly agnostically...
