### ISSUE TITLE
lime rebuild os - haxelib version

### ISSUE THREAD

**Issue by ibilon** [openfl/lime#417]
The haxelib version of lime doesn't include the project directory,
so `lime rebuild os` can't work.

It should print a warning,
many people are saying "tried rebuilding but it changed nothing" (unsurprising since it didn't rebuild at all)

**Comment by jgranick** [comment]
like putting a Build.xml in there with `<error value="Go get the source, yo!" />`

Maybe. I used to include everything (and I like that) but then it does not include the /libs folder (unless the size is really large), so it does make sense to not include the files, but have a nicer message, "cannot rebuild release versions, please clone from the source at ___"

**Comment by ibilon** [comment]
Why closed? It shouldn't be too hard for the build server to include that kind of file.
Or is it done and I've missed it?

If it's not possible the tools could check if Build.xml exists and warn otherwise.
