### ISSUE TITLE
Exception in windows target

### ISSUE THREAD

**Issue by maaniv** [openfl/lime#421]
Build from git. Neko is not working too. Variables 'target' and 'framebuffer' is not null. Callstack:
 	00000000()	
>	lime.ndll!lime::lime_gl_bind_framebuffer(_value * target, _value * framebuffer)  Line 61	C++
 	PROJECT.exe!ExternalPrimitive::__run(const Dynamic & a, const Dynamic & b)  Line 141 + 0x1a bytes	C++
 	PROJECT.exe!Dynamic::operator()(const Dynamic & inArg0, const Dynamic & inArg1)  Line 187 + 0x31 bytes	C++
 	PROJECT.exe!openfl::_internal::renderer::opengl::GLRenderer_obj::render(hx::ObjectPtr<openfl::display::Stage_obj> stage)  Line 392	C++
 	PROJECT.exe!openfl::display::Stage_obj::render(hx::ObjectPtr<lime::graphics::RenderContext_obj> context)  Line 796	C++
 	PROJECT.exe!lime::app::IModule_delegate_<openfl::display::Stage_obj>::render(hx::ObjectPtr<lime::graphics::RenderContext_obj> context)  Line 163 + 0x2f bytes	C++
 	PROJECT.exe!lime::app::Application_obj::render(hx::ObjectPtr<lime::graphics::RenderContext_obj> context)  Line 1169	C++
 	PROJECT.exe!lime::app::__Module_objrender(hx::Object * inObj, const Dynamic & inArg0)  Line 426 + 0x26 bytes	C++
 	PROJECT.exe!hx::CMemberFunction1::__run(const Dynamic & inArg0)  Line 138 + 0x1c bytes	C++
 	PROJECT.exe!Dynamic::operator()(const Dynamic & inArg0)  Line 187 + 0x2b bytes	C++
 	PROJECT.exe!lime::_backend::native::NativeApplication_obj::handleRenderEvent()  Line 671 + 0x94 bytes	C++
 	PROJECT.exe!lime::_backend::native::__NativeApplication_objhandleRenderEvent(hx::Object * inObj)  Line 774 + 0x18 bytes	C++
 	PROJECT.exe!hx::CMemberFunction0::__run()  Line 50 + 0x18 bytes	C++
 	PROJECT.exe!val_call0(hx::Object * arg1)  Line 584 + 0x14 bytes	C++
 	lime.ndll!lime::RenderEvent::Dispatch(lime::RenderEvent * event)  Line 36 + 0x12 bytes	C++
 	lime.ndll!lime::SDLApplication::HandleEvent(SDL_Event * event)  Line 167 + 0xe bytes	C++
 	lime.ndll!lime::SDLApplication::Update()  Line 454	C++
 	lime.ndll!lime::SDLApplication::Exec()  Line 85	C++
 	lime.ndll!lime::lime_application_exec(_value * application)  Line 54 + 0xc bytes	C++
 	PROJECT.exe!ExternalPrimitive::__run(const Dynamic & a)  Line 134 + 0x11 bytes	C++
 	PROJECT.exe!Dynamic::operator()(const Dynamic & inArg0)  Line 187 + 0x2b bytes	C++
 	PROJECT.exe!lime::_backend::native::NativeApplication_obj::exec()  Line 167 + 0x1b bytes	C++
 	PROJECT.exe!lime::app::Application_obj::exec()  Line 212 + 0x1e bytes	C++
 	PROJECT.exe!ApplicationMain_obj::create()  Line 130 + 0x24 bytes	C++
 	PROJECT.exe!ApplicationMain_obj::main()  Line 226 + 0x9 bytes	C++
 	PROJECT.exe!WinMain(void * hInstance, void * hPrevInstance, const char * lpCmdLine, int nCmdShow)  Line 12 + 0x9 bytes	C++
 	PROJECT.exe!__tmainCRTStartup()  Line 275 + 0x1c bytes	C
 	kernel32.dll!@BaseThreadInitThunk@12()  + 0xe bytes	
 	ntdll.dll!___RtlUserThreadStart@8()  + 0x23 bytes	
 	ntdll.dll!__RtlUserThreadStart@8()  + 0x1b bytes

**Comment by jgranick** [comment]
Been running Windows stable, I'm guessing this may have been an issue that was resolved. Thanks!
