### ISSUE TITLE
lime build android fails with ant error

### ISSUE THREAD

**Issue by fserb** [openfl/lime#431]
Building with `aether build android` works perfectly. If I do `lime build android` instead, it fails with:
```
Error: Could not find or load main class org.apache.tools.ant.launch.Launcher
```
after stripping libApplicationMain-v7.so.

**Comment by fserb** [comment]
Just to be clear. On hxcpp 3.2.94, `aether`, builds it with a `null-release.apk` name, so not perfect either.
But `lime` doesn't even get there.

**Comment by fserb** [comment]
on `lime build android`. Going to `bin/android/bin` (where `bin` is the output directory) and manually running `ant release` works fine.

**Comment by fserb** [comment]
The culprit is ANT_HOME.
If it's set on the environment, ant goes crazy and fails.
Is it ok if we remove this?

**Comment by fserb** [comment]
Putting a:
```
Sys.putEnv("ANT_HOME", "");
```
before calling ant on `AndroidHelper.hx` solves it for me.
It seems ANT_HOME is leaking from hxcpp context to the System.command that runs Ant. But Ant uses that somehow.

**Comment by jgranick** [comment]
Do you have ANT_HOME set in your ~/.hxcpp_config.xml file?

**Comment by fserb** [comment]
I do. Because my ant is installed by homebrew, so it's at /usr/local/bin/ant (which is what I provided to 'lime setup android'). I tried to manually remove it, but then it just doesn't find ant when it tries to run it.

**Comment by fserb** [comment]
Removed the ANT_HOME from my hxcpp_config after some upgrades and everything seems to be working fine now.
