### ISSUE TITLE
problems with clean mac install and HAXE/OPENFL

### ISSUE THREAD

**Issue by lewislepton** [openfl/lime#435]
this is a problem i have ran into after a clean install of my computer.

i have followed exactly everything and have what i need installed. i had a flixel install before i wipe the computer, but am choosing to just use openfl instead.
it had worked before i had done the clean install.

but on running, both in terminal and in sublime [using the HAXE build system], am running into trouble and dont know what they are or how to fix. ive followed everything on the sites given. but the same thing
here are some screenshot to show
im also using HAXE 3.2.0 and have tried 3.2.0r2 but both do not work

also have ran the openFL install and it has lime inside, but see that lime is the problem

thanks

![screen shot 2015-05-13 at 16 36 06](https://cloud.githubusercontent.com/assets/11299322/7614694/6b11679c-f990-11e4-9230-65dda557ac72.png)

![screen shot 2015-05-13 at 16 46 01](https://cloud.githubusercontent.com/assets/11299322/7614700/6fb0fd30-f990-11e4-8d1b-2f7eeb4fb67f.png)

**Comment by scriptorum** [comment]
I get this on my Mac as well, and it started right after upgrading to Haxe 3.2. It looks like it's trying to generate icons for the app and choking on a null somewhere.

**Comment by scriptorum** [comment]
FYI, [downloadeding the latest lime source](https://github.com/openfl/lime/blob/master/README.md) and rebuilding it eliminated the issue.

**Comment by lewislepton** [comment]
cool spot. ill give that a go. seemed to have cocked something so just wiping the comp again to start fresh. better safe tahn sorry ;)

**Comment by lewislepton** [comment]
should i use the dev build, or get the master .zip and do that? just to ask before i do it

**Comment by scriptorum** [comment]
What I did was follow the instructions under "[build from source](https://github.com/openfl/lime/blob/master/README.md#building-from-source)."

**Comment by lewislepton** [comment]
awesome balls. cheers. t about to do it. will you let you know

**Comment by jgranick** [comment]
This is resolved in newer builds :smile:
