### ISSUE TITLE
2.4.1 not installing properly on haxelib

### ISSUE THREAD

**Issue by SavedByZero** [openfl/lime#436]
It unpacks, then says "current version is now 1.0.0" and creates a directory called unknown.  Then when I type haxelib upgrade again, it asks if I want to upgrade again and does the same thing.  Rinse, repeat.

**Comment by jgranick** [comment]
Oh, haxelib :sob: 

You can also try installing like this:

 1.) Download from here: http://lib.haxe.org/p/lime

 2.) Run `haxelib local lime-2.4.0.zip` (or whatever file name it is)
