### ISSUE TITLE
Line breaking is not supported in lime TextLayout

### ISSUE THREAD

**Issue by vroad** [openfl/lime#451]
I'm looking for a way to implement this with harfbuzz, but harfbuzz itself doesn't seem to support this. 

https://github.com/behdad/harfbuzz/issues/32

**Comment by vroad** [comment]
Could this be used with harfbuzz?
http://vimgadgets.sourceforge.net/libunibreak/

**Comment by jgranick** [comment]
I believe we need to spend more time investing in the `TextLayout` API, for now, I think it will not support line breaks, but I am open to discussing more in Slack, thanks
