### ISSUE TITLE
gDEBugger doesn't work on lime if DYNAMIC_OGL is defined

### ISSUE THREAD

**Issue by vroad** [openfl/lime#452]
Recently I noticed gDEBugger stopped working, and after removing DYNAMIC_OGL, it started working again.
This suggests that gDEBugger can only hook OpenGL functions statically linked to the app, not dynamically loaded ones. Should we disable this by default, when we build lime without ANGLE?

**Comment by jgranick** [comment]
I'm not sure if there's a way we could make it work with dynamic OpenGL?

Our problem that is if we statically link to OpenGL, this can fail on systems without OpenGL installed. Perhaps this more an issue on Linux than Windows, though

**Comment by vroad** [comment]
Then can we enable this only on Windows?

As of today, all windows systems comes with basic OpenGL support (opengl32.dll), so this shouldn't be a problem for Windows. Newer OpenGL functions are always dynamically loaded with wglGetProcAddress().

Even though this flag is named "DYNAMIC_OGL", functions existed in fixed-pipeline OpenGL is still dynamically linked, at least on Windows. It's implemented in opengl32.dll. Compiler automatically inserts library loading call at startup if this flag is disabled.
