### ISSUE TITLE
Running app on iOs failed (lime_byte_array_init__4)

### ISSUE THREAD

**Issue by zaynyatyi** [openfl/lime#454]
trying to run my application on iOs simulator using lime test ios -simulator.
and i'm getting 
** BUILD SUCCEEDED **

2015-05-27 11:48:34.647 ios-sim[29062:191728] Timeout: 60.000000 second(s)
Primitive not found : lime_byte_array_init__4
 Error Null Function Pointer

lime version is 2.4.1
openfl version 2.2.8

**Comment by jgranick** [comment]
This should be resolved, thanks! :smile:
