### ISSUE TITLE
PlayingSound sample doesn't work on neko

### ISSUE THREAD

**Issue by vroad** [openfl/lime#456]
I pushed two branches that improves lime's audio functionality, though I think we need to solve this first.

After making these changes, I noticed PlayingSound example does not work on neko even with original lime. cpp worked from the beginning, and nodejs worked after implementing val_array_int in node-ndll. Maybe this is same for neko?

https://github.com/openfl/lime/pull/455
https://github.com/vroad/lime/tree/openal-streaming

**Comment by jgranick** [comment]
PlayingSound is working with current builds and the current version of the sample :smile:
