### ISSUE TITLE
[Lime 2.4.2 + OpenFL 3.0.8] fontName returns null with OpenType fonts

### ISSUE THREAD

**Issue by yuigoto** [openfl/lime#458]
I think this issue might be mostly Lime related, so I'm posting here.

I'm using OpenFL 3.0.8 with Lime 2.4.2 and I noticed that, when using OpenType fonts while targeting Flash, fontName returns null.

**This is my test code:**
`trace( Assets.getFont( "fonts/montserrat.otf" ).fontName );`

**Expected output:**
`Montserrat`

**Output:**
_`null`_

Switching back to Lime 2.4.1 the test code returns the expected output.

Using true type fonts also returns the expected output.

Anybody have this same issue?

**Comment by jgranick** [comment]
Confirmed this is working properly with the current Lime release and Montserrat from https://www.fontsquirrel.com/fonts/montserrat :shipit:
