### ISSUE TITLE
Use only one hb_buffer with multiple hb_font

### ISSUE THREAD

**Issue by vroad** [openfl/lime#462]
https://github.com/lxnt/ex-sdl-freetype-harfbuzz/blob/master/ex-sdl-freetype-harfbuzz.c

This harfbuzz example uses only one hb_buffer, clearing contents after each shaping with `hb_buffer_clear_contents`. It seems to be okay to use single hb_buffer instance. Aren't we losing memory and performance for multiple hb_buffer? I also think that hb_font can be shared between multiple TextFields.

**Comment by jgranick** [comment]
Tracking here https://github.com/openfl/lime/issues/368, thanks :smile:
