### ISSUE TITLE
Haxelib Lime 2.4.4 broken?

### ISSUE THREAD

**Issue by cambiata** [openfl/lime#471]
When installing Lime 2.4.4 using haxelib, only a few classes are installed, and the haxelib title/version is **unknown 1.0.0**

**Comment by jgranick** [comment]
This might be your copy of haxelib, some recent versions fail to unzip all the way :cry:

**Comment by jgranick** [comment]
Can you try `haxelib selfupdate`?

**Comment by cambiata** [comment]
Hm, having thee selfupdate problem - on 14.04... https://github.com/HaxeFoundation/haxelib/issues/189

**Comment by jgranick** [comment]
Does that trick work?

`cp /usr/lib/haxe/haxelib /usr/lib/haxe/haxelib2
/usr/lib/haxe/haxelib2 selfupdate
rm /usr/lib/haxe/haxelib2`

**Comment by cambiata** [comment]
Strangely the same (unknown 1.0.0) happened on my win machine. After selfupdate - saying that I already have the latest version - it relaunces, and after that **haxelib lime update** works... 

Now on to the mac..!

**Comment by cambiata** [comment]
Same pattern on the mac, unknown 1.0.0. It doesn't allow me to selfupdate though, not even after the copy trick...

**Comment by cambiata** [comment]
After manually replacing haxe binaries to latest haxe.org-downloadable version (haxelib 3.2.0-rc.3), updating lime to 2.4.4 works on my Elementary OS (Ubuntu 14.04). The same (updating binaries to haxelib 3.2.0-rc.3) doesn't work on my mac though - it still gives the unknown 1.0.0 version,

**Comment by jgranick** [comment]
[!http://i.imgur.com/fcQmia5.jpg]

**Comment by francescoagati** [comment]
can be this the problem? the absense of lib1-mesa-dev? sudo apt-get install libgl1-mesa-dev
