### ISSUE TITLE
HighDPI on Mac is broken

### ISSUE THREAD

**Issue by fserb** [openfl/lime#472]
due to a7c95df6a9eb271ddc76686c3f2931199ba24280 (Lime 2.4.3 works fine) lime is broken for High DPI (Retina) Mac. The app gets the High DPI screen, but stageWidth, stageHeight are still the original values, and the window is the non-retina size.

If you specify <window width=100 height=100> the window created will have 100x100 non high-dpi size (i.e., the same size as before this change), while everything inside the app (stage, etc) will be in high DPI, but non-drawable outside the 100x100 area. This means you can only render things on the bottom right corner of the window. It's messy.

**Comment by steverichey** [comment]
I can confirm this issue, experienced on a 13" MacBook Pro. Lime 2.4.3 works fine for me as well.

**Comment by isohedral** [comment]
I'm having the same issue. I verified that it's not just my code by running PiratePig using "lime test neko -Dlegacy". The entire game is squeezed into the bottom-left quadrant of the screen on my retina display.

**Comment by fserb** [comment]
I tried to mess with this, but didn't get very far:

The first thing I did was to start using SDL_GL_GetDrawableSize instead of SDL_GetWindowSize. This is the correct function to use when going for HighDPI (it returns the actual pixel size). It could also be used to calculate the ratio difference.

If I change that on SDL2Stage, then the whole window area starts getting drawn, except that now Lib.current.stage.stageWidth returns twice the size it should. Example:

Requested on project.xml: 100x100
GetWindowSize: 100x100
GetDrawableSize: 200x200
Lib.current.stage.stageWidth: 400

I'm assuming this means that the stage scaling thing is going insane over this.
I'll keep poking.

**Comment by fserb** [comment]
Oh. I think I got the problem.
Lib.create() creates a stage that has a "nominal" width of 100x100 (which was passed from the project configuration.
Then the Stage tries to calculate the scale factor, which would be: current width / nominal width, which in this case returns 2, but should be 1.
The it says "well, we need to zoom in everything 2x", which leads to this 400.

It all boils down to the fact that the new SDL window created is actually twice the size it should be. I.e., I'm asking for 100x100 and it's creating a 200x200 screen (the same physical size as a 100x100 low dpi).

I can either: 
1. try to make the default window small (i.e., respect the window size requested on Mac).
2. make the nominal size to actually factor in the DPI scaling (by surfacing a scale number somewhere that is getdrawablesize/getwindowsize.

**Comment by isohedral** [comment]
Wow, thanks for looking into this. I'm afraid that I tend to be a Lime/OpenFL end user, with basically zero knowledge of the internals (e.g., SDL), so it's hard for me to agree or disagree with your proposed fixes.

I should note that this problem dovetails nicely with a question I asked previously -- in the newer builds of OpenFL, it's no longer possible to query `openfl.system.Capabilities.screenDPI` (see http://community.openfl.org/t/screendpi-no-longer-valid/1186). If you're thinking about "surfacing a scale number", I'd vote for creating global constants in Lime for the display's horizontal and vertical resolutions and DPI, and perhaps scaling factor as well (is that number independent of the other three?).

**Comment by arthurferrai** [comment]
I got this problem too. 
What are the implications of options 1 and 2?

**Comment by player-03** [comment]
On retina displays on iOS, my stage starts out at half the size it should be. Then after the first frame, the values are corrected and a `RESIZE` event is dispatched. It sounds like what you're seeing is different, but it's probably worth double-checking.

(Also, I don't have a retina Mac, so if that's not it, I have nothing to contribute.)

**Comment by arthurferrai** [comment]
Thanks for the suggestion, but resizing screen doesn't solve the issue.
A possible workaround is mark the .app to open in low resolution on info window.

**Comment by johanvdb** [comment]
I can confirm that I experience the same issues with 2.4.4 on a Macbook Pro Retina, and I can confirm that switching to lime 2.4.3 resolves the issue. I did however find that setting the stage alignment to bottom right causes similar calculation errors, even on 2.4.3, maybe related?

Lib.current.stage.align = StageAlign.BOTTOM_RIGHT;

See the following video for an example: http://youtu.be/Ay7hSXXeRY0

**Comment by isohedral** [comment]
Just installed Lime 2.4.5 today, and I'm no longer seeing this problem with -Dlegacy.

**Comment by jgranick** [comment]
Awesome, thank you :smile:

**Comment by arthurferrai** [comment]
updated lime with version 2.4.7
tried to build using command "lime test mac -Dlegacy -debug"
The window is created and then "Crash Report" window appears.
Building with "neko" works fine.
Building without "-debug" using "mac" also works fine.

**Comment by jgranick** [comment]
Does `lime test mac -Dlegacy -debug -clean` work differently?

**Comment by arthurferrai** [comment]
Nope, same result.
