### ISSUE TITLE
Crush when target to windows(cpp, neko)

### ISSUE THREAD

**Issue by Neugls** [openfl/lime#482]
Build the openfl or lime example successfully when target to windows, but when start up the exe, it crashed.  Target to html5, flash works.

![qq 20150619175949](https://cloud.githubusercontent.com/assets/1432749/8251192/ffa2505e-16ac-11e5-9977-d0096b1a1a5e.png)
![qq 20150619175915](https://cloud.githubusercontent.com/assets/1432749/8251191/ffa0a1e6-16ac-11e5-9df5-4fede42c11ed.png)

**Comment by jgranick** [comment]
I believe this has been resolved :smile:
