### ISSUE TITLE
Compilation issues with Bytes implementation on nodejs

### ISSUE THREAD

**Issue by vroad** [openfl/lime#483]
The biggest problem with this implementation is the use of '''memcpy()''' in `Bytes::Value()`. Why do you allocate memory outside VM and copy that to VM memory in `Value()` call ? That will just make performance much worse than older implementation. You can allocate memory inside VM with `alloc_buffer()` from the beginning, can't you?
https://github.com/openfl/lime/blob/d73460da1843350f2601ffcf6377c1e3dda6a52c/project/src/utils/Bytes.cpp#L24

Other issues:
- does not compile on nodejs, since nodejs still uses length param in the constructor of haxe.io.Bytes: https://github.com/vroad/nodejs-std/blob/14f26d9794b3796e9eec2396a310267c2fd2acd7/haxe/io/Bytes.hx#L32)
- throws an exception on nodejs since Typed Arrays can be passed on node.js. (can be fixed by always using ByteArray on nodejs?): https://github.com/openfl/lime/blob/d73460da1843350f2601ffcf6377c1e3dda6a52c/project/src/utils/Bytes.cpp#L36
- Even after fixing these, still does not work on nodejs since `alloc_raw_string()` is not implemented: https://github.com/openfl/lime/blob/d73460da1843350f2601ffcf6377c1e3dda6a52c/project/src/utils/Bytes.cpp#L228

**Comment by jgranick** [comment]
I have revised the Bytes implementation a few times. How is it working for you now?

**Comment by vroad** [comment]
Well I still needed some code changes to make this work on nodejs.

You are assuming that ByteArray extends Bytes, but on nodejs it doesn't.
Should we solve this problem by creating temporary Bytes instance, or ByteArray should extend Bytes on nodejs as well?
Latter one might be easier, but b and length should be added only for integrating with CFFI APIs.
So I'm creating temporary Bytes on nodejs, for now.

**Comment by vroad** [comment]
I'm using UInt8Array instead of ArrayBuffer or node's Buffer. This enabled us to create UInt8Array or other Typed Arrays without copying another ArrayBuffer.

This might cause problems in some cases, as current Bytes implementation expects node's Buffer.
According to node's document, Buffer's slice method behaves differently than that of ArrayBuffer.
You may not have proelem for other methods thohgh.

https://nodejs.org/api/buffer.html#buffer_new_buffer_size

**Comment by vroad** [comment]
Will you accept pull request for resolving this issue?

Currently nodejs target converts ByteArray to temporary anonymous structure for passing ByteArray to CFFI APIs, so it cannot get changes to that if it's resized.
If CFFI APIs doesn't do resize on that, everything should work fine on nodejs.

Because of this, some of changes may need changes to CFFI APIs(e.g. TextLayout).

**Comment by jgranick** [comment]
Tracking here: https://github.com/openfl/lime/issues/876
