### ISSUE TITLE
Dynamic sound not working on Mac

### ISSUE THREAD

**Issue by bendmorris** [openfl/lime#496]
Creating a new Sound object, adding an event listener for SAMPLE_DATA, and running `sound.play()` causes the following error on Mac desktop target:

	sound = new Sound();
	sound.addEventListener(SampleDataEvent.SAMPLE_DATA, getSamples);
	channel = sound.play();

Called from ApplicationMain::main ApplicationMain.hx line 319
Called from ApplicationMain::create ApplicationMain.hx line 251
Called from lime.app.Application::exec lime/app/Application.hx line 163
Called from lime._backend.native.NativeApplication::exec lime/_backend/native/NativeApplication.hx line 107
Called from extern::cffi /Users/ben/Dev/hxcpp/src/hx/Lib.cpp line 133
Called from lime._backend.native.NativeApplication::handleMouseEvent lime/_backend/native/NativeApplication.hx line 59
Called from lime.app.Application::onMouseUp lime/app/Application.hx line 295
Called from openfl.display.Stage::onMouseUp openfl/display/Stage.hx line 768
Called from openfl.display.Stage::__onMouse openfl/display/Stage.hx line 1226
Called from openfl.display.Stage::__fireEvent openfl/display/Stage.hx line 1076
Called from openfl.display.DisplayObjectContainer::__broadcast openfl/display/DisplayObjectContainer.hx line 639
Called from openfl.display.DisplayObject::__broadcast openfl/display/DisplayObject.hx line 1000
Called from openfl.events.EventDispatcher::dispatchEvent openfl/events/EventDispatcher.hx line 292
Called from retrio.ui.openfl.ToolbarButton::onClick retrio/ui/openfl/ToolbarButton.hx line 42
Called from retrio.ui.openfl.Button::onClick retrio/ui/openfl/Button.hx line 47
Called from retrio.ui.openfl.Shell::loadRom retrio/ui/openfl/Shell.hx line 300
Called from openfl.media.Sound::play openfl/media/Sound.hx line 431
Called from openfl.media.SoundChannel::new openfl/media/SoundChannel.hx line 80
Called from lime.audio.AudioSource::play lime/audio/AudioSource.hx line 163
Called from lime.audio.AudioSource::get_length lime/audio/AudioSource.hx line 374
Error : Null Object Reference

**Comment by ibilon** [comment]
This could interest you: http://community.openfl.org/t/dynamic-audio-crash-on-any-target-other-than-flash/1757/

**Comment by bendmorris** [comment]
Great timing. Looks like there's a workaround, thanks @ibilon!

Also it looks like this should be resolved by https://github.com/openfl/lime/commit/4ac262d061f0eed1a31e94d3fd4049670c9fe11c. I'll build from Git and test later today.
