### ISSUE TITLE
Cant rebuild newest Lime from git -snprintf error

### ISSUE THREAD

**Issue by hoseyjoe** [openfl/lime#497]
Not sure how to fix:
C:\Program Files (x86)\Windows Kits\10\\include\10.0.10056.0\ucrt\stdio.h(1925):
 warning C4005: 'snprintf': macro redefinition
lib/openal/include/config.h(72): note: see previous definition of 'snprintf'
C:\Program Files (x86)\Windows Kits\10\\include\10.0.10056.0\ucrt\stdio.h(1927):
 fatal error C1189: #error:  Macro definition of snprintf conflicts with Standar
d Library function declaration

**Comment by jgranick** [comment]
What version of Visual Studio are you using?

**Comment by hoseyjoe** [comment]
I have VS2013 and VS2015 community editions.  I am assuming MS chagned
something on snprintf?  So maybe this is an issue for the future (2015 not
released yet).  Is there a way to fix it?

Sincerely,
*Joe Williamson*
*Chief Technology Officer*
*Joe.Williamson@RealityCharting.com* <Joe.Williamson@RealityCharting.com>
 <https://www.realitycharting.com>
(Direct) 206-922-7912
(US) 877-722-2770
*www.RealityCharting.com* <http://www.realitycharting.com/>

**Comment by hoseyjoe** [comment]
I was able to build with newest GIT

**Comment by kiroukou** [comment]
Hello,

I have the same issue with lime 2.9.0

```
\Windows Kits\10\include\10.0.10586.0\ucrt\stdio.h(1925): warning C4005: 'snprintf'▒: red▒finition de macro
lib/openal/include/config.h(69): note: voir la d▒finition pr▒c▒dente de 'snprintf'
```

Any idea?

**Comment by kiroukou** [comment]
OpenAL extension seems not up to date in my install  (or is the lib reference which isn't?)

The change here around snprintf doesn prevent that error to show up.
https://github.com/native-toolkit/openal/blob/77986fa62e2218cf3d6a85198a0bbe6f1cfc0677/include/config.h
