### ISSUE TITLE
ArrayBuffers no longer convert to ByteArrays

### ISSUE THREAD

**Issue by ProPuke** [openfl/lime#504]
Typed arrays, for example `utils.UInt8Array` and `utils.Float32Array`, extend `ArrayBufferView` which uses `ArrayBuffer`. However, `ArrayBuffer` is a an _abstract_ of `Bytes`, making it incompatible with `ByteArray` which _extends_ `Bytes`.

We now have a divide in the api, between some functions which use `ByteArray`s and others which use `ArrayBufferView`s, as the two are no longer compatible with one-another, and require memory duplication. Should we be phasing `ByteArray` out, now (in many cases `ByteArray` does seem unneccasary)? Or perhaps we should be favouring composition over inheritance, and have`ByteArray`s _contain_ a `Bytes` member, so we can still easily use them with `ArrayBuffer`s?

**Comment by jgranick** [comment]
Perhaps we should add `@:to` and `@:from` meta-data to the typed arrays in order to allow for cleaner conversion

I was thinking about keeping ByteArray as an abstract in Lime, over Bytes, or, I was thinking about dropping it and using Bytes/typed arrays as the core type, and using ByteArray only in OpenFL

I'm open to suggestions, I agree, though, that we should do something.

**Comment by ProPuke** [comment]
(oops, only just noticed `ByteArray` has a `fromBytes` which doesn't copy. Not as bad as I thought :D)

`@:to` and `@:from` makes sense; Although, it feels to me like api functions should just use `Bytes`. `ByteArray` looks more like a utility type for the user, rather than a datatype.

It's *almost* an abstract, save for the read position and endianness property. I guess it probably deserves to still live, heh. But the api should not necessitate you to use it when you're reading/writing bytes (unless we have any api calls that *need* to affect the read position or endianness. I don't think we do?)

**Comment by jgranick** [comment]
Modern `ByteArray` is an abstract over `Bytes`, so it should convert properly. Thank you :smile:
