### ISSUE TITLE
Unable to load remote images on Android 

### ISSUE THREAD

**Issue by Matan** [openfl/lime#508]
I'm also getting this error #407 when compiling to Android. It seems to happen when you want load a remote image. To recreate, create the sample DisplayingABitmap project and try load a remote image.

For ease of use, add the following to the sample project:
```
var imageLoader = new flash.display.Loader();
imageLoader.contentLoaderInfo.addEventListener(openfl.events.Event.COMPLETE, function(event : openfl.events.Event)
{
    var bmp:flash.display.Bitmap = cast imageLoader.content;
    trace("Loaded image " + bmp.bitmapData.width + "x" + bmp.bitmapData.height);
});

var request:openfl.net.URLRequest = new openfl.net.URLRequest("http://upload.wikimedia.org/wikipedia/en/7/72/Example-serious.jpg");
imageLoader.load(request);
addChild(imageLoader);
```
When compiling for html5, you should see the Wikipedia sample image. On Android, the image never appears and you're left with the error message:
```
No implementation found for java.lang.String org.libsdl.app.SDLActivity.nativeGetHint(java.lang.String) (tried Java_org_libsdl_app_SDLActivity_nativeGetHint and Java_org_libsdl_app_SDLActivity_nativeGetHint__Ljava_lang_String_2)
``` 
Catch the error message with Android Monitor or LogCat.

Using
Ubuntu: 15.04
HaXe: 3.2.0
OpenFL: 3.1.4
Lime: 2.5.0
hxcpp: 3.2.94

**Comment by jgranick** [comment]
Are you using legacy? If not, I've made a commit that should probably help:

https://github.com/openfl/openfl/commit/6852fbd569ec6eaee28a07e7ea910d6edddccf83

**Comment by Matan** [comment]
Thanks! I'm not using legacy. I'll see if I can try out the patch today, otherwise I'll wait for the next release.

**Comment by Matan** [comment]
Loading remote images is working now, but now all the images are displaying as black boxes. See this new ticket:  #518

Closing this issue as this is fixed.
