### ISSUE TITLE
Setting sprite alpha multiple times breaks transparency on html5 target (using dev haxeflixel)

### ISSUE THREAD

**Issue by Tw1ddle** [openfl/lime#520]
I opened an issue with an example here: https://github.com/HaxeFlixel/flixel/issues/1576 but I think it might be a lime rendering issue instead.

The bug is that FlxSprites are being incorrectly rendered as opaque when their alpha is changed/updated more than once on the html5 target.

I noticed that `lime.graphics.utils.ImageDataUtil.colorTransform` is called when the color transform/alpha is changed, but always exits early because of a `buffer.data` null check, I think because image.buffer.data isn't set in `lime.graphics.utils.ImageCanvasUtil.createImageData`.

@jgranick I reverted this createImageData method to your earlier version: https://github.com/openfl/lime/commit/5434424003024bad1c87ffda5ff2365b9bd0bd41#diff-9e56bd57d787d3db5ec513d8de92facb and that makes the alpha get rendered properly again. Not sure what a proper fix is though.

Here are my haxelibs:

```
flixel-addons: git [dev:C:\HaxeToolkit\haxe\lib\flixel-addons/git]
flixel: git [dev:C:\HaxeToolkit\haxe\lib\flixel/git]
hxcpp: [3.2.102]
lime: [2.5.2]
openfl: [3.2.2]
swf: [1.9.1]
```

**Comment by jgranick** [comment]
I believe this is resolved, but if not, please share a small test case and we'll be happy to look into it. Thank you! :smile:
