### ISSUE TITLE
"fork: retry: Resource temporarily unavailable" after prolonged haxe usage - mac

### ISSUE THREAD

**Issue by robochase6000** [openfl/lime#527]
i've noticed this error crop up a number of times since i started using lime, just wondering where the problem might lie

It seems like, i'll be writing code & recompiling a lot via "lime test mac", when suddenly out of the blue terminal will start spitting out:
"fork: retry: Resource temporarily unavailable"

and pretty much the entire computer becomes non-functional.  restarting seems to be the only solution.

i've read a little bit about this error, and i seems like it could be an issue with too many threads or too many 'file descriptors'

i'm leaning toward blaming lime on this one, because it has happened to me on two different machines, numerous times, with different haxe codebases.

can anyone illuminate the issue better and offer a solution? maybe something isn't cleaning up right when the compiler is done? (i have zero knowledge on what is actually happening when you run lime test mac, so sorry if that's a weird question)

**Comment by jgranick** [comment]
I believe the current version of Lime does not leak file handles, but there is the possibility that this is happening somewhere. If you run `lime build mac` repetitively, does it occur, or only with `test`? If it only happens if your application runs, perhaps it is something at runtime -- either your project or something in the framework. This is the first I've heard of it, though.

It happens if `fopen` a file, but don't `fclose` it. Eventually the OS stops giving file handles

**Comment by robochase6000** [comment]
I'll try hammering on both ```lime build mac``` and ```lime test mac``` soon.

interesting about ```fopen``` ... i will say in one of my haxe projects, the code did open some files (and it did a lot with sockets too, if that's at all a clue).  but in my most recent project, it doesn't do anything with that stuff.  unless you mean something deeper in the code? like the stuff actually running my application?

**Comment by jgranick** [comment]
There's a few things in play:

 * Haxe
 * HXCPP
 * Lime tools
 * Lime runtime classes
 * OpenFL

There is a chance that Haxe could be the culprit (some bug?) but I would assume that more people would see the issue if it was.

Similarly, in HXCPP or the Lime tools, I think more people would be seeing it, unless this was some edge case your project hit that others did not. These would have problems, likely, using standard sample projects. I haven't been seeing issues with file handles in a while, so I'm unsure of this.

The more likely chance would be something in a project, or possibly some regression in Lime or OpenFL at runtime -- but again -- I have not been hearing reports or seeing issues myself, so if is, it's some case that we aren't usually visiting (probably?)

**Comment by robochase6000** [comment]
I build from terminal.

i'm experimenting with running ```lsof | wc -l``` between builds, as well as when lime is compiling - i guess it outputs the number of open file descriptors.  it seems like everything is ok - the number fluctuates a bit, but it doesn't seem to continually rise. if i do ```lime clean mac``` then do a fresh ```lime test mac```, and run that command while it's building, the number of processes climbs by a couple hundred, but it almost immediately dips back to where it was initially as soon as the build is done.

so maybe something else is going on.  will keep my eye on this. thanks for your help!
