### ISSUE TITLE
Error: Could not find build target "by"

### ISSUE THREAD

**Issue by ChairmanChao** [openfl/lime#537]
I'm running the basic HelloWorld from the HaxeFlixel on Linux. I have basically no experience with Linux so it's been a real treat getting it even to this point.
When I run "lime test linux -64 -v" I get "Error: Could not find build target "by"".

but the only instance of 'by' i could find was at the bottom of this chunk:

```
Running command: BUILD
 - Copying library file: /home/chairmanchao/haxelib/hxcpp/3,2,102/bin/Linux64/std.dso -> export/linux64/cpp/bin/std.dso
 - Copying library file: /home/chairmanchao/haxelib/hxcpp/3,2,102/bin/Linux64/regexp.dso -> export/linux64/cpp/bin/regexp.dso
 - Copying library file: /home/chairmanchao/haxelib/hxcpp/3,2,102/bin/Linux64/zlib.dso -> export/linux64/cpp/bin/zlib.dso
 - Copying library file: /home/chairmanchao/haxelib/lime/2,5,2/legacy/ndll/Linux64/lime-legacy.ndll -> export/linux64/cpp/bin/lime-legacy.ndll
 - Running command: haxe export/linux64/cpp/haxe/release.hxml -D HXCPP_M64
 - Changing directory: export/linux64/cpp/obj
 - Running command: haxelib run hxcpp Build.xml -DFLX_NO_DEBUG=1 -DFLX_RENDER_TILE=1 -DHXCPP_M64=1 -DNAPE_RELEASE_BUILD=1 -Ddesktop=1 -Dflixel=3.3.11 -Dhaxe3=1 -Dhaxe_ver=3.3 -Dhxcpp=3.2.102 -Dhxcpp_api_level=321 -Dlime=2.5.2 -Dlime-legacy=1 -Dlime-native=1 -Dlime_legacy=1 -Dlime_native=1 -Dlinux=1 -Dnative=1 -Dopenfl=3.2.2 -Dopenfl-legacy=1 -Dopenfl-native=1 -Dopenfl_legacy=1 -Dopenfl_native=1 "-Dsource-header=Generated by Haxe" -Dtools=2.5.2 -DHXCPP_M64 -verbose
```

`"-Dsource-header=Generated by Haxe"` in the final line where it runs  `haxelib run hxcpp Build.xml`
I've tried finding where that's being done so I can try tinkering, but I'm really just at a loss. Any help would be appreciated, thanks!
Jeremy

**Comment by ChairmanChao** [comment]
If it matters `lime test neko` works fine.

**Comment by ooz** [comment]
I have the same issue with the PiratePig and NyanCat examples.

Ubuntu 14.04 64bit
haxe 3.3.0
haxelib 3.2.0-rc.3

```
$ haxelib list
actuate: [1.8.6]
box2d: [1.2.3]
flixel: [3.3.11]
haxelib_client: [3.2.0-rc.3]
hxcpp: [3.2.102]
layout: [1.2.1]
lime-samples: [2.6.0]
lime: [2.6.4]
openfl-samples: [3.3.0]
openfl: [3.3.5]
swf: [2.0.3]
```

The Android target was set up with `lime setup android`. I get the same error message when I run `lime test linux`, but `lime setup linux` isn't currently working (see [this](https://github.com/openfl/lime/pull/424)).

`lime test flash` and `lime test neko` work fine.

**Comment by ooz** [comment]
`lime test linux -Dsource-header=0` fixed it for me.

Source:
http://community.openfl.org/t/error-could-not-find-build-target-by/6571/4

**Comment by jgranick** [comment]
This was fixed recently :smile:
