### ISSUE TITLE
iOS: Make 'idleTimerDisabled' property of application configurable

### ISSUE THREAD

**Issue by ngrebenshikov** [openfl/lime#538]
The purpose: to make possible behaviour when an app have no touches as user input for a short period, the system puts the device into a "sleep” state where the screen dims.

**Comment by jgranick** [comment]
Tracking here: https://github.com/openfl/lime/issues/877 :smile:

**Comment by jgranick** [comment]
My mistake! This was added in Lime 2.6.7, released 10/02/2015, as `System.allowScreenTimeout` :sweat_smile:

https://github.com/openfl/lime/blob/develop/CHANGELOG.md#267-10022015
