### ISSUE TITLE
JNI and HaxeObject.callX crash

### ISSUE THREAD

**Issue by TBaudon** [openfl/lime#547]
Hello,

I'm trying to move on the last lime and openfl haxelib versions and I have some trouble with extensions. 

I made a basic sample that's produce the crash here : https://github.com/TBaudon/HaxeObject-test

Apparently, using HaxeObject.callX from java crash the app.

i'm using : 

openfl 3.3.0
lime 2.5.3
hxcpp 3.2.102

I also use java jdk 1.7 .

Thanks.

**Comment by jgranick** [comment]
I believe this is an issue with threading, the Java code and Haxe code do not execute on the same thread, so it is important to only call Haxe from Java within a callback, such as:

```java
Extension.callbackHandler.post (new Runnable () 
{
	@Override public void run () 
	{
		// call Haxe from here
	}
}
```
