### ISSUE TITLE
compile error project with space in path

### ISSUE THREAD

**Issue by tbrannam** [openfl/lime#555]
Lime Command-Line Tools (2.6.1)

    cd ~/projects/HaxeFlixel\ Tutorial
    lime run flash
    /usr/lib/haxe/std/neko/_std/Sys.hx:87: characters 2-24 : Error chdir /Users/todd/projects/HaxeFlixel
    tools/haxelib/Main.hx:309: characters 17-43 : Called from
    tools/haxelib/Main.hx:1508: characters 2-22 : Called from
    ?:1: characters 1048575-8796094070782 : Called from
    Aborted

    pwd
    /Users/todd/projects/HaxeFlixel Tutorial
    cd ..
    mv HaxeFlixel\ Tutorial/ HaxeFlixelTutorial
    cd HaxeFlixelTutorial/
    lime run flash

**Comment by ibilon** [comment]
Can't reproduce anymore, make sure to use the latest lime/openfl versions.
