### ISSUE TITLE
Sound html5 

### ISSUE THREAD

**Issue by TBaudon** [openfl/lime#556]
I  have a strange bug with last lime haxelib version :

sound is all on right speaker.

I tested it on chrome.

The problem does not occur if I use a soundTransform to set the pan to -0.0000001 

But if I set Zero, all the sound is one right speaker again.

**Comment by TroyEdwardsJr** [comment]
I'm having this issue as well.

**Comment by Tw1ddle** [comment]
@TBaudon I saw this too, it's a Chrome issue. SoundJS added a workaround for it a few days ago: https://github.com/CreateJS/SoundJS/issues/182
