### ISSUE TITLE
HandlingInputEvents sample not picking up correct coordinates on android html5

### ISSUE THREAD

**Issue by johanvdb** [openfl/lime#560]
The HandlingInputEvents sample does not move the block to the correct location of a touch event when accessed via my Samsung Galaxy Note 3 using Chrome, whereas on Mac using Chrome, mouse click events move the block as expected.

I have been having other issues with touch and click events not propagating, so decided to bypass openfl and my own code and test it using one of the samples. 

```
johantheitguy$ haxelib list
actuate: [1.8.6]
box2d: [1.2.3]
flixel-addons: [1.1.0]
flixel-demos: [1.1.2]
flixel-tools: 1.1.0 [1.1.1]
flixel: [3.3.11] 3.3.8
hxargs: [3.0.0]
hxcpp: [3.2.102]
layout: 1.2.0 [1.2.1]
lime-samples: 2.3.0 [2.6.0]
lime: 2.4.3 2.4.4 2.4.5 2.6.0 [2.6.1]
nape: [2.0.19]
openfl-samples: 2.2.2 3.1.0 [3.3.0]
openfl: 3.0.1 3.1.0 3.3.1 [3.3.2]
swf: 1.8.8 [1.9.1]
```

**Comment by DEaDA** [comment]
I have some problem on iOS.

I guess there are bugs in lime 2.6.2. I found one in lime._backend.native.NativeApplication; 
touch = new Touch (touchEventInfo.x, touchEventInfo.x, ... 
must be
touch = new Touch (touchEventInfo.x, touchEventInfo.y, ...
but it's still don't resolve problem in 2.6.3.

**Comment by jgranick** [comment]
Fixed in current releases, thank you :smile:
