### ISSUE TITLE
it keeps asking me if i want to 'install the "lime" command?'

### ISSUE THREAD

**Issue by raould** [openfl/lime#564]
even though i invoked it using the lime command. sorta silly / weird / worrying / frustrating.

```
$ lime setup
hxcpp is up to date
lime-samples is up to date
Do you want to install the "lime" command? [y/n/a] ? n

To finish setup, we recommend you either...

 a) Manually add an alias called "lime" to run "haxelib run lime"
 b) Run the following commands:

sudo cp "/usr/lib/haxe/lib/lime/2,6,2/templates/bin/lime.sh" /usr/local/bin/lime
sudo chmod 755 /usr/local/bin/lime
```

**Comment by ibilon** [comment]
https://github.com/openfl/lime/blob/develop/tools/utils/PlatformSetup.hx#L1684
There's indeed no check if the command is already setup.

**Comment by jgranick** [comment]
Setup does not confirm if it has been run before, but I am tracking the enhancement as a part of this issue, thank you :smile:

https://github.com/openfl/lime/issues/878
