### ISSUE TITLE
"lime create project foo" killed my already existing foo/project.xml

### ISSUE THREAD

**Issue by raould** [openfl/lime#566]
yes, i have it in source control, but i think lime should not do that.

**Comment by ibilon** [comment]
Indeed it should not.
https://github.com/openfl/lime/blob/develop/tools/utils/CreateTemplate.hx#L80

**Comment by jgranick** [comment]
This is intended, actually, so you can overwrite projects with a fresh project template or copy of a sample project, but we can discuss on Slack or the forums, more, if we want to talk about a different way of handling this. Thank you :smile:

**Comment by ibilon** [comment]
A warning about the overwriting would be nice.
