### ISSUE TITLE
/lime/2,6,2/ndll/BlackBerry/lime.so" does not exist

### ISSUE THREAD

**Issue by pozirk** [openfl/lime#568]
**Error: Source path "c:\HaxeToolkit\haxe\lib/lime/2,6,2/ndll/BlackBerry/lime.so" does not exist**
Can't build for Blackberry anymore, get this error message.
I guess, it's just missing.
Thank you!

**Comment by pozirk** [comment]
Just noticed it's not supported yet.

**Comment by jgranick** [comment]
Yeah, still need -Dlegacy for BlackBerry at the moment :smile:
