### ISSUE TITLE
libjpeg is too old (from 1998?)

### ISSUE THREAD

**Issue by vroad** [openfl/lime#575]
For some reason libjpeg 6b is still used. Should be updated as older version may have performance issue or bugs.

On Android libjpeg crashed for some reason on my device. (inside ycc_rgb_convert)

I updated libjpeg from 6b to 9a.
https://github.com/native-toolkit/jpeg/pull/1

**Comment by vroad** [comment]
I pasted the wrong URL...
And this needs small changes in lime as well.

https://github.com/native-toolkit/jpeg/pull/1
https://github.com/vroad/lime/commit/a18ee7644b7381f94d3da1e93f046557c0b8e34c

**Comment by vroad** [comment]
When I try to load jpeg or ogg files, I still get crash on android after updating this... while xml and png loads fine. This seems to be unrelated.

**Comment by jgranick** [comment]
Ah, I had always found this page when looking for the latest:

http://libjpeg.sourceforge.net

Now I see there is this page:

http://www.ijg.org

Have you found any changelogs anywhere, so we can see if the API changes?

**Comment by vroad** [comment]
It's contained in the archive. I only saw it briefly but there seems no backward-incompatible changes.

**Comment by jgranick** [comment]
https://github.com/openfl/lime/issues/880
