### ISSUE TITLE
legacy/ndll/Android/ directory missing

### ISSUE THREAD

**Issue by ramsestom** [openfl/lime#578]
The legacy/ndll/Android/ directory is missing, making legacy build for android to crash. Can you add it to the repository? (Don't know why it disappeared ;) )

**Comment by ibilon** [comment]
Are you using the github version of lime?
If so you need to rebuild the android ndll, `lime rebuild android -Dlegacy`.
Or is it that step that is crashing?

**Comment by ramsestom** [comment]
Yes I am using the github version of lime. Thanks I didn't knew I had to rebuild for legacy too (was only doing a "lime rebuild android"). That should solve the problem ;)
