### ISSUE TITLE
CURLBindings read/write treats data as strings instead of buffers

### ISSUE THREAD

**Issue by rushmobius** [openfl/lime#579]
The readFunction/writeFunctions in URLLoader.hx pass string data to/from the CURLBindings. This prevents binary data from being sent in a POST as the data may contain bytes that are zero. This causes the length of data to post to terminate early due to using the length of the string.

**Comment by jgranick** [comment]
Thanks! This is fixed now, cURL bindings now properly use a Bytes type, I've updated OpenFL to match with additional improvements :smile:
