### ISSUE TITLE
ImageCanvasUtil copPixels crashes Firefox when sourceRect.width or sourceRect.Height < .5

### ISSUE THREAD

**Issue by tjrhodes** [openfl/lime#582]
Hi,

Line 123 in ImageCanvasUtil, needs a check for sourceRect.width and sourceRect.Height, if they round to 0 then everything blows up on Firefox.

I have this...

```
if (sourceImage.buffer.src != null && Std.int(sourceRect.width) > 0 && Std.int(sourceRect.height) > 0) {
```

...which works but I guess isn't the most efficient thing in the world. There should probably be a check before this stage?

Cheers for all the hard work,

Tom.

**Comment by jgranick** [comment]
I think this should fix it, but I did not set up a test case to know (for example) if Flash ignores a sourceRect of 0.8 or rounds it up.

Might be worth looking into.

Does this help? :smile:
