### ISSUE TITLE
Bitcode issues on XCode 7 when targeting iOS versions => 6

### ISSUE THREAD

**Issue by grapefrukt** [openfl/lime#584]
When building for iOS using XCode 7.0 with a `<ios deployment="7.0" />` flag set for the project this linker error will occur:

```
ld: '/xcodetest/Export/ios/PiratePig/lib/arm64-debug/libApplicationMain.a(20c05493_RunLibs.o)' 
does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), 
obtain an updated library from the vendor, or disable bitcode for this target. for architecture 
arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Manually disabling bitcode either in XCode or via editing the project (as text) will make it compile again, as does removing the deployment flag from the project xml. 

I'm using:
```
hxcpp: 3.2.102
lime: 2.6.4
openfl: 3.3.5
```
A copy of the generated project is here: https://dl.dropboxusercontent.com/u/32925/PiratePig.zip

**Comment by jgranick** [comment]
I've flagged it to be disabled by default unless someone does `<config:ios enable-bitcode="true" />`

Perhaps after HXCPP supports bitcode we can keep it based on the deployment version, but for now, I think this seems safer :smile:

**Comment by grapefrukt** [comment]
I suppose it's going to be a requirement for submitting at all at some point, but this will work in the meantime.

**Comment by grapefrukt** [comment]
Also, great work! :cactus:
