### ISSUE TITLE
Class not found : cpp.Float32 in NoLegacy mode

### ISSUE THREAD

**Issue by Omar2002** [openfl/lime#588]
$ haxelib run openfl test android
.../haxe/lib/lime/2,6,6/lime/audio/openal/AL.hx:7: characters 7-18 : Class not found : cpp.Float32

**Comment by jgranick** [comment]
What version of Haxe do you have installed? Could you make sure you have either a stable Haxe 3.1.3 or 3.2.0 installed?

There should be guards around it to handle both

```haxe
#if ((haxe_ver >= 3.2) && cpp)
import cpp.Float32;
#else
typedef Float32 = Float;
#end
```

Thanks!

**Comment by Omar2002** [comment]
actuate: 1.7.2 1.7.3 1.7.5 1.8.0 [1.8.6]
box2d: [1.2.3]
firetongue: 1.0.0 git [dev:E:\Work\my\haxe\lib/firetongue/git]
haxelib_client: [3.2.0-rc.3]
hscript: 2.0.3 2.0.4 [2.0.5]
hxcpp: 3.1.30 3.1.39 3.1.48 3.2.102 [3.2.180]
layout: [1.2.1]
lime-samples: [2.6.0]
lime-tools: 1.4.0 1.5.6 [1.5.7]
lime: 2.6.1 2.6.3 2.6.6 [2.6.9]
openfl-native: [1.4.0]
openfl-samples: 1.3.0 2.2.0 3.1.0 3.3.0 [3.3.1]
openfl-tools: [1.0.10]
openfl: 1.4.0 2.0.0 2.0.1 2.2.1 3.3.1 3.3.2 3.3.4 3.3.6 [3.3.9]
stablexui: 1.0.17 1.1.1 [1.1.5]
swf: [2.1.2]
task: [1.0.6]

thanks!

**Comment by Omar2002** [comment]
I can not finde package cpp and class Float32
Where this class should be located?

**Comment by ibilon** [comment]
This class is located in the haxe std, not in a haxelib.

We need to know your haxe version, which you can get with the command `haxe -version`.

**Comment by jgranick** [comment]
If you have the latest Haxe installed and do not have this file, try reinstalling. On Windows, it seems sometimes files are not copied as part of the install (randomly) :confused:

**Comment by Omar2002** [comment]
Thanks! I will try it.

**Comment by Omar2002** [comment]
Thank you!
I reinstall haxe and it resolve the problem.
