### ISSUE TITLE
[html5] Account for null buffer.data in ImageCanvasUtil.createImageData()

### ISSUE THREAD

**Issue by azrafe7** [openfl/lime#594]
Reproducible with this code, which seems to stop after the ~first frame and doesn't draw the diagonal red line as expected:

```haxe
class Main extends Sprite {
	
	var bmd:BitmapData;
	var i:Int = 0;
	
	public function new () 
	{
		super();
		
		bmd = new BitmapData(100, 100);
		addChild(new Bitmap(bmd));
		
		stage.addEventListener(Event.ENTER_FRAME, onEnterFrame);
	}
	
	public function onEnterFrame(e):Void {
		i %= Std.int(bmd.rect.width);
		bmd.setPixel32(i, i, 0xFFFF0000);
		i++;
	}
}
```

The issue is probably localized here: https://github.com/openfl/lime/blob/80e034721085a05dc0cfa2ab71de58d94594fda2/lime/graphics/utils/ImageCanvasUtil.hx#L177-L188

I've fixed it locally by adding this at the end of `ImageCanvasUtil.createImageData()`

```haxe
		} else if (buffer.data == null) {
			buffer.data = new UInt8Array ((buffer.__srcImageData.data.buffer:js.html.ArrayBuffer));
		}
```

but I'm not sure it's the correct fix.

**Comment by azrafe7** [comment]
Mmmhh... It seems to be a timing issue/race condition somewhere, because if I call the setPixel loop from inside a `for` all works fine.

My temp fix is obviously not the right thing to do, as that will recreate the buffer every frame.

Trying to debug with chrome dev tools and stepping through code I get a random number of pixels drawn (but the first one is always shown). Then at some point `data` gets set to null somewhere (by `sync()` probably) and all breaks.

Ideas?

**Comment by azrafe7** [comment]
What about this at the end of `ImageCanvasUtil.convertToCanvas()`?

```haxe
		} else if (buffer.data == null && buffer.__srcImageData != null) {
			buffer.data = cast buffer.__srcImageData.data;
		}
```

It seems to work for me but, again, I don't know the implications and if it's the proper fix.

**Comment by jgranick** [comment]
Thanks, I just had the same problem, your last fix is working for me here :smile:

**Comment by azrafe7** [comment]
np, thanks.
