### ISSUE TITLE
CPP Cross compiling 32 bit & 64 bit windows app from Linux

### ISSUE THREAD

**Issue by jobs-git** [openfl/lime#601]
Sooner or later, HXCPP will support cross-compilation of Windows app from Linux.

When will lime support these?

I am also testing a 64bit windows app cross-compilation, but a 64bit lime.dll was not in place, I could not as well find the source code for these.

**Comment by ibilon** [comment]
http://community.openfl.org/t/compiling-windows-cpp-from-linux-using-mingw-its-possible/6503

Not sure how well it works even for a hxcpp hello world.
