### ISSUE TITLE
Implement GL.getExtension on native platforms

### ISSUE THREAD

**Issue by Aatu** [openfl/lime#605]
Hi.

If I run `lime.graphics.opengl.GL.getSupportedExtensions()` I get a whole bunch of extension names.
When calling `lime.graphics.opengl.GL.getExtension('GL_ARB_instanced_arrays')` a null gets returned. This happens with all extension names. I am building my app for windows with command `lime test windows`.

On html5 there are much less extensions available, but every extension from above list actually returns something else than null with getExtension. 

I am quite new to haxe, so if there is some silly mistake, or missing setting I need to fix, I would love to hear:)

**Comment by Aatu** [comment]
Ok, so it looks like with webgl the using the extension name returns something usable. With OpenGL what one must do is load the functions from that extension, by name defined in somewhere. For example, one of the functions I was looking was `glVertexAttribDivisorARB`. Calling lime.graphics.opengl.GL.getExtension('glVertexAttribDivisorARB') returns something.

**Comment by jobs-git** [comment]
I think there were changes in the OpenGl support of lime, I get error when I attempt to run the created executable: 

Could not Compile Shader.hx during runtime. ...GL ES and others.

**Comment by jgranick** [comment]
We have support now for GLES2 and WebGL extension constants, with planned support for native extensions that expose new functions. I hope this will continue to improve, thanks :smile:
