### ISSUE TITLE
JPEG/Ogg Vorbis/Font load failure on Android

### ISSUE THREAD

**Issue by vroad** [openfl/lime#608]
I still get crash sometimes while reading JPEG file on Android.
I inserted `__android_log_print` between codes and found out that crash is happening randomly.
Maybe because Bytes is held on stack and it's destroyed by hxcpp's garbage collector? (#498)

https://github.com/openfl/lime/blob/923f16cefdea2fa1e5b8c0df34d5159514b088c6/project/src/graphics/format/JPEG.cpp#L230

I moved `Bytes data;` to higher scope but I still cannot load JPEG.
I copied JPEG error handling code from the Internet and got this error message:
 `Corrupt JPEG data: premature end of data segment`
`Unsupported marker type 0x93`
Bug with `MyDestManager` maybe?

If I just use `FILE*` retrieved with `FILE_HANDLE::getFile()` everything just works fine.

The same thing is happening with OGG vorbis loader.
`OAL_OggMemoryFile fakeFile` is held on stack as well, but it's always destoyed before lime starts Ogg loading.
Simply using `FILE*` or moving fakeFile to higher scope solved this issue.

PNG loader does the same thing with `Bytes`, but never crashed for some reason. It may have finished reading before memory is destroyed.

Font loader crashed when I tried to load "Verdana" or "_serif", which does not exist on Android device.
The crash was inside SDL_RWOps, so there might be a bug in it.

**Comment by vroad** [comment]
I've fixed this by myself in my fork. They were mostly issues with C++ variable scopes, as I said in my previous post. Also, SDLActivity.java was outdated.

I also did other optimizations when I was working on this.
 - Do not open the same file twice
 - Do not copy whole file when loading font

```FILE_HANDLE::getFile()``` works for most file types but not for PNG. SDL returns descriptor of raw APK instead of extracted file for this case? Is this why @jgranick said that you might skip into contents of other files in APK?

```FILE_HANDLE::getFile()``` leaks file descriptor if file is Android assets (unless you manually close the file), so either way it's problematic to use this.

**Comment by jgranick** [comment]
I'm having trouble finding these changes in your fork. Which files were related?

**Comment by vroad** [comment]
Please see this commit. JPEG loader is fixed after this commit though.
https://github.com/vroad/lime/commit/006bd6a907efa10686d2b4ee67c5b1c9e070b2b5

https://github.com/vroad/lime/commits/master/project/src/graphics/format/JPEG.cpp

**Comment by jgranick** [comment]
I found an issue with the latest SDL version we were using, the template for Android was not up-to-date, so a regular file load routine that would hit an unfound file would crash instead of returning a null FILE pointer. With this fixed, it resolves issues that were occurring with font loading, it could be related to JPEG, PNG or other file loads as well

**Comment by vroad** [comment]
You also need to move some variable declarations to appropriate location. Without this fix, app may crash randomly as they get invalid too early.

It's related to all loaders because SDL always looks for expansion files if they are not found in apk assets or internal storage.
