### ISSUE TITLE
Cant compile android (Sound.Java, cannot find symbol error)

### ISSUE THREAD

**Issue by The1andONLYdave** [openfl/lime#610]
lime build android -Dsource-header=0
Error: (more information below)

release:

-code-gen:
[mergemanifest] Found modified input file
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Merging manifests from project and 3 libraries.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Found modified input file
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 7 source files to /Users/dkulsch/workspace-private-StudioProjects/Project-Montezuma/export/android/bin/bin/classes
    [javac] /Users/dkulsch/workspace-private-StudioProjects/Project-Montezuma/export/android/bin/src/org/haxe/lime/GameActivity.java:94: cannot find symbol
    [javac] symbol  : class Sound
    [javac] location: class org.haxe.lime.GameActivity
    [javac] 	private Sound _sound;
    [javac] 	        ^
    [javac] /Users/dkulsch/workspace-private-StudioProjects/Project-Montezuma/export/android/bin/src/org/haxe/lime/GameActivity.java:111: cannot find symbol
    [javac] symbol  : class Sound
    [javac] location: class org.haxe.lime.GameActivity
    [javac] 		_sound = new Sound (getApplication ());
    [javac] 		             ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 2 errors

BUILD FAILED
/Users/dkulsch/Library/Android/sdk/tools/ant/build.xml:716: The following error occurred while executing this line:
/Users/dkulsch/Library/Android/sdk/tools/ant/build.xml:730: Compile failed; see the compiler error output for details.

Total time: 9 seconds

Used Sound with:
**FlxG.sound.playMusic()**
**FlxG.sound.play()**

using .ogg files.

compilation was successfull about a year ago.

** haxelib list**
flixel-addons: [1.1.0]
flixel: [3.3.11]
ganalytics: [0.0.3]
haxelib_client: [3.2.0-rc.3]
hxcpp: [3.2.180]
lime-samples: [2.6.0]
lime: [2.6.9]
linden-google-play: git [dev:/usr/local/lib/haxe/linden-google-play/git]
openfl: [3.3.9]

Found some links with links at google which sayed "compile with **-Dnext**" but this throws other errors:
/usr/local/lib/haxe/flixel/3,3,11/flixel/input/gamepad/FlxGamepadManager.hx:360: lines 360-369 : Type not found : JoystickEvent

Maybe **-Dsource-header=0** causes this? but without i get:
Error: Could not find build target "by"

Any news on this, or should i focus on going the -Dnext way and better solve the errors -Dnext gives?

Greetings, David-Lee

**Comment by jgranick** [comment]
Try and do a clean build, I think the "Sound" issue is caused by having an old Sound.java file in your output directory?

**Comment by ibilon** [comment]
No feedback, open again if you still have this issue after upgrading and doing a clean build.
