### ISSUE TITLE
HTML5 target generates incorrect code for native JavaScript arrays in some cases

### ISSUE THREAD

**Issue by oripessach** [openfl/lime#611]
I ran into this issue in Haxe code generated by Stencyl. This haxe code:

    Engine.engine.getGameAttribute("Level States").insert(Std.int(0), 1);
 
Generates the following JavaScript code:

    com_stencyl_Engine.engine.getGameAttribute("Level States").insert(0,1);

`getGameAttribute()` returns a native JavaScript array, which doesn't have an insert() method. The problem seems to be that `getGameAttribute()` is declared this way:

    public static function getGameAttribute(name:String):Dynamic

so the compiler can't know that .insert() should be mapped to something else.

Seems to me like the JS runtime environment Haxe uses should include an Array like class that can be used instead of the native JS Array.

**Comment by oripessach** [comment]
This is probably a Haxe issue, rather than a problem with openfl or lime.

**Comment by mrcdk** [comment]
The problem isn't related to lime or Haxe, it seems to be a your code issue. When you (Stencyl in this case) use `Dynamic` the compiler won't be able to infer the type, apply optimizations,... It's a way to tell the compiler that you know what you are doing and to not bug you about anything. http://haxe.org/manual/types-dynamic.html 

For that to work, you will need to cast it to the correct type.
```
cast(Engine.engine.getGameAttribute("Level States"), Array<Dynamic>).insert(Std.int(0), 1);
```

A smaller example: http://try.haxe.org/#CFe66

**Comment by oripessach** [comment]
OK, I get the impression that the correct answer is "Haxe isn't a dynamically typed language, so stop trying to treat it like one." 

It's somewhat surprising that accessing Dynamic objects works sometimes, but not at other times, and that this discrepancy seems to be due to an optimization - manipulating Haxe Array objects so they map to JavaScript Array objects. The problem could have been avoided if the Haxe JavaScript runtime included its own Array type, but that would probably be a bad idea for a whole lot of practical reasons...

**Comment by jgranick** [comment]
Yeah, I think it's a matter of things that are compile-time or runtime features. For example, getters and setters really are "get_" and "set_" function calls. This will fail if it's Dynamic (without using `Reflect`), similarly, abstract classes will fail to behave properly, since they are a compile-time feature.
