### ISSUE TITLE
Run code after a build

### ISSUE THREAD

**Issue by player-03** [openfl/lime#612]
FlashDevelop provides a convenient "Post-Build Command Line" feature. It's pretty simple: once the build is finished, it runs your command.

My question is, why can't Lime do this? If this was available through `project.xml`, you could choose a command based on the target, or which flags were set, or whatever.

Example: imagine you had a flag to make an [unstripped Android build](http://community.openfl.org/t/how-to-get-unstripped-binary-of-android-build/6753). If that flag was set, you'd likely want to make a copy of `libApplicationMain` after compiling. It would be easy to check this flag from `project.xml`, but FlashDevelop doesn't have easy access - you'd have launch a program to parse `export/android/haxe/release.hxml`.

---

I'm willing to implement this myself, but first I want to discuss it (per [this advice](http://www.joelonsoftware.com/articles/fog0000000036.html)). Here's what I'm planning to implement, written in the style of the [xml format page](http://www.openfl.org/learn/resources/command-line-tools/project-files/xml-format/).

### `<postbuild />`
The `<postbuild />` tag defines a command to be run after each successful build:

    <postbuild command="echo Android build finished!" if="android" />

If you prefer, you can execute a Haxe file. This requires a file with a static main method.

    <postbuild haxe="PostBuild.hx" />
    
    <postbuild command="haxe -main PostBuild.hx --interp" />

You can use the `open` attribute to open a file, folder, or url. This uses a system-specific command (`start` for Windows, `open` for Mac, or `xdg-open` for Linux) to find the right program.

    <postbuild open="Export/mac" if="mac" />
    <postbuild open="http://www.example.com/" />

To include spaces within arguments, use `<arg />` tags:

    <postbuild command="cp">
        <arg>sample/path/with spaces/file.txt</arg>
        <arg>another path/with spaces/file.txt</arg>
    </postbuild>

If you define multiple `<postbuild />` tags, they'll be executed in order:

    <postbuild command="mkdir folder" />
    <postbuild command="touch folder/file.txt" />
    <postbuild open="folder/file.txt" />

### `<prebuild />`
The `<prebuild />` tag defines a command to be run before building. The syntax is exactly the same as for `<postbuild />`.

**Comment by player-03** [comment]
Now that this is implemented and [submitted](https://github.com/openfl/lime/pull/630), I'm closing the issue.

**Comment by lovedna** [comment]
thanks! i like this very much
