### ISSUE TITLE
iOS: latest changes to OpenGL version check breaks iOS builds

### ISSUE THREAD

**Issue by tanis2000** [openfl/lime#613]
Have a look at this comment here:

https://github.com/openfl/lime/commit/611df0d86c24a8bb6d91a086358e5feef8ed5412#commitcomment-13844540

**Comment by tanis2000** [comment]
On my side I fixed it by replacing that line with:

```
					#ifdef GL_MAJOR_VERSION
					glGetIntegerv (GL_MAJOR_VERSION, &version);
					#endif
```

**Comment by jgranick** [comment]
Fixed in latest Lime :smile:
