### ISSUE TITLE
Crash when returning to home screen on AppleTV

### ISSUE THREAD

**Issue by grapefrukt** [openfl/lime#619]
When pressing the Home button on the remote, the app goes into the background and immediately crashes on [line 148 in OpenGLBindings.cpp](https://github.com/openfl/lime/blob/b6d4093e6b7c4c1bfaa63af53faf4cc3dd862950/project/src/graphics/opengl/OpenGLBindings.cpp#L148)

![screenshot 2015-11-05 14 45 26](https://cloud.githubusercontent.com/assets/158901/10970062/78c038c0-83cc-11e5-9b55-ded3db02c5ef.png)

This is running development builds of OpenFL, Lime and hxcpp.

I'm not entirely sure if this crash is on OpenFL or Lime, but it since Lime touches it last I figured I'd start here.

**Comment by MattTuttle** [comment]
This is definitely related to Lime since it happened to me in HaxePunk as well, using only Lime. I haven't looked too deeply into it but we may need some error handling when the GL context is lost.

**Comment by jgranick** [comment]
This sounds like calling a render() callback when the GL context is actually lost? I thought we had some handling for this, but maybe the events aren't fired in the correct order for Apple TV, or something like that (or some implied render() that triggers too soon?)

**Comment by jgranick** [comment]
Recently resolved an issue like this on iOS, when switching to/from the background. Let me know if there are more issues :smile:
