### ISSUE TITLE
SDL Exposed and Size Changed events force a re-render.

### ISSUE THREAD

**Issue by mauvecow** [openfl/lime#625]
When the SDL receives an exposed or size changed event, it forces a re-render, which also triggers an Event.ENTER_FRAME. This will disrupt the requested stage frame rate, causing your program to run faster than normal. (eg, if I wave another window on top of an existing one, it runs at hyperspeed while redraws are forced.)

From project/src/backend/sdl/SDLApplication.cpp :

```
 case SDL_WINDOWEVENT_EXPOSED:                                   
         RenderEvent::Dispatch (&renderEvent);                                   
         break;                                   
 case SDL_WINDOWEVENT_SIZE_CHANGED:                                   
         ProcessWindowEvent (event);                                   
         RenderEvent::Dispatch (&renderEvent);                                   
         break;
```

While it's probably correct behavior to force a redraw, it also disrupts the requested frame rate, which  might be more preferable to maintain to ensure consistency of one ENTER_FRAME ~= one update cycle (barring slowdown). Your call here.

**Comment by jgranick** [comment]
I'm not sure this avoidable at the moment, but it is a really good point. I've opened another issue to continue to track this for now https://github.com/openfl/openfl/issues/1425

Thanks :smile:

**Comment by jgranick** [comment]
For Lime applications, I believe the separate `update` and `render` methods should help handle this abstraction -- I think we need to draw again due to the OS action, but logically we haven't moved to the next update yet
