### ISSUE TITLE
Webfonts generation doesn't work without -verbose

### ISSUE THREAD

**Issue by slavasitnikov** [openfl/lime#628]
when i run `haxelib run openfl build html5` i see 

```
Warning: Could not find generated font file "assets/fonts/common/AeroMatics-Bold.eot"
Warning: Could not find generated font file "assets/fonts/common/AeroMatics-Bold.woff"
Warning: Could not find generated font file "assets/fonts/common/AeroMatics-Bold.svg"
...
```

if run `haxelib run openfl build html5 -verbose` fonts are generated

generateWebfonts is different for verbose and not verbose. Maybe `ProcessHelper.runProcess ("", webify, [ FileSystem.fullPath (font.sourcePath) ], true, true, true);`  in https://github.com/openfl/lime/blob/master/lime/tools/helpers/HTML5Helper.hx#L83 throw error

**Comment by jgranick** [comment]
This appears to work with the font from here:

http://www.dafont.com/aero-matics.font

It must have been a fluke? 😕
