### ISSUE TITLE
Chrome Native Client

### ISSUE THREAD

**Issue by NekR** [openfl/lime#643]
Any plans to support [Chrome Native Client](https://developer.chrome.com/native-client)? Or it's already supported?

**Comment by ibilon** [comment]
Didn't google drop that?

I don't think we support that or that it's planned.

**Comment by jgranick** [comment]
According to Wikipedia, "On October 12, 2016, a comment on the Chromium issue tracker indicated that Google's Pepper and Native Client teams had been destaffed."

We'll keep investing in HTML5, and keep our eyes on parallel technologies such as Emscripten (which are promising but result in worse performance than standard HTML5 builds for us) :smile:
