### ISSUE TITLE
__fromBytes Function Missing In lime.Assets.hx

### ISSUE THREAD

**Issue by MrJman006** [openfl/lime#650]
lime.Assets.hx is missing a function '__fromBytes' that takes what looks like a ByteArray to process it.

**Comment by ibilon** [comment]
These are really disturbing but are macro reified functions that aren't called on-site but will be used to generate the asset.

**Comment by jgranick** [comment]
I think this might have been a mismatch between OpenFL and the old OpenFL legacy code. OpenFL has an internal "__fromBytes" method on a number of different types, which legacy did not :smile:
