### ISSUE TITLE
BitmapData.setPixels not using the current position of the ByteArray

### ISSUE THREAD

**Issue by juakob** [openfl/lime#654]
The current BitmapData.setPixels expects just the data of your pixels, in flash or in legacy you could use the postition of the ByteArray to indicate from where it should start reading.

**Comment by ibilon** [comment]
That should be in openfl, but actually openfl's setPixels just call lime's.

https://github.com/openfl/lime/blob/develop/lime/graphics/utils/ImageDataUtil.hx#L1047
https://github.com/openfl/lime/blob/75bb6905af1b64b01af68892134afc00550846e0/project/src/graphics/utils/ImageDataUtil.cpp#L586

According to http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/BitmapData.html#setPixels%28%29 it calls `ByteArray.readUnsignedInt()` so I guess position should be taken into account.
At least for openfl.

**Comment by jgranick** [comment]
This issue was moved to openfl/openfl#1426
