### ISSUE TITLE
Investigate ANGLE support for DirectX targets (Windows 8 tablet, Windows Phone 8, Xbox)

### ISSUE THREAD

**Issue by jgranick** [openfl/lime#66]

**Comment by jarkkosyrjala** [comment]
Here's how Kha does this (for reference): https://github.com/KTXSoftware/Kha/wiki/Tools#kfx

**Comment by jgranick** [comment]
This is interesting: https://hg.libsdl.org/SDL/file/tip/docs/README-winrt.md

**Comment by jgranick** [comment]
Not going to track TODO items as issues :smile:
