### ISSUE TITLE
Lime Error; Targetting to Flash & HTML5, 2.8.3

### ISSUE THREAD

**Issue by moshefeit** [openfl/lime#670]
Can't target Flash and HTML5, everytime, it always gave me error.

```
C:/HaxeToolkit/haxe/lib/lime/2,8,3/lime/Assets.hx:1182: characters 71-75 : Array<{ type : haxe.macro.ComplexType, opt : Bool, name : String }> should be Array<haxe.macro.FunctionArg>
C:/HaxeToolkit/haxe/lib/lime/2,8,3/lime/Assets.hx:1182: characters 71-75 : Type parameters are invariant
C:/HaxeToolkit/haxe/lib/lime/2,8,3/lime/Assets.hx:1182: characters 71-75 : { type : haxe.macro.ComplexType, opt : Bool, name : String } should be haxe.macro.FunctionArg
C:/HaxeToolkit/haxe/lib/lime/2,8,3/lime/Assets.hx:1182: characters 71-75 : { type : haxe.macro.ComplexType, opt : Bool, name : String } should be { ?value : Null<haxe.macro.Expr>, type : Null<haxe.macro.ComplexType>, ?opt : Bool, name : String }
C:/HaxeToolkit/haxe/lib/lime/2,8,3/lime/Assets.hx:1182: characters 71-75 : { type : haxe.macro.ComplexType, opt : Bool, name : String } has no field value
C:/HaxeToolkit/haxe/lib/lime/2,8,3/lime/text/Font.hx:25: characters 2-11 : Build failure
```

The related code with this error is The `args` in this function:

> fields.push ({ name: "new", access: [ APublic ], kind: FFun({ args: **args**, expr: constructor, params: [], ret: null }), pos: Context.currentPos () });

https://gist.github.com/moshefeit/aaddc49566be820437cf.js

```
macro public static function embedBytes ():Array<Field> {

            var fields = embedData (":file");

            #if lime_console
            if (false) {
            #else
            if (fields != null) {
            #end

                var constructor = macro {

                    var bytes = haxe.Resource.getBytes (resourceName);

                    super (bytes.length, bytes.b);

                };

                var args = [ { name: "length", opt: false, type: macro :Int }, { name: "bytesData", opt: false, type: macro :haxe.io.BytesData } ];
                fields.push ({ name: "new", access: [ APublic ], kind: FFun({ args: args, expr: constructor, params: [], ret: null }), pos: Context.currentPos () });

            }

            return fields;
        }
```

**Comment by jgranick** [comment]
Are you using Haxe 3.2 or greater? :smile:

**Comment by moshefeit** [comment]
Ugh. So what version do you recommend? 3.1.x good?

**Comment by moshefeit** [comment]
@jgranick Downgraded to 3.1.x, still getting the same error when debug to Flash.

**Comment by jgranick** [comment]
Oh no! I meant the opposite. Haxe 3.2 or greater is what we recommend -- sometimes there are problems when using an old (Haxe 3.1) release, and sometimes when using development releases (Haxe 3.3) there are issues, though we try to remain compatible with the current public release and address dev build issues as we can :smile:

**Comment by moshefeit** [comment]
@jgranick Hmm, weird it is then. Before downgraded, I was using 3.2.0, debug to flash is working but not to HTML5 - was fine, because HTML5 is not my target. Then later, I did `haxelib upgrade', so Lime upgraded to the latest version, and....now can't debug to Flash either.

I will try to reinstall Haxe tho' for the last option.
