### ISSUE TITLE
lime 2.8.3 crashes neko when using some features of opengl

### ISSUE THREAD

**Issue by RuiCuco** [openfl/lime#671]
Try the command

openfl test neko

on the SimpleOpenGLView sample and it crashes. I don't know why.

**Comment by RuiCuco** [comment]
lime 2.9.0 has the same problem. It can build projects for neko, but when running those projects with the command (for the SimpleImage sample, for example)

lime test neko

it gives a segmentation fault. As far as I can see, it's a problem with the OpenGL layer (Cairo works fine). I'm using Ubuntu 14.04 LTS on an Asus Eee-PC with a GMA GPU. The version I had installed previously worked fine, but I can't remember which one it was.

**Comment by jgranick** [comment]
So `--window-hardware=false` works, and the "HelloWorld" sample works alright in OpenGL? So once it tries to load and display a texture, it has an issue?

**Comment by RuiCuco** [comment]
Yes, window-hardware false works, Cairo works. But "HelloWorld" sample doesn't work in OpenGL, that is with window-hardware true. With window-hardware true, I tried putting a trace("just started render function of HelloWorld sample") at the start of the render function, just before the switch, but that doesn't get printed - it's just a segmentation fault. However, "Hello World" in the constructor does get printed. After that, it's just the segmentation fault.

**Comment by jgranick** [comment]
I believe we use `SDL_GL_GetProcAddress` to get references to the system OpenGL library. Can you tell if OpenGL 2 features (such as shaders) work on anything else on the system? Does WebGL work?

**Comment by RuiCuco** [comment]
Well, the sample "SimpleOpenGLView" (which contains some rather simple shaders) from the 'nme' haxelib package works (compiled with nme, not lime). WebGL works, but the GPU is just too weak to do anything useful. The problem seems that the function 'render' doesn't even get called - Neko crashes before that happens. I've attached a file with the last few lines of the output of the command

valgrind ./HelloWorld

Perhaps that helps.

[log.txt](https://github.com/openfl/lime/files/108275/log.txt)

**Comment by RuiCuco** [comment]
I've gone over to http://www.openfl.org/builds/lime/ and tried some of the older builds. The following and previous builds work:

lime-2.6.9.zip

The following and subsequent don't work:

lime-2.6.9-7-g83e0bd4.zip

Something was changed in the combination of Neko/Linux/OpenGL code that causes the error. I forgot to say I'm running 32-bits Ubuntu, but I've seen reports of also failing in 64-bits versions.

The window where the rendering is to occur does appear, but only for about half a second or so. Then it disappears and the program crashes.
