### ISSUE TITLE
Safari embeded images not loaded

### ISSUE THREAD

**Issue by iskolbin** [openfl/lime#675]
Embeded images working in Safari with Lime 2.8.2, but broken in 2.8.3. Culprit is 

``` haxe
image.crossOrigin = "Anonymous";
```

in **lime/graphics/Image.hx**, see this commit: 
https://github.com/openfl/lime/commit/603457892c3c71e1b6a06a9cad575c2a6b67698c

**Comment by ibilon** [comment]
Linked to https://github.com/openfl/lime/pull/697
