### ISSUE TITLE
libc.so not found

### ISSUE THREAD

**Issue by NekR** [openfl/lime#685]
![image](https://cloud.githubusercontent.com/assets/1189265/12694615/c7dbfbb2-c73b-11e5-9fc5-de9b9721c46c.png)

**Comment by jgranick** [comment]
This is resolved with current releases, and NDK 12 or newer :smile:

**Comment by nightblade9** [comment]
I seem to be running into the same issue with the latest version of stuff. Where did I go amiss? Here are the different versions of things I tried:

Haxe version: 3.4.4, 3.4.7
Flixel version: 4.5.1, 4.6.0
OpenFL version: 8.6.4
Lime version: 7.1.1, 7.2.1
HXCPP version: 3.4.49
Android NDK: 8b, 15c, 19c

**Comment by jgranick** [comment]
What Android NDK is being used in your build?

**Comment by Gama11** [comment]
I think the implication is that he has tried all three of them.

**Comment by nightblade9** [comment]
Correct. I tried multiple versions of everything; with the current stack of the latest-everything, I tried NDK 8b, 19c, and 15c (in that order).

**Comment by nightblade9** [comment]
Does anyone have any suggestions how I can fix this?

Shall I open a separate issue for this?

**Comment by nightblade9** [comment]
This is blocking me from releasing my app.

@jgranick / @Gama11 , could either of you (assuming you have a working environment and can build APKs and run them successfully) please give me a full list of all software with versions?

- Haxe, HXCPP, and Android NDK
- OpenFL, Lime, and (ideally) Flixel versions too
