### ISSUE TITLE
Incorrect version haxedef with haxelib dev and explicit versions

### ISSUE THREAD

**Issue by Gama11** [openfl/lime#686]
To reproduce, first enable the dev directory for a haxelib (side note: this happens implicitly when a lib is downloaded via `haxelib git`).

```
C:\>haxelib list openfl
openfl: 3.1.0 3.3.3 3.5.3 [3.6.0] git

C:\>haxelib dev openfl C:\HaxeToolkit\haxe\lib\openfl\3,6,0
Development directory set to C:\HaxeToolkit\haxe\lib\openfl\3,6,0

C:\>haxelib list openfl
openfl: 3.1.0 3.3.3 3.5.3 3.6.0 git [dev:C:\HaxeToolkit\haxe\lib\openfl\3,6,0]
```

Then specify a _different_ version in the include tag for that haxelib:

```xml
<haxelib name="openfl" version="3.5.3" />
```

The resulting `debug.hxml` contains this:

```
-cp C:/HaxeToolkit/haxe/lib/openfl/3,6,0
-D openfl=3.6.0
-D openfl=3.5.3
```

As you'd expect, the last `-D` has precedence, meaning the version define is inconsistent with the actual classpath in this case.

**Comment by ibilon** [comment]
Seems fixed,
I think by https://github.com/openfl/lime/commit/ac0085908c077a656ba99a4df542defcd9143274 but not sure.
