### ISSUE TITLE
GCController not found on ios

### ISSUE THREAD

**Issue by TBaudon** [openfl/lime#688]
Hello, 
just bought a mac and triied to build some project on a fresh install of all latest haxelib and I get a linking error from sdl which is not finding GCController.

I targeted simulator, I don't know if the problem occurs on other target, can't test it yet.

The problem is easy to solve though, all I had to do is adding the GameController.framework to the xcode project.

Thanks

**Comment by mikkelmr** [comment]
This pull request seems to fix the problem https://github.com/openfl/lime/pull/689.

So if it gets accepted, the problem should be fixed.
