### ISSUE TITLE
Issue with handleWindowEvent

### ISSUE THREAD

**Issue by Skoo120** [openfl/lime#691]
On Lime 2.90.
Getting error:

```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
    at lime._backend.flash::FlashApplication/handleWindowEvent()
```

On debug, 
this.parent is available as openfl.display.Application,
this.parent.window is null.

Running this within Flash environment.

**Comment by jgranick** [comment]
I believe this is fixed, but please let me know if there continue to be any issues :smile:
