### ISSUE TITLE
heap corruption detected by dlmalloc

### ISSUE THREAD

**Issue by hpgood** [openfl/lime#692]
when i load image many times, it always crash by "heap corruption detected by dlmalloc".
comand:
openfl test -x -v -Dnext -debug

F/libc    ( 2604): heap corruption detected by dlmalloc
F/libc    ( 2604): Fatal signal 6 (SIGABRT) at 0x00000a2c (code=-6), thread 2619 (SDLThread)
I/DEBUG   (  186): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
I/DEBUG   (  186): Build fingerprint: 'Xiaomi/mocha/mocha:4.4.4/KTU84P/V6.4.2.0.KXFCNCB:user/release-keys'
I/DEBUG   (  186): Revision: '0'
I/DEBUG   (  186): pid: 2604, tid: 2619, name: SDLThread  >>> com.test.demo.DemoApp <<<
I/DEBUG   (  186): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
I/DEBUG   (  186): Abort message: 'heap corruption detected by dlmalloc'
I/DEBUG   (  186):     r0 00000000  r1 00000a3b  r2 00000006  r3 00000000
I/DEBUG   (  186):     r4 00000006  r5 0000000b  r6 00000a3b  r7 0000010c
I/DEBUG   (  186):     r8 71c3c0a0  r9 00000001  sl 6f465038  fp 71c3c068
I/DEBUG   (  186):     ip 71c3c100  sp 71c3bf68  lr 4009d021  pc 400abf88  cpsr 00030010
I/DEBUG   (  186):     d0  636f6c6c616d6c64  d1  206e6f6974707562
I/DEBUG   (  186):     d2  000003e800000079  d3  0000000400000020
I/DEBUG   (  186):     d4  4b40812f4b400000  d5  4b40000046180400
I/DEBUG   (  186):     d6  000000014b402601  d7  3ff0000000000000
I/DEBUG   (  186):     d8  0000000000000000  d9  0000000000000000
I/DEBUG   (  186):     d10 0000000000000000  d11 0000000000000000
I/DEBUG   (  186):     d12 0000000000000000  d13 0000000000000000
I/DEBUG   (  186):     d14 0000000000000000  d15 0000000000000000
I/DEBUG   (  186):     d16 0000000000000002  d17 0000000000000001
I/DEBUG   (  186):     d18 0000000000000000  d19 4088000000000000
I/DEBUG   (  186):     d20 3ff0000000000000  d21 4088000000000000
I/DEBUG   (  186):     d22 409f380000000000  d23 408f380000000000
I/DEBUG   (  186):     d24 3ff0000000000000  d25 408f380000000000
I/DEBUG   (  186):     d26 3fdcdd9f8f922e98  d27 3f81766656057e93
I/DEBUG   (  186):     d28 3fccdd9f8f922e98  d29 3fd0000000000000
I/DEBUG   (  186):     d30 0000000000000001  d31 4000000000000000
I/DEBUG   (  186):     scr 60000010
I/DEBUG   (  186):
I/DEBUG   (  186): backtrace:
I/DEBUG   (  186):     #00  pc 00021f88  /system/lib/libc.so (tgkill+12)
I/DEBUG   (  186):     #01  pc 0001301d  /system/lib/libc.so (pthread_kill+48)
I/DEBUG   (  186):     #02  pc 00013231  /system/lib/libc.so (raise+10)
I/DEBUG   (  186):     #03  pc 00011f67  /system/lib/libc.so
I/DEBUG   (  186):     #04  pc 0002183c  /system/lib/libc.so (abort+4)
I/DEBUG   (  186):     #05  pc 00012a4d  /system/lib/libc.so
I/DEBUG   (  186):     #06  pc 0000f16d  /system/lib/libc.so
I/DEBUG   (  186):     #07  pc 00010071  /system/lib/libc.so (dlmalloc+604)
I/DEBUG   (  186):     #08  pc 0000dc4b  /system/lib/libc.so (malloc+10)
I/DEBUG   (  186):     #09  pc 0000091b  /system/lib/libstdc++.so (operator new(unsigned int)+2)
I/DEBUG   (  186):     #10  pc 00021183  /system/lib/libbinder.so (android::Parcel::read(android::Parcel::FlattenableHelperInterface&) const+44)
I/DEBUG   (  186):     #11  pc 0002aacf  /system/lib/libgui.so
I/DEBUG   (  186):     #12  pc 0002ea0b  /system/lib/libgui.so (android::Surface::dequeueBuffer(ANativeWindowBuffer**, int_)+98)
I/DEBUG   (  186):     #13  pc 0002e051  /system/lib/libgui.so (android::Surface::hook_dequeueBuffer(ANativeWindow_, ANativeWindowBuffer**, int_)+10)
I/DEBUG   (  186):     #14  pc 0000318b  /system/vendor/lib/libnvwsi.so
I/DEBUG   (  186):     #15  pc 000028a1  /system/vendor/lib/libnvwsi.so
I/DEBUG   (  186):     #16  pc 000030af  /system/vendor/lib/libnvglsi.so (_nv067glsi+182)
I/DEBUG   (  186):     #17  pc 00042d53  /system/vendor/lib/libEGL_tegra_impl.so
I/DEBUG   (  186):     #18  pc 00044c3d  /system/vendor/lib/libEGL_tegra_impl.so
I/DEBUG   (  186):     #19  pc 00044df1  /system/vendor/lib/libEGL_tegra_impl.so
I/DEBUG   (  186):     #20  pc 00014a0d  /system/vendor/lib/libEGL_tegra_impl.so
I/DEBUG   (  186):     #21  pc 00015c83  /system/vendor/lib/libEGL_tegra_impl.so
I/DEBUG   (  186):     #22  pc 0000147f  /system/lib/egl/libEGL_tegra.so (eglSwapBuffers+18)
I/DEBUG   (  186):     #23  pc 0000ec9d  /system/lib/libEGL.so (eglSwapBuffers+284)
I/DEBUG   (  186):     #24  pc 002f7580  /data/app-lib/com.test.demo.DemoApp-1/liblime.so
I/DEBUG   (  186):     #25  pc 002e1e90  /data/app-lib/com.test.demo.DemoApp-1/liblime.so
I/DEBUG   (  186):     #26  pc 002a7d48  /data/app-lib/com.test.demo.DemoApp-1/liblime.so
I/DEBUG   (  186):     #27  pc 00297df8  /data/app-lib/com.test.demo.DemoApp-1/liblime.so (SDL_RenderPresent+16)
I/DEBUG   (  186):     #28  pc 00035748  /data/app-lib/com.test.demo.DemoApp-1/liblime.so
I/DEBUG   (  186):     #29  pc 004bb474  /data/app-lib/com.test.demo.DemoApp-1/libApplicationMain.so (lime::_backend::native::NativeRenderer_obj::flip()+464)
I/DEBUG   (  186):
I/DEBUG   (  186): stack:
I/DEBUG   (  186):          71c3bf28  6f465050  /dev/binder
I/DEBUG   (  186):          71c3bf2c  401463cb  /system/lib/libbinder.so (android::Parcel::freeDataNoInit()+30)
I/DEBUG   (  186):          71c3bf30  71c3c0a0  [stack:2619]
I/DEBUG   (  186):          71c3bf34  6f465028  /dev/binder
I/DEBUG   (  186):          71c3bf38  00000028
I/DEBUG   (  186):          71c3bf3c  71c3c0a0  [stack:2619]
I/DEBUG   (  186):          71c3bf40  00000001
I/DEBUG   (  186):          71c3bf44  40146413  /system/lib/libbinder.so (android::Parcel::ipcSetDataReference(unsigned char const_, unsigned int, unsigned int const_, unsigned int, void (_)(android::Parcel_, unsigned char const_, unsigned int, unsigned int const_, unsigned int, void_), void*)+26)
I/DEBUG   (  186):          71c3bf48  71c3c0a0  [stack:2619]
I/DEBUG   (  186):          71c3bf4c  6f465028  /dev/binder
I/DEBUG   (  186):          71c3bf50  00000000
I/DEBUG   (  186):          71c3bf54  728a5498  [anon:libc_malloc]
I/DEBUG   (  186):          71c3bf58  71c3c0a0  [stack:2619]
I/DEBUG   (  186):          71c3bf5c  00000000
I/DEBUG   (  186):          71c3bf60  728a54c8  [anon:libc_malloc]
I/DEBUG   (  186):          71c3bf64  00000000
I/DEBUG   (  186):     #00  71c3bf68  00000006
I/DEBUG   (  186):          71c3bf6c  0000000b
I/DEBUG   (  186):          71c3bf70  00000a3b
I/DEBUG   (  186):          71c3bf74  71c3c100  [stack:2619]
I/DEBUG   (  186):          71c3bf78  71c3c100  [stack:2619]
I/DEBUG   (  186):          71c3bf7c  4009d021  /system/lib/libc.so (pthread_kill+52)
I/DEBUG   (  186):     #01  71c3bf80  00000006
I/DEBUG   (  186):          71c3bf84  00000000
I/DEBUG   (  186):          71c3bf88  735d2a58  [anon:libc_malloc]
I/DEBUG   (  186):          71c3bf8c  4009d235  /system/lib/libc.so (raise+14)
I/DEBUG   (  186):     #02  71c3bf90  71c3bf9c  [stack:2619]
I/DEBUG   (  186):          71c3bf94  4009bf6b  /system/lib/libc.so
I/DEBUG   (  186):
I/DEBUG   (  186): memory near r8:
I/DEBUG   (  186):     71c3c080 00000064 00000000 00000000 00000000
I/DEBUG   (  186):     71c3c090 00000000 00010001 00000000 00000001
I/DEBUG   (  186):     71c3c0a0 00000000 6f465028 00000028 00000028
I/DEBUG   (  186):     71c3c0b0 00000014 6f465050 00000001 00000001
I/DEBUG   (  186):     71c3c0c0 00000000 3f010101 40143295 728a5498
I/DEBUG   (  186):     71c3c0d0 402dba35 00000000 71b3a710 71c3c154
I/DEBUG   (  186):     71c3c0e0 71c3c150 402dfa0d 00000600 000007ce
I/DEBUG   (  186):     71c3c0f0 00000004 00000200 726c9328 71b3aad0
I/DEBUG   (  186):     71c3c100 00000000 73626358 00000002 00000000
I/DEBUG   (  186):     71c3c110 00000000 72e4e7a0 71c3c2b8 00000000
I/DEBUG   (  186):     71c3c120 71c3c1cc ffffffff 71c3c318 402df053
I/DEBUG   (  186):     71c3c130 402df047 6ff6818d 00000001 73014008
I/DEBUG   (  186):     71c3c140 00000000 71c3c220 71c3c1d0 400d8384
I/DEBUG   (  186):     71c3c150 00000000 ffffffff 72e69000 71411c90
I/DEBUG   (  186):     71c3c160 00000000 00000002 00000040 72e69000
I/DEBUG   (  186):     71c3c170 73547910 00000004 0000007f 667d4709
I/DEBUG   (  186):
I/DEBUG   (  186): memory near sl:
I/DEBUG   (  186):     6f465018 00000000 00000000 00000028 00000004
I/DEBUG   (  186):     6f465028 00000000 00000001 00000001 00000001
I/DEBUG   (  186):     6f465038 00000001 66642a85 0000017f 00000068
I/DEBUG   (  186):     6f465048 00000001 00000000 00000014 d2bc1840
I/DEBUG   (  186):     6f465058 f4e00000 00000001 00000000 00000000
I/DEBUG   (  186):     6f465068 00000001 00000000 00000003 00000001
I/DEBUG   (  186):     6f465078 ffffffff 00000004 7f6e5185 5e555c4f
I/DEBUG   (  186):     6f465088 00000000 00000600 00000800 00000600
I/DEBUG   (  186):     6f465098 000005ce 00000800 000007ce 00000600
I/DEBUG   (  186):     6f4650a8 00000800 00000000 00000000 00000000
I/DEBUG   (  186):     6f4650b8 00000000 00000000 42700c93 00000140
I/DEBUG   (  186):     6f4650c8 43a28f5c 43a28f5c 00000000 ffffffff
I/DEBUG   (  186):     6f4650d8 00100100 00200200 00000001 00000000
I/DEBUG   (  186):     6f4650e8 00000000 ffffffff 00100100 00200200
I/DEBUG   (  186):     6f4650f8 00000001 00000000 00000000 00000001
I/DEBUG   (  186):     6f465108 00000001 00000001 00000001 66642a85
I/DEBUG   (  186):
I/DEBUG   (  186): memory near fp:
I/DEBUG   (  186):     71c3c048 71c3c100 00000001 71c3c318 71c3c1f0
I/DEBUG   (  186):     71c3c058 71c3c2e8 402dbad3 00000000 726c8ccc
I/DEBUG   (  186):     71c3c068 402e77b8 73626358 00000000 74340160
I/DEBUG   (  186):     71c3c078 00000064 00000078 00000064 00000000
I/DEBUG   (  186):     71c3c088 00000000 00000000 00000000 00010001
I/DEBUG   (  186):     71c3c098 00000000 00000001 00000000 6f465028
I/DEBUG   (  186):     71c3c0a8 00000028 00000028 00000014 6f465050
I/DEBUG   (  186):     71c3c0b8 00000001 00000001 00000000 3f010101
I/DEBUG   (  186):     71c3c0c8 40143295 728a5498 402dba35 00000000
I/DEBUG   (  186):     71c3c0d8 71b3a710 71c3c154 71c3c150 402dfa0d
I/DEBUG   (  186):     71c3c0e8 00000600 000007ce 00000004 00000200
I/DEBUG   (  186):     71c3c0f8 726c9328 71b3aad0 00000000 73626358
I/DEBUG   (  186):     71c3c108 00000002 00000000 00000000 72e4e7a0
I/DEBUG   (  186):     71c3c118 71c3c2b8 00000000 71c3c1cc ffffffff
I/DEBUG   (  186):     71c3c128 71c3c318 402df053 402df047 6ff6818d
I/DEBUG   (  186):     71c3c138 00000001 73014008 00000000 71c3c220
I/DEBUG   (  186):
I/DEBUG   (  186): memory near ip:
I/DEBUG   (  186):     71c3c0e0 71c3c150 402dfa0d 00000600 000007ce
I/DEBUG   (  186):     71c3c0f0 00000004 00000200 726c9328 71b3aad0
I/DEBUG   (  186):     71c3c100 00000000 73626358 00000002 00000000
I/DEBUG   (  186):     71c3c110 00000000 72e4e7a0 71c3c2b8 00000000
I/DEBUG   (  186):     71c3c120 71c3c1cc ffffffff 71c3c318 402df053
I/DEBUG   (  186):     71c3c130 402df047 6ff6818d 00000001 73014008
I/DEBUG   (  186):     71c3c140 00000000 71c3c220 71c3c1d0 400d8384
I/DEBUG   (  186):     71c3c150 00000000 ffffffff 72e69000 71411c90
I/DEBUG   (  186):     71c3c160 00000000 00000002 00000040 72e69000
I/DEBUG   (  186):     71c3c170 73547910 00000004 0000007f 667d4709
I/DEBUG   (  186):     71c3c180 73547910 7177d0f8 71c3c2b8 71c3c1f0
I/DEBUG   (  186):     71c3c190 6ff68145 72e4e7a0 71c3c318 00000000
I/DEBUG   (  186):     71c3c1a0 71c3c2e8 6ff678a3 00000000 71c3c1d0
I/DEBUG   (  186):     71c3c1b0 71c3c1cc 00000000 71c3c224 00000000
I/DEBUG   (  186):     71c3c1c0 73547910 00000000 71f314b4 00000000
I/DEBUG   (  186):     71c3c1d0 71c3c1e0 7230c3e8 726bf5b8 71ae0d88
I/DEBUG   (  186):
I/DEBUG   (  186): memory near sp:
I/DEBUG   (  186):     71c3bf48 71c3c0a0 6f465028 00000000 728a5498
I/DEBUG   (  186):     71c3bf58 71c3c0a0 00000000 728a54c8 00000000
I/DEBUG   (  186):     71c3bf68 00000006 0000000b 00000a3b 71c3c100
I/DEBUG   (  186):     71c3bf78 71c3c100 4009d021 00000006 00000000
I/DEBUG   (  186):     71c3bf88 735d2a58 4009d235 71c3bf9c 4009bf6b
I/DEBUG   (  186):     71c3bf98 00000000 ffffffdf 000003e8 00000028
I/DEBUG   (  186):     71c3bfa8 00000004 6f465028 6f465050 400d81b8
I/DEBUG   (  186):     71c3bfb8 402efc78 400ab840 667d4709 4009ca51
I/DEBUG   (  186):     71c3bfc8 400ca41b 71c3bfdc ffffff60 40099171
I/DEBUG   (  186):     71c3bfd8 400ca41b 400cdfc0 ffffff60 400d8378
I/DEBUG   (  186):     71c3bfe8 72e38748 4009a075 00000004 00e8a0fc
I/DEBUG   (  186):     71c3bff8 40099e15 00000001 402efc78 71c3c104
I/DEBUG   (  186):     71c3c008 71c3c100 71c3c0a0 00000001 6f465038
I/DEBUG   (  186):     71c3c018 71c3c068 40097c4d 71c3c0a0 400e591f
I/DEBUG   (  186):     71c3c028 71c3c0a0 40147187 71c3c0a0 71c3c068
I/DEBUG   (  186):     71c3c038 00000000 73626358 402efc78 71c3c104
I/DEBUG   (  186):
I/DEBUG   (  186): code around pc:
I/DEBUG   (  186):     400abf68 e8bd00f0 e3700a01 912fff1e e2600000
I/DEBUG   (  186):     400abf78 ea006f79 e92d50f0 e3a07f43 ef000000
I/DEBUG   (  186):     400abf88 e8bd50f0 e3700a01 912fff1e e2600000
I/DEBUG   (  186):     400abf98 ea006f71 e92d50f0 e3a070ee ef000000
I/DEBUG   (  186):     400abfa8 e8bd50f0 e3700a01 912fff1e e2600000
I/DEBUG   (  186):     400abfb8 ea006f69 00000000 e1520003 8a0000ab
I/DEBUG   (  186):     400abfc8 f5d1f040 e92d4001 e3520000 11500001
I/DEBUG   (  186):     400abfd8 08bd8001 f5d1f000 f5d1f040 e3520020
I/DEBUG   (  186):     400abfe8 3a00008f e3520080 3a000084 e2603000
I/DEBUG   (  186):     400abff8 e213303f 0a000015 e0422003 e1b0cf83
I/DEBUG   (  186):     400ac008 44d1c001 44c0c001 24d1c001 24c0c001
I/DEBUG   (  186):     400ac018 24d1c001 24c0c001 e1b0ce83 5a000001
I/DEBUG   (  186):     400ac028 f4a1030d f480031d 3a000001 f421070d
I/DEBUG   (  186):     400ac038 f400071d e1b0cd83 5a000001 f4210a0d
I/DEBUG   (  186):     400ac048 f4000a2d 3a000001 f421020d f400023d
I/DEBUG   (  186):     400ac058 f5d1f080 f5d1f0c0 e3520902 3a000004
I/DEBUG   (  186):
I/DEBUG   (  186): code around lr:
I/DEBUG   (  186):     4009d000 447b4b13 42b3e010 4812d10e 44786a1e
I/DEBUG   (  186):     4009d010 ec90f7fb e9d8f00d 46224631 efaef00e
I/DEBUG   (  186):     4009d020 d00a3001 e00b2400 2b00681b 480ad1eb
I/DEBUG   (  186):     4009d030 44782403 ec7ef7fb f001e002 6804fa1b
I/DEBUG   (  186):     4009d040 fa18f001 46206005 bf00bd70 0003b3a2
I/DEBUG   (  186):     4009d050 0003b396 0003b38e 0003b36a bf7ef7ff
I/DEBUG   (  186):     4009d060 4a3e4b3d 43f0e92d 4606b08b 447b460d
I/DEBUG   (  186):     4009d070 6823589c 930946a1 f9fcf001 8000f8d0
I/DEBUG   (  186):     4009d080 d0482d00 f0104628 280ff80b d8444604
I/DEBUG   (  186):     4009d090 ffe4f7ff d1064286 4629200f e8a2f00d
I/DEBUG   (  186):     4009d0a0 d03c2800 482ee02e f7fb4478 482debc2
I/DEBUG   (  186):     4009d0b0 e0154478 d11342b0 482b6a06 f7fb4478
I/DEBUG   (  186):     4009d0c0 4a2aec3a 46332120 447aa801 fc24f013
I/DEBUG   (  186):     4009d0d0 a8012101 ff22f01a 46061c42 e011d104
I/DEBUG   (  186):     4009d0e0 28006800 e02cd1e6 46294630 f00d4622
I/DEBUG   (  186):     4009d0f0 1c43e8de d11e4607 f9bcf001 29046801

**Comment by jgranick** [comment]
I believe this works properly with recent builds
