### ISSUE TITLE
System.exit() either doesn't compile or crashes

### ISSUE THREAD

**Issue by programmador** [openfl/lime#699]
If I write lime.system.System.exit(0), the lime's behaviour will be next:

1. For windows target visualcpp fails to compile and writes:
`__some_forgotten_text_here__ symbol to the left of a '::' must be a type`

2. For linux target gcc fails to compile and writes:
`Information:./src/MenuState.cpp:376:5: error: ‘::lime’ has not been declared`

3. For neko target it does compile but instead of exiting it actualy crashes:
```
Invalid field access : exit
Called from MenuState.hx line 95
Called from flixel/ui/FlxButton.hx line 516
Called from flixel/ui/FlxButton.hx line 502
Called from openfl/_legacy/events/EventDispatcher.hx line 98
Called from a C function
Called from openfl/_legacy/display/DisplayObject.hx line 258
Called from openfl/_legacy/display/Stage.hx line 944
Called from openfl/_legacy/display/Stage.hx line 417
AL lib: (EE) alc_cleanup: 1 device not closed
FlixelTut: ./lib/openal/Alc/helpers.c:363: EnterCriticalSection: Assertion `ret == 0' failed.
Aborted (core dumped)
```

**Comment by programmador** [comment]
Oh, I forgot. Here's that line from generated cpp file (MenuState.cpp):
`::lime::_system::System_obj::exit((int)0);`

**Comment by ibilon** [comment]
Can't use lime classes on an openfl legacy project.
