### ISSUE TITLE
"lime rebuild windows" does nothing in haxelib version

### ISSUE THREAD

**Issue by vroad** [openfl/lime#712]
I tried building from official source today, but `lime rebuild windows` exited without showing error message. Then I tried `haxelib run hxcpp Build.xml -Dwindows` and it worked.
What is causing this issue? I'm using Visual Studio 2015. hxcpp version is 3.2.205.

**Comment by Gama11** [comment]
Did you manage to solve your issue?

**Comment by vroad** [comment]
Well I just forgot to switch to git repo with haxelib command. It would probably be better to show some error messages when you try to do `lime rebuild` from haxelib version.

`haxelib set lime 2.9.1`
`lime rebuild windows`

outputs nothing.

**Comment by ibilon** [comment]
Like #417

**Comment by jgranick** [comment]
This is intended behavior, `openfl test MyProject windows -rebuild` will walk through and rebuild dependencies, a release version of Lime does not get rebuilt
