### ISSUE TITLE
DPI

### ISSUE THREAD

**Issue by ibilon** [openfl/lime#720]
Now openfl uses information from lime for DPI, (https://github.com/openfl/openfl/issues/718)
but it's not the same as in flash.

For me flash gives 72 and desktop 134.54(...).

Also html5 doesn't have real values, maybe it'd be worth fixing the old code from openfl https://github.com/openfl/openfl/commit/a718b35c0efbc5c9394be7602b647ad3f8e05c51

EDIT: seems to be an issue on android too https://github.com/openfl/lime/issues/369

**Comment by aW4KeNiNG** [comment]
Yes. I have this problem too.

On Android, it reports 72 and it should be 443 (Xperia Z1). The legacy code reports the good value.

**Comment by aW4KeNiNG** [comment]
Any report?

Really i can't jump to OpenFL 3 if it doesn't work. HaxeUI works though dpi to scale the content, and if the result isn't correct, the UI is really small.

**Comment by jgranick** [comment]
We use an SDL API for DPI on native targets. They must not have SDL_GetDisplayDPI implemented on Android. We'll have to decide to either contribute to SDL, or create some workaround.

For the desktop, I suppose the question is whether we want the real DPI or not

**Comment by aW4KeNiNG** [comment]
The legacy code seems to work fine with dpi. I don't know if it should be possible to include those code or it has some dependencies with other useless legacy code. Maybe another reason to avoid using the legacy code in version 3?

**Comment by jgranick** [comment]
Even with newer SDL release versions, I believe this is still unimplemented. I think we'll have to use JNI and get this value ourselves

http://stackoverflow.com/questions/3166501/getting-the-screen-density-programmatically-in-android

**Comment by jgranick** [comment]
I am going to track support for Android DPI values here:

https://github.com/openfl/lime/issues/720

As for desktop, perhaps we should fake the value on the desktop, unless it is a high density display, in which case we'll work in multiples? For the same reason, I am unsure of how we should handle on HTML5, perhaps Lime should implement a measuring algorithm, and OpenFL should (similarly) ignore it and use a constant value for consistency with Flash Player

**Comment by benmerckx** [comment]
#720 is this issue, I think you meant to link to #369
