### ISSUE TITLE
CFFI macro generate static init which is too late

### ISSUE THREAD

**Issue by ibilon** [openfl/lime#724]
CFFI function are generated as

``` haxe
private static function fn (...) = lime.system.CFFI.load (...)
or
private static function fn (...) = new cpp.Callable<...> (...)
```

and they end up being loaded too late to be called from another static variable assignment.

For instance in openfl `static var graphic = new BitmapData(1, 1);`. (https://github.com/openfl/openfl/issues/964)

A solution would be to generate (or fuse) an `__init__` to load these.

**Comment by jgranick** [comment]
This has been resolved by the `NativeCFFI` class internally, but it would be nice to think of a solution in the `lime.system.CFFI` macro (like you mention with `__init__`) if developers use it elsewhere :smile:
