### ISSUE TITLE
develop: lime_drop_event_manager_register throwing EXC_BAD_ACCESS on iOS

### ISSUE THREAD

**Issue by tanis2000** [openfl/lime#733]
I just tried building the SimpleImage example for iOS using the latest develop (lime, hxcpp and haxe) and when I run it with the simulator it throws an exception as detailed in the following screenshot:

![Image of the exception](https://www.evernote.com/shard/s3/sh/c73bf363-4c60-460b-8e4c-f63fd05216e5/ac7850b5deb404e7/res/3c126b88-35b4-4cc6-ba0c-21f243d583eb/skitch.png?resizeSmall&width=832)

**Comment by tanis2000** [comment]
I've encapsulated the offending line in a check like this:

```
		#if (!ios && !android && !tvos)
		lime_drop_event_manager_register (handleDropEvent, dropEventInfo);
		#end
```

and now there's another issue. 

In `SDL_uikitappdelegate.m` it crashes in `main` at the line `UIApplicationMain(argc, argv, nil, [SDLUIKitDelegate getAppDelegateClassName]);`

**Comment by Yanrishatum** [comment]
I may have somewhat same issue actually. But not sure. http://hastebin.com/warolotani.pl
The game loads and runs for a some time, but then it crash with `EXC_BAD_ACCESS`. On a real device.

**Comment by tanis2000** [comment]
@Yanrishatum it does look like something is recursing in the event loop of SDL used by Lime.
At the end it grabs some data and tries to update the status bar and it crashes inside an internal function `vImage::AnyToAnyBlock` (I suppose it's trying to set an image on the status bar).

It might be a totally different issue, though. I'm not sure about it.

BTW I noticed you're working on PocketKingdom :) I didn't know it was written in Haxe. What frameworks are you using, if I may ask?

**Comment by Yanrishatum** [comment]
@tanis2000 As if... Here's another log: http://hastebin.com/wozicafiwo.pl I should've shown this, because stacktrace like that is more frequent.

> What frameworks are you using, if I may ask?

Lime, OFL, HaxePunk (modded to work with OFL3), firetongue (modded), unifill, yagp (my lib), tjson (1.3.0) steamwrap, linc_ogg, hscript, format, format-tiled (my lib), BFont (my lib).

**Comment by tanis2000** [comment]
That still looks like a recursion. I'm having a hard time myself trying to figure out if it's Lime that isn't handling a certain event the correct way and it keeps re-entering the loop or if the problem lies elsewhere. 
From your stacktrace I can tell you that it keeps recursing until it basically runs out of memory and crashes.

Is there any chance you can attach a debugger to that target and check what's going on?

**Comment by jgranick** [comment]
I wonder if this is an HXCPP regression?

The original EXC_BAD_ACCESS comes from Haxe code -- not Lime NDLL code. There's no reason why `dropEventInfo` should throw EXC_BAD_ACCESS, this is only an `addEventListener`-style hook, it does not matter whether iOS or tvOS have drop file events, registering this should just be a non-op in that sense if it never fires.

**Comment by tanis2000** [comment]
I agree with you @jgranick. This shouldn't come from Lime at all. It sounds more like a bad conversion to C++. It would help to be able to have a look at the generated C++ code.

@Yanrishatum can you reproduce the issue with a sample project? What version of Haxe, Lime and hxcpp are you using?

**Comment by tanis2000** [comment]
As a side note, with the dev version of Haxe and Lime 3.0.0 and hxcpp 3.3.49 I am no longer experiencing this issue
