### ISSUE TITLE
Android stage cropped

### ISSUE THREAD

**Issue by bubba169** [openfl/lime#735]
When a Lime Android app is started the window width and height account for the full screen. When there are virtual buttons, the surface seems to get confused and either crop the stage or position it inconsistently on the screen.

Just launching SimpleImage multiple times on the device one after the other on a Android device with virtual OS buttons shows this bug. In 2.8.3 there was a consistent black bar at the bottom of the screen where the buttons live even though they are hidden. This was much more consistent. This happens less when launching with adb but thats probably because the screen is locked and the buttons are already hidden.

**Comment by jgranick** [comment]
This is resolved in current releases, thank you
