### ISSUE TITLE
MouseWheel can't preventDefault() - HTML

### ISSUE THREAD

**Issue by TomByrne** [openfl/lime#743]
when calling preventDefault() on a mouse wheel event, this cancellation doesn't get forwarded on the underlying HTML Event object.

In HTML this makes the Event.MOUSE_WHEEL pretty much useless as you can't prevent scrolling of the page.

It seems like this is not architecturally easy as lime.ui.Window seems to only support one-way information to spawn events.

**Comment by jgranick** [comment]
This is possible since 3.5.0, thank you :grin:
