### ISSUE TITLE
Use NW.js / Electron to test html5 target

### ISSUE THREAD

**Issue by soywiz** [openfl/lime#745]
Instead of opening a webserver + opening the browser, what about using?: http://nwjs.io/

Right now `lime test html5` doesn't end after closing the browser because it doesn't know when browser has terminated.
NW.js would provide a predictable lifecycle + a window that can center to the screen + enable chrome/v8 debugger.

**Comment by ibilon** [comment]
I want to the website and the "normal" link is a 50Mo tar.gz,
too heavy to include.

**Comment by skial** [comment]
I was going to recommend [electron](https://github.com/electron/electron-api-demos/releases) instead, but its only marginally smaller.

**Comment by soywiz** [comment]
I think it is possible to install with npm: https://github.com/nwjs/npm-installer
Another option could be to download on demand. Just as happens when "setup" other stuff.
Also it could be a switch to decide whether to use plain server+browser or nw.js.

I like it because the command would close when closing the window.

Right now I'm integrating gdx-backend-jtransc with gradle:
https://github.com/jtransc/gdx-backend-jtransc/blob/master/cuboc-demo/build.gradle

And I have a task called runHtml5. So people just do: `gradle runHtml5` and it works. But since it starts a webserver and it doesn't exit automatically when closing the windo, is a bit annoying and hard to integrate with debuggers and stuff.

**Comment by soywiz** [comment]
I didn't know about electron. But it looks good to me :) :+1:

**Comment by ibilon** [comment]
Electron has the advantage of being really well known and used,
no idea about nwjs.

Although it seems to be the other way for @soywiz :)

A `lime setup html5` could work.

It would allow for traces to go into the console like all other targets,
and indeed to stop when the window is closed.

Could be nice indeed.

**Comment by soywiz** [comment]
Ok. I have already integrated without lime. And I'm going to describe the process:

Stuff related to electron command (there is a npm package called electron-prebuilt that provides a cli interface for electron, so you can install it with `npm -g install electron-prebuilt`)
```
@JTranscRegisterCommand(target = "js", name = "electron", command = "electron", check = { "electron", "--version" }, getFolderCmd = { "npm", "list", "-g" }, install = {"npm", "-g", "install", "electron-prebuilt" })
@JTranscRunCommand(target = "js", value = { "electron", "{{ outputFolder }}/electron-main.js" })
```

At the javascript side:
```
if (typeof require !== 'undefined') {
	var electron = require('electron');
	if (electron) {
		var ipcRenderer = electron.ipcRenderer;
		console.log = function() { ipcRenderer.send('console.log', Array.from(arguments)); };
		console.warn = function() { ipcRenderer.send('console.warn', Array.from(arguments)); };
		console.error = function() { ipcRenderer.send('console.error', Array.from(arguments)); };
	}
}
```

The electron main:

```
const {app, BrowserWindow} = require('electron');

let mainWindow;

//console.log('electron');

// Quit when all windows are closed.
app.on('window-all-closed', function() {
	if (process.platform != 'darwin') app.quit();
});

// In main process.
const {ipcMain} = require('electron');
ipcMain.on('console.log', (event, arg) => { console.log.apply(console, arg); });
ipcMain.on('console.warn', (event, arg) => { console.warn.apply(console, arg); });
ipcMain.on('console.error', (event, arg) => { console.error.apply(console, arg); });

// This method will be called when Electron has done everything
// initialization and ready for creating browser windows.
app.on('ready', function() {
	// Create the browser window.
	mainWindow = new BrowserWindow({
		title: {{ title|quote }},
		width: {{ initialWidth }},
		height: {{ initialHeight }},
		autoHideMenuBar: true,
		frame: true,
	});

	// and load the index.html of the app.
	mainWindow.loadURL('file://' + __dirname + '/index.html');

	// Emitted when the window is closed.
	mainWindow.on('closed', function() {
		// Dereference the window object, usually you would store windows
		// in an array if your app supports multi windows, this is the time
		// when you should delete the corresponding element.
		mainWindow = null;
	});

	mainWindow.on('unresponsive', function() {
		console.log('Window got unresponsive!');
	});
});
```

**Comment by jgranick** [comment]
I think this should be a separate target

`openfl test windows -js` perhaps?

We could also possibly do this as the node.js target

**Comment by jgranick** [comment]
Tracking here, would be happy to see this :smile:

https://trello.com/c/AElshKia
