### ISSUE TITLE
Use haxe.io TypedArrays?

### ISSUE THREAD

**Issue by soywiz** [openfl/lime#753]
Is there a reason lime is using its own typed arrays? It is like that to be able to target haxe < 3.2? Or that part just kept untouched?
It would be great if it uses internally with a typedef or so (at least on haxe >= 3.2) haxe.io.*Arrays, so I can use them in a portable fashion without having to copy between them. That would be a great speedup for jtransc.

**Comment by jgranick** [comment]
There are nuances about the Haxe typed arrays that do not behave like you would expect, coming from JavaScript typed arrays. The ones we provide work consistently and ultimately abstract over `haxe.io.Bytes`, so there should not be a conversion cost between other Haxe byte APIs

**Comment by soywiz** [comment]
Didn't noticed that. Except for this one: https://github.com/HaxeFoundation/haxe/issues/5273
They should fix that.

So I could convert between them using `haxe.io.Bytes`?

What about something like:
https://github.com/openfl/lime/blob/develop/lime/utils/Int8Array.hx#L123
```
#if (haxe_ver >= 3.2)
@:from static public function fromHaxeIoTypedArray(array:UInt8ArrayData) return new Int8Array(array.view.bytes);
@:to public function ...
#end
```

That would allow to use standard haxe.io.Arrays seamlessly without having to know how to convert them

**Comment by jgranick** [comment]
I would be open to from/to conversion functions in our typed arrays, if someone gets this working and stable, please submit a pull request
