### ISSUE TITLE
Vulkan Support?

### ISSUE THREAD

**Issue by jobs-git** [openfl/lime#754]
How is the status of Vulkan support in Lime?

**Comment by ibilon** [comment]
Nonexistent.

Personally I don't see the point to do that in lime, at least not for now, too few users would benefit from it.

**Comment by jobs-git** [comment]
It could be good thing to consider it in long term plan for Lime.

**Comment by jgranick** [comment]
I'm tracking it here :smile: https://trello.com/c/7LjSvd5Y/58-add-support-for-vulkan
