### ISSUE TITLE
Automatically generating ExternalInterface from Haxe metadata

### ISSUE THREAD

**Issue by vroad** [openfl/lime#755]
Currently bindings that are required to call C++ code is written by hand.
I've just realized that writing bindings by hand is slow and error-prone process. Good programmers are lazy. So we should avoid repetitive process like this.
Could we automate this process with tools like SWIG?

**Comment by ibilon** [comment]
Which bindings exactly are you referring to?

**Comment by vroad** [comment]
OpenGL Bindings, for example? I don't want to repeat the same process when I write bindings for extension or ES3-specific functions.

**Comment by vroad** [comment]
As @jgranick said in slack, adding external tools to dependency might not be ideal solution. So I wrote some type building macro that can generate C++ glue code from Haxe metadata.

**Comment by vroad** [comment]
Initial implementation is available at my repo.

https://github.com/vroad/lime/blob/d92463c680016eb16fbb72cbebb851cd1ebe85fa/lime/system/CFFI.hx#L442
