### ISSUE TITLE
Add "multiDexEnabled" to Android Gradle template

### ISSUE THREAD

**Issue by ibilon** [openfl/lime#757]
http://community.openfl.org/t/multi-dex-support/7281
https://developer.android.com/studio/build/multidex.html

Doesn't seem to require much change.

**Comment by jgranick** [comment]
I wonder if there are any negative consequences?

**Comment by ibilon** [comment]
According to the second link I gave anything below 4.0 (api 14) is likely to misbehave when running a multidex apk, otherwise it doesn't seem to mention negative consequences.
