### ISSUE TITLE
ImageDataUtil.fillRect alpha-premultiplies repeatedly

### ISSUE THREAD

**Issue by MrCoft** [openfl/lime#759]
In OpenFL, the BitmapData constructor produces a "gradient" instead of filling it with color on cpp and neko targets, it works properly in flash and html5.
```haxe
stage.color = 0x0000ff;
stage.addChild(new Bitmap(new BitmapData(20, 20, true, 0xfeff0000)));
```
![image](https://cloud.githubusercontent.com/assets/12239922/16030969/8009da7c-31f6-11e6-81f9-e31055e9f81a.png)
When the alpha is 0x80 instead of 0xfe, it is only about 3 pixels long - it seems the color is alpha premultiplied repeatedly.

**Comment by azrafe7** [comment]
@MrCoft, can you please test if the proposed change fixes the issue for you?

**Comment by MrCoft** [comment]
I wasn't able to run it with the normal nor nightly openfl build and I don't know how to test this in lime alone. But just changing the two lines in ImageDataUtil.hx did not fix the issue.

**Comment by azrafe7** [comment]
You can try this:

 - apply the changes to both `ImageDataUtil.hx` and `ImageDataUtil.cpp`
 - run `lime rebuild windows'

**Comment by MrCoft** [comment]
The haxelib lime's `project` folder is in `/legacy` and looks differenty - it does not have an `ImageDataUtil.cpp`, and I could not find the CFFI function. The loop in the haxe file produces correct color if I force the branch.
I guess it works, just lime got restructured so I can't confirm it.

**Comment by ibilon** [comment]
You need the github version to modify cpp files and rebuild the ndll.

**Comment by MrCoft** [comment]
After building it properly using github versions fillRect works.

**Comment by pozirk** [comment]
There is still a problem on Windows target, but with slightly different example:

```
var bmpd:BitmapData = new BitmapData(100, 100, false, 0xffffff);
var bmp:Bitmap = new Bitmap(bmpd);
addChild(bmp);
```

I have white square as expected on Flash and Android, but nothing on Windows.
Any quick fix for that?

**Comment by pozirk** [comment]
There is still a problem on Windows target, but with slightly different example:

```
var bmpd:BitmapData = new BitmapData(100, 100, false, 0xffffff);
var bmp:Bitmap = new Bitmap(bmpd);
addChild(bmp);
```

I have white square as expected on Flash and Android, but nothing on Windows.
Any quick fix for that?
