### ISSUE TITLE
Android app may start more than once without clearing previous state when Activity is killed by OS

### ISSUE THREAD

**Issue by vroad** [openfl/lime#765]
You can debug this with "Don't keep activities" in developers option.

When an android app goes to background and other apps request more memory, OS may
1. Destroy activity without killing app's process (onDestroy is always called)
2. Kill app's process (onDestory may not be called, or app may be killed even when it's in middle of execution)

A problem might occur with 1. Current implementation of SDLActivity tries to stop thread by sending quit event to C++ side. When app is reopened some global states may still be stored in memory, and that may cause issues.

You might be able to avoid this issue by manually calling dlopen/dlclose to load/unload libApplicationMain.so, but this only works on cpp. I couldn't find a way to unload assemblies on Xamarin.Android. Xamarin.Android's runtime automatically loads assembly into default AppDomain when app is launched, which makes it difficult to unload assemblies by loading assemblies into separate AppDomain.

I'm avoiding this issue currently by keeping SDLThread/SDLSurface when onDestroy is called with `isFinishing()` = false.

https://developer.android.com/training/basics/activity-lifecycle/stopping.html

**Comment by jgranick** [comment]
Calling `System.exit(0)` is the best approach I've found so far, as we try and exit from the Haxe side, we want a clean restart when we come back
