### ISSUE TITLE
Migrate from SDL_Renderer to direct SDL_GL initialization calls

### ISSUE THREAD

**Issue by vroad** [openfl/lime#766]
SDL's renderer has various 2d drawing functions, but we are already using cairo for 2d rendering. Why should we keep using SDL's renderer then? I've found that you can directly draw to Window's surface with SDL_GetWindowSurface.

https://wiki.libsdl.org/SDL_GetWindowSurface
https://wiki.libsdl.org/CategoryRender

**Comment by ibilon** [comment]
Not sure if you are saying we should use or not use sdl's drawing features?

**Comment by vroad** [comment]
I think that we shouldn't use it. We can achieve the same thing with SDL_GetWindowSurface. There is no reason to include SDL's feature that we'll never use. And isn't it bad to use futures that are specific to SDL? That might make porting to another backend difficult.

**Comment by ibilon** [comment]
But we aren't using it now, or I'm missing something in the codebase, so what's the issue?

**Comment by jgranick** [comment]
I'm open to changing this, if someone has a pull request that's stable. We probably should not use `SDL_Renderer` since we aren't truly using it -- it's been a means to creating our context and handling resizes for us, but ultimately this restricts our flexibility

**Comment by jgranick** [comment]
This is done :smile:
