### ISSUE TITLE
Why does Window::SetTitle return string?

### ISSUE THREAD

**Issue by vroad** [openfl/lime#767]
Can't this be void?

**Comment by ibilon** [comment]
That's the way setter work in haxe,
if you are talking about the c++ code: while it's not required it's probably easier to match the same behavior everywhere.

**Comment by vroad** [comment]
I was talking about C++ code. I don't think C++ function should return values in the same way as Haxe.

In ExtternalInterface.cpp, interface function is freeing char returned from SetTitle. Doesn't that cause a issue?

**Comment by vroad** [comment]
Return type of `SetEnableTextEvents` is void in C++, so there are some inconsistencies in C++ code.

**Comment by tienery** [comment]
Is #805 somehow related to this?

**Comment by jgranick** [comment]
Happy to discuss this more on Slack, I agree we may look at some housekeeping
