### ISSUE TITLE
Do we really need to have wrapper code in lime.graphics.opengl.GL class, which allows you to access OpenGL functions statically?

### ISSUE THREAD

**Issue by vroad** [openfl/lime#768]
I think that this isn't really needed. If you want to access some OpenGL functions globally, you can do that by holding the context as a global variable by yourself. That's why WebGLRenderingContext only has instance methods. Why not implementing nattive OpenGL context in the same way as WebGLRenderingContext? I saw that instance method version (`lime.graphics.GLRenderContext`) is also there, but duplicating code will make refactoring difficult.

Also, exposing OpenGL contants that are not available in other platforms (such as WebGL specific constants) looks bad. This lead to misunderstanding that `UNPACK_FLIP_Y_WEBGL` is available on native targets. I saw this in Stage3D code in past, but this shouldn't compile on native. Can't we solve this by simply using `typedef GL = js.html.webgl.RenderingContext`? (or `typedef GL = lime._backend.native.opengl.RenderingContext` on native?)

It might be bad to include constants from OpenGL extensions in `GL` class as well. `BGRA_EXT` is not available on any WebGL implementations, for example. This shouldn't compile on WebGL.

**Comment by vroad** [comment]
I've also found that `GLRenderContext `has OpenGL constants as instance fields, but why should we duplicate these fields from `GL` and make them instance fields? I don't understand.

https://github.com/openfl/lime/blob/23be78719850b17421b68960f690709599e25330/lime/graphics/GLRenderContext.hx#L14

I would suggest creating classes like `GLES20`, `GLES30` which works almost identically as `WebGLRenderingContext`.

**Comment by jgranick** [comment]
This was fixed recently :smile:
