### ISSUE TITLE
Run always on 8.1

### ISSUE THREAD

**Issue by julio6114** [openfl/lime#771]
Hi,

When I launch project on ios simulator like that:
`lime run ios -simulator`
the simulator is always on 8.1 sdk
`Launch app on "com.apple.CoreSimulator.SimDeviceType.iPhone-6, 8.1"`

I've got 7.3.1 Xcode

I don't see what I can do to fix it

Thanks

**Comment by julio6114** [comment]
I find solution, runtime 8.1 files stays on directory but unavailable on xcode :(
So sorry

**Comment by ibilon** [comment]
Not 100% sure, did you fix your problem?
