### ISSUE TITLE
SDLWindow::Close causes double free?

### ISSUE THREAD

**Issue by vroad** [openfl/lime#776]
https://github.com/openfl/lime/blob/4b2520a13f5e61046586812ec12fd5b49b78ba14/project/src/backend/sdl/SDLWindow.cpp#L173

`SDL_DestroyWindow` will be called in destructor again when finalizer is executed?

It might be better to do `delete this` instead of just destroying `SDLWindow`. You can then use `val_gc(handle, NULL)` or `free_abstract` to unset finalizer/C++ pointer.

**Comment by jgranick** [comment]
I believe this is resolved, but please tell me if there are more issues here
