### ISSUE TITLE
ANGLE build should use SDL_opengles2.h rather than GL.h or SDL_opengl.h

### ISSUE THREAD

**Issue by vroad** [openfl/lime#778]
https://github.com/openfl/lime/blob/130e8e703e52436c7d5de6a57fe5999a30f94ecb/project/src/graphics/opengl/OpenGL.h#L57-L67

**Comment by jobs-git** [comment]
This maybe the reason why Angle is slow?

**Comment by jgranick** [comment]
I believe I have pulled in the relevant changes, thank you
