### ISSUE TITLE
HTML5 target 'null' in path using Lime 3.0.0 + OpenFL 4.0.0

### ISSUE THREAD

**Issue by Matan** [openfl/lime#779]
Hi,

The new path structure is putting a 'null' in the build path.

Reproduce by:
<code>openfl create DisplayingABitmap && cd DisplayingABitmap && openfl build html5</code>

Then, observe:
<pre>OpenFL Command-Line Tools (4.0.0-LdHLlk)

Initializing project...
Using project file: /home/matan/work/intellij/DisplayingABitmap/project.xml
Reading HXCPP config: /home/matan/.hxcpp_config.xml
Using target platform: HTML5

Running command: UPDATE
 - Copying template file: /usr/lib/haxe/lib/lime/3,0,0/templates/html5/template/index.html -> Export/html5/null/bin//index.html
 - Copying template file: /usr/lib/haxe/lib/openfl/4,0,0/templates/html5/template/index.html -> Export/html5/null/bin//index.html
 - Copying template file: /usr/lib/haxe/lib/lime/3,0,0/templates/haxe/DefaultAssetLibrary.hx -> Export/html5/null/haxe/DefaultAssetLibrary.hx
 - Copying template file: /usr/lib/haxe/lib/lime/3,0,0/templates/haxe/ApplicationMain.hx -> Export/html5/null/haxe/ApplicationMain.hx
 - Copying template file: /usr/lib/haxe/lib/openfl/4,0,0/templates/haxe/ApplicationMain.hx -> Export/html5/null/haxe/ApplicationMain.hx
 - Copying template file: /usr/lib/haxe/lib/openfl/4,0,0/templates/haxe/NMEPreloader.hx -> Export/html5/null/haxe/NMEPreloader.hx
 - Copying template file: /usr/lib/haxe/lib/lime/3,0,0/templates/html5/hxml/final.hxml -> Export/html5/null/haxe/final.hxml
 - Copying template file: /usr/lib/haxe/lib/lime/3,0,0/templates/html5/hxml/debug.hxml -> Export/html5/null/haxe/debug.hxml
 - Copying template file: /usr/lib/haxe/lib/lime/3,0,0/templates/html5/hxml/release.hxml -> Export/html5/null/haxe/release.hxml
 - Copying template file: /usr/lib/haxe/lib/openfl/4,0,0/templates/html5/hxml/final.hxml -> Export/html5/null/haxe/final.hxml
 - Copying template file: /usr/lib/haxe/lib/openfl/4,0,0/templates/html5/hxml/debug.hxml -> Export/html5/null/haxe/debug.hxml
 - Copying template file: /usr/lib/haxe/lib/openfl/4,0,0/templates/html5/hxml/release.hxml -> Export/html5/null/haxe/release.hxml

Running command: BUILD
 - Running command: haxe Export/html5/null/haxe/release.hxml
</pre>

Does the same with ```-debug``` and ```-final```.

The issue lies in the fact that when ```initialize``` is being called, ```buildTarget``` is still ```null```.

Order of execution, note ```initialize``` before ```super```:
https://github.com/openfl/lime/blob/master/lime/tools/platforms/HTML5Platform.hx#L28-L30

Use of ```buildTarget``` while ```null```:
https://github.com/openfl/lime/blob/master/lime/tools/platforms/HTML5Platform.hx#L107

Assignment of ```buildTarget``` with in ```super``` after the fact:
https://github.com/openfl/lime/blob/master/lime/project/PlatformTarget.hx#L28-L42

Hope this helps to fix the problem. :)

Thanks,
Matan

**Comment by vroad** [comment]
It's fixed in https://github.com/openfl/lime/commit/357b682fb36924868187698556a795e3ade60007 and new tag including that fix (3.0.1) is pushed to git, though I still cannot download that version from haxelib somehow.

**Comment by jgranick** [comment]
`haxelib submit` as down earlier when we tried to release, 4.0.1 and 3.0.1 are out now :smile:
