### ISSUE TITLE
`lime display cpp` outputs two `-D flixel` lines when haxelib depending on flixel is used

### ISSUE THREAD

**Issue by IBwWG** [openfl/lime#792]
lime 2.9.1...

I have a project that was compiling last month with flixel versions like `4.0.0 4.0.1 [git]`.  I need the git version because it's from my fork with not-yet-integrated pull requests; its haxelib.json declares that it is version 4.0.1.  My project also uses flxscrollablearea 0.3.1 (my lib) whose haxelib.json declares dependence on flixel 4.0.0 and openfl 3.6.0.  My project uses openfl 3.6.1.  Code completion and lookups were also working.

Last week I made a new project, installing flixel version 4.1.1, and used that.  All good.

Now I go back to my first project, which needs my custom PRs, and so won't compile with flixel 4.1.1.  So I ran `haxelib set flixel git`.  Now the flixel versions look like `4.0.0 4.0.1 4.1.1 [git]`, as they should.  Code completion and lookups still work correctly, going for the git version instead of 4.0.0.  But my project won't compile, citing missing functions that are only in the git version.  Then I notice that the References folder in HaxeDevelop looks like https://github.com/fdorg/flashdevelop/issues/1257 but with flixel 4.0.0 and flixel git (openfl is not duplicated.)  That's when I discovered that `lime display cpp` incorrectly outputs two pairs of lines for flixel, a 4.0.0/4.0.0 pair and a git/4.0.1 pair.  openfl again is OK here.

If I `haxelib remove flixel 4.0.0` then the `lime display cpp` output is correct; however my project still won't compile, saying, `Error: Could not find haxelib "flxscrollablearea", does it need to be installed?`.  Yet `haxelib list` still shows it installed just fine.

To get that to go away, I temporarily changed the haxelib.json file for flxscrollablearea 0.3.1 to depend on flixel "git", but that's not really a proper solution, since it would break future updates via haxelib and also isn't true (I don't want to push that change, since the lib is actually compatible with 4.0.0 still.)  How can I get it to work how it was before, without breaking my haxelib.json?

**Comment by jgranick** [comment]
We changed Lime so that if you import a library version first, it prints a warning later (and will not load a second version) where before it could process parts of two different versions for the same library.

This should help clean up these types of issues, though this change isn't planned to be backported to the old Lime 2.9 release. Hopefully Flixel can get things updated
