### ISSUE TITLE
crossOrigin unnecessary in Image.__fromBase64 (and incompatible with Safari)

### ISSUE THREAD

**Issue by er453r** [openfl/lime#793]
This line: https://github.com/openfl/lime/blob/develop/lime/graphics/Image.hx#L1101

    image.crossOrigin = "Anonymous";

It's unnecessary in `Image.__fromBase64`, it works well in all browsers except newer versions of Safari, which give `Cross-origin image load denied by Cross-Origin Resource Sharing policy.`.

The solution is to remove the line completely from this function - then it works in every browser.

More info on this problem here: http://stackoverflow.com/questions/31643096/why-does-safari-throw-cors-error-when-setting-base64-data-on-a-crossorigin-an

**Comment by jgranick** [comment]
Thanks :smile:
