### ISSUE TITLE
Make object files from official lime builds available?

### ISSUE THREAD

**Issue by Tw1ddle** [openfl/lime#796]
I gather that .obj files are not currently included with the lime haxelib releases/version tags on GitHub. Not having the .obj files means I cannot symbolicate the lime parts of stack traces/crash logs from logcat output on Android using the ndk-stack NDK tool. Would it make sense to provide the object files available from the official lime releases to make this possible? If not, what is a good way to make sense of the stack traces that go into lime code?

The reason I ask is that I have a crash I cannot reproduce when using lime 2.9.1 built on my local PC, but see when using lime 2.9.1 haxelib release. It is a divide by 0 somewhere in the lime-legacy audio code:

> 08-07 00:32:34.008   394   394 F DEBUG   : signal 8 (SIGFPE), code -6 (SI_TKILL), fault addr 0x5c48
> ...snip...
> 08-07 00:32:34.114   394   394 F DEBUG   :     #00 pc 000420a0  /system/lib/libc.so (tgkill+12)
> 08-07 00:32:34.114   394   394 F DEBUG   :     #01 pc 0003fcad  /system/lib/libc.so (pthread_kill+32)
> 08-07 00:32:34.114   394   394 F DEBUG   :     #02 pc 0001c463  /system/lib/libc.so (raise+10)
> 08-07 00:32:34.114   394   394 F DEBUG   :     #03 pc 002b4a58  /data/app/uk.co.someapp/lib/arm/liblime-legacy.so (__aeabi_idiv0+8)
> 08-07 00:32:34.114   394   394 F DEBUG   :     #04 pc 00045e1c  /data/app/uk.co.someapp/lib/arm/liblime-legacy.so
> 08-07 00:32:34.114   394   394 F DEBUG   :     #05 pc 0004792c  /data/app/uk.co.someapp/lib/arm/liblime-legacy.so
> 08-07 00:32:34.115   394   394 F DEBUG   :     #06 pc 0008f54c  /data/app/uk.co.someapp/lib/arm/liblime-legacy.so
> 08-07 00:32:34.115   394   394 F DEBUG   :     #07 pc 00a956a4  /data/app/uk.co.someapp/lib/arm/libApplicationMain.so (ExternalPrimitive::__run(Dynamic const&, Dynamic const&, Dynamic const&, Dynamic const&)+400)
> 08-07 00:32:34.115   394   394 F DEBUG   :     #08 pc 000b2c60  /data/app/uk.co.someapp/lib/arm/libApplicationMain.so (Dynamic::operator()(Dynamic const&, Dynamic const&, Dynamic const&, Dynamic const&)+96)
> 08-07 00:32:34.115   394   394 F DEBUG   :     #09 pc 0024a3dc  /data/app/uk.co.someapp/lib/arm/libApplicationMain.so (openfl::_legacy::media::SoundChannel_obj::__construct(Dynamic, hx::Null<double>, hx::Null<int>, hx::ObjectPtropenfl::media::SoundTransform_obj)+716)
> 08-07 00:32:34.115   394   394 F DEBUG   :     #10 pc 0024a624  /data/app/uk.co.someapp/lib/arm/libApplicationMain.so (openfl::_legacy::media::SoundChannel_obj::__new(Dynamic, hx::Null<double>, hx::Null<int>, hx::ObjectPtropenfl::media::SoundTransform_obj)+172)
> 08-07 00:32:34.115   394   394 F DEBUG   :     #11 pc 002562d4  /data/app/uk.co.someapp/lib/arm/libApplicationMain.so (openfl::_legacy::media::Sound_obj::play(hx::Null<double>, hx::Null<int>, hx::ObjectPtropenfl::media::SoundTransform_obj)+2084)
> ...snip...

Thanks.

**Comment by ibilon** [comment]
Well they can't be included in the haxelib release, maybe they could be put online,
but are you sure they can be used on another computer? (not familiar with that)

And can't you just use the one you built if it doesn't crash?
I know that's bypassing the issue, but it's simple :)

**Comment by Tw1ddle** [comment]
I'm not certain either, but I always assumed you could resymbolicate a stack trace using ndk-stack on whatever PC, so long as the object files match. I'd hope to use ndk-stack with a line like:

`$NDK/ndk-stack -sym $LIME_PROJECT_PATH/obj/local/$ARCHITECTURE -dump mycrashdump.txt`

Anyway yeah, for the time being I can sidestep the issue. It's a mystery though :smile:
