### ISSUE TITLE
How to get executable path with lime?

### ISSUE THREAD

**Issue by r3d9u11** [openfl/lime#803]
Hello. How I can get current executable path in Haxe when programm was launched by lime/openfl?

for example:

```
#if neko
    trace('neko >> ${neko.vm.Module.local().name}');
#elseif cpp
    trace('cpp  >> ${Sys.executablePath()}');
#end
```

will return:
- result for neko target (`lime test linux -64 -neko`): `neko >>`
- result for cpp target (`lime test linux -64 -cpp`): `cpp >> /usr/local/bin/lime`

(this example works fine when I launch compiled files "bin/Main" or "neko bin/Main.n" directly, but I need to get this path when programm was launched by lime/openfl too)

(theme on stackoverflow http://stackoverflow.com/questions/39253573/how-to-get-executable-path)

Thanks.

**Comment by ibilon** [comment]
`Sys.executablePath()` was buggy (but you can use it on neko too I think),
if you have haxe 3.3+ can you try `Sys.programPath()`?

**Comment by r3d9u11** [comment]
No, I haven't haxe 3.3 yet
When I install it, I'll try to call this function

Thank you for your answer!
