### ISSUE TITLE
Follow in Event build macro

### ISSUE THREAD

**Issue by Gama11** [openfl/lime#806]
While debugging some Haxe display bug, @Simn pointed out that this code (https://github.com/openfl/lime/blob/3.1.0/lime/app/Event.hx#L68):

```haxe
switch (Context.getLocalType ()) {
			
	case TInst (_, [ TFun (args, result) ]):
```

would be more robust if it looked like this:

```haxe
switch (Context.follow(Context.getLocalType ())) {
	
	case TInst(_, [ Context.follow(_) => TFun(args, result) ]):
```

@ibilon wanted to look into this.

**Comment by Simn** [comment]
Note that this is true for virtually any check on `haxe.macro.Type`. To be completely safe all these types should be followed, and followed recursively as well.

**Comment by jgranick** [comment]
Does this work with Haxe 3.2.1?
