### ISSUE TITLE
Add 2.9.x bugfix branch

### ISSUE THREAD

**Issue by bendmorris** [openfl/lime#807]
Flixel is currently locked to Lime 2.9.1, but there's at least one major crash in that version:

https://github.com/haxeflixel/flixel/issues/1930

Can we create a bugfix 2.9.x branch similar to the "openfl3" branch for openfl, backport this and any other fixes/improvements that don't break compatibility until flixel is current, and put out a new patch release with these improvements?

**Comment by ibilon** [comment]
@jgranick will have to look if the ndll build system can do that

**Comment by Tembac** [comment]
There was also a problem with text on Mac os using lime 2.9.1. We talked about it here: http://community.openfl.org/t/android-build-shows-a-black-screen-and-i-cant-find-error-message/7670/14

And @vroad made a fix but I'm not sure if it was added to the release. https://github.com/vroad/lime/commit/efa8d76b3bc6a9b5aaf0e35565260aa513d892d8
