### ISSUE TITLE
Rebuilding the tools with Haxe 3.3.0 dev breaks icons

### ISSUE THREAD

**Issue by Gama11** [openfl/lime#808]
If I do `lime rebuild tools` with latest Haxe dev, built applications are missing their icon. This might have to do with incorrect command quoting when calling `ReplaceVistaIcon.exe` (there is a `The system cannot find the path specified.`  error in the output right after that command).

Haxe 3.3.0 has breaking changes in its `Sys.command()` API: https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-3.3.0#syscommand-and-sysioprocess

**Comment by jgranick** [comment]
Fixed 😁 

https://github.com/openfl/lime/commit/7f4c0c3caeb1f18a0e6d2a45a2d4cdd4faaddc95
