### ISSUE TITLE
neko binaries in the template

### ISSUE THREAD

**Issue by ibilon** [openfl/lime#815]
lime ships its own version of neko
https://github.com/openfl/lime/tree/develop/templates/neko/bin

1. the user doesn't get why its neko isn't used
1. it's not up to date: the mac version still doesn't have the increase op code limit fix
1. manual concatenation of neko and n file is incorrect on linux (strip will remove the n part)

it'd be better to remove this and use nekotools boot instead

**Comment by jgranick** [comment]
There are a few motivations for it

1. Including Neko means we can (theoretically) support cross-desktop builds
2. This is an issue -- I think we should consider getting Neko building on the OpenFL build server
3. The manual concatenation is what `nekotools boot` does

If we started building Neko ourselves, we could consider a few options

1. If we begin contributing fixes or improvements to Neko, we could deploy an updated version right away
2. We could embed Neko inside of an HXCPP wrapper, enabling Neko use beyond the desktop

Either way, between Node.js, standard JavaScript, Neko and the upcoming C# support (or even previous Java support) it may be worth discussing some of the features (fast dev testing or cross-desktop support) and consider a recommended path

**Comment by ibilon** [comment]
1. Oh right, cross-desktop build, that's indeed a nice feature to have
2. That would be nice
3. I'm not sure that's still the case on linux, IIRC a method of adding the n part as a data section of the elf executable was discussed, but not sure if that is merged yet

I started adding support for cppia to the tools, works ok but I have yet to add an automatic way to build the host.
It could replace neko I think, compilation speed should be as fast as well as running speed, but you could have a single file exe without ndll (once a mechanism for including the cppia is added)

**Comment by mastef** [comment]
Any idea how to get around this temporarily? Is there a way to specify a different neko version, or are there any commands that need to be called after patching the files yourself?

Currently fighting with the opcode limitation on Mac

**Comment by ibilon** [comment]
Joshua removed them, so now if you use the latest git version it'll use the version of neko you have installed.
