### ISSUE TITLE
window close event can't be canceld

### ISSUE THREAD

**Issue by ibilon** [openfl/lime#817]
when the "x" of the window is clicked,
because it can't be canceled at sdl level.

Tried using `SDL_SetEventFilter` but it just prevent the event from going to the event queue,
it doesn't prevent the internal state modification.

Maybe it could be done if we used a "native" window + `SDL_CreateWindowFrom`,
if the native gui toolkit has a cancelable closing.
But not sure if that would allow the sdl window events to still work.

**Comment by jgranick** [comment]
I thought this was possible if you ignore SDL_QUIT events?

**Comment by ibilon** [comment]
No it's received after the last window is closed, that allows the application to run even with no window open, but doesn't prevent any window from closing.
