### ISSUE TITLE
HTML5 numpad key codes are inconsistent with Flash

### ISSUE THREAD

**Issue by Gama11** [openfl/lime#818]
On HTML5, numpad key codes collide with letters, making it impossible to tell them apart. Tested with Lime 3.2.1.

```haxe
package;

import lime.app.Application;
import lime.app.IModule;
import lime.ui.Window;
import lime.ui.KeyCode;
import lime.ui.KeyModifier;

class Main extends Application 
{
	public function new() 
	{
		super();
		Application.current.addModule(new Module());
	}
}

class Module extends lime.app.Module
{
	override public function onKeyDown(window:Window, keyCode:KeyCode, modifier:KeyModifier):Void
	{
		trace(keyCode);
	}
}
```

Flash:

`a`: 97
`b`: 98
`c`: 99
`Numpad 1`: 1073741913
`Numpad 2`: 1073741914
`Numpad 3`: 1073741915

HTML5:

`a`: 97
`b`: 98
`c`: 99
`Numpad 1`: 97
`Numpad 2`: 98
`Numpad 3`: 99

**Comment by jgranick** [comment]
Does this commit help?

https://github.com/openfl/lime/commit/e83713373ef9b70112637acc83c76ab50f75a975

**Comment by jgranick** [comment]
and if you like, the Lime `Application` class is a `Module`, too :smile:

```haxe
package;

import lime.app.Application;
import lime.ui.Window;
import lime.ui.KeyCode;
import lime.ui.KeyModifier;

class Main extends Application 
{
    public function new() 
    {
        super();
    }

    override public function onKeyDown(window:Window, keyCode:KeyCode, modifier:KeyModifier):Void
    {
        trace(keyCode);
    }
}
```

**Comment by Gama11** [comment]
Oh, I see. I figured I must have been doing something wrong - never used the Lime API directly before. :)

Appears to be consistent now. Should've checked the dev branch first.

**Comment by jgranick** [comment]
Oh no! It's perfectly valid -- just thought I'd point it since it makes quick tests simpler.

No problem, we just have a couple bigger changes that need to be tested before we can do another release

**Comment by Gama11** [comment]
No worries, we need to finish OpenFL 4 support for Flixel first to benefit from this anyway.

**Comment by Gama11** [comment]
And yeah, I meant 'doing wrong' in the context of creating a minimal code snippet.
