### ISSUE TITLE
The "lime rebuild" command doesn't support platform handlers

### ISSUE THREAD

**Issue by nikolay-mamaev** [openfl/lime#826]
Building OpenFL extensions is impossible for non-standard build targets.

The "lime rebuild" command creates a build project (HXProject) manually in its code, ignoring any xml files put into a haxelib's directory. In fact, currently there is no way to configure anyhow a "lime rebuild" project (unless using lime tool's command-line parameters like "--dependency", "--haxedef" and so on).

I'd like to propose to introduce the `overrides.xml` or `overrides.lime` file, coupled with a small change in `CommandLineTools.hx`, that solves this problem. Technically, the overrides file can be used not only for the "lime rebuild" command, but for number of other lime commands as well:
* "create"
* "clean"
* "update"
* "display"
* "build"
* "run"
* "rerun"
* "uninstall"
* "trace"
* "test"
* "deploy"
All these commands create HXProject's and all of these projects' parameters technically can be fine-tuned with the overrides file. But it doesn't make sense because all these commands deal with OpenFL's project.xml file which can be modified directly to modify parameters of an HXProject created by lime.

Example of an `overrides.xml` / `overrides.lime` file:

```
    <project>
        <target name="newCoolPlatform" handler="new-cool-platform-handler-haxelib" />
    </project>
```

Proposed modification in the `/lime/tools/CommandLineTools.hx`:

```
	public function new () {

		// ...

		if (LogHelper.verbose && command != "") {			
			// ...
		}

		var overridesFile = "";

		if (words.length == 2) {
			if (FileSystem.exists (words[0]) && FileSystem.isDirectory (words[0])) {
				overridesFile = findOverridesFile (words[0]);
			}
		} else {
			overridesFile = findOverridesFile (Sys.getCwd ());
		}

		if (overridesFile.length > 0) {
			var oldWd = Sys.getCwd ();
			try { Sys.setCwd (Path.directory (overridesFile)); } catch (e:Dynamic) {}
			var overridesFileProject = new ProjectXMLParser (Path.withoutDirectory (overridesFile));
			if (overridesFileProject != null) {
				LogHelper.info ("", '${LogHelper.accentColor}Using overrides file: ${Path.withoutDirectory(overridesFile)} ${LogHelper.resetColor}');
				overridesFileProject.architectures = [];
				overrides.merge(overridesFileProject);
			}
			try { Sys.setCwd (oldWd); } catch (e:Dynamic) {}
		}
		
		switch (command) {
			// ...
		}
		
		// ...
	}

	// ...

	private function findOverridesFile (path:String):String {

		if (FileSystem.exists (PathHelper.combine (path, "overrides.lime"))) {
			
			return PathHelper.combine (path, "overrides.lime");
			
		} else if (FileSystem.exists (PathHelper.combine (path, "overrides.xml"))) {
			
			return PathHelper.combine (path, "overrides.xml");
			
		}

		return "";
	}
```

**Comment by jgranick** [comment]
Hello,

I have made some initial changes to Lime tools to help support this behavior.

Instead of "~/.hxcpp_config.xml" for the storage of ANDROID_NDK and other environment variables for a build, I have moved to a default "~/.lime/config.xml" file with a matching LIME_CONFIG environment variable (if you wish to use a different path)

I am very interested in feedback on whether this feels good, or if we should consider implementing this differently.

This has support for `lime setup` values, but is a valid Lime project file, so it can support the addition of a platform target or additional behaviors.

For now I have also added a `lime config` command -- this prints the full contents of the ".lime/config.xml" file, and also supports `lime config ANDROID_NDK` (or the name of another define) to get the value

**Comment by nikolay-mamaev** [comment]
Hi Joshua,

Sorry for late reply. This sounds good, thank you! Currently, with my proposal above, we have to place overrides.xml into each haxelib building ndll's with the "lime rebuild" command, so having a single file is much more preferred.

For our purposes, having a lime config file with a path set by the $LIME_CONFIG is sufficient, so seems we don't need a command-line parameter for overrides.

For now, we will continue using my proposal, and plan to rework this when integrate an updated lime version to use the LIME_CONFIG file.

Thank you!

**Comment by jgranick** [comment]
Cool, well let me know if we can continue to improve how this is all designed. I think a custom target is smart for how you guys are set up, but I want to make sure it behaves like a first-class citizen, so I really appreciate this feedback. Have a great day :smile:
