### ISSUE TITLE
[lime.Assets] There is no asset library named "" in lime 3.4.0

### ISSUE THREAD

**Issue by vroad** [openfl/lime#834]
I couldn't load assets in lime-samples with this error... Tried with haxelib version.

**Comment by jgranick** [comment]
I had this error yesterday, but this fixed it

https://github.com/openfl/openfl/commit/402face085ec93358cf25fd46042ecef05bfadf0

Do you have that commit?

**Comment by jgranick** [comment]
I see it now, thank you.

It's the timing of waiting for assets to be loaded, but triggering before `onPreloaderComplete` is dispatched

https://github.com/openfl/lime/commit/87f331ca3c4b3607a2f0772352513ddfd9461461

This will go out in a minor release
