### ISSUE TITLE
bug in lime.Assets 

### ISSUE THREAD

**Issue by ramsestom** [openfl/lime#836]
Just updated to lime 3.4.1 and every time I want to build a new project, it fails with this error:

`Class<lime.Assets> has no field initialize`

**Comment by jgranick** [comment]
Did you update OpenFL to `4.4.1` to match? Where does this error come from? Do you have any overridden templates? (such as `DefaultAssetLibrary`)

**Comment by ramsestom** [comment]
I performed an `haxelib update` but for a strange reason, openFL did not update... Forcing it with an `haxelib install openfl` fixed it. Thanks.
