### ISSUE TITLE
Does disabling SSE4.1 on openal-soft improve backward compatibility?

### ISSUE THREAD

**Issue by vroad** [openfl/lime#837]
I guess SSE4.1 is only used when CPU supports it, so disabling it at compile time doesn't improve compatibility with older computers.

https://github.com/native-toolkit/openal/commit/806867f198dfeb12de2f9f61c5aadd041eb544c3

**Comment by jgranick** [comment]
Yes, I believe this helped support for some older systems, which might have been running Windows XP, I'm not sure. If we find this is not necessary, I'd be happy to rediscuss it :smile:
