### ISSUE TITLE
[lime.Assets] There is no asset library named "" after upgrading to Lime 3.4.1

### ISSUE THREAD

**Issue by sfiq** [openfl/lime#842]
I've just upgraded lime from version 3.3.0 to 3.4.1 through haxelib and I've been getting this error.
I heard this was a bug from 3.4.0 and was supposedly fixed in this version

**Comment by jgranick** [comment]
Are you also using OpenFL? Was that upgraded? If not, how soon do you reference the Assets class?

**Comment by sfiq** [comment]
I'm using Lime, I started referencing the asset class after the onWindowCreate event, where I would load all of my assets

**Comment by jgranick** [comment]
Can you try using the onPreloadComplete event, and see if that works?

**Comment by sfiq** [comment]
Seems like the onWindowCreate event triggers before assets are preloaded, it works now.
