### ISSUE TITLE
lime.system.System.applicationStorageDirectory works wrong in windows

### ISSUE THREAD

**Issue by praleks** [openfl/lime#846]
lime.system.System.applicationStorageDirectory works wrong in windows when username contains non ASCII symbols (like cyrilics)
in legacy it worked well when was openfl.utils.SystemPath.applicationStorageDirectory

**Comment by jgranick** [comment]
We did make improvements to this, but it seems there are still some remaining issues. Closed in favor of https://github.com/openfl/lime/issues/1083

Thank you
