### ISSUE TITLE
Lime rebuild error with OpenAL  for Android target

### ISSUE THREAD

**Issue by kiroukou** [openfl/lime#848]
Hello,

I'm trying to recompile the current development branch of Lime, but I 'm having the following error:

``
- Compile : lib/openal/OpenAL32/alEffect.c
Error: While running :arm-linux-androideabi-g++ -Ilib/openal/Alc -Ilib/openal/include/ -Ilib/openal/OpenAL32/include/ -DAL_ALEXT_PROTOTYPES -D_LARGEFILE_SOURCE -D_LARGE_FILES -fPIC -fvisibility=hidden -pthread --std=c99 -Wno-psabi -fsigned-char --sysroot=C:\Development\android-ndk/platforms/android-9/arch-arm -IC:\Development\android-ndk/sources/cxx-stl/gnu-libstdc++/4.8/include -IC:\Development\android-ndk/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=0 -IC:/HaxeToolkit/haxelib/hxcpp/3,3,49/include -Iinclude -fpic -fvisibility=hidden -ffunction-sections -funwind-tables -fstack-protector -fno-short-enums "-D_LINUX_STDDEF_H " -Wno-psabi -DHXCPP_CPP11 -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__ -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__ -march=armv5te -mtune=xscale -msoft-float -fomit-frame-pointer -fexceptions -fno-strict-aliasing -finline-limit=10000 -DANDROID=ANDROID -DHX_ANDROID -DHXCPP_ANDROID_PLATFORM=9 -Wa,--noexecstack -O2 -DNDEBUG -c -x c ./lib/openal/common/atomic.c -oD:/gitlibs/lime/project/obj/android/19ac901b_atomic.obj
In file included from ./lib/openal/common/atomic.c:4:0:
lib/openal/include/atomic.h:14:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
``

What are the requirements to recompile the lime binaries ?

Thanks

**Comment by jgranick** [comment]
Can you try using a newer NDK? I think we use r11 or r12 now, due to issues in Android N support otherwise

**Comment by kiroukou** [comment]
Hello Joshua,
I tried that with r13, without any success.  But ok I'll have a look with r12 and let you know asap.

That would be a nice information to note in the README at each upgrade.

**Comment by rmsmith** [comment]
Hi guys, I am also hitting this error.  @kiroukou did you find an NDK version that worked?  I am on `r10c` presently.

**Comment by jgranick** [comment]
I am setting up a new machine right now, I installed NDK r13b (the one available on the Android NDK developer site) and am using a current version of HXCPP, and it is building fine :smile:

**Comment by rmsmith** [comment]
Yeah, so `r13b` worked for me after learning about `~/.hxcpp_config.xml` and making sure the `ANDROID_NDK_ROOT` in that file matched what was set in `lime setup android`.  Hope that helps @kiroukou

**Comment by kiroukou** [comment]
Hello rmsmith & Joshua !
Yes I managed to get it work on OSX platform finally.  Wasn't sure about windows, so thank you about the information .
