### ISSUE TITLE
iOS build

### ISSUE THREAD

**Issue by mayakwd** [openfl/lime#849]
We definitely need to improve build configuration for iOS (XCode 8.1).
I've made some research and build custom version of lime, found how to compile signed .ipa with provisioning profile and identity.

Configuration now looks like
`<certificate team-id="XXXXXXXXX" provisioning-profile="xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx" identity="iPhone Developer: Ilya Malanin (XXXXXXXXX)" />`

During the build step you should just pass to xcodebuild two additional parameters: 

IOSHelper.build:
```
		if (project.certificate != null) {
			if (project.certificate.provisioningProfile != null) {
				commands.push("PROVISIONING_PROFILE="+project.certificate.provisioningProfile);
			}

			if (project.certificate.identity != null) {
				commands.push("CODE_SIGN_IDENTITY="+project.certificate.identity);
			}
		}

```

**Comment by jgranick** [comment]
Thanks! This was just committed :smile:

If you pull the newest Lime version, try to `lime rebuild tools`, then see if the identity and profile work for you properly.

I changed the way that `<certificate />` works internally, here's how you set this up for iOS:

```xml
<certificate team-id="" identity="" />
<config:ios provisioning-profile="" />
```

or

```xml
<config:ios team-id="" identity="" provisioning-profile="" />
```

**Comment by mayakwd** [comment]
Great news Joshua! Thank you! I'll check it in a next week (right now I don't have mac on hand)

**Comment by mayakwd** [comment]
@jgranick I've tried to compile with rebuilded tools, and found that signing is not work properly.
You should add this parameters on the build step, not on the signing. Arguments CODE_SIGN_IDENTITY and PROVISIONING_PROFILE should be provided to "xcodebuild" (in the build step), not for the "codesign".

**Comment by jgranick** [comment]
Thanks, I'll look into this :smile:

**Comment by jgranick** [comment]
I believe this is resolved, can you tell if the current release of OpenFL and Lime is working here?
