### ISSUE TITLE
Problem with HaxelibHelper or ProjectXMLParser and flixel library

### ISSUE THREAD

**Issue by Beeblerox** [openfl/lime#852]
Hello!

I'm working on flixel to make it work with openfl 4 and up to lime 3.3.0 i was able to compile sample flixel projects, but after updatin lime to 3.4.1 i get this output:
```
Called from ? line 1
Called from CommandLineTools.hx line 1569
Called from CommandLineTools.hx line 24
Called from CommandLineTools.hx line 130
Called from CommandLineTools.hx line 1443
Called from lime/project/ProjectXMLParser.hx line 23
Called from lime/project/ProjectXMLParser.hx line 56
Called from lime/project/ProjectXMLParser.hx line 2116
Called from lime/project/ProjectXMLParser.hx line 1301
Called from lime/tools/helpers/HaxelibHelper.hx line 31
Called from /usr/lib/haxe/std/haxe/format/JsonParser.hx line 74
Called from /usr/lib/haxe/std/haxe/format/JsonParser.hx line 78
Called from /usr/lib/haxe/std/haxe/format/JsonParser.hx line 249
Uncaught exception - Invalid char 44 at position 397
Build halted with errors.
```

i think that the problem is with `HaxelibHelper` or `ProjectXMLParser`.

In order to reproduce this issue you'll need flixel from this branch https://github.com/Beeblerox/flixel/tree/Separate-render and you'll have to use this demo: https://github.com/Beeblerox/flixel-demos/tree/dev/Other/FrameCollections

The only thing i can tell you that there wasn't this issue in lime 3.3.0, but it was introduced in lime 3.4.0
i was trying to compile project both with Haxe 3.3 and Haxe 3.4rc and still no luck.
And i'm on Windows 10 (wonder if it somehow affects or not)

**Comment by jgranick** [comment]
I would first see if the path looks correct, and if it's loading

https://github.com/openfl/lime/blob/develop/lime/tools/helpers/HaxelibHelper.hx#L31

Then I wonder if it's something with the contents of the JSON file, perhaps a bad character it doesn't recognize, or a file encoding it can't handle (like a UTF-8 bug or something?)

...or a bug with Haxe JSON?

**Comment by Beeblerox** [comment]
i don't know how to do it, because i hadn't worked with haxe macros feature at all and don't know how to print file contents at this time.
But as i written earlier i've tried the same code but with lime 3.3.0 and it worked

**Comment by mayakwd** [comment]
@Beeblerox, can you provide this `project.xml` file?

**Comment by mayakwd** [comment]
@Beeblerox the problem is in incrorrect json. Look here: 
https://github.com/Beeblerox/flixel/blob/Separate-render/haxelib.json#L10
this is an incorrect definition for object.

**Comment by Beeblerox** [comment]
@mayakwd thank you for advice!!!
i'll check it tonight when i get home

**Comment by Beeblerox** [comment]
@mayakwd thank you again. i fixed json file and it succesfully compiled.
It's strange that this file worked with previous versions of lime
