### ISSUE TITLE
Why does System::GetDirectory return string pointer instead of string?

### ISSUE THREAD

**Issue by vroad** [openfl/lime#853]
Why should this be pointer? Do you think that it's faster?
It's not going to be faster because it's generally faster to allocate objects on stack, and compiler can optimize away unnecessary copies in this case. On C++11 move may also be used to avoid copies.

https://en.wikipedia.org/wiki/Return_value_optimization
http://stackoverflow.com/questions/17473753/c11-return-value-optimization-or-move
https://github.com/openfl/lime/blob/c046d3d39d7d9a275cb14c496f7fb6bf094bd674/project/src/backend/sdl/SDLSystem.cpp#L91

To me it looks like a premature optimization that just makes code unnecessary complex.
You could even return CFFI string allocated with `alloc_string()` directly, if performance is really concern.

**Comment by jgranick** [comment]
Are you saying to return `std::wstring` instead of `std::wstring*`?

I'd be happy to talk more, but I don't want to do it here like its a bug :smile:
