### ISSUE TITLE
CFFI issue on Android target, lime 3.5.0

### ISSUE THREAD

**Issue by hiepth** [openfl/lime#854]
I've just upgraded library
lime 3.5.0
openfl 4.5.0
haxe 3.4.0rc1

My project compile well after some minor code change.
But when run on an Android device, my app crash with following error:
crashed:	2016-12-08 16:13:18
duration:	00:00:01
error:		JNI Exception
stack:
lime.system.JNI.createStaticMethod (lime/system/JNI.hx line 115) 

Some thing wrong with CFFI?

**Comment by jgranick** [comment]
Can you test OpenFL samples, and see if they work? Do you override any templates in your project?
