### ISSUE TITLE
API design of Cairo and CURL

### ISSUE THREAD

**Issue by vroad** [openfl/lime#855]
Why does CURL classes need handle param to call APIs while cairo doesn't?
Doesn't it make more sense to store this inside class, like Cairo?

I'm not sure why abstracts are used in both CURL and cairo either, because using abstract here doesn't seem to help much here. As it casts implicitly from anything(since `CFFIPointer` is just a typedef of `Dynamic`) you may end up using wrong value as a handle.

There are things that cannot be done in abstract classes, though you may not consider these useful in this case.
 - Type checking with `Std.is`, casting, and inheritance (might be useful for cairo surfaces?)
 - Obtaining list of methods and calling them via reflections (might be useful for scripting)
 - Cannot be easily shared across modules in modular mode

At least abstracts are not better in every way.

**Comment by jgranick** [comment]
I would be happy to talk about this more, but I want to use Github Issues for bug tracking. Do you think the forums or Slack is a better place? Trello?
