### ISSUE TITLE
Provide Gamepad Vibration capability (Windows, Xbox, Playstation, WiiU)

### ISSUE THREAD

**Issue by alexandervrs** [openfl/lime#861]
Crosspost from the OpenFL issue [#1360](https://github.com/openfl/openfl/issues/1360) , since a lime API is needed for this.

There should be a function to provide gamepad vibration capability to the platforms that is supported.

It should use any gamepad device based on its ID you provide, both left and right motors with normalized values from 0.0 (no vibration) to 1.0 (full vibration)

Windows & Xbox could be done via XInput (and DInput if you wish to also support legacy gamepads)
WiiU, Playstation 3/4 controllers also have vibration capabilities.

Gamepad vibration adds so much feedback to a game that it'd be a shame to overlook it.

**Comment by jgranick** [comment]
Tracking here :smile: https://trello.com/c/eDTwQTyC/24-force-feedback-support
