### ISSUE TITLE
Use a dedicated "name" field for determining the App's storage folder name

### ISSUE THREAD

**Issue by alexandervrs** [openfl/lime#863]
I noticed that your application's storage directory is usually `%appdata%/<Companyname>/<Appname>`
or just `%appdata%/<Appname>` if you leave the company field blank in project.xml, which is fine.

This is my project.xml section for Windows
```xml
<section if="windows">
	<meta title="My Title" company="CompanyName" version="1.0.0" package="com.company.sample" />
	<app main="Main" path="Builds" file="AppName" />
	<window fullscreen="false" orientation="landscape" borderless="false" resizable="false" vsync="true" hardware="true" allow-shaders="true" require-shaders="true" depth-buffer="true" antialiasing="2" />
</section>
```

However this is defined in the `<app>` node as "**file**", this has the side effect that this field is really supposed to be the **output filename** for the .exe, and sometimes you may not want the folder name for the storage directory and the output filename to have the same name. 
Or have different titles per platform (e.g. Super Awesome App - Mac Edition) to signify some differences or some sort of branding. Or you may want your games to share the same save location so they'd have to use the same storage directory.

As such, could there be a dedicated "**display-name**" or "**name**" field for it in the meta node?

Currently I just rename the filename after compilation, but could be cleaner to just have a more dedicated field for it like some other engines do.

Also it should not affect just Windows, but also other platforms like Mac & Linux (if e.g. the app saves files in `~/.config/<Companyname>/<Appname>`)

**Comment by jgranick** [comment]
Tracking here: https://trello.com/c/CV7bUMTG/49-add-a-way-to-specify-the-company-and-app-name-when-retrieving-the-storage-directory
