### ISSUE TITLE
Howler sound get_length null error

### ISSUE THREAD

**Issue by jerobarraco** [openfl/lime#867]
this code consistently fails in

> nande@nande-killa:~$ haxelib list
> actuate: 1.8.6 [1.8.7]
> box2d: [1.2.3]
> haxelib: [3.3.0]
> haxelib_client: [3.2.0-rc.3]
> hxcpp: [3.3.49]
> layout: [1.2.1]
> lime-samples: [2.6.0]
> lime: 2.9.1 3.0.3 2.8.3 3.2.1 [3.3.0]
> openfl-samples: 3.3.1 [4.0.0]
> openfl-tools: [1.0.10]
> openfl: 3.6.1 4.0.3 3.5.3 4.2.0 [4.3.0]
> spritesheet: [1.2.0]
> swf: 2.2.0 2.2.3 [2.2.4]

```
musics[chan] = Assets.getMusic(PATH+ "music/" + name + FORMAT);
trace("Music length " +musics[chan].length);
```

here, __buffer.data is undefined

> Uncaught TypeError: Cannot read property 'length' of undefined
>     at openfl_media_Sound.get_length

```
,get_length: function() {
		if(this.__buffer != null) {
			var samples = this.__buffer.data.length * 8 / (this.__buffer.channels * this.__buffer.bitsPerSample);
			return samples / this.__buffer.sampleRate * 1000 | 0;
		}
		return 0;
	}
```

i can steal the same info from __buffer.__srcHowl._duration but those 2 vars are private

**Comment by jgranick** [comment]
This appears to be working with the latest sources :smile:
