### ISSUE TITLE
(SimpleOpenGL, HerokuShaders) Android, blank screen during rotation or app switch

### ISSUE THREAD

**Issue by labe-me** [openfl/lime#88]
Using the git version of lime, NDKV9=1, android api 16, nexus 7 (up to date).

When the device is rotated the screen goes black/white (context lost?), no error message in the log cat.

When the application is paused (switch to desktop) the screen goes black too.

Forcing the orientation to landscape in the project.lime prevent the black/white screen on rotation but not on app pause.

**Comment by jgranick** [comment]
I believe the context should be preserved in this case now, and when not preserved, context lost/restored events should be dispatched
