### ISSUE TITLE
Add lime.ui.ScanCode, with conversion to/from KeyCode

### ISSUE THREAD

**Issue by jgranick** [openfl/lime#882]
More discussion here:

http://community.openfl.org/t/layout-independent-key-events/8629/5

**Comment by starry-abyss** [comment]
Unfortunately, I have zero values for almost every letter (tested across layouts) when using in KeyboardEvent.KEY_DOWN handler: `trace(ScanCode.fromKeyCode(event.keyCode));`

It seems I get the correct results with event.charCode instead and only when Shift is not pressed, which leads me to an assumption that the letter case needs to be converted somewhere along the way?

**Comment by starry-abyss** [comment]
Also keys like ALT, SHIFT, Home, PageUp and some others give zero Scancode too.

**Comment by jgranick** [comment]
Apologies, the translation works only from `lime.ui.KeyCode`, not `openfl.ui.Keyboard` values.

Try this:

```haxe
stage.window.onKeyDown.add (window_onKeyDown);

...

private function window_onKeyDown (keyCode:KeyCode, modifier:KeyModifier):Void {
    
    var scanCode:ScanCode = keyCode;
    trace (scanCode);
    
}
```

**Comment by starry-abyss** [comment]
OK, this works now I think.
Maybe consider somehow guard against feeding raw Ints to Scancode converter?
Thank you!
