### ISSUE TITLE
Cannot prevent android back button application close.

### ISSUE THREAD

**Issue by jgranick** [openfl/lime#884]
_From @xoopx on January 9, 2017 19:6_

I use Pirate Pig exemple with code
Even this code doen't make trick
```
Lib.current.stage.addEventListener(KeyboardEvent.KEY_UP, onKeyUp);

private function onKeyUp(e:KeyboardEvent):Void {
	if (e.keyCode == 27 || e.keyCode == 1073742094 || e.keyCode == Keyboard.ESCAPE || e.keyCode == lime.ui.KeyCode.APP_CONTROL_BACK) {
		//e.preventDefault();
		e.stopImmediatePropagation();
		//e.stopPropagation();
		return;
	}
	e.stopImmediatePropagation();
}
```
I use openfl 4.5.0, lime 3.5.0

_Copied from original issue: openfl/openfl#1424_

**Comment by jgranick** [comment]
Does this work?

```haxe
stage.addEventListener (KeyboardEvent.KEY_UP, stage_onKeyUp);

private function stage_onKeyUp (event:KeyboardEvent):Void {
    
    if (event.keyCode == KeyCode.APP_CONTROL_BACK) {
        
        event.preventDefault ();
        
    }
    
}
```

**Comment by jgranick** [comment]
_From @xoopx on January 10, 2017 10:46_

No same problem. Tested on two devices. I use android-ndk-r13b.

**Comment by jgranick** [comment]
I thought this was a Lime issue, but it turns out it was a problem with `KeyboardEvent` not being cancelable. Looks like it's cancelable in AIR, but not in Flash Player. I wonder if we should allow all to be canceled, or only certain events. Either way, we need to be able to cancel the back button :smile:

**Comment by xoopx** [comment]
Everything went well!
