### ISSUE TITLE
Use bytes internally (not seconds) to improve native AudioSource.currentTime

### ISSUE THREAD

**Issue by jgranick** [openfl/lime#898]
Getting and setting the current time for the native AudioSource backend is done using OpenAL SEC_OFFSET, but there appear to be some precision issues.

Perhaps using bytes as the offset would be quicker or more accurate, so let's try it

**Comment by raould** [comment]
I don't understand how all this works, but I worry/don't understand how one would convert byte position to time position? Is there associated metadata that helps do that calculation? What about the audio being compressed, does that change the calculation as things go along? etc.

**Comment by raould** [comment]
Psuedo confirmation:

http://slick.ninjacave.com/forum/viewtopic.php?p=6320
Kev posted this about the timer.
http://lwjgl.org/forum/index.php/topic,2643.0.html
The response I got from Dan at Creative was:
Quote:
Getting playback offsets is not going to be anywhere near as precise I'm afraid. The "Generic Hardware" and "Generic Software" devices only update the playback positions every 25 milliseconds.
I've finally proven this is the case. OpenAL only updates every 25ms while Java Sound updates every ~5ms. Case closed! It has been quite an adventure!

**Comment by raould** [comment]
p.s. thank you! i locally backported this udpate to lime 2.9.1 since that is what flixel is stuck at, and it looks really good so far :-)

**Comment by PaulGene** [comment]
could this be pushed to https://github.com/openfl/lime/tree/legacy as a lot of us are still using it!
