### ISSUE TITLE
Ability to get pressure data from pen tablets like Wacom and Huion

### ISSUE THREAD

**Issue by alexandervrs** [openfl/lime#905]
It seems that a lot of apps can be created with Haxe/lime/OpenFL, but the one app that seems impossible at this moment is a drawing application that supports pen pressure from pen tablets like Wacom and Huion.

I'd suggest there were ways in the input category to get:
> Pen tablet availability overall
> Pen cursor X,Y coordinates
> Pen Pressure amount
> Pen Tilt amount (not priority, not all devices support this)
> Eraser Tip active (whether the user is now using the back of the pen to erase, not priority, not all devices support this)

Windows, Mac and Linux seem possible to do, HTML5 could use the Pointer Events API perhaps?

**Comment by jgranick** [comment]
Do you know if this comes through as a `Touch` event at all?

Lime has `pressure` in the `Touch` API, I believe it should work on mobile devices that report pressure, but I'm not sure

It does appear that SDL2 does not support Wacom tablets

http://stackoverflow.com/questions/38863527/wacom-tablet-with-sdl2

So this would require low-level code

https://developer.wacom.com

**Comment by jgranick** [comment]
I think this is a really fun idea, but I have the feeling that in the end, it would be out-of-scope for Lime to support, based on the platform-specific code required to make it work. However, I would be happy to help work with anyone interested in integrating support for C++ pen tablet SDKs, or other code necessary to integrate proper support 😁

**Comment by devdoomari** [comment]
see https://github.com/nicarran/jpen for example. (LGPL code)
 - specifically: https://github.com/nicarran/jpen/tree/master/src/main/c
