### ISSUE TITLE
Compilation Server error invalid field access.

### ISSUE THREAD

**Issue by Triangle345** [openfl/lime#912]
I'm trying to use a compilation server to speed up neko compile times.  Waiting 4 seconds for compile is kind of slow so I heard a compilation server might speed things up. However; when building with the compilation server for the first time, everything works fine. When building again I get an error 

    C:\HaxeToolkit\haxe\std/haxe/macro/Compiler.hx:250: lines 250-264 : Invalid field access : __a
    <null pos>:1: character 0 : Called from
    C:\HaxeToolkit\haxe\std/neko/_std/Array.hx:291: characters 9-17 : Called from
    Aborted

I'm simply starting a server like so:

    haxe --wait 6000

and attempting to build like so:

    lime build neko -v --connect 6000

Figured I would add some more detail to this:
When I build without compilation server, no matter how many times, everything builds fine.
When I stop the compilation server and start it again, it builds fine only for the first time; subsequent builds all have this error after the first.

**Comment by Gama11** [comment]
Lime and Haxe versions?

**Comment by Triangle345** [comment]
Haxe - 3.4.0
Lime - 2.9.1

**Comment by Triangle345** [comment]
I also have a working example on github where this issue happens:
https://github.com/Triangle345/haxevoronoi

**Comment by Gama11** [comment]
Looks like I can reproduce this (even with Flixel's Mode demo, not just your project). This is really more of a Haxe than a Lime issue though.

Might be the same issue as https://github.com/HaxeFoundation/haxe/issues/5886.

**Comment by francescoagati** [comment]
i have notice that is like if at the second execution with cache compiler server the variables and the enviroment defined in the first execution are erased. with partials lib i have the same problem.
