### ISSUE TITLE
Consumption of RAM

### ISSUE THREAD

**Issue by r3d9u11** [openfl/lime#913]
(just question for a little discussion)

Hi. With older versions of lime an empty project consumed about 12mb ram for an x32 cpp-target (~13-15mb for an x64). But with newest (3.7.2) about 40-50mb at startup. And in application with minimal UI the consumption of RAM is growing up to 100mb.

Whether it is influenced by the newest version of lime, or it may be influence of newest version of g++?

Linux Mint 18.1 x64 and Windows 7 x64
Targets: cpp 32 and 64
Current libs: hxcpp 3.4.49, lime 3.7.2, openfl 4.7.3
Target config: release
g++ --version: (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

Is any ideas, how to reduce consumption of RAM?

Thanks.

**Comment by jgranick** [comment]
Could you try some Lime samples, and see if this is true for Lime, or only OpenFL?

Thanks :smile:

**Comment by r3d9u11** [comment]
Here results of my several easy tests:

Linux Mint 18.1 x64
Haxe 3.4.0
Haxelib:
```
$ haxelib list
actuate: [1.8.7]
box2d: [1.2.3]
dataTree: [git]
format: [3.3.0]
haxe-crypto: [0.0.7]
haxity: [git]
hscript: [2.0.7]
hvm: [0.0.2]
hxcpp: [3.4.49]
layout: [1.2.1]
lime-samples: [3.4.0]
lime-tools: [1.5.7]
lime: 3.7.2 [git]
openfl-native: [1.4.0]
openfl-samples: [4.7.0]
openfl-tools: [1.0.10]
openfl: [4.7.3]
stablexui: [git]
systools: [git]
typext: [git]
```
lime was built from sources:
`$lime rebuild linux -64 -final -clean -static`

Lime:
* empty project [lime-test.zip](https://github.com/openfl/lime/files/771021/lime-test.zip)
  * cmd: `lime rebuild linux -64 -final -clean`
  * ram consumption at app-startup: 38.2mb - 40.2mb
* empty project (with static linking)
  * cmd: `lime rebuild linux -64 -final -clean -static`
  * ram consumption at app-startup: 26.3mb
* lime [hello-world](https://github.com/openfl/lime-samples/tree/master/demos/HelloWorld) (with static linking)
  * cmd: `lime rebuild linux -64 -final -clean -static`
  * ram consumption at app-startup: 31.0mb

OpenFL:
* empty project [test-openfl.zip](https://github.com/openfl/lime/files/771025/test-openfl.zip)
  * cmd: `lime rebuild linux -64 -final -clean`
  * ram consumption at app-startup: 42.2mb
* empty project (with static linking)
  * cmd: `lime rebuild linux -64 -final -clean -static`
  * ram consumption at app-startup: 31.2mb

as you can see from the results the Lime consumes the most part of resources
