### ISSUE TITLE
Crash when using fromBytes to load Vorbis (OGG) files.

### ISSUE THREAD

**Issue by starburst997** [openfl/lime#918]
Using 
```haxe
VorbisFile.fromFile("assets/test1.ogg");
```
I get no crash and everything works as expected, however using
```haxe
VorbisFile.fromBytes(bytes);
```
I get crashes when using any "seek" function and "randomly" when using "read".

*By randomly I mean it's seems to be impacted by the time it takes to process the file, while experimenting I disabled some costly function inside the loop and I could get more "read"*

I created a test case for this bug available [here](https://github.com/starburst997/openfl-bug-vorbis-1/), it begin by using the "fromFile", save a WAV file then proceed with using "fromBytes".

To test the "read" bug makes sure to comment this [line](https://github.com/starburst997/openfl-bug-vorbis-1/blob/master/src/Main.hx#L152) as it will crash there.

**Comment by jgranick** [comment]
Thanks for the test case :smile:

_linking here so I don't forget!_

https://github.com/starburst997/openfl-bug-vorbis-1

**Comment by jgranick** [comment]
Fixed :smile:

https://github.com/openfl/lime/commit/cdd9a293115997157c0ad4a60ba0044d4a56a693

**Comment by starburst997** [comment]
Yay! Thank you so much!
