### ISSUE TITLE
Smarter FileHelper

### ISSUE THREAD

**Issue by mastef** [openfl/lime#945]
Right now FileHelper does a lot of re-copying of already copied files, and has a crude binary/non-binary check. The problem ( at least in the old Ant build process ), is that it keeps recopying unchanged text files from extensions - e.g. `.java` files which get re-built with `javac` to `.class` on every android build; I assume since each of them are processed and so on every build there is a modified mtime. This way pre-dexing can't be utilised neither, since the .jar files keep changing, although nothing really changed.

( But also e.g. `jar` files are currently not recognised as binary files, so on every build they are re-opened and checked. Should add `jar` to binary extensions list. )

To measure how slow this process is, actually just log out every file that is being copied again and again. 

I thought about 2 different solutions to this to improve build speed drastically.

1. in the export directory change the mtime of each extension's file that was copied over to the original's mtime, otherwise javac recompiles the .java files to new .class files which get dexed/merged again - _however i haven't found a way to change mtime in haxe_. Then on new build you'd compare mtime and filesize or checksum against each other ( to detect if processing happened )

2. another possibility is to make a small db ( file based? sqlite based? ) that is filled after each successful build with the source files mtimes + if they were processed or copied unchanged.

And then on new build there'd be a comparison against the last build snapshot if:
- mtime is newer or not
- if file was actually being changed in build process or not ( e.g. if version numbers are updated in source files )

That could speed up all the unnecessary re-copying, re-updating and re-packing on every Android build at least.

**Comment by mastef** [comment]
Found maybe a simpler way - Currently after processing any text file, a new text file is generated in the export directory due to the processing.

https://github.com/openfl/lime/blob/23f98d63415528aaa1b294358eeee5980fc22ad1/lime/tools/helpers/FileHelper.hx#L158-L160

We can compare if the old contents are the same as the new contents, and in this case simply run `copyIfNewer` instead of creating a new file :

```hx
if (fileContents == result) {
	// file contents same after processing, just copy original if newer
	copyIfNewer (source, destination);
} else {
	// file has been processed, create new file
	var fileOutput:FileOutput = File.write (destination, true);
	fileOutput.writeString (result);
	fileOutput.close ();
}
```

**Comment by mastef** [comment]
Taking it a step further, checking if the destination content is the same as the source content, I managed to tone down copying from 692 files per build to 4 : 

```md
Original FileHelper   :  692 files copied/created per build
Post-processing check :   56 files copied/created per build
Pre-build comparison  :    4 files copied/created per build
```

Speed of copying is of course comparable - this mainly seems to help with any other post-processing tools which compare `mtime` for re-compiling. It seems pre-dexing works now as it should in 95% of the cases ( 1-2 pre-dex creations _sometimes_ still happen, sometimes they don't ), and I managed to reduce build time from 1:30+ mins to 00:35 with debug signing taking the longest. The project is fairly complex now with 14 extensions, but nothing out of the ordinary.

```hx
if (fileContents == result) {
	// file contents same after processing, just copy original if newer
	copyIfNewer (source, destination);
} else {
	// file has been changed during processing
	if (FileSystem.exists (destination)) {
		var destContents:String = File.getContent (destination);
		if(result == destContents) {
			// existing compiled file is same as our result, abort.
			return;
		}
	}

	// output file has different content than old compiled file, create new file
	var fileOutput:FileOutput = File.write (destination, true);
	fileOutput.writeString (result);
	fileOutput.close ();
}
```

**Comment by mastef** [comment]
@jgranick oh I nearly forgot about this. I was using it in my personal lime for a long time, and it worked without issues. What do you think?

**Comment by jgranick** [comment]
We do not copy the new file if the destination file exists, and has the same content:

https://github.com/openfl/lime/blob/develop/lime/tools/helpers/FileHelper.hx#L210-L211

So this was changed

**Comment by mastef** [comment]
Oh yeah, nice!
