### ISSUE TITLE
Wrong key code?

### ISSUE THREAD

**Issue by Marc010** [openfl/lime#95]
Lime and Openfl both return 1073741907 for cpp/windows while other os/target combinations return 144.

This might be related: http://wiki.libsdl.org/SDLKeycodeLookup

I think Openfl uses SDL to get the keycode wich uses numbers over 1073741824 for keys without character representations.
Openfl is a implemention of the flash api so it should probably return keycodes similar to how flash does it .

Causes a crash in HaxePunk: https://github.com/HaxePunk/HaxePunk/pull/243

**Comment by Draknek** [comment]
This is still an issue as of the most recent git version of lime. Function keys are mapped incorrectly, e.g. F4 sends the keycode for "S".

Full list of incorrect keycodes here: https://github.com/openfl/openfl-native/issues/193

I don't know why https://github.com/openfl/openfl-native/pull/199 was closed, it claims to fix this? (cc @jgranick)

**Comment by jgranick** [comment]
There is still more work that could be done on consistency, but I just tested a simple `onKeyDown` handler in Lime, and yes, it does return high values for F1-F12, but this matches the same values in the `lime.ui.KeyCode` enum, so `trace (keyCode == KeyCode.F1)` is true.

Similarly, OpenFL appears to be handling things based on the Lime KeyCode enum, so it maps Lime F1 keys to Flash/OpenFL F1 key codes.

I'm going to mark this as "fixed" again based on what I'm finding. Please feel free to let me know if you encounter a case where it is wrong, and which path (legacy or Lime 2) it is on, etc.

Thank you!
