### ISSUE TITLE
"lime test html5" open empty browser window on Ubuntu

### ISSUE THREAD

**Issue by bendmorris** [openfl/lime#955]
I'm on Ubuntu 16.04, with Chrome as my default browser. When I run `lime test html5` it opens a new Chrome window with a single empty tab. Navigating to localhost:3000 works. Not sure if this is an issue with my setup or the CLI tool, but this is a fresh Ubuntu installation.

Also, "lime setup html5" complains that "either" html5 is not a valid target or no setup is required. html5 is obviously a valid target so that message could be more specific.

**Comment by ashes999** [comment]
What does your project look like?

If you're using HaxeFlixel (which uses lime), you can build any of the default generated templates and see if those work in the web. They should.

Do you see any errors in Chrome's developer tools console?

**Comment by jgranick** [comment]
Does it work if Chrome is already open?

**Comment by bendmorris** [comment]
@ashes999 this happens for any project, and there aren't errors in the console - there wouldn't be, because it doesn't open anything, only an empty tab.

@jgranick it does this regardless of whether Chrome is already open.

**Comment by jgranick** [comment]
It has been working for me on Ubuntu 16.04 at work, this is based on the tools and Node HTTP server. These are the commands used currently:

https://github.com/openfl/lime/blob/develop/lime/tools/helpers/HTML5Helper.hx#L90

An older version of Lime had an arbitrary time between launching the server and running the default web browser, but the current version uses a command in HTTP server that has been more reliable

**Comment by jgranick** [comment]
In the meantime, `openfl test html5 -nolaunch` should help -- it prints when the server is ready, so you can go reload an open tab to the web server :smile:

**Comment by jgranick** [comment]
It might have something to do with Chrome? I just realized, it's worked for me with Firefox and Opera, but I haven't tried using Chrome as my default on Linux. I'm not sure 😦

**Comment by ashes999** [comment]
I developed a couple of games on Chrome on Linux. It works fine for me. I never experienced this problem.

**Comment by Arthur-W-White** [comment]
I am having the same issue. Will check with firefox right way. How can we help reproduce this issue?

**Comment by Arthur-W-White** [comment]
Works fine if I set FireFox to be the default browser so it must be related to Chrome Version 57.0.2987.133 unknown (64-bit)
