### ISSUE TITLE
Can't run lime on Cloud9

### ISSUE THREAD

**Issue by ashes999** [openfl/lime#958]
Hi,

I got HaxeFlixel working on Cloud9 last year, and [documented the few caveats here](https://ashes999.github.io/learnhaxe/haxeflixel-in-cloud9.html).

I tried the same process today.  HaxeFlixel installs with Lime 2.9.1 by default. Running `haxelib run lime` prints `Error: Library lime version 2.9.1 does not have a run script`.

That's strange. So I installed lime separately with `haxelib install lime` and ended up with version 4.0.3. Running `haxelib run lime` prints the same error.

I assume this error is not a true indication of lime being broken, but something else in Cloud9 muddling things. How can I troubleshoot this error?

Edit: I just checked [the source code] and it looks like it's looking for `run.n`, which I can see on GitHub. Maybe it's a permissions issue?

**Comment by jgranick** [comment]
Does it have Neko? Does `neko run.n` do anything, or `neko tools/tools.n` from the Lime directory?

**Comment by ashes999** [comment]
Bingo.

I have neko and `neko tools/tools.n` informs me that `hxcpp` isn't installed. Okay, strange, so I run `haxelib list` and I get an error about the haxelib directory doesn't exist.

Turns out haxelib doesn't like `~/workspace/haxelib` as a directory; it keeps disappearing (?!). Instead, setting the full path (eg. `/home/ubuntu/workspace/haxelib` works.

Sorry, this wasn't a lime-specific problem. Thanks for helping me sort it out.

**Comment by jgranick** [comment]
No problem :wink:

**Comment by zesterer** [comment]
Perhaps it should automatically convert any path relative to the home directory to an absolute path?
