### ISSUE TITLE
setResolution wanted for Android platform

### ISSUE THREAD

**Issue by Hasufel** [openfl/lime#96]
This is a request for the equivalent on Android platforms of stage.setResolution that is available on desktop platforms: being able to switch resolution on the fly while staying in fullscreen. Thank you for your attention.

**Comment by jgranick** [comment]
I wonder if the SDL2-based Android target will support display mode switching, this could be investigated when fullscreen display mode switching is officially supported, it's not part of the Lime API at the moment :smile:
