### ISSUE TITLE
Add support for JS `<dependency embed="true"/>`

### ISSUE THREAD

**Issue by jgranick** [openfl/lime#961]
Certain dependencies on JS may be more valuable if they are packed into the final application JS file, rather than included as separate files.

We should look at an embedded option that merges them together into one file

**Comment by nykevinwong** [comment]
great, when can we have this feature ready?

**Comment by nykevinwong** [comment]
currently itch.io supports uploading HTML games, but there are limits such as maximum 100 files only.
https://itch.io/docs/creators/html5#viewing-your-game 
if we can have bundled js into one file as well as assets/resources into one file, that will be great!!

**Comment by jgranick** [comment]
This is supported in Lime 7.3 :smile:
