### ISSUE TITLE
Mac Requires OS X 10.12

### ISSUE THREAD

**Issue by starburst997** [openfl/lime#969]
See: http://community.openfl.org/t/mac-requires-os-x-10-12/8515/5

Just like it was said in that thread, easy fix, just need to set the appropriate environment var, call:
```
export MACOSX_DEPLOYMENT_TARGET="10.6"
```
Before your build command.

Doesn't occurs on OpenFL 3 legacy mode, but does on the latest OpenFL 4.

**Comment by RblSb** [comment]
Does someone else have this problem? I do not have it at 10.9
