### ISSUE TITLE
WAV.cpp: Searching for the fmt chunk skips over too much data

### ISSUE THREAD

**Issue by RichardBrown384** [openfl/lime#977]
The problem is essentially [here](https://github.com/openfl/lime/blob/7f7273fff4d43d71c3ab3b2ab2faf4f4198b2127/project/src/media/containers/WAV.cpp#L91)

    lime::fseek (file, wave_format.subChunkSize, SEEK_CUR);

and the correct version should be something like

    lime::fseek(file, currentHead + 8 + wave_format.subChunkSize, SEEK_SET);

While searching for the fmt chunk you first read in the entire chunk (24 bytes) and then you seek to a position wave_format.subChunkSize relative to the end of the chunk. 

The impact of this is that files that contain chunks before the fmt chunk can't be read by lime.

**Comment by jgranick** [comment]
Please give this fix a try. I don't have the same files as you, but I believe this should resolve the issue :smile:
