### ISSUE TITLE
Add support for a HashLink target

### ISSUE THREAD

**Issue by Gama11** [openfl/lime#979]
It would be great to have support for [HashLink](http://hashlink.haxe.org/) (for a number of reasons). Has anybody started looking into this yet?

**Comment by jgranick** [comment]
_(copying another message)_

The first step is to learn more about the way that HashLink handles native C bindings.

https://github.com/HaxeFoundation/hashlink/blob/master/libs/sqlite/sqlite.c#L85

We use "CFFI Prime", which is compatible with Neko CFFI, older HXCPP CFFI and newer HXCPP high-performance bindings. Ideally, we will want to find a way to either create separate bindings for HL and for other runtimes, or create a macro that is compatible with all three binding styles.

If we can determine this for HL, then we should be able to then approach HL as we do Neko, where we use a precompiled Lime binary, but compile the Haxe code to HL and run in a VM at runtime. I'm very open to this, if we can sort out the more technical bit (above) first :smile:

**Comment by jgranick** [comment]
Split into additional smaller issues: #1058 #1059 #1057 #1060
