### ISSUE TITLE
Glitchy window resizing on cpp target

### ISSUE THREAD

**Issue by cwkx** [openfl/lime#98]
At the moment the resizing of windows on the cpp target is a little bit glitchy, and sometimes can hang for a second or so before repainting. Please could this attempt to be more consistent with the flash target, doing proper repainting on resize or, if thats not possible, prevent the artefacts/flickering that occurs during the resize events. 

Currently resize events fire as soon as the window dimensions change in flash resizing, and only once after resizing in cpp.

**Comment by jgranick** [comment]
This is entirely based on when SDL2 dispatches resize events, I'm not sure we can handle this differently without introducing changes at an SDL2 level
