### ISSUE TITLE
Android app packageName is always overwritten by Meta.package default value

### ISSUE THREAD

**Issue by giuppe** [openfl/lime#981]
i found that the ::APP_PACKAGE:: template variable, for example in AndroidManifest.xml, is substituted with a default value of "com.example.app", even if I put the attribute packageName in an <app /> tag.
However if I define the package in the "package" attribute of a <meta /> tag, it works.

Looking at the code, this could be the culprit: [(line 941 of HXProject.hx)](https://github.com/openfl/lime/blob/develop/lime/project/HXProject.hx#L941)

`context.APP_PACKAGE = context.META_PACKAGE = meta.packageName;`

The previous lines copy all the attributes of <app /> and <meta /> to the corresponding "APP_*" and "META_*" fields of the template context, so the eventual package/packageName attribute in <app /> is always overwritten by the corresponding value in <meta /> or, if missing, by its default value.

A solution could be adding a conditional statement (assuming that the <app /> value of packageName should have the precedence over the <meta /> attribute):

`if(Reflect.hasField (app, "packageName")){
    context.APP_PACKAGE = context.META_PACKAGE = app.packageName;
}else{
    context.APP_PACKAGE = context.META_PACKAGE = meta.packageName;
}
`

**Comment by jgranick** [comment]
I'm sorry for the delay in getting back to you :smile:

The expected method of setting the `::META_PACKAGE::` template value is `<meta package="" />` in your project XML (or `meta.packageName = "...";` in an HXP project)

The `<app />` tag for the package name is deprecated, and `"packageName"` is not supported. It would be called `meta.package = ""` internally if that were valid Haxe code :smile:

Please let me know if there are other issues using `<meta package="" />`. Thank you :grin:

**Comment by giuppe** [comment]
Hi,
could it make sense to insert some sort of deprecation warning/critical error during compilation? There are a lot of old tutorials on the net that suggests putting packageName under <app />, and it seems to work in some places, but it silently fail elsewhere and it's very confusing for a newbie.

This, or setting something like "please.set.the.meta.package.attribute.in.project.xml" as default package :)
