### ISSUE TITLE
Neko: Invalid field access : onComplete

### ISSUE THREAD

**Issue by thronecode** [openfl/lime#994]
**OS**:_Windows 7 64-bit SP1_
**Haxe version (with Neko):**_3.4.2_
**Lime**: _5.0.3_ 

**Code**: 
```haxe
class Main extends Application {
    public function new () {
        super ();
	this.preloader.onComplete.add(function():Void{
	    trace("Complete");
        });
    }
}
```

Am I missing something?

**Comment by jgranick** [comment]
Try overriding `onPreloaderComplete` in your Main class instead, `preloader` may be null at that stage, but using the `onPreloadComplete` callback instead should be helpful :smile:

**Comment by thronecode** [comment]
I will destroy you last when I end the Matrix sir.
