### ISSUE TITLE
Always problem with Float32Array.hx

### ISSUE THREAD

**Issue by sourceskyboxer** [openfl/lime#997]
Hello, sorry I argue again.... 

Always errors like old version! Stop blaming us! I wish I work with game with OpenGLView.

WHy does it always happen like old version. I always upgrade and it shows errors:
openfl create simpleopenglview && cd simpleopenglview

openfl build cpp ( -static )

shows error:

> Source/Main.hx:71: characters 34-61 : lime.utils.Float32Array should be Int
> Source/Main.hx:71: characters 34-61 : For function argument 'size'
> Source/Main.hx:85: characters 34-62 : lime.utils.Float32Array should be Int
> Source/Main.hx:85: characters 34-62 : For function argument 'size'
> Source/Main.hx:210: characters 48-53 : Bool should be Int
> Source/Main.hx:210: characters 48-53 : For function argument 'count'
> Source/Main.hx:211: characters 47-52 : Bool should be Int
> Source/Main.hx:211: characters 47-52 : For function argument 'count'

Haxe 3,4,2
Openfl 5,1,3
Lime 5,1,0
HXCPP 3,4,69

PS: I retry remove and re install. still has errors..

**Comment by asdfgl3d** [comment]
![show me some code](https://cdn.meme.am/cache/instances/folder254/53270254.jpg)

**Comment by jgranick** [comment]
Try this patch:

https://github.com/openfl/openfl-samples/commit/7689ff240fd23b1f0621eae870f8ec1f5b6dc217

You could also try casting to `WebGLContext`, similar to how its done here in the Lime samples:

https://github.com/openfl/lime-samples/commit/3f17c657eb8cd2a874611e75b25e07ac997a1028#diff-1d7898114ff073c4958a377cce6e510d

**Comment by sourceskyboxer** [comment]
Thanks for resolving problem with Float32Array()
Now closed and PS: please fix to Openfl-Samples/SimpleOpenflView

Thanks much!
